/- GENERATED (relcert --emit-viability2; do not edit).

S3 bounded-viability census: per benchmark, per right mode, per evolve-box face —
strict (R6 boundary probe) / growth<M> (UNSAT(box ∧ ġ > M); anchors within budget
g₀ + M·dt < 0 keep the face for the piece duration). 2026-07-16: 1121/1121 faces
certified suite-wide, zero fails (R6 strict-only census: 9/126 modes); 1085 faces after the
2026-10-08 suite deduplication (`docs/SUITE-DEDUPE.md`). -/

namespace RelCertifier

def arm_chain_rung1_viab2 : List (String × List (Nat × String)) := [("Approach", [(0, "strict"), (1, "growth1")]), ("Return", [(0, "growth1"), (1, "strict")])]
def arm_chain_rung2_viab2 : List (String × List (Nat × String)) := [("ApproachFast", [(0, "strict"), (1, "growth1")]), ("ApproachSlow", [(0, "strict"), (1, "growth1")]), ("Return", [(0, "growth1"), (1, "strict")])]
def arm_chain_rung3_viab2 : List (String × List (Nat × String)) := [("ApproachA", [(0, "strict"), (1, "growth1")]), ("ApproachB", [(0, "strict"), (1, "growth1")]), ("ApproachC", [(0, "strict"), (1, "growth1")]), ("Hold", [(0, "growth0"), (1, "growth0")])]
def arm_fidelity_low_viab2 : List (String × List (Nat × String)) := [("Approach", [(0, "strict"), (1, "growth1")]), ("Return", [(0, "growth1"), (1, "strict")])]
def arm_fidelity_mid_viab2 : List (String × List (Nat × String)) := [("ApproachFast", [(0, "strict"), (1, "growth1")]), ("ApproachSlow", [(0, "strict"), (1, "growth1")]), ("Hold", [(0, "strict"), (1, "strict")])]
def attitude_rate_viab2 : List (String × List (Nat × String)) := [("RECOVER", [(0, "strict"), (1, "strict"), (2, "strict"), (3, "strict"), (4, "strict"), (5, "strict")]), ("TRACK", [(0, "strict"), (1, "strict"), (2, "strict"), (3, "strict"), (4, "strict"), (5, "strict")])]
def endurance_gain_M1_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "strict"), (2, "strict")]), ("MODER", [(0, "growth0"), (1, "strict"), (2, "strict")]), ("FLAT", [(0, "growth0"), (1, "strict"), (2, "strict")])]
def endurance_orderlift_1to2_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "strict"), (4, "strict")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "strict"), (4, "strict")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "strict"), (4, "strict")])]
def endurance_orderlift_2to3_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "strict"), (1, "strict"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth4"), (6, "strict")]), ("MODER", [(0, "strict"), (1, "strict"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth4"), (6, "strict")]), ("FLAT", [(0, "strict"), (1, "strict"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth4"), (6, "strict")])]
def match_multi_rate_viab2 : List (String × List (Nat × String)) := [("DRIVE", [(0, "growth0"), (1, "strict"), (2, "strict")]), ("STALL", [(0, "growth0"), (1, "growth4"), (2, "strict")])]
def refinement_ladder_rover_rung1_2to3_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "strict"), (2, "strict")]), ("MODER", [(0, "growth0"), (1, "strict"), (2, "strict")]), ("FLAT", [(0, "growth0"), (1, "strict"), (2, "strict")])]
def refinement_ladder_rover_rung2_3to6_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "strict"), (9, "growth0"), (10, "growth0")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "strict"), (9, "growth0"), (10, "growth0")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "strict"), (9, "growth0"), (10, "growth0")])]
def refinement_ladder_rover_rung2_6dof_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "strict"), (6, "strict")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "strict"), (6, "strict")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "strict"), (6, "strict")])]
def refinement_ladder_rover_rung2b_6dof_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "strict"), (8, "strict"), (9, "growth0"), (10, "growth0")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "strict"), (8, "strict"), (9, "growth0"), (10, "growth0")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "strict"), (8, "strict"), (9, "growth0"), (10, "growth0")])]
def refinement_ladder_rover_rung2c_6dof_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "strict"), (9, "growth0"), (10, "growth0")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "strict"), (9, "growth0"), (10, "growth0")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "strict"), (9, "growth0"), (10, "growth0")])]
def refinement_ladder_rover_rung3_6to8_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "strict"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "growth0"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "strict")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "strict"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "growth0"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "strict")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "strict"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "growth0"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "strict")])]
def refinement_ladder_rover_rung4_8to12_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "strict"), (5, "strict"), (6, "growth0"), (7, "growth0"), (8, "growth0"), (9, "growth0"), (10, "strict"), (11, "strict"), (12, "growth2"), (13, "growth2"), (14, "growth0"), (15, "growth2"), (16, "growth2"), (17, "strict"), (18, "strict"), (19, "strict"), (20, "strict"), (21, "strict"), (22, "strict")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "strict"), (5, "strict"), (6, "growth0"), (7, "growth0"), (8, "growth0"), (9, "growth0"), (10, "strict"), (11, "strict"), (12, "growth2"), (13, "growth2"), (14, "growth0"), (15, "growth2"), (16, "growth2"), (17, "strict"), (18, "strict"), (19, "strict"), (20, "strict"), (21, "strict"), (22, "strict")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "strict"), (5, "strict"), (6, "growth0"), (7, "growth0"), (8, "growth0"), (9, "growth0"), (10, "strict"), (11, "strict"), (12, "growth2"), (13, "growth2"), (14, "growth0"), (15, "growth2"), (16, "growth2"), (17, "strict"), (18, "strict"), (19, "strict"), (20, "strict"), (21, "strict"), (22, "strict")])]
def robot_braking_viab2 : List (String × List (Nat × String)) := [("FAST", [(0, "growth2"), (1, "strict")]), ("MID", [(0, "growth2"), (1, "strict")]), ("SLOW", [(0, "strict"), (1, "strict")])]
def rover3_M1_viab2 : List (String × List (Nat × String)) := [("Recover", [(0, "strict"), (1, "strict"), (2, "growth1")]), ("Drive", [(0, "strict"), (1, "strict"), (2, "growth1")]), ("Safe", [(0, "strict"), (1, "growth0"), (2, "growth0")])]
def rover3tier_M1_viab2 : List (String × List (Nat × String)) := [("ACCEL", [(0, "growth0"), (1, "strict"), (2, "strict")]), ("COAST", [(0, "growth0"), (1, "strict"), (2, "strict")])]
def rover3tier_rung12_viab2 : List (String × List (Nat × String)) := [("ACCEL", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "strict")]), ("COAST", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "strict")])]
def rover_4d_box_viab2 : List (String × List (Nat × String)) := [("APPROACH", [(0, "strict"), (1, "strict"), (2, "strict"), (3, "strict")]), ("SETTLE", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0")])]
def rover_attitude_cone_12dof_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "strict"), (1, "strict"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "growth0"), (9, "growth0"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "strict"), (20, "strict"), (21, "strict"), (22, "strict")]), ("MODER", [(0, "strict"), (1, "strict"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "growth0"), (9, "growth0"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "strict"), (20, "strict"), (21, "strict"), (22, "strict")]), ("FLAT", [(0, "strict"), (1, "strict"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "growth0"), (9, "growth0"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "strict"), (20, "strict"), (21, "strict"), (22, "strict")])]
def rover_coupled_viab2 : List (String × List (Nat × String)) := [("Recover", [(0, "strict"), (1, "strict"), (2, "growth1"), (3, "growth0"), (4, "growth0")]), ("Drive", [(0, "strict"), (1, "strict"), (2, "growth1"), (3, "growth0"), (4, "growth0")]), ("Safe", [(0, "strict"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "growth0")])]
def rover_dof_terrain_rung1_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "strict"), (4, "strict")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "strict"), (4, "strict")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "strict"), (4, "strict")])]
def rover_dof_terrain_rung2_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "strict"), (8, "strict"), (9, "growth0"), (10, "growth0")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "strict"), (8, "strict"), (9, "growth0"), (10, "growth0")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "strict"), (8, "strict"), (9, "growth0"), (10, "growth0")])]
def rover_dof_terrain_rung3_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "growth0"), (9, "growth0"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "growth0"), (20, "growth0"), (21, "strict"), (22, "strict")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "growth0"), (9, "growth0"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "growth0"), (20, "growth0"), (21, "strict"), (22, "strict")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "growth0"), (9, "growth0"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "growth0"), (20, "growth0"), (21, "strict"), (22, "strict")])]
def rover_dof_terrain_rung3_8d_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "strict"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "growth0"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "strict")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "strict"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "growth0"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "strict")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "strict"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "growth0"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "strict")])]
def rover_drag_viab2 : List (String × List (Nat × String)) := [("Track", [(0, "strict"), (1, "strict")])]
def rover_position_viab2 : List (String × List (Nat × String)) := [("Recover", [(0, "strict"), (1, "strict"), (2, "growth1"), (3, "growth0"), (4, "growth0")]), ("Drive", [(0, "strict"), (1, "strict"), (2, "growth1"), (3, "growth0"), (4, "growth0")]), ("Safe", [(0, "strict"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "growth0")])]
def rover_terrain_M1_viab2 : List (String × List (Nat × String)) := [("ROUGH", [(0, "growth0"), (1, "strict"), (2, "strict")]), ("FLAT", [(0, "growth0"), (1, "strict"), (2, "strict")]), ("SMOOTH", [(0, "growth0"), (1, "strict"), (2, "strict")])]
def rover_tier_r1_viab2 : List (String × List (Nat × String)) := [("Cruise", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict")])]
def shield_unreachable_viab2 : List (String × List (Nat × String)) := [("Cruise", []), ("Continue", []), ("Shield", [])]
def story1_attdist_rung_a_6to8_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "strict"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "growth0"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "strict")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "strict"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "growth0"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "strict")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "growth0"), (3, "growth0"), (4, "strict"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "growth0"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "strict")])]
def story1_attdist_rung_b_12dof_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "strict"), (5, "strict"), (6, "growth0"), (7, "growth0"), (8, "growth0"), (9, "growth0"), (10, "strict"), (11, "strict"), (12, "growth2"), (13, "growth2"), (14, "growth0"), (15, "growth2"), (16, "growth2"), (17, "strict"), (18, "strict"), (19, "strict"), (20, "strict"), (21, "strict"), (22, "strict")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "strict"), (5, "strict"), (6, "growth0"), (7, "growth0"), (8, "growth0"), (9, "growth0"), (10, "strict"), (11, "strict"), (12, "growth2"), (13, "growth2"), (14, "growth0"), (15, "growth2"), (16, "growth2"), (17, "strict"), (18, "strict"), (19, "strict"), (20, "strict"), (21, "strict"), (22, "strict")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "strict"), (5, "strict"), (6, "growth0"), (7, "growth0"), (8, "growth0"), (9, "growth0"), (10, "strict"), (11, "strict"), (12, "growth2"), (13, "growth2"), (14, "growth0"), (15, "growth2"), (16, "growth2"), (17, "strict"), (18, "strict"), (19, "strict"), (20, "strict"), (21, "strict"), (22, "strict")])]
def story2_lateral_rung_a_8dof_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "growth1"), (12, "strict"), (13, "strict"), (14, "strict")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "growth1"), (12, "strict"), (13, "strict"), (14, "strict")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "growth1"), (12, "strict"), (13, "strict"), (14, "strict")])]
def story2_lateral_rung_b_12dof_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "growth0"), (12, "growth0"), (13, "growth0"), (14, "growth0"), (15, "growth0"), (16, "growth0"), (17, "growth1"), (18, "strict"), (19, "growth1"), (20, "strict"), (21, "strict"), (22, "strict")]), ("MODER", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "growth0"), (12, "growth0"), (13, "growth0"), (14, "growth0"), (15, "growth0"), (16, "growth0"), (17, "growth1"), (18, "strict"), (19, "growth1"), (20, "strict"), (21, "strict"), (22, "strict")]), ("FLAT", [(0, "growth0"), (1, "growth0"), (2, "strict"), (3, "strict"), (4, "growth0"), (5, "strict"), (6, "strict"), (7, "strict"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "growth0"), (12, "growth0"), (13, "growth0"), (14, "growth0"), (15, "growth0"), (16, "growth0"), (17, "growth1"), (18, "strict"), (19, "growth1"), (20, "strict"), (21, "strict"), (22, "strict")])]
def story3_rollover_base_12dof_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "strict"), (1, "strict"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "growth0"), (13, "growth0"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "growth0"), (20, "growth0"), (21, "growth0"), (22, "growth0")]), ("MODER", [(0, "strict"), (1, "strict"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "growth0"), (13, "growth0"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "growth0"), (20, "growth0"), (21, "growth0"), (22, "growth0")]), ("FLAT", [(0, "strict"), (1, "strict"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "growth0"), (13, "growth0"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "growth0"), (20, "growth0"), (21, "growth0"), (22, "growth0")])]
def story3_rollover_ladder_rung_a_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "strict"), (1, "strict"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "growth0"), (13, "growth0"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "growth0"), (20, "growth0"), (21, "growth0"), (22, "growth0")]), ("MODER", [(0, "strict"), (1, "strict"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "growth0"), (13, "growth0"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "growth0"), (20, "growth0"), (21, "growth0"), (22, "growth0")]), ("FLAT", [(0, "strict"), (1, "strict"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "growth0"), (13, "growth0"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "growth0"), (20, "growth0"), (21, "growth0"), (22, "growth0")])]
def story3_rollover_ladder_rung_b_viab2 : List (String × List (Nat × String)) := [("STEEP", [(0, "growth8"), (1, "growth8"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "growth0"), (20, "growth0"), (21, "growth0"), (22, "growth0")]), ("MODER", [(0, "growth8"), (1, "growth8"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "growth0"), (20, "growth0"), (21, "growth0"), (22, "growth0")]), ("FLAT", [(0, "growth8"), (1, "growth8"), (2, "growth0"), (3, "growth0"), (4, "growth0"), (5, "growth0"), (6, "growth0"), (7, "growth0"), (8, "strict"), (9, "strict"), (10, "strict"), (11, "strict"), (12, "strict"), (13, "strict"), (14, "growth0"), (15, "strict"), (16, "strict"), (17, "strict"), (18, "strict"), (19, "growth0"), (20, "growth0"), (21, "growth0"), (22, "growth0")])]
def watertank_viab2 : List (String × List (Nat × String)) := [("Low", [(0, "strict"), (1, "strict")]), ("Mid", [(0, "strict"), (1, "growth4")]), ("High", [(0, "strict"), (1, "strict")])]

end RelCertifier
