/-
Copyright (c) 2026 relCertifier-lean contributors.
Released under Apache 2.0 license.

# BenchCoversNC aggregator (re-exports the per-benchmark leaves) (GENERATED leaf — do not edit)

Per-benchmark leaf module (X0 modularization): editing one benchmark no longer
re-elaborates the whole instance battery. Import only from whole-suite consumers.
-/
import RelCertifier.Instances.BenchCoversNC.arm_chain_rung1
import RelCertifier.Instances.BenchCoversNC.arm_chain_rung2
import RelCertifier.Instances.BenchCoversNC.arm_fidelity_low
import RelCertifier.Instances.BenchCoversNC.arm_fidelity_mid
import RelCertifier.Instances.BenchCoversNC.arm_refinement
import RelCertifier.Instances.BenchCoversNC.attitude_rate
import RelCertifier.Instances.BenchCoversNC.endurance_gain_M1
import RelCertifier.Instances.BenchCoversNC.endurance_orderlift_1to2
import RelCertifier.Instances.BenchCoversNC.endurance_orderlift_2to3
import RelCertifier.Instances.BenchCoversNC.match_multi_eps
import RelCertifier.Instances.BenchCoversNC.match_multi_rate
import RelCertifier.Instances.BenchCoversNC.plant_fan_low
import RelCertifier.Instances.BenchCoversNC.plant_fan_mid
import RelCertifier.Instances.BenchCoversNC.refinement_ladder_rover_rung2_3to6
import RelCertifier.Instances.BenchCoversNC.refinement_ladder_rover_rung2_6dof
import RelCertifier.Instances.BenchCoversNC.refinement_ladder_rover_rung2b_6dof
import RelCertifier.Instances.BenchCoversNC.refinement_ladder_rover_rung2c_6dof
import RelCertifier.Instances.BenchCoversNC.robot_braking
import RelCertifier.Instances.BenchCoversNC.rover3_M1
import RelCertifier.Instances.BenchCoversNC.rover3tier_M1
import RelCertifier.Instances.BenchCoversNC.rover3tier_rung12
import RelCertifier.Instances.BenchCoversNC.rover_4d_box
import RelCertifier.Instances.BenchCoversNC.rover_coupled
import RelCertifier.Instances.BenchCoversNC.rover_drag
import RelCertifier.Instances.BenchCoversNC.rover_position
import RelCertifier.Instances.BenchCoversNC.rover_terrain_M1
import RelCertifier.Instances.BenchCoversNC.rover_tier_r1
import RelCertifier.Instances.BenchCoversNC.story1_attdist_rung_a_6to8
import RelCertifier.Instances.BenchCoversNC.story1_attdist_rung_b_12dof
import RelCertifier.Instances.BenchCoversNC.story2_lateral_rung_a_8dof
import RelCertifier.Instances.BenchCoversNC.story2_lateral_rung_b_12dof
import RelCertifier.Instances.BenchCoversNC.story3_rollover_ladder_rung_b
import RelCertifier.Instances.BenchCoversNC.watertank
