/-
Copyright (c) 2026 relCertifier-lean contributors.
Released under Apache 2.0 license.

# T3+ — `endurance_orderlift_1to2`, modal Theorem 3 (multiF, GENERATED)

Generated by `scripts/gen_multif_instance.py` from the coordinate spec: the plain
list-invariant pattern at n = 3 with 1 invariant components in the cover's
stratified-DC order, the one-way terrain chain, and climb dispatch. Existence is
Z3-free (stratified faces).

Residuals: six stratified-DC verdict packs (`VerdO l m`). Axioms: the standard
three + `z3_unsat_sound` at those leaves.
-/
import RelCertifier.Proofs.Encoding.EnvelopeChainM
import RelCertifier.Proofs.Encoding.RepoPrefixR
import RelCertifier.Proofs.Encoding.Reparam
import RelCertifier.Proofs.Encoding.WindowRF
import RelCertifier.Proofs.Encoding.CanonicalInv
import RelCertifier.Proofs.Encoding.CoverInstance
import RelCertifier.Proofs.Flow.StratifiedFaces
import RelCertifier.Instances.BenchIR.endurance_orderlift_1to2

namespace RelCertifier
namespace EnduranceOrderlift1to2Modal

open DL DLCalTiming DLRel Parse Set

set_option maxHeartbeats 12800000

def vsO : List String := ["v", "s", "a"]
def dummyO : Parse.PMode := ⟨"", [], .tt, .tt, []⟩
def mLO (l : ℕ) : Parse.PMode := endurance_orderlift_1to2_IR.L.modes.getD l dummyO
def mRO (q : ℕ) : Parse.PMode := endurance_orderlift_1to2_IR.R.modes.getD q dummyO

abbrev mvO : Var 3 := (Side.Aux, 0)
abbrev aO : Fin 3 := (1 : Fin 3)
abbrev tgO : Var 3 := (Side.Aux, aO)

noncomputable def fLO (l : ℕ) : Fin 3 → Term (Var 3) := hostDyn vsO 3 Side.L (mLO l)
noncomputable def fRO (q : ℕ) : Fin 3 → Term (Var 3) := hostDyn vsO 3 Side.R (mRO q)
noncomputable def domLO : Formula (Var 3) := hostEvolve vsO 3 Side.L (mLO 0)
noncomputable def domRO : Formula (Var 3) := hostEvolve vsO 3 Side.R (mRO 0)
noncomputable def envO : Formula (Var 3) := Formula.and domLO domRO

def atomsOf : Parse.PForm → List Parse.PForm
  | .and x y => atomsOf x ++ atomsOf y
  | f => [f]

def invOPF : Parse.PForm :=
  (endurance_orderlift_1to2_IR.invariants.getD 0 ("", Parse.PForm.tt)).2

noncomputable def gAt (i : ℕ) : Term (Var 3) :=
  ((Run.invToG vsO 3 ((atomsOf invOPF).getD i .tt)).map ITerm.toHost).getD (Term.const 0)

noncomputable def gO : Term (Var 3) := gAt 0
noncomputable def gsO : List (Term (Var 3)) := []

/-! ## Side-splits -/

theorem fLO_pipe (l : ℕ) (i : Fin 3) : fLO l i =
    (((some (mLO l)).bind (Run.dynOf vsO 3 Side.L)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem fRO_pipe (q : ℕ) (i : Fin 3) : fRO q i =
    (((some (mRO q)).bind (Run.dynOf vsO 3 Side.R)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem domLO_pipe : domLO =
    (((some (mLO 0)).bind (fun m => Run.lowerF vsO 3 Side.L m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl
theorem domRO_pipe : domRO =
    (((some (mRO 0)).bind (fun m => Run.lowerF vsO 3 Side.R m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl

theorem hfLO (l : ℕ) (hl : l < 3) : ∀ i, (fLO l i).fv ⊆ range Lv := fun i x hx =>
  side_eq_L_mem (field_pipeline_side (resolvesTo_L vsO) (some (mLO l))
    (by interval_cases l <;>
      simp [mLO, endurance_orderlift_1to2_IR, Parse.PExpr.namesFree]) i x
    (fLO_pipe l i ▸ hx))

theorem hfRO (q : ℕ) (hq : q < 3) : ∀ i, (fRO q i).fv ⊆ range Rv := fun i x hx =>
  side_eq_R_mem (field_pipeline_side (resolvesTo_R vsO) (some (mRO q))
    (by interval_cases q <;>
      simp [mRO, endurance_orderlift_1to2_IR, Parse.PExpr.namesFree]) i x
    (fRO_pipe q i ▸ hx))

theorem hdomLO : domLO.fv ⊆ range Lv := fun x hx =>
  side_eq_L_mem (form_pipeline_side (resolvesTo_L vsO) (some (mLO 0))
    (by simp [mLO, endurance_orderlift_1to2_IR, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domLO_pipe ▸ hx))

theorem hdomRO : domRO.fv ⊆ range Rv := fun x hx =>
  side_eq_R_mem (form_pipeline_side (resolvesTo_R vsO) (some (mRO 0))
    (by simp [mRO, endurance_orderlift_1to2_IR, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domRO_pipe ▸ hx))

theorem hgAt (i : ℕ) : (gAt i).fv ⊆ range Lv ∪ range Rv := invToG_pipeline_LR _

theorem hmvg : ∀ g' ∈ gO :: gsO, mvO ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [gO, gsO, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with rfl <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem htgg : ∀ g' ∈ gO :: gsO, tgO ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [gO, gsO, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with rfl <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem hmvFO : mvO ∉ (FM gO gsO).fv := notMem_FM_fv hmvg
theorem htgFO : tgO ∉ (FM gO gsO).fv := notMem_FM_fv htgg

theorem hmvenvO : mvO ∉ envO.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomLO h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomRO h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))
theorem htgenvO : tgO ∉ envO.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomLO h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomRO h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))

/-! ## The right graph (one-way chain) -/

noncomputable def modeO (q : ℕ) : RMode (Var 3) :=
  { sys := rightBlock (fRO q) (Term.const 1), dom := domRO, weight := 1 }

def edgeO (st tgt : ℕ) : REdge (Var 3) :=
  { src := st, tgt := tgt, guard := Formula.tt, pruned := false }

noncomputable def GrO : SearchGraph (Var 3) :=
  { modes := [modeO 0, modeO 1, modeO 2],
    edges := [edgeO 0 1, edgeO 0 0, edgeO 1 2, edgeO 1 1, edgeO 2 2] }

theorem GrO_modeAt (q : ℕ) (hq : q < 3) : GrO.modeAt q = some (modeO q) := by
  interval_cases q <;> rfl

theorem httO : ∀ q, ∀ e ∈ GrO.edgesFrom q, e.guard = Formula.tt := by
  intro q e he
  have hmem : e ∈ GrO.edges := List.mem_of_mem_filter he
  simp only [GrO, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> rfl

theorem hltO : ∀ q, ∀ e ∈ GrO.edgesFrom q, e.tgt < GrO.modes.length := by
  intro q e he
  have hmem : e ∈ GrO.edges := List.mem_of_mem_filter he
  simp only [GrO, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> norm_num [GrO, edgeO]

theorem hRvO : ∀ q m, GrO.modeAt q = some m →
    m.sys.boundSet ∪ m.sys.readVars ∪ m.dom.fv ⊆ range Rv := by
  intro q m hm
  have hqm : q < 3 ∧ m = modeO q := by
    match q with
    | 0 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrO] using hm.symm⟩
    | 1 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrO] using hm.symm⟩
    | 2 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrO] using hm.symm⟩
    | q + 3 => exact absurd hm (by simp [SearchGraph.modeAt, GrO])
  obtain ⟨hq3, rfl⟩ := hqm
  intro y hy
  rcases hy with (hy | hy) | hy
  · exact rightBlock_boundSet_sub (fRO q) (Term.const 1) hy
  · exact rightBlock_readVars_sub (fRO q) (Term.const 1) (hfRO q hq3)
      (by simp [Term.fv]) hy
  · exact hdomRO hy

theorem edgeO_mem : ∀ st tgt, edgeO st tgt ∈ GrO.edges →
    edgeO st tgt ∈ GrO.edgesFrom st :=
  fun st tgt he => List.mem_filter.mpr ⟨he, by simp [edgeO]⟩

theorem hfreshO : ∀ q m, GrO.modeAt q = some m →
    mvO ∉ (Program.ode m.sys m.dom).fv := by
  intro q m hm hmv
  exact aux_notin_range_Rv 0 (hRvO q m hm (vars_ode_sub _ _ (Or.inl hmv)))

/-! ## The left window family -/

noncomputable def leftDataO : List ((Fin 3 → Term (Var 3)) × Formula (Var 3) × ℕ) :=
  [(fLO 0, domLO, 4), (fLO 1, domLO, 4), (fLO 2, domLO, 4)]

noncomputable def leftProgsO (dt : ℝ) : List (Program (Var 3)) :=
  leftDataO.map (fun d => windowSeg (leftBlock d.1) d.2.1 tgO dt d.2.2)

theorem hLO : ∀ d ∈ leftDataO, (∀ i, (d.1 i).fv ⊆ range Lv) ∧ d.2.1.fv ⊆ range Lv := by
  intro d hd
  simp only [leftDataO, List.mem_cons, List.not_mem_nil, or_false] at hd
  rcases hd with rfl | rfl | rfl
  · exact ⟨hfLO 0 (by norm_num), hdomLO⟩
  · exact ⟨hfLO 1 (by norm_num), hdomLO⟩
  · exact ⟨hfLO 2 (by norm_num), hdomLO⟩

theorem hframesO (dt : ℝ) : ∀ P ∈ leftProgsO dt, FramesMv P mvO := by
  intro P hP
  simp only [leftProgsO, List.mem_map] at hP
  obtain ⟨d, hd, rfl⟩ := hP
  refine framesMv_window (leftBlock d.1) d.2.1 tgO dt d.2.2 mvO (by decide) ?_
  intro h
  obtain ⟨i, hi⟩ := leftBlock_bound_sub d.1 _ h
  exact aux_ne_Lv 0 i hi

/-! ## Parse pins -/

theorem ho030 : Run.parseRat "0.30" = some ((3:ℚ)/10) := by
  have h : parseQ "0.30" = some (⟨30, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem ho050 : Run.parseRat "0.50" = some ((1:ℚ)/2) := by
  have h : parseQ "0.50" = some (⟨50, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem ho065 : Run.parseRat "0.65" = some ((13:ℚ)/20) := by
  have h : parseQ "0.65" = some (⟨65, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem ho3 : Run.parseRat "3" = some (3) := by
  have h : parseQ "3" = some (⟨3, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem ho0 : Run.parseRat "0" = some (0) := by
  have h : parseQ "0" = some (⟨0, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem ho1 : Run.parseRat "1" = some (1) := by
  have h : parseQ "1" = some (⟨1, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hom05 : Run.parseRat "-0.5" = some (-(1:ℚ)/2) := by
  have h : parseQ "-0.5" = some (⟨-5, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem ho07 : Run.parseRat "0.7" = some ((7:ℚ)/10) := by
  have h : parseQ "0.7" = some (⟨7, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem ho00 : Run.parseRat "0.0" = some (0) := by
  have h : parseQ "0.0" = some (⟨0, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem ho08 : Run.parseRat "0.8" = some ((4:ℚ)/5) := by
  have h : parseQ "0.8" = some (⟨8, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num

/-! ## Field and shape pins -/

noncomputable def cstO (q : ℕ) : ℝ := if q = 0 then 3/10 else if q = 1 then 1/2 else 13/20

theorem fRO0_eval (q : ℕ) (hq : q < 3) (x : State (Var 3)) :
    Term.eval (fRO q 0) x = 3 * (cstO q - x (Rv 0)) := by
  interval_cases q <;>
    simp [fRO, hostDyn, mRO, endurance_orderlift_1to2_IR, vsO, Run.dynOf,
      Run.lowerE, ho030, ho050, ho065, ho3, ho0, ho1, hom05, ho07, ho00, ho08, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv, cstO]
theorem fRO1_eval (q : ℕ) (hq : q < 3) (x : State (Var 3)) :
    Term.eval (fRO q 1) x = x (Rv 0) := by
  interval_cases q <;>
    simp [fRO, hostDyn, mRO, endurance_orderlift_1to2_IR, vsO, Run.dynOf,
      Run.lowerE, ho030, ho050, ho065, ho3, ho0, ho1, hom05, ho07, ho00, ho08, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRO2_eval (q : ℕ) (hq : q < 3) (x : State (Var 3)) :
    Term.eval (fRO q 2) x = 0 := by
  interval_cases q <;>
    simp [fRO, hostDyn, mRO, endurance_orderlift_1to2_IR, vsO, Run.dynOf,
      Run.lowerE, ho030, ho050, ho065, ho3, ho0, ho1, hom05, ho07, ho00, ho08, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]

theorem sat_domRO (x : State (Var 3)) : Formula.sat domRO x ↔
    (-(1:ℝ)/2 ≤ x (Rv 2) ∧ x (Rv 2) ≤ (7:ℝ)/10 ∧ 0 ≤ x (Rv 1) ∧ 0 ≤ x (Rv 0) ∧ x (Rv 0) ≤ (4:ℝ)/5) := by
  simp only [domRO, hostEvolve, mRO, endurance_orderlift_1to2_IR, vsO]
  simp [Run.lowerF, Run.lowerE, hom05, ho07, ho00, ho08,
    Run.resolveVar, List.findIdx?_cons, IForm.toHost, ITerm.toHost, Formula.sat,
    CompOp.interp, Term.eval, Rv]
  tauto

/-! ## Faces -/

noncomputable def faceVLo : Term (Var 3) :=
  Term.binop AOp.sub (Term.const (0)) (Term.var (Rv 0))
noncomputable def faceVHi : Term (Var 3) :=
  Term.binop AOp.sub (Term.var (Rv 0)) (Term.const ((4:ℝ)/5))
noncomputable def faceSLo : Term (Var 3) :=
  Term.binop AOp.sub (Term.const 0) (Term.var (Rv 1))
noncomputable def faceALo : Term (Var 3) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 2))
noncomputable def faceAHi : Term (Var 3) :=
  Term.binop AOp.sub (Term.var (Rv 2)) (Term.const ((7:ℝ)/10))

noncomputable def gsSO : List (Term (Var 3)) :=
  [faceVLo, faceVHi]
noncomputable def gsNO : List (Term (Var 3)) :=
  [faceSLo, faceALo, faceAHi]

theorem faces_fv_RO : ∀ gT' ∈ gsSO ++ gsNO, ∀ x ∈ gT'.fv, x ∈ range Rv := by
  intro gT' hgT x hx
  simp only [gsSO, gsNO, List.cons_append, List.nil_append, List.mem_cons,
    List.not_mem_nil, or_false] at hgT
  rcases hgT with rfl | rfl | rfl | rfl | rfl <;>
    · simp only [faceVLo, faceVHi, faceSLo, faceALo, faceAHi, Term.fv,
        Set.mem_union, Set.mem_empty_iff_false, false_or, or_false,
        Set.mem_singleton_iff] at hx
      exact ⟨_, hx.symm⟩

/-! ## The frozen-left joint field -/

theorem odeField_RO (q : ℕ) (hq : q < 3) (x : State (Var 3)) :
    odeField (jointSys (fun _ => Term.const 0) (fRO q) (Term.const ((2:ℝ)))) x
      = fun c =>
        if c = Rv 0 then ((2:ℝ)) * (3 * (cstO q - x (Rv 0)))
        else if c = Rv 1 then ((2:ℝ)) * x (Rv 0)
        else 0 := by
  funext c
  by_cases hc : c ∈ (jointSys (fun _ => Term.const 0) (fRO q) (Term.const ((2:ℝ)))).bound
  · rw [show odeField (jointSys (fun _ => Term.const 0) (fRO q) (Term.const ((2:ℝ)))) x c
        = ((jointSys (fun _ => Term.const 0) (fRO q) (Term.const ((2:ℝ)))).rhs c).eval x from by
      simp only [odeField, if_pos hc]]
    obtain ⟨p, hp, hfst⟩ : ∃ p ∈ jointSys (fun _ => Term.const 0) (fRO q) (Term.const ((2:ℝ))),
        p.1 = c := by simpa [ODESystem.bound, List.mem_map] using hc
    rw [← hfst, ODESystem.rhs_eq_of_mem (jointSys_wellFormed _ _ _) hp]
    rw [jointSys_split] at hp
    have hne : ∀ (a b : Fin 3), a ≠ b → (Rv a : Var 3) ≠ Rv b := by
      intro a b hab
      simp [Rv, Prod.ext_iff]
      exact fun h => hab (by exact_mod_cast h)
    rcases List.mem_append.mp hp with hp | hp
    · obtain ⟨j, -, rfl⟩ := List.mem_map.mp hp
      have hLR : ∀ k : Fin 3, (Lv j : Var 3) ≠ Rv k := by
        intro k
        simp [Lv, Rv, Prod.ext_iff]
      simp [Term.eval, hLR 0, hLR 1]
    · obtain ⟨j, -, rfl⟩ := List.mem_map.mp hp
      fin_cases j
      · simp [Term.eval, AOp.interp, fRO0_eval q hq]
      · simp [Term.eval, AOp.interp, fRO1_eval q hq,
          hne 1 0 (by decide)]
      · simp [Term.eval, AOp.interp, fRO2_eval q hq,
          hne 2 0 (by decide),
          hne 2 1 (by decide)]
  · have hnotR : ∀ j : Fin 3, c ≠ Rv j := by
      intro j hceq
      refine hc ?_
      rw [hceq, jointSys_split]
      simp only [ODESystem.bound, List.map_append, List.mem_append]
      exact Or.inr (by
        simp only [rightBlock, List.map_map, List.mem_map]
        exact ⟨j, List.mem_finRange j, rfl⟩)
    simp only [odeField, if_neg hc, if_neg (hnotR 0), if_neg (hnotR 1)]

/-! ## Strict inflow -/

theorem hbndS_O (q : ℕ) (hq : q < 3) : ∀ gT' ∈ gsSO, ∀ x : State (Var 3),
    Term.eval gT' x = 0 →
    Lie (jointSys (fun _ => Term.const 0) (fRO q) (Term.const ((2:ℝ))))
      (fun ω => Term.eval gT' ω) x < 0 := by
  have hne : ∀ (a b : Fin 3), a ≠ b → (Rv a : Var 3) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro gT' hgT x hface
  simp only [gsSO, List.mem_cons, List.not_mem_nil, or_false] at hgT
  rcases hgT with rfl | rfl
  · have hx : x (Rv 0) = 0 := by
      simp only [faceVLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 3) => Term.eval faceVLo ω)
        = fun y => (-1 : ℝ) * y (Rv 0) + (0) := by
      funext y; simp [faceVLo, Term.eval, AOp.interp]
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 0) (-1) (0) x,
      odeField_RO q hq]
    simp only [eq_self_iff_true, if_true, if_pos rfl, hx]
    interval_cases q <;> norm_num [cstO]
  · have hx : x (Rv 0) = (4:ℝ)/5 := by
      simp only [faceVHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 3) => Term.eval faceVHi ω)
        = fun y => (1 : ℝ) * y (Rv 0) + (-((4:ℝ)/5)) := by
      funext y; simp [faceVHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 0) 1 (-((4:ℝ)/5)) x,
      odeField_RO q hq]
    simp only [eq_self_iff_true, if_true, if_pos rfl, hx]
    interval_cases q <;> norm_num [cstO]

/-! ## Non-strict faces -/

theorem hbndN_O (q : ℕ) (hq : q < 3) : ∀ i (hi : i < gsNO.length),
    ∀ x : State (Var 3),
    (∀ gT' ∈ gsSO ++ ([] : List (Term (Var 3))), Term.eval gT' x ≤ 0) →
    Lie (jointSys (fun _ => Term.const 0) (fRO q) (Term.const ((2:ℝ))))
      (fun ω => Term.eval gsNO[i] ω) x ≤ 0 := by
  have hne : ∀ (a b : Fin 3), a ≠ b → (Rv a : Var 3) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro i hi x hx
  have hib : i < 3 := by simpa [gsNO] using hi
  interval_cases i
  · show Lie _ (fun ω => Term.eval faceSLo ω) x ≤ 0
    have hv0 : 0 ≤ x (Rv 0) := by
      have := hx faceVLo (List.mem_append_left _ (by simp [gsSO]))
      simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
    have hfun : (fun ω : State (Var 3) => Term.eval faceSLo ω)
        = fun y => (-1 : ℝ) * y (Rv 1) + 0 := by
      funext y; simp [faceSLo, Term.eval, AOp.interp]
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 1) (-1) 0 x,
      odeField_RO q hq]
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    linarith
  · show Lie _ (fun ω => Term.eval faceALo ω) x ≤ 0
    have hfun : (fun ω : State (Var 3) => Term.eval faceALo ω)
        = fun y => (-1 : ℝ) * y (Rv 2) + (-(1:ℝ)/2) := by
      funext y; simp [faceALo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 2) (-1) (-(1:ℝ)/2) x,
      odeField_RO q hq]
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceAHi ω) x ≤ 0
    have hfun : (fun ω : State (Var 3) => Term.eval faceAHi ω)
        = fun y => (1 : ℝ) * y (Rv 2) + (-((7:ℝ)/10)) := by
      funext y; simp [faceAHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 2) 1 (-((7:ℝ)/10)) x,
      odeField_RO q hq]
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide))]
    norm_num

/-! ## Lipschitz and field bound -/

theorem hLip_O (q : ℕ) (hq : q < 3) (ν : State (Var 3)) :
    LipschitzOnWith 20 (odeField (jointSys (fun _ => Term.const 0) (fRO q) (Term.const ((2:ℝ)))))
      (Metric.closedBall ν 1) := by
  have hne : ∀ (a b : Fin 3), a ≠ b → (Rv a : Var 3) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  rw [lipschitzOnWith_iff_dist_le_mul]
  intro x hx y hy
  rw [Metric.mem_closedBall] at hx hy
  rw [odeField_RO q hq, odeField_RO q hq]
  have hdc : ∀ j : Fin 3, |x (Rv j) - y (Rv j)| ≤ dist x y := by
    intro j
    have h := dist_le_pi_dist x y (Rv j)
    rwa [Real.dist_eq] at h
  have hd : (0:ℝ) ≤ dist x y := dist_nonneg
  have hcoe : ((20 : NNReal) : ℝ) = 20 := rfl
  rw [hcoe]
  refine dist_pi_le_iff (by positivity) |>.mpr ?_
  intro c
  by_cases hc0 : c = Rv 0
  · subst hc0
    simp only [eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |3 * (cstO q - x (Rv 0)) - 3 * (cstO q - y (Rv 0))| ≤ 3 * dist x y := by
      have hdiff : 3 * (cstO q - x (Rv 0)) - 3 * (cstO q - y (Rv 0)) = -(3 : ℝ) * (x (Rv 0) - y (Rv 0)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(3 : ℝ)| = 3 := by norm_num
      rw [habs]
      nlinarith [hdc 0]
    have hfac : ∀ A B : ℝ, ((2:ℝ)) * A - ((2:ℝ)) * B = ((2:ℝ)) * (A - B) := by
      intro A B; ring
    rw [hfac, abs_mul, abs_of_pos (show (0:ℝ) < ((2:ℝ)) by norm_num)]
    nlinarith [hcore, hd]
  by_cases hc1 : c = Rv 1
  · subst hc1
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |x (Rv 0) - y (Rv 0)| ≤ 1 * dist x y := by
      have hdiff : x (Rv 0) - y (Rv 0) = (1 : ℝ) * (x (Rv 0) - y (Rv 0)) := by ring
      rw [hdiff, abs_mul]
      have habs : |(1 : ℝ)| = 1 := by norm_num
      rw [habs]
      nlinarith [hdc 0]
    have hfac : ∀ A B : ℝ, ((2:ℝ)) * A - ((2:ℝ)) * B = ((2:ℝ)) * (A - B) := by
      intro A B; ring
    rw [hfac, abs_mul, abs_of_pos (show (0:ℝ) < ((2:ℝ)) by norm_num)]
    nlinarith [hcore, hd]
  · simp only [if_neg hc0, if_neg hc1]
    simp [dist_nonneg]

theorem hfbnd_O (q : ℕ) (hq : q < 3) (ν : State (Var 3))
    (hν : ∀ gT' ∈ gsSO, Term.eval gT' ν ≤ 0) :
    ∀ x ∈ Metric.closedBall ν 1,
      ‖odeField (jointSys (fun _ => Term.const 0) (fRO q) (Term.const ((2:ℝ)))) x‖
        ≤ ((40:NNReal) : ℝ) := by
  have hne : ∀ (a b : Fin 3), a ≠ b → (Rv a : Var 3) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro x hx
  rw [Metric.mem_closedBall] at hx
  have hbandf : ∀ (j : Fin 3) (lo hi : ℝ),
      lo ≤ ν (Rv j) → ν (Rv j) ≤ hi → -2 ≤ lo → hi ≤ 2 → |x (Rv j)| ≤ 3 := by
    intro j lo hi hl hh hlo1 hhi1
    have h := dist_le_pi_dist x ν (Rv j)
    rw [Real.dist_eq] at h
    have hνb : |ν (Rv j)| ≤ 2 := abs_le.mpr ⟨by linarith, by linarith⟩
    have h2 := abs_sub_abs_le_abs_sub (x (Rv j)) (ν (Rv j))
    linarith [abs_le.mp hνb, hx]
  have hxb0 : |x (Rv 0)| ≤ 3 := by
    refine hbandf 0 (0) ((4:ℝ)/5) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν faceVLo (by simp [gsSO])
      simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
    · have := hν faceVHi (by simp [gsSO])
      simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
  rw [odeField_RO q hq]
  refine pi_norm_le_iff_of_nonneg (by norm_num) |>.mpr ?_
  intro c
  have hLcoe : ((40:NNReal) : ℝ) = 40 := rfl
  rw [hLcoe]
  by_cases hc0 : c = Rv 0
  · subst hc0
    simp only [eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcst : 0 ≤ cstO q ∧ cstO q ≤ 1 := by
      interval_cases q <;> norm_num [cstO]
    have hcore : |3 * (cstO q - x (Rv 0))| ≤ 12 := by
      obtain ⟨hcl, hch⟩ := hcst
      rw [abs_le]
      constructor <;> nlinarith [abs_le.mp hxb0]
    rw [show ((2:ℝ)) * (3 * (cstO q - x (Rv 0))) = ((2:ℝ)) * (3 * (cstO q - x (Rv 0))) from by ring, abs_mul,
      abs_of_pos (show (0:ℝ) < ((2:ℝ)) by norm_num)]
    nlinarith [hcore, abs_nonneg (3 * (cstO q - x (Rv 0)))]
  by_cases hc1 : c = Rv 1
  · subst hc1
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcore : |x (Rv 0)| ≤ 3 := hxb0
    rw [show ((2:ℝ)) * (x (Rv 0)) = ((2:ℝ)) * (x (Rv 0)) from by ring, abs_mul,
      abs_of_pos (show (0:ℝ) < ((2:ℝ)) by norm_num)]
    nlinarith [hcore, abs_nonneg (x (Rv 0))]
  · simp only [if_neg hc0, if_neg hc1]
    norm_num

/-! ## Existence -/

theorem esO (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt) :
    ∀ σ, Formula.sat (Formula.and (FM gO gsO) envO) σ →
      HExistSegB (fLO l) (fRO m) (Term.const ((2:ℝ))) domLO domRO dt
        (Function.update σ tgO 0) := by
  intro σ hσ
  have hR : Formula.sat domRO σ := hσ.2.2
  rw [sat_domRO] at hR
  obtain ⟨hd2l, hd2h, hd1l, hd0l, hd0h⟩ := hR
  have hupd : ∀ j : Fin 3, σ (Side.R, j) = Function.update σ tgO 0 (Side.R, j) := by
    intro j
    rw [Function.update_of_ne (by simp [tgO, Prod.ext_iff])]
  have hfS : ∀ gT' ∈ gsSO, Term.eval gT' (Function.update σ tgO 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsSO, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with rfl | rfl <;>
      · first
          | (simp only [faceVLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceVHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
  have hfN : ∀ gT' ∈ gsNO, Term.eval gT' (Function.update σ tgO 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsNO, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with rfl | rfl | rfl <;>
      · first
          | (simp only [faceSLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceALo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceAHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
  refine HExistSegB_of_viability_stratified (fLO l) (fRO m) (Term.const ((2:ℝ)))
    domLO domRO gsSO [] gsNO 0 le_rfl
    (jointSys_wellFormed _ _ _)
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLO l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_RO gT' (by
        rcases List.mem_append.mp hgT with h | h
        · exact List.mem_append_left _ h
        · exact absurd h (List.not_mem_nil)) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLO l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_RO gT' (List.mem_append_right _ hgT) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro gT' hgT x _ hface
      exact hbndS_O m hm gT' hgT x hface)
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))
    (by
      intro i hi x hxs _
      exact hbndN_O m hm i hi x hxs)
    (by
      intro x hS hN
      have hS' : ∀ gT' ∈ gsSO, Term.eval gT' x ≤ 0 :=
        fun gT' hgT => hS gT' (List.mem_append_left _ hgT)
      have hb0l : 0 ≤ x (Rv 0) := by
        have := hS' faceVLo (by simp [gsSO])
        simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
      have hb0h : x (Rv 0) ≤ (4:ℝ)/5 := by
        have := hS' faceVHi (by simp [gsSO])
        simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
      have hb1l : 0 ≤ x (Rv 1) := by
        have := hN faceSLo (by simp [gsNO])
        simp only [faceSLo, Term.eval, AOp.interp] at this; linarith
      have hb2l : -(1:ℝ)/2 ≤ x (Rv 2) := by
        have := hN faceALo (by simp [gsNO])
        simp only [faceALo, Term.eval, AOp.interp] at this; linarith
      have hb2h : x (Rv 2) ≤ (7:ℝ)/10 := by
        have := hN faceAHi (by simp [gsNO])
        simp only [faceAHi, Term.eval, AOp.interp] at this; linarith
      exact (sat_domRO x).mpr ⟨hb2l, hb2h, hb1l, hb0l, hb0h⟩)
    20 40 1 one_pos
    (fun ν0 _ => hLip_O m hm ν0)
    (fun ν0 h0 => hfbnd_O m hm ν0 (fun gT hgT => h0 gT (List.mem_append_left _ hgT)))
    dt hdt
    (Function.update σ tgO 0)
    hfS
    hfN
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))

/-! ## The route verdicts (stratified-DC at the cover's λ) -/

def VerdO (l m : ℕ) : Prop :=
  ∀ i (hi : i < (gO :: gsO).length),
    z3solve (flowQuery ⟨(gO :: gsO)[i], fLO l, fRO m, Term.const ((2:ℝ)),
      strataDomHost (Formula.and domLO domRO) ((gO :: gsO).take i)⟩) = Verdict.unsat
    ∨ z3solve (flowQueryStrict ⟨(gO :: gsO)[i], fLO l, fRO m, Term.const ((2:ℝ)),
      strataDomHost (Formula.and domLO domRO) ((gO :: gsO).take i)⟩) = Verdict.unsat
    ∨ z3solve (flowQuerySuperlevel ⟨(gO :: gsO)[i], fLO l, fRO m, Term.const ((2:ℝ)),
      strataDomHost (Formula.and domLO domRO) ((gO :: gsO).take i)⟩) = Verdict.unsat

/-! ## The coupling at λ, and its λ = 1 transport (L7) -/

theorem coupleO (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdO l m) :
    ∀ σ', Formula.sat (Formula.and (FM gO gsO) envO) σ' → σ' tgO = 0 →
      faModalB (Equiv.refl (Var 3))
        (Program.ode (DLCalTiming.clk tgO (leftBlock (fLO l))) domLO)
        (Program.ode (rightBlock (fRO m) (Term.const ((2:ℝ)))) domRO)
        (Formula.and (FM gO gsO) envO) tgO dt σ' := by
  intro σ' hσ' htg0
  have hupd : Function.update σ' tgO (0 : ℝ) = σ' := by
    funext x
    by_cases hx : x = tgO
    · subst hx; rw [Function.update_self]; exact htg0.symm
    · rw [Function.update_of_ne hx]
  have hAll := segPresAll_from_strata_verdicts' (fLO l) (fRO m) (Term.const ((2:ℝ)))
    (Formula.and domLO domRO) (gO :: gsO) hv
  have hboxes : ∀ g' ∈ gO :: gsO, Formula.sat (Formula.box (Program.ode
      (leftBlock (fLO l) ++ rightBlock (fRO m) (Term.const ((2:ℝ))))
      (Formula.and domLO domRO)) (invLe g')) σ' := by
    intro g' hg'
    rw [sat_box]
    intro ω hω
    rw [sat_invLe]
    refine hAll σ' ?_ ω (by rw [← jointSys_split] at hω; exact hω) g' hg'
    intro g hg
    exact (sat_FM_iff gO gsO σ').mp hσ'.1 g hg
  have hbase := segment_faModalB_from_certB_list gO gsO (fLO l) (fRO m)
    (Term.const ((2:ℝ))) domLO domRO tgO dt
    (LR_blocks_disjoint _ _ _ (hfLO l hl) (hfRO m hm) (by simp [Term.fv]))
    (fun v hv' => Or.inl (by
      obtain ⟨i, rfl⟩ := hdomLO hv'
      exact Lv_mem_leftBlock_boundSet _ i))
    (fun v hv' => Or.inl (by
      obtain ⟨i, rfl⟩ := hdomRO hv'
      exact Rv_mem_rightBlock_boundSet _ _ i))
    (fun h => by
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLO l) _ h
      exact aux_ne_Lv aO i hi)
    (fun h => aux_notin_range_Lv aO (leftBlock_readVars_sub (fLO l) (hfLO l hl) h))
    (fun h => by
      obtain ⟨i, hi⟩ := rightBlock_bound_sub (fRO m) (Term.const ((2:ℝ))) _ h
      exact aux_ne_Rv aO i hi)
    (fun h => aux_notin_range_Rv aO (rightBlock_readVars_sub (fRO m)
      (Term.const ((2:ℝ))) (hfRO m hm) (by simp [Term.fv]) h))
    (fun h => aux_notin_range_Rv aO (rightBlock_boundSet_sub (fRO m)
      (Term.const ((2:ℝ))) h))
    (fun h => aux_notin_range_Lv aO (hdomLO h))
    (fun h => aux_notin_range_Rv aO (hdomRO h))
    htgg hboxes
    (esO l m hl hm dt hdt σ' hσ')
  rw [hupd] at hbase
  refine faModalB_strengthen_plant ?_ hbase
  intro ν μ hplant hsem
  have hdomLν : Formula.sat domLO ν := sem_ode_ends_in_domain hplant.1
  have hdomRμ : Formula.sat domRO μ := sem_ode_ends_in_domain hsem
  have hdomLμ : Formula.sat domLO μ := by
    rwa [(Formula.coincidence domLO (fun v hv' => sem_ode_mask hsem (by
      obtain ⟨i, rfl⟩ := hdomLO hv'
      intro hb
      obtain ⟨j, hj⟩ := rightBlock_bound_sub (fRO m) (Term.const ((2:ℝ))) _ hb
      exact absurd hj (by simp [Lv, Rv, Prod.ext_iff]))) :
        Formula.sat domLO μ ↔ Formula.sat domLO ν)]
  exact ⟨hdomLμ, hdomRμ⟩

theorem couple1O (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdO l m) :
    ∀ σ, Formula.sat (Formula.and (FM gO gsO) envO) σ →
      faModalB (Equiv.refl (Var 3))
        (Program.ode (DLCalTiming.clk tgO (leftBlock (fLO l))) domLO)
        (Program.ode (rightBlock (fRO m) (Term.const 1)) domRO) (Formula.and (FM gO gsO) envO) tgO dt
        (Function.update σ tgO 0) := by
  intro σ hσ
  have htgφ : tgO ∉ (Formula.and (FM gO gsO) envO).fv := by
    intro h
    rcases h with h | h
    · exact htgFO h
    · exact htgenvO h
  have hupdφ : Formula.sat (Formula.and (FM gO gsO) envO)
      (Function.update σ tgO 0) := by
    rwa [(Formula.coincidence (Formula.and (FM gO gsO) envO) (fun v hv' =>
      Function.update_of_ne (fun hc => htgφ (by rw [← hc]; exact hv')) _ _) :
        Formula.sat (Formula.and (FM gO gsO) envO) _ ↔ _)]
  refine faModalB_monoQ ?_ (coupleO l m hl hm dt hdt hv
    (Function.update σ tgO 0) hupdφ (Function.update_self _ _ _))
  intro ν μ hsem
  exact sem_rightBlock_reparam ((2:ℝ)) 1 (by norm_num) one_pos hsem

/-! ## The window response (4 pieces at the in-place mode) -/

theorem respondO (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdO l m) (path : List ℕ) (hpath : ∀ p ∈ path, p < 3)
    {σ : State (Var 3)}
    (hσ : Formula.sat (Formula.and (FM gO gsO) envO) σ) :
    Formula.sat (faModal (Equiv.refl (Var 3))
      (windowSeg (leftBlock (fLO l)) domLO tgO dt 4)
      (bigSeq ((path.map (fun p => Program.ode (rightBlock (fRO p) (Term.const 1)) domRO))
        ++ [Program.ode (rightBlock (fRO m) (Term.const 1)) domRO,
        Program.ode (rightBlock (fRO m) (Term.const 1)) domRO,
        Program.ode (rightBlock (fRO m) (Term.const 1)) domRO,
        Program.ode (rightBlock (fRO m) (Term.const 1)) domRO]))
      (Formula.and (FM gO gsO) envO)) σ := by
  have hfa := Hmulti_windowRF_prefixed (fLO l) domLO (FM gO gsO) envO
    aO dt 4 htgFO htgenvO
    (path.map (fun p => (⟨fRO p, Term.const 1, domRO⟩ : RepoHop 3)))
    (by
      intro h hh
      obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hh
      exact ⟨hfRO p (hpath p hp), by simp [Term.fv], hdomRO⟩)
    (fun σ' hσ' => hσ'.2.1)
    (by
      intro h hh σ' hσ' htg'
      obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hh
      obtain ⟨ρ, hsem, hρσ⟩ := static_hop_existsR (fR := fRO p)
        (lam := Term.const 1) (domR := domRO) hσ'.2.2
      exact ⟨ρ, hsem, hρσ ▸ hσ'⟩)
    (hfLO l hl) hdomLO
    (List.replicate 4 (Program.ode (rightBlock (fRO m) (Term.const 1)) domRO)) (by simp) (by norm_num)
    (by
      intro Q hQ
      rw [List.eq_of_mem_replicate hQ, Program.rename_refl]
      exact hdisH_progR (⟨fRO m, Term.const 1, domRO⟩ : RepoHop 3)
        (hfRO m hm) (by simp [Term.fv]) hdomRO (hfLO l hl) hdomLO)
    (by
      intro Q hQ σ' hσ'
      rw [List.eq_of_mem_replicate hQ]
      exact couple1O l m hl hm dt hdt hv σ' hσ')
    hσ
  rw [show (path.map (fun p => (⟨fRO p, Term.const 1, domRO⟩ : RepoHop 3))).map
      (fun h => h.progR)
      = path.map (fun p => Program.ode (rightBlock (fRO p) (Term.const 1)) domRO)
    from by rw [List.map_map]; rfl] at hfa
  simpa [List.replicate] using hfa

/-! ## The step provider — every window certifies every mode, so the response
stays in place -/

theorem HmultiO (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : ∀ l m : ℕ, l < 3 → m < 3 → VerdO l m) :
    ∀ P ∈ leftProgsO dt, ∀ (q : ℕ), q < GrO.modes.length → ∀ σ, σ mvO = (q : ℝ) →
      Formula.sat (Formula.and (FM gO gsO) envO) σ →
      ∃ segs : List (ℕ × RMode (Var 3) × REdge (Var 3)),
        (∀ s ∈ segs, GrO.modeAt s.1 = some s.2.1 ∧ s.2.2 ∈ GrO.edgesFrom s.1) ∧
        List.IsChain (fun a b => a.2.2.tgt = b.1) segs ∧
        (∀ s, segs.head? = some s → s.1 = q) ∧
        Formula.sat (faModal (Equiv.refl (Var 3)) P
          (bigSeq (segs.map (fun s => Program.ode s.2.1.sys s.2.1.dom)))
          (Formula.and (FM gO gsO) envO)) σ := by
  intro P hP q hq σ hmv hσ
  have hq3 : q < 3 := by simpa [GrO] using hq
  have hself : GrO.modeAt q = some (modeO q) ∧ edgeO q q ∈ GrO.edgesFrom q := by
    refine ⟨GrO_modeAt q hq3, edgeO_mem q q ?_⟩
    interval_cases q <;> simp [GrO]
  have hstep : ∀ (a b : ℕ × RMode (Var 3) × REdge (Var 3)) rest,
      a.2.2.tgt = b.1 → List.IsChain (fun x y => x.2.2.tgt = y.1) (b :: rest) →
      List.IsChain (fun x y => x.2.2.tgt = y.1) (a :: b :: rest) := by
    intro a b rest hab hrest
    refine hrest.cons ?_
    intro y hy
    rw [List.head?_cons, Option.mem_some_iff] at hy
    subst hy
    exact hab
  have hhead1 : ∀ (a : ℕ × RMode (Var 3) × REdge (Var 3)) rest s,
      (a :: rest : List _).head? = some s → s = a := by
    intro a rest s hs
    simpa [List.head?_cons] using hs.symm
  simp only [leftProgsO, leftDataO, List.map_cons, List.map_nil, List.mem_cons,
    List.not_mem_nil, or_false] at hP
  have halign : ∀ st tgt : ℕ, st < 3 → tgt < 3 → edgeO st tgt ∈ GrO.edges →
      GrO.modeAt st = some (modeO st) ∧ edgeO st tgt ∈ GrO.edgesFrom st :=
    fun st tgt hs ht he => ⟨GrO_modeAt st hs, edgeO_mem st tgt he⟩
  rcases hP with rfl | rfl | rfl
  all_goals interval_cases q
  · refine ⟨[(0, modeO 0, edgeO 0 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl | rfl
      · exact halign 0 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondO 0 1 (by norm_num) (by norm_num) dt hdt (hv 0 1 (by norm_num) (by norm_num)) [0] (by intro p hp; simp only [List.mem_cons, List.not_mem_nil, or_false] at hp; rcases hp with rfl <;> norm_num) hσ
      simpa [modeO, List.replicate] using this
  · refine ⟨[(1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondO 0 1 (by norm_num) (by norm_num) dt hdt (hv 0 1 (by norm_num) (by norm_num)) [] (by simp) hσ
      simpa [modeO, List.replicate] using this
  · refine ⟨[(2, modeO 2, edgeO 2 2), (2, modeO 2, edgeO 2 2), (2, modeO 2, edgeO 2 2), (2, modeO 2, edgeO 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrO])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondO 0 2 (by norm_num) (by norm_num) dt hdt (hv 0 2 (by norm_num) (by norm_num)) [] (by simp) hσ
      simpa [modeO, List.replicate] using this
  · refine ⟨[(0, modeO 0, edgeO 0 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl | rfl
      · exact halign 0 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondO 1 1 (by norm_num) (by norm_num) dt hdt (hv 1 1 (by norm_num) (by norm_num)) [0] (by intro p hp; simp only [List.mem_cons, List.not_mem_nil, or_false] at hp; rcases hp with rfl <;> norm_num) hσ
      simpa [modeO, List.replicate] using this
  · refine ⟨[(1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondO 1 1 (by norm_num) (by norm_num) dt hdt (hv 1 1 (by norm_num) (by norm_num)) [] (by simp) hσ
      simpa [modeO, List.replicate] using this
  · refine ⟨[(2, modeO 2, edgeO 2 2), (2, modeO 2, edgeO 2 2), (2, modeO 2, edgeO 2 2), (2, modeO 2, edgeO 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrO])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondO 1 2 (by norm_num) (by norm_num) dt hdt (hv 1 2 (by norm_num) (by norm_num)) [] (by simp) hσ
      simpa [modeO, List.replicate] using this
  · refine ⟨[(0, modeO 0, edgeO 0 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl | rfl
      · exact halign 0 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondO 2 1 (by norm_num) (by norm_num) dt hdt (hv 2 1 (by norm_num) (by norm_num)) [0] (by intro p hp; simp only [List.mem_cons, List.not_mem_nil, or_false] at hp; rcases hp with rfl <;> norm_num) hσ
      simpa [modeO, List.replicate] using this
  · refine ⟨[(1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1), (1, modeO 1, edgeO 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrO])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondO 2 1 (by norm_num) (by norm_num) dt hdt (hv 2 1 (by norm_num) (by norm_num)) [] (by simp) hσ
      simpa [modeO, List.replicate] using this
  · refine ⟨[(2, modeO 2, edgeO 2 2), (2, modeO 2, edgeO 2 2), (2, modeO 2, edgeO 2 2), (2, modeO 2, edgeO 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrO])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrO])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondO 2 2 (by norm_num) (by norm_num) dt hdt (hv 2 2 (by norm_num) (by norm_num)) [] (by simp) hσ
      simpa [modeO, List.replicate] using this

/-- **`endurance_orderlift_1to2`, modal Theorem 3** (λ = (2:ℝ), k = 4). -/
theorem endurance_orderlift_1to2_modal (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : ∀ l m : ℕ, l < 3 → m < 3 → VerdO l m) :
    RFormula.rvalid (theorem3Form
      (bigChoice (leftProgsO dt))
      (rightAutomatonBody GrO mvO)
      (RFormula.and (RFormula.and (canonInvM gO gsO) (envLR domLO domRO))
        (mvValidR mvO GrO.modes.length))) := by
  refine theorem3_faithful_multiF_LR GrO mvO (FM gO gsO) domLO domRO
    (leftProgsO dt) (canonInvM gO gsO) (encode_canonInvM gO gsO) ?_ ?_ ?_
  · exact hdis_multi GrO 0 1 dt leftDataO (by decide) httO hRvO hLO
  · exact hstep_assembled_multiF GrO mvO (FM gO gsO) envO (leftProgsO dt)
      hmvFO hmvenvO hfreshO httO hltO (hframesO dt)
      (HmultiO dt hdt hv)
  · exact hddF_multiE GrO 0 1 dt leftDataO (canonInvM gO gsO) domLO domRO
      (by decide) httO hRvO hLO
      (canonInvM_varsL gO gsO (by
        intro g' hg'
        simp only [gO, gsO, List.mem_cons, List.not_mem_nil, or_false] at hg'
        rcases hg' with rfl <;> exact hgAt _))
      (canonInvM_varsR gO gsO) hdomLO hdomRO

end EnduranceOrderlift1to2Modal
end RelCertifier
