/-
Copyright (c) 2026 relCertifier-lean contributors.
Released under Apache 2.0 license.

# T3+ — `endurance_orderlift_2to3`, modal Theorem 3 (multiF, GENERATED)

Generated by `scripts/gen_multif_instance.py` from the coordinate spec: the plain
list-invariant pattern at n = 4 with 2 invariant components in the cover's
stratified-DC order, the one-way terrain chain, and climb dispatch. Existence is
Z3-free (stratified faces).

Residuals: six stratified-DC verdict packs (`VerdJ l m`). Axioms: the standard
three + `z3_unsat_sound` at those leaves.
-/
import RelCertifier.Proofs.Encoding.EnvelopeChainM
import RelCertifier.Proofs.Encoding.RepoPrefixR
import RelCertifier.Proofs.Encoding.Reparam
import RelCertifier.Proofs.Encoding.WindowRF
import RelCertifier.Proofs.Encoding.CanonicalInv
import RelCertifier.Proofs.Encoding.CoverInstance
import RelCertifier.Proofs.Flow.AffineFaces2
import RelCertifier.Instances.BenchIR.endurance_orderlift_2to3

namespace RelCertifier
namespace EnduranceOrderlift2to3Modal

open DL DLCalTiming DLRel Parse Set

set_option maxHeartbeats 12800000

def vsJ : List String := ["v", "s", "a", "j"]
def dummyJ : Parse.PMode := ⟨"", [], .tt, .tt, []⟩
def mLJ (l : ℕ) : Parse.PMode := endurance_orderlift_2to3_IR.L.modes.getD l dummyJ
def mRJ (q : ℕ) : Parse.PMode := endurance_orderlift_2to3_IR.R.modes.getD q dummyJ

abbrev mvJ : Var 4 := (Side.Aux, 0)
abbrev aJ : Fin 4 := (1 : Fin 4)
abbrev tgJ : Var 4 := (Side.Aux, aJ)

noncomputable def fLJ (l : ℕ) : Fin 4 → Term (Var 4) := hostDyn vsJ 4 Side.L (mLJ l)
noncomputable def fRJ (q : ℕ) : Fin 4 → Term (Var 4) := hostDyn vsJ 4 Side.R (mRJ q)
noncomputable def domLJ : Formula (Var 4) := hostEvolve vsJ 4 Side.L (mLJ 0)
noncomputable def domRJ : Formula (Var 4) := hostEvolve vsJ 4 Side.R (mRJ 0)
noncomputable def envJ : Formula (Var 4) := Formula.and domLJ domRJ

def atomsOf : Parse.PForm → List Parse.PForm
  | .and x y => atomsOf x ++ atomsOf y
  | f => [f]

def invJPF : Parse.PForm :=
  (endurance_orderlift_2to3_IR.invariants.getD 0 ("", Parse.PForm.tt)).2

noncomputable def gAt (i : ℕ) : Term (Var 4) :=
  ((Run.invToG vsJ 4 ((atomsOf invJPF).getD i .tt)).map ITerm.toHost).getD (Term.const 0)

noncomputable def gJ : Term (Var 4) := gAt 0
noncomputable def gsJ : List (Term (Var 4)) := [gAt 1]

/-! ## Side-splits -/

theorem fLJ_pipe (l : ℕ) (i : Fin 4) : fLJ l i =
    (((some (mLJ l)).bind (Run.dynOf vsJ 4 Side.L)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem fRJ_pipe (q : ℕ) (i : Fin 4) : fRJ q i =
    (((some (mRJ q)).bind (Run.dynOf vsJ 4 Side.R)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem domLJ_pipe : domLJ =
    (((some (mLJ 0)).bind (fun m => Run.lowerF vsJ 4 Side.L m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl
theorem domRJ_pipe : domRJ =
    (((some (mRJ 0)).bind (fun m => Run.lowerF vsJ 4 Side.R m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl

theorem hfLJ (l : ℕ) (hl : l < 3) : ∀ i, (fLJ l i).fv ⊆ range Lv := fun i x hx =>
  side_eq_L_mem (field_pipeline_side (resolvesTo_L vsJ) (some (mLJ l))
    (by interval_cases l <;>
      simp [mLJ, endurance_orderlift_2to3_IR, Parse.PExpr.namesFree]) i x
    (fLJ_pipe l i ▸ hx))

theorem hfRJ (q : ℕ) (hq : q < 3) : ∀ i, (fRJ q i).fv ⊆ range Rv := fun i x hx =>
  side_eq_R_mem (field_pipeline_side (resolvesTo_R vsJ) (some (mRJ q))
    (by interval_cases q <;>
      simp [mRJ, endurance_orderlift_2to3_IR, Parse.PExpr.namesFree]) i x
    (fRJ_pipe q i ▸ hx))

theorem hdomLJ : domLJ.fv ⊆ range Lv := fun x hx =>
  side_eq_L_mem (form_pipeline_side (resolvesTo_L vsJ) (some (mLJ 0))
    (by simp [mLJ, endurance_orderlift_2to3_IR, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domLJ_pipe ▸ hx))

theorem hdomRJ : domRJ.fv ⊆ range Rv := fun x hx =>
  side_eq_R_mem (form_pipeline_side (resolvesTo_R vsJ) (some (mRJ 0))
    (by simp [mRJ, endurance_orderlift_2to3_IR, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domRJ_pipe ▸ hx))

theorem hgAt (i : ℕ) : (gAt i).fv ⊆ range Lv ∪ range Rv := invToG_pipeline_LR _

theorem hmvg : ∀ g' ∈ gJ :: gsJ, mvJ ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [gJ, gsJ, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with rfl | rfl <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem htgg : ∀ g' ∈ gJ :: gsJ, tgJ ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [gJ, gsJ, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with rfl | rfl <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem hmvFJ : mvJ ∉ (FM gJ gsJ).fv := notMem_FM_fv hmvg
theorem htgFJ : tgJ ∉ (FM gJ gsJ).fv := notMem_FM_fv htgg

theorem hmvenvJ : mvJ ∉ envJ.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomLJ h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomRJ h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))
theorem htgenvJ : tgJ ∉ envJ.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomLJ h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomRJ h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))

/-! ## The right graph (one-way chain) -/

noncomputable def modeJ (q : ℕ) : RMode (Var 4) :=
  { sys := rightBlock (fRJ q) (Term.const 1), dom := domRJ, weight := 1 }

def edgeJ (st tgt : ℕ) : REdge (Var 4) :=
  { src := st, tgt := tgt, guard := Formula.tt, pruned := false }

noncomputable def GrJ : SearchGraph (Var 4) :=
  { modes := [modeJ 0, modeJ 1, modeJ 2],
    edges := [edgeJ 0 1, edgeJ 0 0, edgeJ 1 2, edgeJ 1 1, edgeJ 2 2] }

theorem GrJ_modeAt (q : ℕ) (hq : q < 3) : GrJ.modeAt q = some (modeJ q) := by
  interval_cases q <;> rfl

theorem httJ : ∀ q, ∀ e ∈ GrJ.edgesFrom q, e.guard = Formula.tt := by
  intro q e he
  have hmem : e ∈ GrJ.edges := List.mem_of_mem_filter he
  simp only [GrJ, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> rfl

theorem hltJ : ∀ q, ∀ e ∈ GrJ.edgesFrom q, e.tgt < GrJ.modes.length := by
  intro q e he
  have hmem : e ∈ GrJ.edges := List.mem_of_mem_filter he
  simp only [GrJ, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> norm_num [GrJ, edgeJ]

theorem hRvJ : ∀ q m, GrJ.modeAt q = some m →
    m.sys.boundSet ∪ m.sys.readVars ∪ m.dom.fv ⊆ range Rv := by
  intro q m hm
  have hqm : q < 3 ∧ m = modeJ q := by
    match q with
    | 0 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrJ] using hm.symm⟩
    | 1 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrJ] using hm.symm⟩
    | 2 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrJ] using hm.symm⟩
    | q + 3 => exact absurd hm (by simp [SearchGraph.modeAt, GrJ])
  obtain ⟨hq3, rfl⟩ := hqm
  intro y hy
  rcases hy with (hy | hy) | hy
  · exact rightBlock_boundSet_sub (fRJ q) (Term.const 1) hy
  · exact rightBlock_readVars_sub (fRJ q) (Term.const 1) (hfRJ q hq3)
      (by simp [Term.fv]) hy
  · exact hdomRJ hy

theorem edgeJ_mem : ∀ st tgt, edgeJ st tgt ∈ GrJ.edges →
    edgeJ st tgt ∈ GrJ.edgesFrom st :=
  fun st tgt he => List.mem_filter.mpr ⟨he, by simp [edgeJ]⟩

theorem hfreshJ : ∀ q m, GrJ.modeAt q = some m →
    mvJ ∉ (Program.ode m.sys m.dom).fv := by
  intro q m hm hmv
  exact aux_notin_range_Rv 0 (hRvJ q m hm (vars_ode_sub _ _ (Or.inl hmv)))

/-! ## The left window family -/

noncomputable def leftDataJ : List ((Fin 4 → Term (Var 4)) × Formula (Var 4) × ℕ) :=
  [(fLJ 0, domLJ, 2), (fLJ 1, domLJ, 2), (fLJ 2, domLJ, 2)]

noncomputable def leftProgsJ (dt : ℝ) : List (Program (Var 4)) :=
  leftDataJ.map (fun d => windowSeg (leftBlock d.1) d.2.1 tgJ dt d.2.2)

theorem hLJ : ∀ d ∈ leftDataJ, (∀ i, (d.1 i).fv ⊆ range Lv) ∧ d.2.1.fv ⊆ range Lv := by
  intro d hd
  simp only [leftDataJ, List.mem_cons, List.not_mem_nil, or_false] at hd
  rcases hd with rfl | rfl | rfl
  · exact ⟨hfLJ 0 (by norm_num), hdomLJ⟩
  · exact ⟨hfLJ 1 (by norm_num), hdomLJ⟩
  · exact ⟨hfLJ 2 (by norm_num), hdomLJ⟩

theorem hframesJ (dt : ℝ) : ∀ P ∈ leftProgsJ dt, FramesMv P mvJ := by
  intro P hP
  simp only [leftProgsJ, List.mem_map] at hP
  obtain ⟨d, hd, rfl⟩ := hP
  refine framesMv_window (leftBlock d.1) d.2.1 tgJ dt d.2.2 mvJ (by decide) ?_
  intro h
  obtain ⟨i, hi⟩ := leftBlock_bound_sub d.1 _ h
  exact aux_ne_Lv 0 i hi

/-! ## Parse pins -/

theorem hj480 : Run.parseRat "4.80" = some ((24:ℚ)/5) := by
  have h : parseQ "4.80" = some (⟨480, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hj800 : Run.parseRat "8.00" = some (8) := by
  have h : parseQ "8.00" = some (⟨800, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hj1040 : Run.parseRat "10.40" = some ((52:ℚ)/5) := by
  have h : parseQ "10.40" = some (⟨1040, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hj4 : Run.parseRat "4" = some (4) := by
  have h : parseQ "4" = some (⟨4, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hj0 : Run.parseRat "0" = some (0) := by
  have h : parseQ "0" = some (⟨0, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hj1 : Run.parseRat "1" = some (1) := by
  have h : parseQ "1" = some (⟨1, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hj00 : Run.parseRat "0.0" = some (0) := by
  have h : parseQ "0.0" = some (⟨0, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hj28 : Run.parseRat "2.8" = some ((14:ℚ)/5) := by
  have h : parseQ "2.8" = some (⟨28, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hjm16 : Run.parseRat "-1.6" = some (-(8:ℚ)/5) := by
  have h : parseQ "-1.6" = some (⟨-16, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hj14 : Run.parseRat "1.4" = some ((7:ℚ)/5) := by
  have h : parseQ "1.4" = some (⟨14, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hj085 : Run.parseRat "0.85" = some ((17:ℚ)/20) := by
  have h : parseQ "0.85" = some (⟨85, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hj1440 : Run.parseRat "14.40" = some ((72:ℚ)/5) := by
  have h : parseQ "14.40" = some (⟨1440, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hj2400 : Run.parseRat "24.00" = some (24) := by
  have h : parseQ "24.00" = some (⟨2400, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hj3120 : Run.parseRat "31.20" = some ((156:ℚ)/5) := by
  have h : parseQ "31.20" = some (⟨3120, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hj48 : Run.parseRat "48" = some (48) := by
  have h : parseQ "48" = some (⟨48, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hj16b : Run.parseRat "16" = some (16) := by
  have h : parseQ "16" = some (⟨16, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hj3 : Run.parseRat "3" = some (3) := by
  have h : parseQ "3" = some (⟨3, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]

/-! ## Field and shape pins -/

noncomputable def cstJ (q : ℕ) : ℝ := if q = 0 then 24/5 else if q = 1 then 8 else 52/5

theorem fRJ0_eval (q : ℕ) (hq : q < 3) (x : State (Var 4)) :
    Term.eval (fRJ q 0) x = x (Rv 2) - 4 * x (Rv 0) := by
  interval_cases q <;>
    simp [fRJ, hostDyn, mRJ, endurance_orderlift_2to3_IR, vsJ, Run.dynOf,
      Run.lowerE, hj480, hj800, hj1040, hj4, hj0, hj1, hj00, hj28, hjm16, hj14, hj085, hj1440, hj2400, hj3120, hj48, hj16b, hj3, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRJ1_eval (q : ℕ) (hq : q < 3) (x : State (Var 4)) :
    Term.eval (fRJ q 1) x = x (Rv 0) := by
  interval_cases q <;>
    simp [fRJ, hostDyn, mRJ, endurance_orderlift_2to3_IR, vsJ, Run.dynOf,
      Run.lowerE, hj480, hj800, hj1040, hj4, hj0, hj1, hj00, hj28, hjm16, hj14, hj085, hj1440, hj2400, hj3120, hj48, hj16b, hj3, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRJ2_eval (q : ℕ) (hq : q < 3) (x : State (Var 4)) :
    Term.eval (fRJ q 2) x = cstJ q - 4 * x (Rv 2) := by
  interval_cases q <;>
    simp [fRJ, hostDyn, mRJ, endurance_orderlift_2to3_IR, vsJ, Run.dynOf,
      Run.lowerE, hj480, hj800, hj1040, hj4, hj0, hj1, hj00, hj28, hjm16, hj14, hj085, hj1440, hj2400, hj3120, hj48, hj16b, hj3, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv, cstJ]
theorem fRJ3_eval (q : ℕ) (hq : q < 3) (x : State (Var 4)) :
    Term.eval (fRJ q 3) x = 0 := by
  interval_cases q <;>
    simp [fRJ, hostDyn, mRJ, endurance_orderlift_2to3_IR, vsJ, Run.dynOf,
      Run.lowerE, hj480, hj800, hj1040, hj4, hj0, hj1, hj00, hj28, hjm16, hj14, hj085, hj1440, hj2400, hj3120, hj48, hj16b, hj3, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]

theorem sat_domRJ (x : State (Var 4)) : Formula.sat domRJ x ↔
    (0 ≤ x (Rv 2) ∧ x (Rv 2) ≤ (14:ℝ)/5 ∧ -(8:ℝ)/5 ≤ x (Rv 3) ∧ x (Rv 3) ≤ (7:ℝ)/5 ∧ 0 ≤ x (Rv 1) ∧ 0 ≤ x (Rv 0) ∧ x (Rv 0) ≤ (17:ℝ)/20) := by
  simp only [domRJ, hostEvolve, mRJ, endurance_orderlift_2to3_IR, vsJ]
  simp [Run.lowerF, Run.lowerE, hj00, hj28, hjm16, hj14, hj085,
    Run.resolveVar, List.findIdx?_cons, IForm.toHost, ITerm.toHost, Formula.sat,
    CompOp.interp, Term.eval, Rv]
  tauto

/-! ## Faces -/

noncomputable def faceALo : Term (Var 4) :=
  Term.binop AOp.sub (Term.const (0)) (Term.var (Rv 2))
noncomputable def faceAHi : Term (Var 4) :=
  Term.binop AOp.sub (Term.var (Rv 2)) (Term.const ((14:ℝ)/5))
noncomputable def faceVLo : Term (Var 4) :=
  Term.binop AOp.sub (Term.const (0)) (Term.var (Rv 0))
noncomputable def faceVHi : Term (Var 4) :=
  Term.binop AOp.sub (Term.var (Rv 0)) (Term.const ((17:ℝ)/20))
noncomputable def faceSLo : Term (Var 4) :=
  Term.binop AOp.sub (Term.const 0) (Term.var (Rv 1))
noncomputable def faceJLo : Term (Var 4) :=
  Term.binop AOp.sub (Term.const (-(8:ℝ)/5)) (Term.var (Rv 3))
noncomputable def faceJHi : Term (Var 4) :=
  Term.binop AOp.sub (Term.var (Rv 3)) (Term.const ((7:ℝ)/5))

noncomputable def faceVAux : Term (Var 4) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ))) (Term.var (Rv 0))

noncomputable def gsSJ : List (Term (Var 4)) :=
  [faceALo, faceAHi, faceVAux, faceVHi]
noncomputable def gsNJ : List (Term (Var 4)) :=
  [faceJLo, faceJHi]

theorem faces_fv_RJ : ∀ gT' ∈ gsSJ ++ gsNJ, ∀ x ∈ gT'.fv, x ∈ range Rv := by
  intro gT' hgT x hx
  simp only [gsSJ, gsNJ, List.cons_append, List.nil_append, List.mem_cons,
    List.not_mem_nil, or_false] at hgT
  rcases hgT with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
    · simp only [faceALo, faceAHi, faceVAux, faceVLo, faceVHi, faceSLo, faceJLo, faceJHi, Term.fv,
        Set.mem_union, Set.mem_empty_iff_false, false_or, or_false,
        Set.mem_singleton_iff] at hx
      exact ⟨_, hx.symm⟩

/-! ## The frozen-left joint field -/

theorem odeField_RJ (q : ℕ) (hq : q < 3) (x : State (Var 4)) :
    odeField (jointSys (fun _ => Term.const 0) (fRJ q) (Term.const (1))) x
      = fun c =>
        if c = Rv 0 then x (Rv 2) - 4 * x (Rv 0)
        else if c = Rv 1 then x (Rv 0)
        else if c = Rv 2 then cstJ q - 4 * x (Rv 2)
        else 0 := by
  funext c
  by_cases hc : c ∈ (jointSys (fun _ => Term.const 0) (fRJ q) (Term.const (1))).bound
  · rw [show odeField (jointSys (fun _ => Term.const 0) (fRJ q) (Term.const (1))) x c
        = ((jointSys (fun _ => Term.const 0) (fRJ q) (Term.const (1))).rhs c).eval x from by
      simp only [odeField, if_pos hc]]
    obtain ⟨p, hp, hfst⟩ : ∃ p ∈ jointSys (fun _ => Term.const 0) (fRJ q) (Term.const (1)),
        p.1 = c := by simpa [ODESystem.bound, List.mem_map] using hc
    rw [← hfst, ODESystem.rhs_eq_of_mem (jointSys_wellFormed _ _ _) hp]
    rw [jointSys_split] at hp
    have hne : ∀ (a b : Fin 4), a ≠ b → (Rv a : Var 4) ≠ Rv b := by
      intro a b hab
      simp [Rv, Prod.ext_iff]
      exact fun h => hab (by exact_mod_cast h)
    rcases List.mem_append.mp hp with hp | hp
    · obtain ⟨j, -, rfl⟩ := List.mem_map.mp hp
      have hLR : ∀ k : Fin 4, (Lv j : Var 4) ≠ Rv k := by
        intro k
        simp [Lv, Rv, Prod.ext_iff]
      simp [Term.eval, hLR 0, hLR 1, hLR 2]
    · obtain ⟨j, -, rfl⟩ := List.mem_map.mp hp
      fin_cases j
      · simp [Term.eval, AOp.interp, fRJ0_eval q hq]
      · simp [Term.eval, AOp.interp, fRJ1_eval q hq,
          hne 1 0 (by decide)]
      · simp [Term.eval, AOp.interp, fRJ2_eval q hq,
          hne 2 0 (by decide),
          hne 2 1 (by decide)]
      · simp [Term.eval, AOp.interp, fRJ3_eval q hq,
          hne 3 0 (by decide),
          hne 3 1 (by decide),
          hne 3 2 (by decide)]
  · have hnotR : ∀ j : Fin 4, c ≠ Rv j := by
      intro j hceq
      refine hc ?_
      rw [hceq, jointSys_split]
      simp only [ODESystem.bound, List.map_append, List.mem_append]
      exact Or.inr (by
        simp only [rightBlock, List.map_map, List.mem_map]
        exact ⟨j, List.mem_finRange j, rfl⟩)
    simp only [odeField, if_neg hc, if_neg (hnotR 0), if_neg (hnotR 1), if_neg (hnotR 2)]

/-! ## Strict inflow -/

theorem hbndS_J (q : ℕ) (hq : q < 3) : ∀ gT' ∈ gsSJ, ∀ x : State (Var 4),
    (∀ gT'' ∈ gsSJ, Term.eval gT'' x ≤ 0) →
    Term.eval gT' x = 0 →
    Lie (jointSys (fun _ => Term.const 0) (fRJ q) (Term.const (1)))
      (fun ω => Term.eval gT' ω) x < 0 := by
  have hne : ∀ (a b : Fin 4), a ≠ b → (Rv a : Var 4) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro gT' hgT x hsub hface
  have ha0 : 0 ≤ x (Rv 2) := by
    have := hsub faceALo (by simp [gsSJ])
    simp only [faceALo, Term.eval, AOp.interp] at this; linarith
  have ha28 : x (Rv 2) ≤ (14:ℝ)/5 := by
    have := hsub faceAHi (by simp [gsSJ])
    simp only [faceAHi, Term.eval, AOp.interp] at this; linarith
  simp only [gsSJ, List.mem_cons, List.not_mem_nil, or_false] at hgT
  rcases hgT with rfl | rfl | rfl | rfl
  · have hx : x (Rv 2) = 0 := by
      simp only [faceALo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 4) => Term.eval faceALo ω)
        = fun y => (-1 : ℝ) * y (Rv 2) + (0) := by
      funext y; simp [faceALo, Term.eval, AOp.interp]
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 2) (-1) (0) x,
      odeField_RJ q hq]
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)),
      eq_self_iff_true, if_true, if_pos rfl, hx]
    interval_cases q <;> norm_num [cstJ]
  · have hx : x (Rv 2) = (14:ℝ)/5 := by
      simp only [faceAHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 4) => Term.eval faceAHi ω)
        = fun y => (1 : ℝ) * y (Rv 2) + (-((14:ℝ)/5)) := by
      funext y; simp [faceAHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 2) 1 (-((14:ℝ)/5)) x,
      odeField_RJ q hq]
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)),
      eq_self_iff_true, if_true, if_pos rfl, hx]
    interval_cases q <;> norm_num [cstJ]
  · have hx : x (Rv 0) = -1 := by
      simp only [faceVAux, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 4) => Term.eval faceVAux ω)
        = fun y => (0 : ℝ) * y (Rv 2) + (-1 : ℝ) * y (Rv 0) + (-1) := by
      funext y; simp [faceVAux, Term.eval, AOp.interp]; ring
    have hfun2 : (fun ω : State (Var 4) => Term.eval faceVAux ω)
        = fun y => (0 : ℝ) * y (Rv 2) + ((-1 : ℝ) * y (Rv 0) + (-1)) := by
      rw [hfun]; funext y; ring
    rw [hfun, show (fun y : State (Var 4) => (0 : ℝ) * y (Rv 2) + (-1 : ℝ) * y (Rv 0) + (-1))
        = fun y => (-1 : ℝ) * y (Rv 0) + (-1) from by funext y; ring,
      lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 0) (-1) (-1) x,
      odeField_RJ q hq]
    simp only [eq_self_iff_true, if_true, if_pos rfl]
    nlinarith [ha0, hx]
  · have hx : x (Rv 0) = (17:ℝ)/20 := by
      simp only [faceVHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 4) => Term.eval faceVHi ω)
        = fun y => (1 : ℝ) * y (Rv 0) + (-((17:ℝ)/20)) := by
      funext y; simp [faceVHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 0) 1 (-((17:ℝ)/20)) x,
      odeField_RJ q hq]
    simp only [eq_self_iff_true, if_true, if_pos rfl, hx]
    nlinarith [ha28, hx]

/-! ## Non-strict faces -/

theorem hbndN_J (q : ℕ) (hq : q < 3) : ∀ i (hi : i < gsNJ.length),
    ∀ x : State (Var 4),
    (∀ gT' ∈ gsSJ ++ ([] : List (Term (Var 4))), Term.eval gT' x ≤ 0) →
    (∀ gT' ∈ gsNJ.take i, Term.eval gT' x ≤ 0) →
    Lie (jointSys (fun _ => Term.const 0) (fRJ q) (Term.const (1)))
      (fun ω => Term.eval gsNJ[i] ω) x ≤ 0 := by
  have hne : ∀ (a b : Fin 4), a ≠ b → (Rv a : Var 4) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro i hi x hx hN
  have hib : i < 2 := by simpa [gsNJ] using hi
  interval_cases i
  · show Lie _ (fun ω => Term.eval faceJLo ω) x ≤ 0
    have hfun : (fun ω : State (Var 4) => Term.eval faceJLo ω)
        = fun y => (-1 : ℝ) * y (Rv 3) + (-((8:ℝ)/5)) := by
      funext y; simp [faceJLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 3) (-1) (-((8:ℝ)/5)) x,
      odeField_RJ q hq]
    simp only [if_neg (hne 3 0 (by decide)), if_neg (hne 3 1 (by decide)),
      if_neg (hne 3 2 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceJHi ω) x ≤ 0
    have hfun : (fun ω : State (Var 4) => Term.eval faceJHi ω)
        = fun y => (1 : ℝ) * y (Rv 3) + (-((7:ℝ)/5)) := by
      funext y; simp [faceJHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 3) 1 (-((7:ℝ)/5)) x,
      odeField_RJ q hq]
    simp only [if_neg (hne 3 0 (by decide)), if_neg (hne 3 1 (by decide)),
      if_neg (hne 3 2 (by decide))]
    norm_num

/-! ## Lipschitz and field bound -/

theorem hLip_J (q : ℕ) (hq : q < 3) (ν : State (Var 4)) :
    LipschitzOnWith 20 (odeField (jointSys (fun _ => Term.const 0) (fRJ q) (Term.const (1))))
      (Metric.closedBall ν 1) := by
  have hne : ∀ (a b : Fin 4), a ≠ b → (Rv a : Var 4) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  rw [lipschitzOnWith_iff_dist_le_mul]
  intro x hx y hy
  rw [Metric.mem_closedBall] at hx hy
  rw [odeField_RJ q hq, odeField_RJ q hq]
  have hdc : ∀ j : Fin 4, |x (Rv j) - y (Rv j)| ≤ dist x y := by
    intro j
    have h := dist_le_pi_dist x y (Rv j)
    rwa [Real.dist_eq] at h
  have hd : (0:ℝ) ≤ dist x y := dist_nonneg
  have hcoe : ((20 : NNReal) : ℝ) = 20 := rfl
  rw [hcoe]
  refine dist_pi_le_iff (by positivity) |>.mpr ?_
  intro c
  by_cases hc0 : c = Rv 0
  · subst hc0
    simp only [eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hdiff : x (Rv 2) - 4 * x (Rv 0) - (y (Rv 2) - 4 * y (Rv 0))
        = (x (Rv 2) - y (Rv 2)) - 4 * (x (Rv 0) - y (Rv 0)) := by ring
    rw [hdiff]
    have h1 := hdc 2
    have h2 := hdc 0
    have := abs_sub (x (Rv 2) - y (Rv 2)) (4 * (x (Rv 0) - y (Rv 0)))
    have h4 : |4 * (x (Rv 0) - y (Rv 0))| ≤ 4 * dist x y := by
      rw [abs_mul]
      have : |(4:ℝ)| = 4 := by norm_num
      rw [this]
      nlinarith
    calc |(x (Rv 2) - y (Rv 2)) - 4 * (x (Rv 0) - y (Rv 0))|
        ≤ |x (Rv 2) - y (Rv 2)| + |4 * (x (Rv 0) - y (Rv 0))| := by
          rw [sub_eq_add_neg]
          refine (abs_add_le _ _).trans ?_
          rw [abs_neg]
      _ ≤ 20 * dist x y := by nlinarith
  by_cases hc1 : c = Rv 1
  · subst hc1
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    nlinarith [hdc 0]
  by_cases hc2 : c = Rv 2
  · subst hc2
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)),
      eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hdiff : cstJ q - 4 * x (Rv 2) - (cstJ q - 4 * y (Rv 2))
        = -4 * (x (Rv 2) - y (Rv 2)) := by ring
    rw [hdiff, abs_mul]
    have habs : |(-4 : ℝ)| = 4 := by norm_num
    rw [habs]
    nlinarith [hdc 2]
  · simp only [if_neg hc0, if_neg hc1, if_neg hc2]
    simp [dist_nonneg]

theorem hfbnd_J (q : ℕ) (hq : q < 3) (ν : State (Var 4))
    (hν : ∀ gT' ∈ gsSJ, Term.eval gT' ν ≤ 0) :
    ∀ x ∈ Metric.closedBall ν 1,
      ‖odeField (jointSys (fun _ => Term.const 0) (fRJ q) (Term.const (1))) x‖
        ≤ ((32:NNReal) : ℝ) := by
  have hne : ∀ (a b : Fin 4), a ≠ b → (Rv a : Var 4) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro x hx
  rw [Metric.mem_closedBall] at hx
  have hband : ∀ (j : Fin 4) (lo hi : ℝ),
      lo ≤ ν (Rv j) → ν (Rv j) ≤ hi → -3 ≤ lo → hi ≤ 3 → |x (Rv j)| ≤ 4 := by
    intro j lo hi hl hh hlo hhi
    have h := dist_le_pi_dist x ν (Rv j)
    rw [Real.dist_eq] at h
    have hνb : |ν (Rv j)| ≤ 3 := abs_le.mpr ⟨by linarith, by linarith⟩
    have h2 := abs_sub_abs_le_abs_sub (x (Rv j)) (ν (Rv j))
    linarith [abs_le.mp hνb, hx]
  have hxa : |x (Rv 2)| ≤ 4 := by
    refine hband 2 0 ((14:ℝ)/5) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν faceALo (by simp [gsSJ])
      simp only [faceALo, Term.eval, AOp.interp] at this; linarith
    · have := hν faceAHi (by simp [gsSJ])
      simp only [faceAHi, Term.eval, AOp.interp] at this; linarith
  have hxv : |x (Rv 0)| ≤ 4 := by
    refine hband 0 (-1) ((17:ℝ)/20) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν faceVAux (by simp [gsSJ])
      simp only [faceVAux, Term.eval, AOp.interp] at this; linarith
    · have := hν faceVHi (by simp [gsSJ])
      simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
  rw [odeField_RJ q hq]
  refine pi_norm_le_iff_of_nonneg (by norm_num) |>.mpr ?_
  intro c
  have hLcoe : ((32:NNReal) : ℝ) = 32 := rfl
  rw [hLcoe]
  by_cases hc0 : c = Rv 0
  · subst hc0
    simp only [eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have : |x (Rv 2) - 4 * x (Rv 0)| ≤ |x (Rv 2)| + |4 * x (Rv 0)| := by
      rw [sub_eq_add_neg]
      refine (abs_add_le _ _).trans ?_
      rw [abs_neg]
    have h4 : |4 * x (Rv 0)| = 4 * |x (Rv 0)| := by rw [abs_mul]; norm_num
    nlinarith [abs_le.mp hxa, abs_le.mp hxv, abs_nonneg (x (Rv 0)), abs_nonneg (x (Rv 2))]
  by_cases hc1 : c = Rv 1
  · subst hc1
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl,
      Real.norm_eq_abs]
    linarith [abs_le.mp hxv]
  by_cases hc2 : c = Rv 2
  · subst hc2
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)),
      eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcst : 0 ≤ cstJ q ∧ cstJ q ≤ 52/5 := by
      interval_cases q <;> norm_num [cstJ]
    obtain ⟨hcl, hch⟩ := hcst
    rw [abs_le]
    constructor <;> nlinarith [abs_le.mp hxa]
  · simp only [if_neg hc0, if_neg hc1, if_neg hc2]
    simp

/-! ## Existence -/

theorem esJ (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt) :
    ∀ σ, Formula.sat (Formula.and (FM gJ gsJ) envJ) σ →
      HExistSegB (fLJ l) (fRJ m) (Term.const (1)) domLJ domRJ dt
        (Function.update σ tgJ 0) := by
  intro σ hσ
  have hR : Formula.sat domRJ σ := hσ.2.2
  rw [sat_domRJ] at hR
  obtain ⟨hd2l, hd2h, hd3l, hd3h, hd1l, hd0l, hd0h⟩ := hR
  have hupd : ∀ j : Fin 4, σ (Side.R, j) = Function.update σ tgJ 0 (Side.R, j) := by
    intro j
    rw [Function.update_of_ne (by simp [tgJ, Prod.ext_iff])]
  have hfS : ∀ gT' ∈ gsSJ, Term.eval gT' (Function.update σ tgJ 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsSJ, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with rfl | rfl | rfl | rfl <;>
      · first
          | (simp only [faceALo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceAHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceVAux, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceVHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
  have hfN : ∀ gT' ∈ gsNJ, Term.eval gT' (Function.update σ tgJ 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsNJ, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with rfl | rfl | rfl | rfl <;>
      · first
          | (simp only [faceVLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceSLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceJLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceJHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
  refine HExistSegB_of_viability_stratA2 (fLJ l) (fRJ m) (Term.const (1))
    domLJ domRJ gsSJ [] gsNJ 0 le_rfl
    ([] : List (Var 4 × ℝ × ℝ × ℝ))
    [((Rv 0 : Var 4), 4, 0, 0)]
    [((Rv 1 : Var 4), 0)]
    (jointSys_wellFormed _ _ _)
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLJ l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_RJ gT' (by
        rcases List.mem_append.mp hgT with h | h
        · exact List.mem_append_left _ h
        · exact absurd h (List.not_mem_nil)) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLJ l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_RJ gT' (List.mem_append_right _ hgT) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by
      intro p hp hb
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLJ l) _ hb
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro p hp hb
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLJ l) _ hb
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by
      intro p hp
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      norm_num)
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by
      intro p hp
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      norm_num)
    (by
      intro gT' hgT x hsub hface
      exact hbndS_J m hm gT' hgT x
        (fun g hg => hsub g (List.mem_append_left _ hg)) hface)
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))
    (by
      intro i hi x hxs hNs
      exact hbndN_J m hm i hi x hxs hNs)
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by
      intro p hp x hxs _
      have hne : ∀ (a b : Fin 4), a ≠ b → (Rv a : Var 4) ≠ Rv b := by
        intro a b hab
        simp [Rv, Prod.ext_iff]
        exact fun h => hab (by exact_mod_cast h)
      have ha0 : 0 ≤ x (Rv 2) := by
        have := hxs faceALo (List.mem_append_left _ (by simp [gsSJ]))
        simp only [faceALo, Term.eval, AOp.interp] at this; linarith
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      rw [odeField_RJ m hm]
      simp only [eq_self_iff_true, if_true, if_pos rfl]
      show (0:ℝ) - 4 * x (Rv 0) ≤ x (Rv 2) - 4 * x (Rv 0)
      linarith)
    (by
      intro p hp x hxs hn hAU hAL
      have hne : ∀ (a b : Fin 4), a ≠ b → (Rv a : Var 4) ≠ Rv b := by
        intro a b hab
        simp [Rv, Prod.ext_iff]
        exact fun h => hab (by exact_mod_cast h)
      have hv0 : (0:ℝ) ≤ x (Rv 0) := by
        have := hAL ((Rv 0 : Var 4), 4, 0, 0) (by simp)
        simpa using this
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      rw [odeField_RJ m hm]
      simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
      exact hv0)
    (by
      intro x hS hN hAU hAL hML
      have hS' : ∀ gT' ∈ gsSJ, Term.eval gT' x ≤ 0 :=
        fun gT' hgT => hS gT' (List.mem_append_left _ hgT)
      have hb2l : 0 ≤ x (Rv 2) := by
        have := hS' faceALo (by simp [gsSJ])
        simp only [faceALo, Term.eval, AOp.interp] at this; linarith
      have hb2h : x (Rv 2) ≤ (14:ℝ)/5 := by
        have := hS' faceAHi (by simp [gsSJ])
        simp only [faceAHi, Term.eval, AOp.interp] at this; linarith
      have hb3l : -(8:ℝ)/5 ≤ x (Rv 3) := by
        have := hN faceJLo (by simp [gsNJ])
        simp only [faceJLo, Term.eval, AOp.interp] at this; linarith
      have hb3h : x (Rv 3) ≤ (7:ℝ)/5 := by
        have := hN faceJHi (by simp [gsNJ])
        simp only [faceJHi, Term.eval, AOp.interp] at this; linarith
      have hb0l : 0 ≤ x (Rv 0) := by
        have := hAL ((Rv 0 : Var 4), 4, 0, 0) (by simp)
        simpa using this
      have hb0h : x (Rv 0) ≤ (17:ℝ)/20 := by
        have := hS' faceVHi (by simp [gsSJ])
        simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
      have hb1l : 0 ≤ x (Rv 1) := by
        have := hML ((Rv 1 : Var 4), 0) (by simp)
        simpa using this
      exact (sat_domRJ x).mpr ⟨hb2l, hb2h, hb3l, hb3h, hb1l, hb0l, hb0h⟩)
    20 32 1 one_pos
    (fun ν0 _ => hLip_J m hm ν0)
    (fun ν0 h0 => hfbnd_J m hm ν0 (fun gT hgT => h0 gT (List.mem_append_left _ hgT)))
    dt hdt
    (Function.update σ tgJ 0)
    hfS
    hfN
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by
      intro p hp
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      show (0:ℝ) ≤ Function.update σ tgJ 0 (Rv 0)
      rw [← hupd 0]
      linarith)
    (by
      intro p hp
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      show (0:ℝ) ≤ Function.update σ tgJ 0 (Rv 1)
      rw [← hupd 1]
      linarith)
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))

/-! ## The route verdicts (stratified-DC at the cover's λ) -/

def VerdJ (l m : ℕ) : Prop :=
  ∀ i (hi : i < (gJ :: gsJ).length),
    z3solve (flowQuery ⟨(gJ :: gsJ)[i], fLJ l, fRJ m, Term.const (1),
      strataDomHost (Formula.and domLJ domRJ) ((gJ :: gsJ).take i)⟩) = Verdict.unsat
    ∨ z3solve (flowQueryStrict ⟨(gJ :: gsJ)[i], fLJ l, fRJ m, Term.const (1),
      strataDomHost (Formula.and domLJ domRJ) ((gJ :: gsJ).take i)⟩) = Verdict.unsat
    ∨ z3solve (flowQuerySuperlevel ⟨(gJ :: gsJ)[i], fLJ l, fRJ m, Term.const (1),
      strataDomHost (Formula.and domLJ domRJ) ((gJ :: gsJ).take i)⟩) = Verdict.unsat

/-! ## The coupling at λ, and its λ = 1 transport (L7) -/

theorem coupleJ (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdJ l m) :
    ∀ σ', Formula.sat (Formula.and (FM gJ gsJ) envJ) σ' → σ' tgJ = 0 →
      faModalB (Equiv.refl (Var 4))
        (Program.ode (DLCalTiming.clk tgJ (leftBlock (fLJ l))) domLJ)
        (Program.ode (rightBlock (fRJ m) (Term.const (1))) domRJ)
        (Formula.and (FM gJ gsJ) envJ) tgJ dt σ' := by
  intro σ' hσ' htg0
  have hupd : Function.update σ' tgJ (0 : ℝ) = σ' := by
    funext x
    by_cases hx : x = tgJ
    · subst hx; rw [Function.update_self]; exact htg0.symm
    · rw [Function.update_of_ne hx]
  have hAll := segPresAll_from_strata_verdicts' (fLJ l) (fRJ m) (Term.const (1))
    (Formula.and domLJ domRJ) (gJ :: gsJ) hv
  have hboxes : ∀ g' ∈ gJ :: gsJ, Formula.sat (Formula.box (Program.ode
      (leftBlock (fLJ l) ++ rightBlock (fRJ m) (Term.const (1)))
      (Formula.and domLJ domRJ)) (invLe g')) σ' := by
    intro g' hg'
    rw [sat_box]
    intro ω hω
    rw [sat_invLe]
    refine hAll σ' ?_ ω (by rw [← jointSys_split] at hω; exact hω) g' hg'
    intro g hg
    exact (sat_FM_iff gJ gsJ σ').mp hσ'.1 g hg
  have hbase := segment_faModalB_from_certB_list gJ gsJ (fLJ l) (fRJ m)
    (Term.const (1)) domLJ domRJ tgJ dt
    (LR_blocks_disjoint _ _ _ (hfLJ l hl) (hfRJ m hm) (by simp [Term.fv]))
    (fun v hv' => Or.inl (by
      obtain ⟨i, rfl⟩ := hdomLJ hv'
      exact Lv_mem_leftBlock_boundSet _ i))
    (fun v hv' => Or.inl (by
      obtain ⟨i, rfl⟩ := hdomRJ hv'
      exact Rv_mem_rightBlock_boundSet _ _ i))
    (fun h => by
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLJ l) _ h
      exact aux_ne_Lv aJ i hi)
    (fun h => aux_notin_range_Lv aJ (leftBlock_readVars_sub (fLJ l) (hfLJ l hl) h))
    (fun h => by
      obtain ⟨i, hi⟩ := rightBlock_bound_sub (fRJ m) (Term.const (1)) _ h
      exact aux_ne_Rv aJ i hi)
    (fun h => aux_notin_range_Rv aJ (rightBlock_readVars_sub (fRJ m)
      (Term.const (1)) (hfRJ m hm) (by simp [Term.fv]) h))
    (fun h => aux_notin_range_Rv aJ (rightBlock_boundSet_sub (fRJ m)
      (Term.const (1)) h))
    (fun h => aux_notin_range_Lv aJ (hdomLJ h))
    (fun h => aux_notin_range_Rv aJ (hdomRJ h))
    htgg hboxes
    (esJ l m hl hm dt hdt σ' hσ')
  rw [hupd] at hbase
  refine faModalB_strengthen_plant ?_ hbase
  intro ν μ hplant hsem
  have hdomLν : Formula.sat domLJ ν := sem_ode_ends_in_domain hplant.1
  have hdomRμ : Formula.sat domRJ μ := sem_ode_ends_in_domain hsem
  have hdomLμ : Formula.sat domLJ μ := by
    rwa [(Formula.coincidence domLJ (fun v hv' => sem_ode_mask hsem (by
      obtain ⟨i, rfl⟩ := hdomLJ hv'
      intro hb
      obtain ⟨j, hj⟩ := rightBlock_bound_sub (fRJ m) (Term.const (1)) _ hb
      exact absurd hj (by simp [Lv, Rv, Prod.ext_iff]))) :
        Formula.sat domLJ μ ↔ Formula.sat domLJ ν)]
  exact ⟨hdomLμ, hdomRμ⟩

theorem couple1J (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdJ l m) :
    ∀ σ, Formula.sat (Formula.and (FM gJ gsJ) envJ) σ →
      faModalB (Equiv.refl (Var 4))
        (Program.ode (DLCalTiming.clk tgJ (leftBlock (fLJ l))) domLJ)
        (Program.ode (rightBlock (fRJ m) (Term.const 1)) domRJ) (Formula.and (FM gJ gsJ) envJ) tgJ dt
        (Function.update σ tgJ 0) := by
  intro σ hσ
  have htgφ : tgJ ∉ (Formula.and (FM gJ gsJ) envJ).fv := by
    intro h
    rcases h with h | h
    · exact htgFJ h
    · exact htgenvJ h
  have hupdφ : Formula.sat (Formula.and (FM gJ gsJ) envJ)
      (Function.update σ tgJ 0) := by
    rwa [(Formula.coincidence (Formula.and (FM gJ gsJ) envJ) (fun v hv' =>
      Function.update_of_ne (fun hc => htgφ (by rw [← hc]; exact hv')) _ _) :
        Formula.sat (Formula.and (FM gJ gsJ) envJ) _ ↔ _)]
  refine faModalB_monoQ ?_ (coupleJ l m hl hm dt hdt hv
    (Function.update σ tgJ 0) hupdφ (Function.update_self _ _ _))
  intro ν μ hsem
  exact sem_rightBlock_reparam (1) 1 (by norm_num) one_pos hsem

/-! ## The window response (2 pieces at the in-place mode) -/

theorem respondJ (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdJ l m) (path : List ℕ) (hpath : ∀ p ∈ path, p < 3)
    {σ : State (Var 4)}
    (hσ : Formula.sat (Formula.and (FM gJ gsJ) envJ) σ) :
    Formula.sat (faModal (Equiv.refl (Var 4))
      (windowSeg (leftBlock (fLJ l)) domLJ tgJ dt 2)
      (bigSeq ((path.map (fun p => Program.ode (rightBlock (fRJ p) (Term.const 1)) domRJ))
        ++ [Program.ode (rightBlock (fRJ m) (Term.const 1)) domRJ,
        Program.ode (rightBlock (fRJ m) (Term.const 1)) domRJ]))
      (Formula.and (FM gJ gsJ) envJ)) σ := by
  have hfa := Hmulti_windowRF_prefixed (fLJ l) domLJ (FM gJ gsJ) envJ
    aJ dt 2 htgFJ htgenvJ
    (path.map (fun p => (⟨fRJ p, Term.const 1, domRJ⟩ : RepoHop 4)))
    (by
      intro h hh
      obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hh
      exact ⟨hfRJ p (hpath p hp), by simp [Term.fv], hdomRJ⟩)
    (fun σ' hσ' => hσ'.2.1)
    (by
      intro h hh σ' hσ' htg'
      obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hh
      obtain ⟨ρ, hsem, hρσ⟩ := static_hop_existsR (fR := fRJ p)
        (lam := Term.const 1) (domR := domRJ) hσ'.2.2
      exact ⟨ρ, hsem, hρσ ▸ hσ'⟩)
    (hfLJ l hl) hdomLJ
    (List.replicate 2 (Program.ode (rightBlock (fRJ m) (Term.const 1)) domRJ)) (by simp) (by norm_num)
    (by
      intro Q hQ
      rw [List.eq_of_mem_replicate hQ, Program.rename_refl]
      exact hdisH_progR (⟨fRJ m, Term.const 1, domRJ⟩ : RepoHop 4)
        (hfRJ m hm) (by simp [Term.fv]) hdomRJ (hfLJ l hl) hdomLJ)
    (by
      intro Q hQ σ' hσ'
      rw [List.eq_of_mem_replicate hQ]
      exact couple1J l m hl hm dt hdt hv σ' hσ')
    hσ
  rw [show (path.map (fun p => (⟨fRJ p, Term.const 1, domRJ⟩ : RepoHop 4))).map
      (fun h => h.progR)
      = path.map (fun p => Program.ode (rightBlock (fRJ p) (Term.const 1)) domRJ)
    from by rw [List.map_map]; rfl] at hfa
  simpa [List.replicate] using hfa

/-! ## The step provider — every window certifies every mode, so the response
stays in place -/

theorem HmultiJ (dt : ℝ) (hdt : 0 ≤ dt) (hv00 : VerdJ 0 0) (hv01 : VerdJ 0 1) (hv02 : VerdJ 0 2) (hv11 : VerdJ 1 1) (hv12 : VerdJ 1 2) (hv22 : VerdJ 2 2) :
    ∀ P ∈ leftProgsJ dt, ∀ (q : ℕ), q < GrJ.modes.length → ∀ σ, σ mvJ = (q : ℝ) →
      Formula.sat (Formula.and (FM gJ gsJ) envJ) σ →
      ∃ segs : List (ℕ × RMode (Var 4) × REdge (Var 4)),
        (∀ s ∈ segs, GrJ.modeAt s.1 = some s.2.1 ∧ s.2.2 ∈ GrJ.edgesFrom s.1) ∧
        List.IsChain (fun a b => a.2.2.tgt = b.1) segs ∧
        (∀ s, segs.head? = some s → s.1 = q) ∧
        Formula.sat (faModal (Equiv.refl (Var 4)) P
          (bigSeq (segs.map (fun s => Program.ode s.2.1.sys s.2.1.dom)))
          (Formula.and (FM gJ gsJ) envJ)) σ := by
  intro P hP q hq σ hmv hσ
  have hq3 : q < 3 := by simpa [GrJ] using hq
  have hself : GrJ.modeAt q = some (modeJ q) ∧ edgeJ q q ∈ GrJ.edgesFrom q := by
    refine ⟨GrJ_modeAt q hq3, edgeJ_mem q q ?_⟩
    interval_cases q <;> simp [GrJ]
  have hstep : ∀ (a b : ℕ × RMode (Var 4) × REdge (Var 4)) rest,
      a.2.2.tgt = b.1 → List.IsChain (fun x y => x.2.2.tgt = y.1) (b :: rest) →
      List.IsChain (fun x y => x.2.2.tgt = y.1) (a :: b :: rest) := by
    intro a b rest hab hrest
    refine hrest.cons ?_
    intro y hy
    rw [List.head?_cons, Option.mem_some_iff] at hy
    subst hy
    exact hab
  have hhead1 : ∀ (a : ℕ × RMode (Var 4) × REdge (Var 4)) rest s,
      (a :: rest : List _).head? = some s → s = a := by
    intro a rest s hs
    simpa [List.head?_cons] using hs.symm
  simp only [leftProgsJ, leftDataJ, List.map_cons, List.map_nil, List.mem_cons,
    List.not_mem_nil, or_false] at hP
  have halign : ∀ st tgt : ℕ, st < 3 → tgt < 3 → edgeJ st tgt ∈ GrJ.edges →
      GrJ.modeAt st = some (modeJ st) ∧ edgeJ st tgt ∈ GrJ.edgesFrom st :=
    fun st tgt hs ht he => ⟨GrJ_modeAt st hs, edgeJ_mem st tgt he⟩
  rcases hP with rfl | rfl | rfl
  all_goals interval_cases q
  · refine ⟨[(0, modeJ 0, edgeJ 0 0), (0, modeJ 0, edgeJ 0 0)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl
      · exact halign 0 0 (by norm_num) (by norm_num) (by simp [GrJ])
      · exact halign 0 0 (by norm_num) (by norm_num) (by simp [GrJ])
    · exact (hstep _ _ _ rfl (by simp))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondJ 0 0 (by norm_num) (by norm_num) dt hdt hv00 [] (by simp) hσ
      simpa [modeJ, List.replicate] using this
  · refine ⟨[(1, modeJ 1, edgeJ 1 1), (1, modeJ 1, edgeJ 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrJ])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrJ])
    · exact (hstep _ _ _ rfl (by simp))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondJ 0 1 (by norm_num) (by norm_num) dt hdt hv01 [] (by simp) hσ
      simpa [modeJ, List.replicate] using this
  · refine ⟨[(2, modeJ 2, edgeJ 2 2), (2, modeJ 2, edgeJ 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrJ])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrJ])
    · exact (hstep _ _ _ rfl (by simp))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondJ 0 2 (by norm_num) (by norm_num) dt hdt hv02 [] (by simp) hσ
      simpa [modeJ, List.replicate] using this
  · refine ⟨[(0, modeJ 0, edgeJ 0 1), (1, modeJ 1, edgeJ 1 1), (1, modeJ 1, edgeJ 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl
      · exact halign 0 1 (by norm_num) (by norm_num) (by simp [GrJ])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrJ])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrJ])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondJ 1 1 (by norm_num) (by norm_num) dt hdt hv11 [0] (by intro p hp; simp only [List.mem_cons, List.not_mem_nil, or_false] at hp; rcases hp with rfl <;> norm_num) hσ
      simpa [modeJ, List.replicate] using this
  · refine ⟨[(1, modeJ 1, edgeJ 1 1), (1, modeJ 1, edgeJ 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrJ])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrJ])
    · exact (hstep _ _ _ rfl (by simp))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondJ 1 1 (by norm_num) (by norm_num) dt hdt hv11 [] (by simp) hσ
      simpa [modeJ, List.replicate] using this
  · refine ⟨[(2, modeJ 2, edgeJ 2 2), (2, modeJ 2, edgeJ 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrJ])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrJ])
    · exact (hstep _ _ _ rfl (by simp))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondJ 1 2 (by norm_num) (by norm_num) dt hdt hv12 [] (by simp) hσ
      simpa [modeJ, List.replicate] using this
  · refine ⟨[(0, modeJ 0, edgeJ 0 1), (1, modeJ 1, edgeJ 1 2), (2, modeJ 2, edgeJ 2 2), (2, modeJ 2, edgeJ 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl
      · exact halign 0 1 (by norm_num) (by norm_num) (by simp [GrJ])
      · exact halign 1 2 (by norm_num) (by norm_num) (by simp [GrJ])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrJ])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrJ])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondJ 2 2 (by norm_num) (by norm_num) dt hdt hv22 [0, 1] (by intro p hp; simp only [List.mem_cons, List.not_mem_nil, or_false] at hp; rcases hp with rfl | rfl <;> norm_num) hσ
      simpa [modeJ, List.replicate] using this
  · refine ⟨[(1, modeJ 1, edgeJ 1 2), (2, modeJ 2, edgeJ 2 2), (2, modeJ 2, edgeJ 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl
      · exact halign 1 2 (by norm_num) (by norm_num) (by simp [GrJ])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrJ])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrJ])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondJ 2 2 (by norm_num) (by norm_num) dt hdt hv22 [1] (by intro p hp; simp only [List.mem_cons, List.not_mem_nil, or_false] at hp; rcases hp with rfl <;> norm_num) hσ
      simpa [modeJ, List.replicate] using this
  · refine ⟨[(2, modeJ 2, edgeJ 2 2), (2, modeJ 2, edgeJ 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrJ])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrJ])
    · exact (hstep _ _ _ rfl (by simp))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondJ 2 2 (by norm_num) (by norm_num) dt hdt hv22 [] (by simp) hσ
      simpa [modeJ, List.replicate] using this

/-- **`endurance_orderlift_2to3`, modal Theorem 3** (λ = 1, k = 2). -/
theorem endurance_orderlift_2to3_modal (dt : ℝ) (hdt : 0 ≤ dt) (hv00 : VerdJ 0 0) (hv01 : VerdJ 0 1) (hv02 : VerdJ 0 2) (hv11 : VerdJ 1 1) (hv12 : VerdJ 1 2) (hv22 : VerdJ 2 2) :
    RFormula.rvalid (theorem3Form
      (bigChoice (leftProgsJ dt))
      (rightAutomatonBody GrJ mvJ)
      (RFormula.and (RFormula.and (canonInvM gJ gsJ) (envLR domLJ domRJ))
        (mvValidR mvJ GrJ.modes.length))) := by
  refine theorem3_faithful_multiF_LR GrJ mvJ (FM gJ gsJ) domLJ domRJ
    (leftProgsJ dt) (canonInvM gJ gsJ) (encode_canonInvM gJ gsJ) ?_ ?_ ?_
  · exact hdis_multi GrJ 0 1 dt leftDataJ (by decide) httJ hRvJ hLJ
  · exact hstep_assembled_multiF GrJ mvJ (FM gJ gsJ) envJ (leftProgsJ dt)
      hmvFJ hmvenvJ hfreshJ httJ hltJ (hframesJ dt)
      (HmultiJ dt hdt hv00 hv01 hv02 hv11 hv12 hv22)
  · exact hddF_multiE GrJ 0 1 dt leftDataJ (canonInvM gJ gsJ) domLJ domRJ
      (by decide) httJ hRvJ hLJ
      (canonInvM_varsL gJ gsJ (by
        intro g' hg'
        simp only [gJ, gsJ, List.mem_cons, List.not_mem_nil, or_false] at hg'
        rcases hg' with rfl | rfl <;> exact hgAt _))
      (canonInvM_varsR gJ gsJ) hdomLJ hdomRJ

end EnduranceOrderlift2to3Modal
end RelCertifier
