/-
Copyright (c) 2026 relCertifier-lean contributors.
Released under Apache 2.0 license.

# T3+ — `endurance_gain_M1`, modal Theorem 3 (multiF, GENERATED)

Generated by `scripts/gen_multif_instance.py` from the coordinate spec: the plain
list-invariant pattern at n = 2 with 1 invariant components in the cover's
stratified-DC order, the one-way terrain chain, and climb dispatch. Existence is
Z3-free (stratified faces).

Residuals: six stratified-DC verdict packs (`VerdG l m`). Axioms: the standard
three + `z3_unsat_sound` at those leaves.
-/
import RelCertifier.Proofs.Encoding.EnvelopeChainM
import RelCertifier.Proofs.Encoding.RepoPrefixR
import RelCertifier.Proofs.Encoding.Reparam
import RelCertifier.Proofs.Encoding.WindowRF
import RelCertifier.Proofs.Encoding.CanonicalInv
import RelCertifier.Proofs.Encoding.CoverInstance
import RelCertifier.Proofs.Flow.StratifiedFaces
import RelCertifier.Instances.BenchIR.endurance_gain_M1

namespace RelCertifier
namespace EnduranceGainM1Modal

open DL DLCalTiming DLRel Parse Set

set_option maxHeartbeats 12800000

def vsG : List String := ["v", "s"]
def dummyG : Parse.PMode := ⟨"", [], .tt, .tt, []⟩
def mLG (l : ℕ) : Parse.PMode := endurance_gain_M1_IR.L.modes.getD l dummyG
def mRG (q : ℕ) : Parse.PMode := endurance_gain_M1_IR.R.modes.getD q dummyG

abbrev mvG : Var 2 := (Side.Aux, 0)
abbrev aG : Fin 2 := (1 : Fin 2)
abbrev tgG : Var 2 := (Side.Aux, aG)

noncomputable def fLG (l : ℕ) : Fin 2 → Term (Var 2) := hostDyn vsG 2 Side.L (mLG l)
noncomputable def fRG (q : ℕ) : Fin 2 → Term (Var 2) := hostDyn vsG 2 Side.R (mRG q)
noncomputable def domLG : Formula (Var 2) := hostEvolve vsG 2 Side.L (mLG 0)
noncomputable def domRG : Formula (Var 2) := hostEvolve vsG 2 Side.R (mRG 0)
noncomputable def envG : Formula (Var 2) := Formula.and domLG domRG

def atomsOf : Parse.PForm → List Parse.PForm
  | .and x y => atomsOf x ++ atomsOf y
  | f => [f]

def invGPF : Parse.PForm :=
  (endurance_gain_M1_IR.invariants.getD 0 ("", Parse.PForm.tt)).2

noncomputable def gAt (i : ℕ) : Term (Var 2) :=
  ((Run.invToG vsG 2 ((atomsOf invGPF).getD i .tt)).map ITerm.toHost).getD (Term.const 0)

noncomputable def gG : Term (Var 2) := gAt 0
noncomputable def gsG : List (Term (Var 2)) := []

/-! ## Side-splits -/

theorem fLG_pipe (l : ℕ) (i : Fin 2) : fLG l i =
    (((some (mLG l)).bind (Run.dynOf vsG 2 Side.L)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem fRG_pipe (q : ℕ) (i : Fin 2) : fRG q i =
    (((some (mRG q)).bind (Run.dynOf vsG 2 Side.R)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem domLG_pipe : domLG =
    (((some (mLG 0)).bind (fun m => Run.lowerF vsG 2 Side.L m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl
theorem domRG_pipe : domRG =
    (((some (mRG 0)).bind (fun m => Run.lowerF vsG 2 Side.R m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl

theorem hfLG (l : ℕ) (hl : l < 3) : ∀ i, (fLG l i).fv ⊆ range Lv := fun i x hx =>
  side_eq_L_mem (field_pipeline_side (resolvesTo_L vsG) (some (mLG l))
    (by interval_cases l <;>
      simp [mLG, endurance_gain_M1_IR, Parse.PExpr.namesFree]) i x
    (fLG_pipe l i ▸ hx))

theorem hfRG (q : ℕ) (hq : q < 3) : ∀ i, (fRG q i).fv ⊆ range Rv := fun i x hx =>
  side_eq_R_mem (field_pipeline_side (resolvesTo_R vsG) (some (mRG q))
    (by interval_cases q <;>
      simp [mRG, endurance_gain_M1_IR, Parse.PExpr.namesFree]) i x
    (fRG_pipe q i ▸ hx))

theorem hdomLG : domLG.fv ⊆ range Lv := fun x hx =>
  side_eq_L_mem (form_pipeline_side (resolvesTo_L vsG) (some (mLG 0))
    (by simp [mLG, endurance_gain_M1_IR, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domLG_pipe ▸ hx))

theorem hdomRG : domRG.fv ⊆ range Rv := fun x hx =>
  side_eq_R_mem (form_pipeline_side (resolvesTo_R vsG) (some (mRG 0))
    (by simp [mRG, endurance_gain_M1_IR, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domRG_pipe ▸ hx))

theorem hgAt (i : ℕ) : (gAt i).fv ⊆ range Lv ∪ range Rv := invToG_pipeline_LR _

theorem hmvg : ∀ g' ∈ gG :: gsG, mvG ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [gG, gsG, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with rfl <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem htgg : ∀ g' ∈ gG :: gsG, tgG ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [gG, gsG, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with rfl <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem hmvFG : mvG ∉ (FM gG gsG).fv := notMem_FM_fv hmvg
theorem htgFG : tgG ∉ (FM gG gsG).fv := notMem_FM_fv htgg

theorem hmvenvG : mvG ∉ envG.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomLG h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomRG h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))
theorem htgenvG : tgG ∉ envG.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomLG h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomRG h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))

/-! ## The right graph (one-way chain) -/

noncomputable def modeG (q : ℕ) : RMode (Var 2) :=
  { sys := rightBlock (fRG q) (Term.const 1), dom := domRG, weight := 1 }

def edgeG (st tgt : ℕ) : REdge (Var 2) :=
  { src := st, tgt := tgt, guard := Formula.tt, pruned := false }

noncomputable def GrG : SearchGraph (Var 2) :=
  { modes := [modeG 0, modeG 1, modeG 2],
    edges := [edgeG 0 1, edgeG 0 0, edgeG 1 2, edgeG 1 1, edgeG 2 2] }

theorem GrG_modeAt (q : ℕ) (hq : q < 3) : GrG.modeAt q = some (modeG q) := by
  interval_cases q <;> rfl

theorem httG : ∀ q, ∀ e ∈ GrG.edgesFrom q, e.guard = Formula.tt := by
  intro q e he
  have hmem : e ∈ GrG.edges := List.mem_of_mem_filter he
  simp only [GrG, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> rfl

theorem hltG : ∀ q, ∀ e ∈ GrG.edgesFrom q, e.tgt < GrG.modes.length := by
  intro q e he
  have hmem : e ∈ GrG.edges := List.mem_of_mem_filter he
  simp only [GrG, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> norm_num [GrG, edgeG]

theorem hRvG : ∀ q m, GrG.modeAt q = some m →
    m.sys.boundSet ∪ m.sys.readVars ∪ m.dom.fv ⊆ range Rv := by
  intro q m hm
  have hqm : q < 3 ∧ m = modeG q := by
    match q with
    | 0 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrG] using hm.symm⟩
    | 1 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrG] using hm.symm⟩
    | 2 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrG] using hm.symm⟩
    | q + 3 => exact absurd hm (by simp [SearchGraph.modeAt, GrG])
  obtain ⟨hq3, rfl⟩ := hqm
  intro y hy
  rcases hy with (hy | hy) | hy
  · exact rightBlock_boundSet_sub (fRG q) (Term.const 1) hy
  · exact rightBlock_readVars_sub (fRG q) (Term.const 1) (hfRG q hq3)
      (by simp [Term.fv]) hy
  · exact hdomRG hy

theorem edgeG_mem : ∀ st tgt, edgeG st tgt ∈ GrG.edges →
    edgeG st tgt ∈ GrG.edgesFrom st :=
  fun st tgt he => List.mem_filter.mpr ⟨he, by simp [edgeG]⟩

theorem hfreshG : ∀ q m, GrG.modeAt q = some m →
    mvG ∉ (Program.ode m.sys m.dom).fv := by
  intro q m hm hmv
  exact aux_notin_range_Rv 0 (hRvG q m hm (vars_ode_sub _ _ (Or.inl hmv)))

/-! ## The left window family -/

noncomputable def leftDataG : List ((Fin 2 → Term (Var 2)) × Formula (Var 2) × ℕ) :=
  [(fLG 0, domLG, 2), (fLG 1, domLG, 2), (fLG 2, domLG, 3)]

noncomputable def leftProgsG (dt : ℝ) : List (Program (Var 2)) :=
  leftDataG.map (fun d => windowSeg (leftBlock d.1) d.2.1 tgG dt d.2.2)

theorem hLG : ∀ d ∈ leftDataG, (∀ i, (d.1 i).fv ⊆ range Lv) ∧ d.2.1.fv ⊆ range Lv := by
  intro d hd
  simp only [leftDataG, List.mem_cons, List.not_mem_nil, or_false] at hd
  rcases hd with rfl | rfl | rfl
  · exact ⟨hfLG 0 (by norm_num), hdomLG⟩
  · exact ⟨hfLG 1 (by norm_num), hdomLG⟩
  · exact ⟨hfLG 2 (by norm_num), hdomLG⟩

theorem hframesG (dt : ℝ) : ∀ P ∈ leftProgsG dt, FramesMv P mvG := by
  intro P hP
  simp only [leftProgsG, List.mem_map] at hP
  obtain ⟨d, hd, rfl⟩ := hP
  refine framesMv_window (leftBlock d.1) d.2.1 tgG dt d.2.2 mvG (by decide) ?_
  intro h
  obtain ⟨i, hi⟩ := leftBlock_bound_sub d.1 _ h
  exact aux_ne_Lv 0 i hi

/-! ## Parse pins -/

theorem hg030 : Run.parseRat "0.30" = some ((3:ℚ)/10) := by
  have h : parseQ "0.30" = some (⟨30, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hg050 : Run.parseRat "0.50" = some ((1:ℚ)/2) := by
  have h : parseQ "0.50" = some (⟨50, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hg065 : Run.parseRat "0.65" = some ((13:ℚ)/20) := by
  have h : parseQ "0.65" = some (⟨65, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hg2 : Run.parseRat "2" = some (2) := by
  have h : parseQ "2" = some (⟨2, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hg3 : Run.parseRat "3" = some (3) := by
  have h : parseQ "3" = some (⟨3, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hg0 : Run.parseRat "0" = some (0) := by
  have h : parseQ "0" = some (⟨0, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hg1 : Run.parseRat "1" = some (1) := by
  have h : parseQ "1" = some (⟨1, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hg00 : Run.parseRat "0.0" = some (0) := by
  have h : parseQ "0.0" = some (⟨0, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hg08 : Run.parseRat "0.8" = some ((4:ℚ)/5) := by
  have h : parseQ "0.8" = some (⟨8, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hg345 : Run.parseRat "3.45" = some ((69:ℚ)/20) := by
  have h : parseQ "3.45" = some (⟨345, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num

/-! ## Field and shape pins -/

noncomputable def cstG (q : ℕ) : ℝ := if q = 0 then 3/10 else if q = 1 then 1/2 else 13/20

theorem fRG0_eval (q : ℕ) (hq : q < 3) (x : State (Var 2)) :
    Term.eval (fRG q 0) x = 2 * (cstG q - x (Rv 0)) := by
  interval_cases q <;>
    simp [fRG, hostDyn, mRG, endurance_gain_M1_IR, vsG, Run.dynOf,
      Run.lowerE, hg030, hg050, hg065, hg2, hg3, hg0, hg1, hg00, hg08, hg345, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv, cstG]
theorem fRG1_eval (q : ℕ) (hq : q < 3) (x : State (Var 2)) :
    Term.eval (fRG q 1) x = x (Rv 0) := by
  interval_cases q <;>
    simp [fRG, hostDyn, mRG, endurance_gain_M1_IR, vsG, Run.dynOf,
      Run.lowerE, hg030, hg050, hg065, hg2, hg3, hg0, hg1, hg00, hg08, hg345, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]

theorem sat_domRG (x : State (Var 2)) : Formula.sat domRG x ↔
    (0 ≤ x (Rv 1) ∧ 0 ≤ x (Rv 0) ∧ x (Rv 0) ≤ (4:ℝ)/5) := by
  simp only [domRG, hostEvolve, mRG, endurance_gain_M1_IR, vsG]
  simp [Run.lowerF, Run.lowerE, hg00, hg08,
    Run.resolveVar, List.findIdx?_cons, IForm.toHost, ITerm.toHost, Formula.sat,
    CompOp.interp, Term.eval, Rv]
  tauto

/-! ## Faces -/

noncomputable def faceVLo : Term (Var 2) :=
  Term.binop AOp.sub (Term.const (0)) (Term.var (Rv 0))
noncomputable def faceVHi : Term (Var 2) :=
  Term.binop AOp.sub (Term.var (Rv 0)) (Term.const ((4:ℝ)/5))
noncomputable def faceSLo : Term (Var 2) :=
  Term.binop AOp.sub (Term.const 0) (Term.var (Rv 1))

noncomputable def gsSG : List (Term (Var 2)) :=
  [faceVLo, faceVHi]
noncomputable def gsNG : List (Term (Var 2)) :=
  [faceSLo]

theorem faces_fv_RG : ∀ gT' ∈ gsSG ++ gsNG, ∀ x ∈ gT'.fv, x ∈ range Rv := by
  intro gT' hgT x hx
  simp only [gsSG, gsNG, List.cons_append, List.nil_append, List.mem_cons,
    List.not_mem_nil, or_false] at hgT
  rcases hgT with rfl | rfl | rfl <;>
    · simp only [faceVLo, faceVHi, faceSLo, Term.fv,
        Set.mem_union, Set.mem_empty_iff_false, false_or, or_false,
        Set.mem_singleton_iff] at hx
      exact ⟨_, hx.symm⟩

/-! ## The frozen-left joint field -/

theorem odeField_RG (q : ℕ) (hq : q < 3) (x : State (Var 2)) :
    odeField (jointSys (fun _ => Term.const 0) (fRG q) (Term.const (1))) x
      = fun c =>
        if c = Rv 0 then 2 * (cstG q - x (Rv 0))
        else if c = Rv 1 then x (Rv 0)
        else 0 := by
  funext c
  by_cases hc : c ∈ (jointSys (fun _ => Term.const 0) (fRG q) (Term.const (1))).bound
  · rw [show odeField (jointSys (fun _ => Term.const 0) (fRG q) (Term.const (1))) x c
        = ((jointSys (fun _ => Term.const 0) (fRG q) (Term.const (1))).rhs c).eval x from by
      simp only [odeField, if_pos hc]]
    obtain ⟨p, hp, hfst⟩ : ∃ p ∈ jointSys (fun _ => Term.const 0) (fRG q) (Term.const (1)),
        p.1 = c := by simpa [ODESystem.bound, List.mem_map] using hc
    rw [← hfst, ODESystem.rhs_eq_of_mem (jointSys_wellFormed _ _ _) hp]
    rw [jointSys_split] at hp
    have hne : ∀ (a b : Fin 2), a ≠ b → (Rv a : Var 2) ≠ Rv b := by
      intro a b hab
      simp [Rv, Prod.ext_iff]
      exact fun h => hab (by exact_mod_cast h)
    rcases List.mem_append.mp hp with hp | hp
    · obtain ⟨j, -, rfl⟩ := List.mem_map.mp hp
      have hLR : ∀ k : Fin 2, (Lv j : Var 2) ≠ Rv k := by
        intro k
        simp [Lv, Rv, Prod.ext_iff]
      simp [Term.eval, hLR 0, hLR 1]
    · obtain ⟨j, -, rfl⟩ := List.mem_map.mp hp
      fin_cases j
      · simp [Term.eval, AOp.interp, fRG0_eval q hq]
      · simp [Term.eval, AOp.interp, fRG1_eval q hq,
          hne 1 0 (by decide)]
  · have hnotR : ∀ j : Fin 2, c ≠ Rv j := by
      intro j hceq
      refine hc ?_
      rw [hceq, jointSys_split]
      simp only [ODESystem.bound, List.map_append, List.mem_append]
      exact Or.inr (by
        simp only [rightBlock, List.map_map, List.mem_map]
        exact ⟨j, List.mem_finRange j, rfl⟩)
    simp only [odeField, if_neg hc, if_neg (hnotR 0), if_neg (hnotR 1)]

/-! ## Strict inflow -/

theorem hbndS_G (q : ℕ) (hq : q < 3) : ∀ gT' ∈ gsSG, ∀ x : State (Var 2),
    Term.eval gT' x = 0 →
    Lie (jointSys (fun _ => Term.const 0) (fRG q) (Term.const (1)))
      (fun ω => Term.eval gT' ω) x < 0 := by
  have hne : ∀ (a b : Fin 2), a ≠ b → (Rv a : Var 2) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro gT' hgT x hface
  simp only [gsSG, List.mem_cons, List.not_mem_nil, or_false] at hgT
  rcases hgT with rfl | rfl
  · have hx : x (Rv 0) = 0 := by
      simp only [faceVLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 2) => Term.eval faceVLo ω)
        = fun y => (-1 : ℝ) * y (Rv 0) + (0) := by
      funext y; simp [faceVLo, Term.eval, AOp.interp]
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 0) (-1) (0) x,
      odeField_RG q hq]
    simp only [eq_self_iff_true, if_true, if_pos rfl, hx]
    interval_cases q <;> norm_num [cstG]
  · have hx : x (Rv 0) = (4:ℝ)/5 := by
      simp only [faceVHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 2) => Term.eval faceVHi ω)
        = fun y => (1 : ℝ) * y (Rv 0) + (-((4:ℝ)/5)) := by
      funext y; simp [faceVHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 0) 1 (-((4:ℝ)/5)) x,
      odeField_RG q hq]
    simp only [eq_self_iff_true, if_true, if_pos rfl, hx]
    interval_cases q <;> norm_num [cstG]

/-! ## Non-strict faces -/

theorem hbndN_G (q : ℕ) (hq : q < 3) : ∀ i (hi : i < gsNG.length),
    ∀ x : State (Var 2),
    (∀ gT' ∈ gsSG ++ ([] : List (Term (Var 2))), Term.eval gT' x ≤ 0) →
    Lie (jointSys (fun _ => Term.const 0) (fRG q) (Term.const (1)))
      (fun ω => Term.eval gsNG[i] ω) x ≤ 0 := by
  have hne : ∀ (a b : Fin 2), a ≠ b → (Rv a : Var 2) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro i hi x hx
  have hib : i < 1 := by simpa [gsNG] using hi
  interval_cases i
  · show Lie _ (fun ω => Term.eval faceSLo ω) x ≤ 0
    have hv0 : 0 ≤ x (Rv 0) := by
      have := hx faceVLo (List.mem_append_left _ (by simp [gsSG]))
      simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
    have hfun : (fun ω : State (Var 2) => Term.eval faceSLo ω)
        = fun y => (-1 : ℝ) * y (Rv 1) + 0 := by
      funext y; simp [faceSLo, Term.eval, AOp.interp]
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 1) (-1) 0 x,
      odeField_RG q hq]
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    linarith

/-! ## Lipschitz and field bound -/

theorem hLip_G (q : ℕ) (hq : q < 3) (ν : State (Var 2)) :
    LipschitzOnWith 8 (odeField (jointSys (fun _ => Term.const 0) (fRG q) (Term.const (1))))
      (Metric.closedBall ν 1) := by
  have hne : ∀ (a b : Fin 2), a ≠ b → (Rv a : Var 2) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  rw [lipschitzOnWith_iff_dist_le_mul]
  intro x hx y hy
  rw [Metric.mem_closedBall] at hx hy
  rw [odeField_RG q hq, odeField_RG q hq]
  have hdc : ∀ j : Fin 2, |x (Rv j) - y (Rv j)| ≤ dist x y := by
    intro j
    have h := dist_le_pi_dist x y (Rv j)
    rwa [Real.dist_eq] at h
  have hd : (0:ℝ) ≤ dist x y := dist_nonneg
  have hcoe : ((8 : NNReal) : ℝ) = 8 := rfl
  rw [hcoe]
  refine dist_pi_le_iff (by positivity) |>.mpr ?_
  intro c
  by_cases hc0 : c = Rv 0
  · subst hc0
    simp only [eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |2 * (cstG q - x (Rv 0)) - 2 * (cstG q - y (Rv 0))| ≤ 2 * dist x y := by
      have hdiff : 2 * (cstG q - x (Rv 0)) - 2 * (cstG q - y (Rv 0)) = -(2 : ℝ) * (x (Rv 0) - y (Rv 0)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(2 : ℝ)| = 2 := by norm_num
      rw [habs]
      nlinarith [hdc 0]
    skip
    nlinarith [hcore, hd]
  by_cases hc1 : c = Rv 1
  · subst hc1
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |x (Rv 0) - y (Rv 0)| ≤ 1 * dist x y := by
      have hdiff : x (Rv 0) - y (Rv 0) = (1 : ℝ) * (x (Rv 0) - y (Rv 0)) := by ring
      rw [hdiff, abs_mul]
      have habs : |(1 : ℝ)| = 1 := by norm_num
      rw [habs]
      nlinarith [hdc 0]
    skip
    nlinarith [hcore, hd]
  · simp only [if_neg hc0, if_neg hc1]
    simp [dist_nonneg]

theorem hfbnd_G (q : ℕ) (hq : q < 3) (ν : State (Var 2))
    (hν : ∀ gT' ∈ gsSG, Term.eval gT' ν ≤ 0) :
    ∀ x ∈ Metric.closedBall ν 1,
      ‖odeField (jointSys (fun _ => Term.const 0) (fRG q) (Term.const (1))) x‖
        ≤ ((10:NNReal) : ℝ) := by
  have hne : ∀ (a b : Fin 2), a ≠ b → (Rv a : Var 2) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro x hx
  rw [Metric.mem_closedBall] at hx
  have hbandf : ∀ (j : Fin 2) (lo hi : ℝ),
      lo ≤ ν (Rv j) → ν (Rv j) ≤ hi → -2 ≤ lo → hi ≤ 2 → |x (Rv j)| ≤ 3 := by
    intro j lo hi hl hh hlo1 hhi1
    have h := dist_le_pi_dist x ν (Rv j)
    rw [Real.dist_eq] at h
    have hνb : |ν (Rv j)| ≤ 2 := abs_le.mpr ⟨by linarith, by linarith⟩
    have h2 := abs_sub_abs_le_abs_sub (x (Rv j)) (ν (Rv j))
    linarith [abs_le.mp hνb, hx]
  have hxb0 : |x (Rv 0)| ≤ 3 := by
    refine hbandf 0 (0) ((4:ℝ)/5) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν faceVLo (by simp [gsSG])
      simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
    · have := hν faceVHi (by simp [gsSG])
      simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
  rw [odeField_RG q hq]
  refine pi_norm_le_iff_of_nonneg (by norm_num) |>.mpr ?_
  intro c
  have hLcoe : ((10:NNReal) : ℝ) = 10 := rfl
  rw [hLcoe]
  by_cases hc0 : c = Rv 0
  · subst hc0
    simp only [eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcst : 0 ≤ cstG q ∧ cstG q ≤ 1 := by
      interval_cases q <;> norm_num [cstG]
    have hcore : |2 * (cstG q - x (Rv 0))| ≤ 8 := by
      obtain ⟨hcl, hch⟩ := hcst
      rw [abs_le]
      constructor <;> nlinarith [abs_le.mp hxb0]

    nlinarith [hcore, abs_nonneg (2 * (cstG q - x (Rv 0)))]
  by_cases hc1 : c = Rv 1
  · subst hc1
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcore : |x (Rv 0)| ≤ 3 := hxb0

    nlinarith [hcore, abs_nonneg (x (Rv 0))]
  · simp only [if_neg hc0, if_neg hc1]
    norm_num

/-! ## Existence -/

theorem esG (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt) :
    ∀ σ, Formula.sat (Formula.and (FM gG gsG) envG) σ →
      HExistSegB (fLG l) (fRG m) (Term.const (1)) domLG domRG dt
        (Function.update σ tgG 0) := by
  intro σ hσ
  have hR : Formula.sat domRG σ := hσ.2.2
  rw [sat_domRG] at hR
  obtain ⟨hd1l, hd0l, hd0h⟩ := hR
  have hupd : ∀ j : Fin 2, σ (Side.R, j) = Function.update σ tgG 0 (Side.R, j) := by
    intro j
    rw [Function.update_of_ne (by simp [tgG, Prod.ext_iff])]
  have hfS : ∀ gT' ∈ gsSG, Term.eval gT' (Function.update σ tgG 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsSG, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with rfl | rfl <;>
      · first
          | (simp only [faceVLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceVHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
  have hfN : ∀ gT' ∈ gsNG, Term.eval gT' (Function.update σ tgG 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsNG, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with rfl <;>
      · first
          | (simp only [faceSLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
  refine HExistSegB_of_viability_stratified (fLG l) (fRG m) (Term.const (1))
    domLG domRG gsSG [] gsNG 0 le_rfl
    (jointSys_wellFormed _ _ _)
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLG l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_RG gT' (by
        rcases List.mem_append.mp hgT with h | h
        · exact List.mem_append_left _ h
        · exact absurd h (List.not_mem_nil)) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLG l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_RG gT' (List.mem_append_right _ hgT) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro gT' hgT x _ hface
      exact hbndS_G m hm gT' hgT x hface)
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))
    (by
      intro i hi x hxs _
      exact hbndN_G m hm i hi x hxs)
    (by
      intro x hS hN
      have hS' : ∀ gT' ∈ gsSG, Term.eval gT' x ≤ 0 :=
        fun gT' hgT => hS gT' (List.mem_append_left _ hgT)
      have hb0l : 0 ≤ x (Rv 0) := by
        have := hS' faceVLo (by simp [gsSG])
        simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
      have hb0h : x (Rv 0) ≤ (4:ℝ)/5 := by
        have := hS' faceVHi (by simp [gsSG])
        simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
      have hb1l : 0 ≤ x (Rv 1) := by
        have := hN faceSLo (by simp [gsNG])
        simp only [faceSLo, Term.eval, AOp.interp] at this; linarith
      exact (sat_domRG x).mpr ⟨hb1l, hb0l, hb0h⟩)
    8 10 1 one_pos
    (fun ν0 _ => hLip_G m hm ν0)
    (fun ν0 h0 => hfbnd_G m hm ν0 (fun gT hgT => h0 gT (List.mem_append_left _ hgT)))
    dt hdt
    (Function.update σ tgG 0)
    hfS
    hfN
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))

/-! ## The route verdicts (stratified-DC at the cover's λ) -/

def VerdG (l m : ℕ) : Prop :=
  ∀ i (hi : i < (gG :: gsG).length),
    z3solve (flowQuery ⟨(gG :: gsG)[i], fLG l, fRG m, Term.const (1),
      strataDomHost (Formula.and domLG domRG) ((gG :: gsG).take i)⟩) = Verdict.unsat
    ∨ z3solve (flowQueryStrict ⟨(gG :: gsG)[i], fLG l, fRG m, Term.const (1),
      strataDomHost (Formula.and domLG domRG) ((gG :: gsG).take i)⟩) = Verdict.unsat
    ∨ z3solve (flowQuerySuperlevel ⟨(gG :: gsG)[i], fLG l, fRG m, Term.const (1),
      strataDomHost (Formula.and domLG domRG) ((gG :: gsG).take i)⟩) = Verdict.unsat

/-! ## The coupling at λ, and its λ = 1 transport (L7) -/

theorem coupleG (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdG l m) :
    ∀ σ', Formula.sat (Formula.and (FM gG gsG) envG) σ' → σ' tgG = 0 →
      faModalB (Equiv.refl (Var 2))
        (Program.ode (DLCalTiming.clk tgG (leftBlock (fLG l))) domLG)
        (Program.ode (rightBlock (fRG m) (Term.const (1))) domRG)
        (Formula.and (FM gG gsG) envG) tgG dt σ' := by
  intro σ' hσ' htg0
  have hupd : Function.update σ' tgG (0 : ℝ) = σ' := by
    funext x
    by_cases hx : x = tgG
    · subst hx; rw [Function.update_self]; exact htg0.symm
    · rw [Function.update_of_ne hx]
  have hAll := segPresAll_from_strata_verdicts' (fLG l) (fRG m) (Term.const (1))
    (Formula.and domLG domRG) (gG :: gsG) hv
  have hboxes : ∀ g' ∈ gG :: gsG, Formula.sat (Formula.box (Program.ode
      (leftBlock (fLG l) ++ rightBlock (fRG m) (Term.const (1)))
      (Formula.and domLG domRG)) (invLe g')) σ' := by
    intro g' hg'
    rw [sat_box]
    intro ω hω
    rw [sat_invLe]
    refine hAll σ' ?_ ω (by rw [← jointSys_split] at hω; exact hω) g' hg'
    intro g hg
    exact (sat_FM_iff gG gsG σ').mp hσ'.1 g hg
  have hbase := segment_faModalB_from_certB_list gG gsG (fLG l) (fRG m)
    (Term.const (1)) domLG domRG tgG dt
    (LR_blocks_disjoint _ _ _ (hfLG l hl) (hfRG m hm) (by simp [Term.fv]))
    (fun v hv' => Or.inl (by
      obtain ⟨i, rfl⟩ := hdomLG hv'
      exact Lv_mem_leftBlock_boundSet _ i))
    (fun v hv' => Or.inl (by
      obtain ⟨i, rfl⟩ := hdomRG hv'
      exact Rv_mem_rightBlock_boundSet _ _ i))
    (fun h => by
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLG l) _ h
      exact aux_ne_Lv aG i hi)
    (fun h => aux_notin_range_Lv aG (leftBlock_readVars_sub (fLG l) (hfLG l hl) h))
    (fun h => by
      obtain ⟨i, hi⟩ := rightBlock_bound_sub (fRG m) (Term.const (1)) _ h
      exact aux_ne_Rv aG i hi)
    (fun h => aux_notin_range_Rv aG (rightBlock_readVars_sub (fRG m)
      (Term.const (1)) (hfRG m hm) (by simp [Term.fv]) h))
    (fun h => aux_notin_range_Rv aG (rightBlock_boundSet_sub (fRG m)
      (Term.const (1)) h))
    (fun h => aux_notin_range_Lv aG (hdomLG h))
    (fun h => aux_notin_range_Rv aG (hdomRG h))
    htgg hboxes
    (esG l m hl hm dt hdt σ' hσ')
  rw [hupd] at hbase
  refine faModalB_strengthen_plant ?_ hbase
  intro ν μ hplant hsem
  have hdomLν : Formula.sat domLG ν := sem_ode_ends_in_domain hplant.1
  have hdomRμ : Formula.sat domRG μ := sem_ode_ends_in_domain hsem
  have hdomLμ : Formula.sat domLG μ := by
    rwa [(Formula.coincidence domLG (fun v hv' => sem_ode_mask hsem (by
      obtain ⟨i, rfl⟩ := hdomLG hv'
      intro hb
      obtain ⟨j, hj⟩ := rightBlock_bound_sub (fRG m) (Term.const (1)) _ hb
      exact absurd hj (by simp [Lv, Rv, Prod.ext_iff]))) :
        Formula.sat domLG μ ↔ Formula.sat domLG ν)]
  exact ⟨hdomLμ, hdomRμ⟩

theorem couple1G (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdG l m) :
    ∀ σ, Formula.sat (Formula.and (FM gG gsG) envG) σ →
      faModalB (Equiv.refl (Var 2))
        (Program.ode (DLCalTiming.clk tgG (leftBlock (fLG l))) domLG)
        (Program.ode (rightBlock (fRG m) (Term.const 1)) domRG) (Formula.and (FM gG gsG) envG) tgG dt
        (Function.update σ tgG 0) := by
  intro σ hσ
  have htgφ : tgG ∉ (Formula.and (FM gG gsG) envG).fv := by
    intro h
    rcases h with h | h
    · exact htgFG h
    · exact htgenvG h
  have hupdφ : Formula.sat (Formula.and (FM gG gsG) envG)
      (Function.update σ tgG 0) := by
    rwa [(Formula.coincidence (Formula.and (FM gG gsG) envG) (fun v hv' =>
      Function.update_of_ne (fun hc => htgφ (by rw [← hc]; exact hv')) _ _) :
        Formula.sat (Formula.and (FM gG gsG) envG) _ ↔ _)]
  refine faModalB_monoQ ?_ (coupleG l m hl hm dt hdt hv
    (Function.update σ tgG 0) hupdφ (Function.update_self _ _ _))
  intro ν μ hsem
  exact sem_rightBlock_reparam (1) 1 (by norm_num) one_pos hsem

/-! ## The window response (2 pieces at the in-place mode) -/

theorem respondG (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdG l m) (path : List ℕ) (hpath : ∀ p ∈ path, p < 3)
    {σ : State (Var 2)}
    (hσ : Formula.sat (Formula.and (FM gG gsG) envG) σ) :
    Formula.sat (faModal (Equiv.refl (Var 2))
      (windowSeg (leftBlock (fLG l)) domLG tgG dt 2)
      (bigSeq ((path.map (fun p => Program.ode (rightBlock (fRG p) (Term.const 1)) domRG))
        ++ [Program.ode (rightBlock (fRG m) (Term.const 1)) domRG,
        Program.ode (rightBlock (fRG m) (Term.const 1)) domRG]))
      (Formula.and (FM gG gsG) envG)) σ := by
  have hfa := Hmulti_windowRF_prefixed (fLG l) domLG (FM gG gsG) envG
    aG dt 2 htgFG htgenvG
    (path.map (fun p => (⟨fRG p, Term.const 1, domRG⟩ : RepoHop 2)))
    (by
      intro h hh
      obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hh
      exact ⟨hfRG p (hpath p hp), by simp [Term.fv], hdomRG⟩)
    (fun σ' hσ' => hσ'.2.1)
    (by
      intro h hh σ' hσ' htg'
      obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hh
      obtain ⟨ρ, hsem, hρσ⟩ := static_hop_existsR (fR := fRG p)
        (lam := Term.const 1) (domR := domRG) hσ'.2.2
      exact ⟨ρ, hsem, hρσ ▸ hσ'⟩)
    (hfLG l hl) hdomLG
    (List.replicate 2 (Program.ode (rightBlock (fRG m) (Term.const 1)) domRG)) (by simp) (by norm_num)
    (by
      intro Q hQ
      rw [List.eq_of_mem_replicate hQ, Program.rename_refl]
      exact hdisH_progR (⟨fRG m, Term.const 1, domRG⟩ : RepoHop 2)
        (hfRG m hm) (by simp [Term.fv]) hdomRG (hfLG l hl) hdomLG)
    (by
      intro Q hQ σ' hσ'
      rw [List.eq_of_mem_replicate hQ]
      exact couple1G l m hl hm dt hdt hv σ' hσ')
    hσ
  rw [show (path.map (fun p => (⟨fRG p, Term.const 1, domRG⟩ : RepoHop 2))).map
      (fun h => h.progR)
      = path.map (fun p => Program.ode (rightBlock (fRG p) (Term.const 1)) domRG)
    from by rw [List.map_map]; rfl] at hfa
  simpa [List.replicate] using hfa

theorem respond3G (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdG l m) (path : List ℕ) (hpath : ∀ p ∈ path, p < 3)
    {σ : State (Var 2)}
    (hσ : Formula.sat (Formula.and (FM gG gsG) envG) σ) :
    Formula.sat (faModal (Equiv.refl (Var 2))
      (windowSeg (leftBlock (fLG l)) domLG tgG dt 3)
      (bigSeq ((path.map (fun p => Program.ode (rightBlock (fRG p) (Term.const 1)) domRG))
        ++ [Program.ode (rightBlock (fRG m) (Term.const 1)) domRG,
        Program.ode (rightBlock (fRG m) (Term.const 1)) domRG,
        Program.ode (rightBlock (fRG m) (Term.const 1)) domRG]))
      (Formula.and (FM gG gsG) envG)) σ := by
  have hfa := Hmulti_windowRF_prefixed (fLG l) domLG (FM gG gsG) envG
    aG dt 3 htgFG htgenvG
    (path.map (fun p => (⟨fRG p, Term.const 1, domRG⟩ : RepoHop 2)))
    (by
      intro h hh
      obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hh
      exact ⟨hfRG p (hpath p hp), by simp [Term.fv], hdomRG⟩)
    (fun σ' hσ' => hσ'.2.1)
    (by
      intro h hh σ' hσ' htg'
      obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hh
      obtain ⟨ρ, hsem, hρσ⟩ := static_hop_existsR (fR := fRG p)
        (lam := Term.const 1) (domR := domRG) hσ'.2.2
      exact ⟨ρ, hsem, hρσ ▸ hσ'⟩)
    (hfLG l hl) hdomLG
    (List.replicate 3 (Program.ode (rightBlock (fRG m) (Term.const 1)) domRG)) (by simp) (by norm_num)
    (by
      intro Q hQ
      rw [List.eq_of_mem_replicate hQ, Program.rename_refl]
      exact hdisH_progR (⟨fRG m, Term.const 1, domRG⟩ : RepoHop 2)
        (hfRG m hm) (by simp [Term.fv]) hdomRG (hfLG l hl) hdomLG)
    (by
      intro Q hQ σ' hσ'
      rw [List.eq_of_mem_replicate hQ]
      exact couple1G l m hl hm dt hdt hv σ' hσ')
    hσ
  rw [show (path.map (fun p => (⟨fRG p, Term.const 1, domRG⟩ : RepoHop 2))).map
      (fun h => h.progR)
      = path.map (fun p => Program.ode (rightBlock (fRG p) (Term.const 1)) domRG)
    from by rw [List.map_map]; rfl] at hfa
  simpa [List.replicate] using hfa


/-! ## The step provider — every window certifies every mode, so the response
stays in place -/

theorem HmultiG (dt : ℝ) (hdt : 0 ≤ dt) (hv00 : VerdG 0 0) (hv01 : VerdG 0 1) (hv02 : VerdG 0 2) (hv11 : VerdG 1 1) (hv12 : VerdG 1 2) (hv22 : VerdG 2 2) :
    ∀ P ∈ leftProgsG dt, ∀ (q : ℕ), q < GrG.modes.length → ∀ σ, σ mvG = (q : ℝ) →
      Formula.sat (Formula.and (FM gG gsG) envG) σ →
      ∃ segs : List (ℕ × RMode (Var 2) × REdge (Var 2)),
        (∀ s ∈ segs, GrG.modeAt s.1 = some s.2.1 ∧ s.2.2 ∈ GrG.edgesFrom s.1) ∧
        List.IsChain (fun a b => a.2.2.tgt = b.1) segs ∧
        (∀ s, segs.head? = some s → s.1 = q) ∧
        Formula.sat (faModal (Equiv.refl (Var 2)) P
          (bigSeq (segs.map (fun s => Program.ode s.2.1.sys s.2.1.dom)))
          (Formula.and (FM gG gsG) envG)) σ := by
  intro P hP q hq σ hmv hσ
  have hq3 : q < 3 := by simpa [GrG] using hq
  have hself : GrG.modeAt q = some (modeG q) ∧ edgeG q q ∈ GrG.edgesFrom q := by
    refine ⟨GrG_modeAt q hq3, edgeG_mem q q ?_⟩
    interval_cases q <;> simp [GrG]
  have hstep : ∀ (a b : ℕ × RMode (Var 2) × REdge (Var 2)) rest,
      a.2.2.tgt = b.1 → List.IsChain (fun x y => x.2.2.tgt = y.1) (b :: rest) →
      List.IsChain (fun x y => x.2.2.tgt = y.1) (a :: b :: rest) := by
    intro a b rest hab hrest
    refine hrest.cons ?_
    intro y hy
    rw [List.head?_cons, Option.mem_some_iff] at hy
    subst hy
    exact hab
  have hhead1 : ∀ (a : ℕ × RMode (Var 2) × REdge (Var 2)) rest s,
      (a :: rest : List _).head? = some s → s = a := by
    intro a rest s hs
    simpa [List.head?_cons] using hs.symm
  simp only [leftProgsG, leftDataG, List.map_cons, List.map_nil, List.mem_cons,
    List.not_mem_nil, or_false] at hP
  have halign : ∀ st tgt : ℕ, st < 3 → tgt < 3 → edgeG st tgt ∈ GrG.edges →
      GrG.modeAt st = some (modeG st) ∧ edgeG st tgt ∈ GrG.edgesFrom st :=
    fun st tgt hs ht he => ⟨GrG_modeAt st hs, edgeG_mem st tgt he⟩
  rcases hP with rfl | rfl | rfl
  all_goals interval_cases q
  · refine ⟨[(0, modeG 0, edgeG 0 0), (0, modeG 0, edgeG 0 0)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl
      · exact halign 0 0 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 0 0 (by norm_num) (by norm_num) (by simp [GrG])
    · exact (hstep _ _ _ rfl (by simp))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondG 0 0 (by norm_num) (by norm_num) dt hdt hv00 [] (by simp) hσ
      simpa [modeG, List.replicate] using this
  · refine ⟨[(1, modeG 1, edgeG 1 1), (1, modeG 1, edgeG 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrG])
    · exact (hstep _ _ _ rfl (by simp))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondG 0 1 (by norm_num) (by norm_num) dt hdt hv01 [] (by simp) hσ
      simpa [modeG, List.replicate] using this
  · refine ⟨[(2, modeG 2, edgeG 2 2), (2, modeG 2, edgeG 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrG])
    · exact (hstep _ _ _ rfl (by simp))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondG 0 2 (by norm_num) (by norm_num) dt hdt hv02 [] (by simp) hσ
      simpa [modeG, List.replicate] using this
  · refine ⟨[(0, modeG 0, edgeG 0 1), (1, modeG 1, edgeG 1 1), (1, modeG 1, edgeG 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl
      · exact halign 0 1 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrG])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondG 1 1 (by norm_num) (by norm_num) dt hdt hv11 [0] (by intro p hp; simp only [List.mem_cons, List.not_mem_nil, or_false] at hp; rcases hp with rfl <;> norm_num) hσ
      simpa [modeG, List.replicate] using this
  · refine ⟨[(1, modeG 1, edgeG 1 1), (1, modeG 1, edgeG 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrG])
    · exact (hstep _ _ _ rfl (by simp))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondG 1 1 (by norm_num) (by norm_num) dt hdt hv11 [] (by simp) hσ
      simpa [modeG, List.replicate] using this
  · refine ⟨[(2, modeG 2, edgeG 2 2), (2, modeG 2, edgeG 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrG])
    · exact (hstep _ _ _ rfl (by simp))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondG 1 2 (by norm_num) (by norm_num) dt hdt hv12 [] (by simp) hσ
      simpa [modeG, List.replicate] using this
  · refine ⟨[(0, modeG 0, edgeG 0 1), (1, modeG 1, edgeG 1 2), (2, modeG 2, edgeG 2 2), (2, modeG 2, edgeG 2 2), (2, modeG 2, edgeG 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl | rfl
      · exact halign 0 1 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 1 2 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrG])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respond3G 2 2 (by norm_num) (by norm_num) dt hdt hv22 [0, 1] (by intro p hp; simp only [List.mem_cons, List.not_mem_nil, or_false] at hp; rcases hp with rfl | rfl <;> norm_num) hσ
      simpa [modeG, List.replicate] using this
  · refine ⟨[(1, modeG 1, edgeG 1 2), (2, modeG 2, edgeG 2 2), (2, modeG 2, edgeG 2 2), (2, modeG 2, edgeG 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl
      · exact halign 1 2 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrG])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respond3G 2 2 (by norm_num) (by norm_num) dt hdt hv22 [1] (by intro p hp; simp only [List.mem_cons, List.not_mem_nil, or_false] at hp; rcases hp with rfl <;> norm_num) hσ
      simpa [modeG, List.replicate] using this
  · refine ⟨[(2, modeG 2, edgeG 2 2), (2, modeG 2, edgeG 2 2), (2, modeG 2, edgeG 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrG])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrG])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respond3G 2 2 (by norm_num) (by norm_num) dt hdt hv22 [] (by simp) hσ
      simpa [modeG, List.replicate] using this

/-- **`endurance_gain_M1`, modal Theorem 3** (λ = 1, k = 2). -/
theorem endurance_gain_M1_modal (dt : ℝ) (hdt : 0 ≤ dt) (hv00 : VerdG 0 0) (hv01 : VerdG 0 1) (hv02 : VerdG 0 2) (hv11 : VerdG 1 1) (hv12 : VerdG 1 2) (hv22 : VerdG 2 2) :
    RFormula.rvalid (theorem3Form
      (bigChoice (leftProgsG dt))
      (rightAutomatonBody GrG mvG)
      (RFormula.and (RFormula.and (canonInvM gG gsG) (envLR domLG domRG))
        (mvValidR mvG GrG.modes.length))) := by
  refine theorem3_faithful_multiF_LR GrG mvG (FM gG gsG) domLG domRG
    (leftProgsG dt) (canonInvM gG gsG) (encode_canonInvM gG gsG) ?_ ?_ ?_
  · exact hdis_multi GrG 0 1 dt leftDataG (by decide) httG hRvG hLG
  · exact hstep_assembled_multiF GrG mvG (FM gG gsG) envG (leftProgsG dt)
      hmvFG hmvenvG hfreshG httG hltG (hframesG dt)
      (HmultiG dt hdt hv00 hv01 hv02 hv11 hv12 hv22)
  · exact hddF_multiE GrG 0 1 dt leftDataG (canonInvM gG gsG) domLG domRG
      (by decide) httG hRvG hLG
      (canonInvM_varsL gG gsG (by
        intro g' hg'
        simp only [gG, gsG, List.mem_cons, List.not_mem_nil, or_false] at hg'
        rcases hg' with rfl <;> exact hgAt _))
      (canonInvM_varsR gG gsG) hdomLG hdomRG

end EnduranceGainM1Modal
end RelCertifier
