/-
Copyright (c) 2026 relCertifier-lean contributors.
Released under Apache 2.0 license.

# EvolStrengthenings aggregator (re-exports the per-benchmark leaves) (GENERATED leaf — do not edit)

Per-benchmark leaf module (X0 modularization): editing one benchmark no longer
re-elaborates the whole instance battery. Import only from whole-suite consumers.
-/
import RelCertifier.Instances.EvolStrengthenings.arm_chain_rung1
import RelCertifier.Instances.EvolStrengthenings.arm_chain_rung2
import RelCertifier.Instances.EvolStrengthenings.arm_chain_rung3
import RelCertifier.Instances.EvolStrengthenings.arm_fidelity_low
import RelCertifier.Instances.EvolStrengthenings.arm_fidelity_mid
import RelCertifier.Instances.EvolStrengthenings.attitude_rate
import RelCertifier.Instances.EvolStrengthenings.endurance_gain_M1
import RelCertifier.Instances.EvolStrengthenings.endurance_orderlift_1to2
import RelCertifier.Instances.EvolStrengthenings.endurance_orderlift_2to3
import RelCertifier.Instances.EvolStrengthenings.match_multi_rate
import RelCertifier.Instances.EvolStrengthenings.refinement_ladder_rover_rung1_2to3
import RelCertifier.Instances.EvolStrengthenings.refinement_ladder_rover_rung2_3to6
import RelCertifier.Instances.EvolStrengthenings.refinement_ladder_rover_rung2_6dof
import RelCertifier.Instances.EvolStrengthenings.refinement_ladder_rover_rung2b_6dof
import RelCertifier.Instances.EvolStrengthenings.refinement_ladder_rover_rung2c_6dof
import RelCertifier.Instances.EvolStrengthenings.refinement_ladder_rover_rung3_6to8
import RelCertifier.Instances.EvolStrengthenings.refinement_ladder_rover_rung4_8to12
import RelCertifier.Instances.EvolStrengthenings.robot_braking
import RelCertifier.Instances.EvolStrengthenings.rover3_M1
import RelCertifier.Instances.EvolStrengthenings.rover3tier_M1
import RelCertifier.Instances.EvolStrengthenings.rover3tier_rung12
import RelCertifier.Instances.EvolStrengthenings.rover_4d_box
import RelCertifier.Instances.EvolStrengthenings.rover_attitude_cone_12dof
import RelCertifier.Instances.EvolStrengthenings.rover_coupled
import RelCertifier.Instances.EvolStrengthenings.rover_dof_terrain_rung1
import RelCertifier.Instances.EvolStrengthenings.rover_dof_terrain_rung2
import RelCertifier.Instances.EvolStrengthenings.rover_dof_terrain_rung3
import RelCertifier.Instances.EvolStrengthenings.rover_dof_terrain_rung3_8d
import RelCertifier.Instances.EvolStrengthenings.rover_drag
import RelCertifier.Instances.EvolStrengthenings.rover_position
import RelCertifier.Instances.EvolStrengthenings.rover_terrain_M1
import RelCertifier.Instances.EvolStrengthenings.rover_tier_r1
import RelCertifier.Instances.EvolStrengthenings.story1_attdist_rung_a_6to8
import RelCertifier.Instances.EvolStrengthenings.story1_attdist_rung_b_12dof
import RelCertifier.Instances.EvolStrengthenings.story2_lateral_rung_a_8dof
import RelCertifier.Instances.EvolStrengthenings.story2_lateral_rung_b_12dof
import RelCertifier.Instances.EvolStrengthenings.story3_rollover_base_12dof
import RelCertifier.Instances.EvolStrengthenings.story3_rollover_ladder_rung_a
import RelCertifier.Instances.EvolStrengthenings.story3_rollover_ladder_rung_b
import RelCertifier.Instances.EvolStrengthenings.watertank
