/-
Copyright (c) 2026 relCertifier-lean contributors.
Released under Apache 2.0 license.

# T3+ — `rover3_M1`, modal Theorem 3 (multiF, GENERATED)

Generated by `scripts/gen_multif_instance.py` from the coordinate spec: the plain
list-invariant pattern at n = 2 with 1 invariant components in the cover's
stratified-DC order, the one-way terrain chain, and climb dispatch. Existence is
Z3-free (stratified faces).

Residuals: six stratified-DC verdict packs (`VerdP l m`). Axioms: the standard
three + `z3_unsat_sound` at those leaves.
-/
import RelCertifier.Proofs.Encoding.EnvelopeChainM
import RelCertifier.Proofs.Encoding.RepoPrefixR
import RelCertifier.Proofs.Encoding.WindowGrowth
import RelCertifier.Proofs.Encoding.CanonicalInv
import RelCertifier.Proofs.Encoding.CoverInstance
import RelCertifier.Proofs.Flow.StratifiedFaces
import RelCertifier.Instances.BenchIR.rover3_M1

namespace RelCertifier
namespace Rover3M1Modal

open DL DLCalTiming DLRel Parse Set

set_option maxHeartbeats 12800000

def vsP : List String := ["px", "vx"]
def dummyP : Parse.PMode := ⟨"", [], .tt, .tt, []⟩
def mLP (l : ℕ) : Parse.PMode := rover3_M1_IR.L.modes.getD l dummyP
def mRP (q : ℕ) : Parse.PMode := rover3_M1_IR.R.modes.getD q dummyP

abbrev mvP : Var 2 := (Side.Aux, 0)
abbrev aP : Fin 2 := (1 : Fin 2)
abbrev tgP : Var 2 := (Side.Aux, aP)

noncomputable def fLP (l : ℕ) : Fin 2 → Term (Var 2) := hostDyn vsP 2 Side.L (mLP l)
noncomputable def fRP (q : ℕ) : Fin 2 → Term (Var 2) := hostDyn vsP 2 Side.R (mRP q)
noncomputable def domLP : Formula (Var 2) := hostEvolve vsP 2 Side.L (mLP 0)
noncomputable def domRP : Formula (Var 2) := hostEvolve vsP 2 Side.R (mRP 0)
noncomputable def envP : Formula (Var 2) := Formula.and domLP domRP

def atomsOf : Parse.PForm → List Parse.PForm
  | .and x y => atomsOf x ++ atomsOf y
  | f => [f]

def invPPF : Parse.PForm :=
  (rover3_M1_IR.invariants.getD 2 ("", Parse.PForm.tt)).2

noncomputable def gAt (i : ℕ) : Term (Var 2) :=
  ((Run.invToG vsP 2 ((atomsOf invPPF).getD i .tt)).map ITerm.toHost).getD (Term.const 0)

noncomputable def gP : Term (Var 2) := gAt 0
noncomputable def gsP : List (Term (Var 2)) := []

/-! ## Side-splits -/

theorem fLP_pipe (l : ℕ) (i : Fin 2) : fLP l i =
    (((some (mLP l)).bind (Run.dynOf vsP 2 Side.L)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem fRP_pipe (q : ℕ) (i : Fin 2) : fRP q i =
    (((some (mRP q)).bind (Run.dynOf vsP 2 Side.R)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem domLP_pipe : domLP =
    (((some (mLP 0)).bind (fun m => Run.lowerF vsP 2 Side.L m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl
theorem domRP_pipe : domRP =
    (((some (mRP 0)).bind (fun m => Run.lowerF vsP 2 Side.R m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl

theorem hfLP (l : ℕ) (hl : l < 3) : ∀ i, (fLP l i).fv ⊆ range Lv := fun i x hx =>
  side_eq_L_mem (field_pipeline_side (resolvesTo_L vsP) (some (mLP l))
    (by interval_cases l <;>
      simp [mLP, rover3_M1_IR, Parse.PExpr.namesFree]) i x
    (fLP_pipe l i ▸ hx))

theorem hfRP (q : ℕ) (hq : q < 3) : ∀ i, (fRP q i).fv ⊆ range Rv := fun i x hx =>
  side_eq_R_mem (field_pipeline_side (resolvesTo_R vsP) (some (mRP q))
    (by interval_cases q <;>
      simp [mRP, rover3_M1_IR, Parse.PExpr.namesFree]) i x
    (fRP_pipe q i ▸ hx))

theorem hdomLP : domLP.fv ⊆ range Lv := fun x hx =>
  side_eq_L_mem (form_pipeline_side (resolvesTo_L vsP) (some (mLP 0))
    (by simp [mLP, rover3_M1_IR, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domLP_pipe ▸ hx))

theorem hdomRP : domRP.fv ⊆ range Rv := fun x hx =>
  side_eq_R_mem (form_pipeline_side (resolvesTo_R vsP) (some (mRP 0))
    (by simp [mRP, rover3_M1_IR, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domRP_pipe ▸ hx))

theorem hgAt (i : ℕ) : (gAt i).fv ⊆ range Lv ∪ range Rv := invToG_pipeline_LR _

theorem hmvg : ∀ g' ∈ gP :: gsP, mvP ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [gP, gsP, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with rfl <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem htgg : ∀ g' ∈ gP :: gsP, tgP ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [gP, gsP, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with rfl <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem hmvFP : mvP ∉ (FM gP gsP).fv := notMem_FM_fv hmvg
theorem htgFP : tgP ∉ (FM gP gsP).fv := notMem_FM_fv htgg

theorem hmvenvP : mvP ∉ envP.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomLP h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomRP h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))
theorem htgenvP : tgP ∉ envP.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomLP h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomRP h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))

/-! ## The right graph (one-way chain) -/

noncomputable def modeP (q : ℕ) : RMode (Var 2) :=
  { sys := rightBlock (fRP q) (Term.const 1), dom := domRP, weight := 1 }

def edgeP (st tgt : ℕ) : REdge (Var 2) :=
  { src := st, tgt := tgt, guard := Formula.tt, pruned := false }

noncomputable def GrP : SearchGraph (Var 2) :=
  { modes := [modeP 0, modeP 1, modeP 2],
    edges := [edgeP 0 1, edgeP 0 0, edgeP 1 2, edgeP 1 1, edgeP 2 2] }

theorem GrP_modeAt (q : ℕ) (hq : q < 3) : GrP.modeAt q = some (modeP q) := by
  interval_cases q <;> rfl

theorem httP : ∀ q, ∀ e ∈ GrP.edgesFrom q, e.guard = Formula.tt := by
  intro q e he
  have hmem : e ∈ GrP.edges := List.mem_of_mem_filter he
  simp only [GrP, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> rfl

theorem hltP : ∀ q, ∀ e ∈ GrP.edgesFrom q, e.tgt < GrP.modes.length := by
  intro q e he
  have hmem : e ∈ GrP.edges := List.mem_of_mem_filter he
  simp only [GrP, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> norm_num [GrP, edgeP]

theorem hRvP : ∀ q m, GrP.modeAt q = some m →
    m.sys.boundSet ∪ m.sys.readVars ∪ m.dom.fv ⊆ range Rv := by
  intro q m hm
  have hqm : q < 3 ∧ m = modeP q := by
    match q with
    | 0 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrP] using hm.symm⟩
    | 1 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrP] using hm.symm⟩
    | 2 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrP] using hm.symm⟩
    | q + 3 => exact absurd hm (by simp [SearchGraph.modeAt, GrP])
  obtain ⟨hq3, rfl⟩ := hqm
  intro y hy
  rcases hy with (hy | hy) | hy
  · exact rightBlock_boundSet_sub (fRP q) (Term.const 1) hy
  · exact rightBlock_readVars_sub (fRP q) (Term.const 1) (hfRP q hq3)
      (by simp [Term.fv]) hy
  · exact hdomRP hy

theorem edgeP_mem : ∀ st tgt, edgeP st tgt ∈ GrP.edges →
    edgeP st tgt ∈ GrP.edgesFrom st :=
  fun st tgt he => List.mem_filter.mpr ⟨he, by simp [edgeP]⟩

theorem hfreshP : ∀ q m, GrP.modeAt q = some m →
    mvP ∉ (Program.ode m.sys m.dom).fv := by
  intro q m hm hmv
  exact aux_notin_range_Rv 0 (hRvP q m hm (vars_ode_sub _ _ (Or.inl hmv)))

/-! ## The left window family -/

noncomputable def leftDataP : List ((Fin 2 → Term (Var 2)) × Formula (Var 2) × ℕ) :=
  [(fLP 0, domLP, 2), (fLP 1, domLP, 2), (fLP 2, domLP, 2)]

noncomputable def leftProgsP (dt : ℝ) : List (Program (Var 2)) :=
  leftDataP.map (fun d => windowSeg (leftBlock d.1) d.2.1 tgP dt d.2.2)

theorem hLP : ∀ d ∈ leftDataP, (∀ i, (d.1 i).fv ⊆ range Lv) ∧ d.2.1.fv ⊆ range Lv := by
  intro d hd
  simp only [leftDataP, List.mem_cons, List.not_mem_nil, or_false] at hd
  rcases hd with rfl | rfl | rfl
  · exact ⟨hfLP 0 (by norm_num), hdomLP⟩
  · exact ⟨hfLP 1 (by norm_num), hdomLP⟩
  · exact ⟨hfLP 2 (by norm_num), hdomLP⟩

theorem hframesP (dt : ℝ) : ∀ P ∈ leftProgsP dt, FramesMv P mvP := by
  intro P hP
  simp only [leftProgsP, List.mem_map] at hP
  obtain ⟨d, hd, rfl⟩ := hP
  refine framesMv_window (leftBlock d.1) d.2.1 tgP dt d.2.2 mvP (by decide) ?_
  intro h
  obtain ⟨i, hi⟩ := leftBlock_bound_sub d.1 _ h
  exact aux_ne_Lv 0 i hi

/-! ## Parse pins -/

theorem hp04 : Run.parseRat "0.4" = some ((2:ℚ)/5) := by
  have h : parseQ "0.4" = some (⟨4, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hp02 : Run.parseRat "0.2" = some ((1:ℚ)/5) := by
  have h : parseQ "0.2" = some (⟨2, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hp01 : Run.parseRat "0.1" = some ((1:ℚ)/10) := by
  have h : parseQ "0.1" = some (⟨1, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hpm05 : Run.parseRat "-0.5" = some (-(1:ℚ)/2) := by
  have h : parseQ "-0.5" = some (⟨-5, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hp0 : Run.parseRat "0" = some (0) := by
  have h : parseQ "0" = some (⟨0, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hp1 : Run.parseRat "1" = some (1) := by
  have h : parseQ "1" = some (⟨1, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hp00 : Run.parseRat "0.0" = some (0) := by
  have h : parseQ "0.0" = some (⟨0, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hpm005 : Run.parseRat "-0.05" = some (-(1:ℚ)/20) := by
  have h : parseQ "-0.05" = some (⟨-5, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hp025 : Run.parseRat "0.25" = some ((1:ℚ)/4) := by
  have h : parseQ "0.25" = some (⟨25, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hp03 : Run.parseRat "0.3" = some ((3:ℚ)/10) := by
  have h : parseQ "0.3" = some (⟨3, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hp075 : Run.parseRat "0.75" = some ((3:ℚ)/4) := by
  have h : parseQ "0.75" = some (⟨75, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hp11 : Run.parseRat "1.1" = some ((11:ℚ)/10) := by
  have h : parseQ "1.1" = some (⟨11, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hp05 : Run.parseRat "0.5" = some ((1:ℚ)/2) := by
  have h : parseQ "0.5" = some (⟨5, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hp20 : Run.parseRat "2.0" = some (2) := by
  have h : parseQ "2.0" = some (⟨20, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hp2 : Run.parseRat "2" = some (2) := by
  have h : parseQ "2" = some (⟨2, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hp120 : Run.parseRat "12.0" = some (12) := by
  have h : parseQ "12.0" = some (⟨120, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num

theorem hp10 : Run.parseRat "1.0" = some (1) := by
  have h : parseQ "1.0" = some (⟨10, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]

/-! ## Field and shape pins -/

noncomputable def cstP (q : ℕ) : ℝ := if q = 0 then 2/5 else if q = 1 then 1/5 else 0

theorem fRP0_eval (q : ℕ) (hq : q < 3) (x : State (Var 2)) :
    Term.eval (fRP q 0) x = x (Rv 1) := by
  interval_cases q <;>
    · simp [fRP, hostDyn, mRP, rover3_M1_IR, vsP, Run.dynOf,
      Run.lowerE, hp04, hp02, hp0, hp1, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
      try ring

theorem fRP1_eval (q : ℕ) (hq : q < 3) (x : State (Var 2)) :
    Term.eval (fRP q 1) x = cstP q := by
  interval_cases q <;>
    · simp [fRP, hostDyn, mRP, rover3_M1_IR, vsP, Run.dynOf,
      Run.lowerE, hp04, hp02, hp0, hp1, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv, cstP]
      try norm_num
theorem sat_domRP (x : State (Var 2)) : Formula.sat domRP x ↔
    (-(1:ℝ)/20 ≤ x (Rv 0) ∧ (1:ℝ)/4 ≤ x (Rv 1) ∧ x (Rv 1) ≤ (11:ℝ)/10) := by
  simp only [domRP, hostEvolve, mRP, rover3_M1_IR, vsP]
  simp [Run.lowerF, Run.lowerE, hpm005, hp025, hp11,
    Run.resolveVar, List.findIdx?_cons, IForm.toHost, ITerm.toHost, Formula.sat,
    CompOp.interp, Term.eval, Rv]
  tauto


/-! ## The invariant's shape and the left-side extractors -/

theorem eval_gP (x : State (Var 2)) :
    Term.eval gP x = x (Lv 0) - (x (Rv 0) + 2) := by
  have hdL : ("L_px".drop 2).copy = "px" := by decide
  have hdR : ("R_px".drop 2).copy = "px" := by decide
  simp [gP, gAt, atomsOf, invPPF, rover3_M1_IR, Run.invToG, Run.lowerE, vsP,
    Run.resolveVar, Parse.dr, hdL, hdR, List.findIdx?_cons, hp20,
    ITerm.toHost, Term.eval, AOp.interp, Lv, Rv]

theorem sat_domLP (x : State (Var 2)) : Formula.sat domLP x ↔
    (-(1:ℝ)/20 ≤ x (Lv 0) ∧ x (Lv 0) ≤ 12 ∧ -(1:ℝ)/20 ≤ x (Lv 1) ∧ x (Lv 1) ≤ 1) := by
  simp only [domLP, hostEvolve, mLP, rover3_M1_IR, vsP]
  simp [Run.lowerF, Run.lowerE, hpm005, hp120, hp10, Run.resolveVar,
    List.findIdx?_cons, IForm.toHost, ITerm.toHost, Formula.sat,
    CompOp.interp, Term.eval, Lv]
  tauto

/-! ## Window facts specialized to the left position -/

theorem leftBlock_wf (fL : Fin 2 → Term (Var 2)) : (leftBlock fL).WellFormed := by
  have hLinj : Function.Injective (Lv (n := 2)) := by
    intro a b h; simpa [Lv, Prod.ext_iff] using h
  unfold ODESystem.WellFormed leftBlock
  simp only [List.map_map, Function.comp_def]
  exact (List.nodup_finRange 2).map hLinj

theorem htg_leftBlock (fL : Fin 2 → Term (Var 2)) : tgP ∉ (leftBlock fL).bound := by
  intro h
  obtain ⟨i, hi⟩ := leftBlock_bound_sub fL _ h
  exact aux_ne_Lv 1 i hi

theorem fLP0_eval (l : ℕ) (hl : l < 3) (x : State (Var 2)) :
    Term.eval (fLP l 0) x = x (Lv 1) := by
  interval_cases l <;>
    · simp [fLP, hostDyn, mLP, rover3_M1_IR, vsP, Run.dynOf,
        Run.lowerE, hp02, hp01, hpm05, hp0, hp1, Run.resolveVar,
        List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Lv]

theorem window_pxL_bound (l : ℕ) (hl : l < 3) (dt : ℝ) (hdt : 0 ≤ dt) (k : ℕ)
    {σ ν : State (Var 2)}
    (hsem : Program.sem (windowSeg (leftBlock (fLP l)) domLP tgP dt k) σ ν) :
    ν (Lv 0) ≤ σ (Lv 0) + (k : ℝ) * dt := by
  have hwfL := leftBlock_wf (fLP l)
  have htgb := htg_leftBlock (fLP l)
  have hbnd : ∀ x : State (Var 2), Formula.sat domLP x →
      Lie (DLCalTiming.clk tgP (leftBlock (fLP l)))
        (fun ω => Term.eval (Term.var (Lv 0)) ω) x ≤ 1 := by
    intro x hx
    have hfun : (fun ω : State (Var 2) => Term.eval (Term.var (Lv 0)) ω)
        = fun y => (1 : ℝ) * y (Lv 0) + 0 := by
      funext y; simp [Term.eval]
    rw [hfun, lie_affine_coord _ (clk_wellFormed tgP _ hwfL htgb) (Lv 0) 1 0 x]
    have hmem : ((Lv 0 : Var 2), fLP l 0) ∈ DLCalTiming.clk tgP (leftBlock (fLP l)) := by
      simp only [DLCalTiming.clk, List.mem_append]
      exact Or.inl (List.mem_map.mpr ⟨0, List.mem_finRange 0, rfl⟩)
    have hb : (Lv 0 : Var 2) ∈ (DLCalTiming.clk tgP (leftBlock (fLP l))).bound :=
      List.mem_map.mpr ⟨_, hmem, rfl⟩
    have hfield : odeField (DLCalTiming.clk tgP (leftBlock (fLP l))) x (Lv 0)
        = Term.eval (fLP l 0) x := by
      simp only [odeField, if_pos hb]
      rw [ODESystem.rhs_eq_of_mem (clk_wellFormed tgP _ hwfL htgb) hmem]
    rw [hfield, fLP0_eval l hl]
    have := (sat_domLP x).mp hx
    linarith [this.2.2.2]
  have hg := windowSeg_growth (leftBlock (fLP l)) domLP tgP dt k hwfL htgb
    (Term.var (Lv 0)) 1 (by norm_num)
    (by intro h; simp only [Term.fv, Set.mem_singleton_iff] at h;
        exact absurd h (by simp [tgP, Lv, Prod.ext_iff])) hbnd hdt hsem
  simpa [Term.eval] using hg

theorem window_maskP (l : ℕ) (dt : ℝ) (k : ℕ)
    {σ ν : State (Var 2)}
    (hsem : Program.sem (windowSeg (leftBlock (fLP l)) domLP tgP dt k) σ ν) :
    ∀ j : Fin 2, ν (Rv j) = σ (Rv j) := by
  intro j
  refine windowSeg_mask (leftBlock (fLP l)) domLP tgP dt k (leftBlock_wf (fLP l))
    (htg_leftBlock (fLP l)) hsem (Rv j) ?_
  intro h
  simp only [DLCalTiming.clk, ODESystem.bound, List.map_append, List.mem_append] at h
  rcases h with h | h
  · obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLP l) _ (by simpa [ODESystem.bound] using h)
    exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])
  · simp only [List.map_cons, List.map_nil, List.mem_singleton] at h
    exact absurd h (by simp [Rv, tgP, Prod.ext_iff])

/-! ## The Safe hold run -/

/-- The Safe-mode hold: velocity frozen, position linear — any duration. -/
theorem sem_safe_hold (τ : ℝ) (hτ : 0 ≤ τ) {μ : State (Var 2)}
    (hdom : Formula.sat domRP μ) :
    Program.sem (Program.ode (rightBlock (fRP 2) (Term.const 1)) domRP) μ
      (fun x => if x = Rv 0 then μ (Rv 0) + μ (Rv 1) * τ else μ x) := by
  have hR : (-(1:ℝ)/20 ≤ μ (Rv 0) ∧ (1:ℝ)/4 ≤ μ (Rv 1) ∧ μ (Rv 1) ≤ (11:ℝ)/10) := by
    have := (sat_domRP μ).mp hdom
    exact ⟨this.1, this.2.1, this.2.2⟩
  have hne10 : (Rv 1 : Var 2) ≠ Rv 0 := by simp [Rv, Prod.ext_iff]
  classical
  refine ⟨τ, fun t x => if x = Rv 0 then μ (Rv 0) + μ (Rv 1) * t else μ x,
    hτ, ?_, ?_, ?_, ?_, ?_⟩
  · funext x
    by_cases h0 : x = Rv 0
    · subst h0; simp
    · simp [if_neg h0]
  · rfl
  · intro t ht p hp
    simp only [rightBlock, List.mem_map, List.mem_finRange] at hp
    obtain ⟨i, -, rfl⟩ := hp
    fin_cases i
    · have heval : Term.eval (Term.binop AOp.mul (Term.const 1) (fRP 2 ⟨0, by norm_num⟩))
          (fun x => if x = Rv 0 then μ (Rv 0) + μ (Rv 1) * t else μ x)
          = μ (Rv 1) := by
        simp [Term.eval, AOp.interp, show fRP 2 ⟨0, by norm_num⟩ = fRP 2 0 from rfl,
          fRP0_eval 2 (by norm_num), if_neg hne10]
      simp only [heval]
      have h2 : HasDerivWithinAt (fun u : ℝ => μ (Rv 0) + μ (Rv 1) * u)
          (μ (Rv 1) * 1) (Set.Icc 0 τ) t :=
        ((hasDerivWithinAt_id t (Set.Icc (0:ℝ) τ)).const_mul (μ (Rv 1))).const_add (μ (Rv 0))
      have heq : μ (Rv 1) * 1 = μ (Rv 1) := by ring
      rw [heq] at h2
      refine HasDerivWithinAt.congr h2 ?_ ?_
      · intro y _; simp
      · simp
    · have heval : Term.eval (Term.binop AOp.mul (Term.const 1) (fRP 2 ⟨1, by norm_num⟩))
          (fun x => if x = Rv 0 then μ (Rv 0) + μ (Rv 1) * t else μ x)
          = 0 := by
        simp [Term.eval, AOp.interp, show fRP 2 ⟨1, by norm_num⟩ = fRP 2 1 from rfl,
          fRP1_eval 2 (by norm_num), cstP]
      simp only [heval]
      refine HasDerivWithinAt.congr
        (hasDerivWithinAt_const t (Set.Icc (0:ℝ) τ) (μ (Rv 1))) ?_ ?_
      · intro y _; simp [if_neg hne10]
      · simp [if_neg hne10]
  · intro t ht x hx
    have hx0 : x ≠ Rv 0 := by
      intro h; subst h
      exact hx (by
        simp only [rightBlock, ODESystem.bound, List.map_map, List.mem_map]
        exact ⟨0, List.mem_finRange 0, rfl⟩)
    simp [if_neg hx0]
  · intro t ht
    rw [sat_domRP]
    have ht0 : (0:ℝ) ≤ t := ht.1
    have hne10' : (Rv 1 : Var 2) ≠ Rv 0 := by simp [Rv, Prod.ext_iff]
    refine ⟨?_, ?_, ?_⟩
    · simp only [eq_self_iff_true, if_true, if_pos rfl]
      have : 0 ≤ μ (Rv 1) * t := mul_nonneg (by linarith [hR.2.1]) ht0
      linarith [hR.1]
    · simp only [if_neg hne10']
      exact hR.2.1
    · simp only [if_neg hne10']
      exact hR.2.2

/-! ## The catch-up step provider — hops to Safe, one hold run, endpoint arithmetic -/

theorem HmultiP (dt : ℝ) (hdt : 0 ≤ dt) :
    ∀ P ∈ leftProgsP dt, ∀ (q : ℕ), q < GrP.modes.length → ∀ σ, σ mvP = (q : ℝ) →
      Formula.sat (Formula.and (FM gP gsP) envP) σ →
      ∃ segs : List (ℕ × RMode (Var 2) × REdge (Var 2)),
        (∀ s ∈ segs, GrP.modeAt s.1 = some s.2.1 ∧ s.2.2 ∈ GrP.edgesFrom s.1) ∧
        List.IsChain (fun a b => a.2.2.tgt = b.1) segs ∧
        (∀ s, segs.head? = some s → s.1 = q) ∧
        Formula.sat (faModal (Equiv.refl (Var 2)) P
          (bigSeq (segs.map (fun s => Program.ode s.2.1.sys s.2.1.dom)))
          (Formula.and (FM gP gsP) envP)) σ := by
  intro P hP q hq σ hmv hσ
  have hq3 : q < 3 := by simpa [GrP] using hq
  have hφ : σ (Lv 0) ≤ σ (Rv 0) + 2 := by
    have := (sat_FM_iff gP gsP σ).mp hσ.1 gP List.mem_cons_self
    rw [eval_gP] at this
    linarith
  have hdomRσ : Formula.sat domRP σ := hσ.2.2
  have hRb := (sat_domRP σ).mp hdomRσ
  simp only [leftProgsP, leftDataP, List.map_cons, List.map_nil, List.mem_cons,
    List.not_mem_nil, or_false] at hP
  -- the response is mode-path-to-Safe (zero-duration) plus one Safe hold of 8·dt
  have hchain2 : ∀ (a b c : ℕ × RMode (Var 2) × REdge (Var 2)),
      a.2.2.tgt = b.1 → b.2.2.tgt = c.1 →
      List.IsChain (fun x y => x.2.2.tgt = y.1) [a, b, c] := by
    intro a b c hab hbc
    refine (List.isChain_cons.mpr ⟨?_, ?_⟩)
    · intro y hy
      rw [List.head?_cons, Option.mem_some_iff] at hy
      subst hy; exact hab
    · refine (List.isChain_cons.mpr ⟨?_, by simp⟩)
      intro y hy
      rw [List.head?_cons, Option.mem_some_iff] at hy
      subst hy; exact hbc
  have hbuild : ∀ (l : ℕ), l < 3 → P = windowSeg (leftBlock (fLP l)) domLP tgP dt 2 →
      ∃ segs : List (ℕ × RMode (Var 2) × REdge (Var 2)),
        (∀ s ∈ segs, GrP.modeAt s.1 = some s.2.1 ∧ s.2.2 ∈ GrP.edgesFrom s.1) ∧
        List.IsChain (fun a b => a.2.2.tgt = b.1) segs ∧
        (∀ s, segs.head? = some s → s.1 = q) ∧
        Formula.sat (faModal (Equiv.refl (Var 2)) P
          (bigSeq (segs.map (fun s => Program.ode s.2.1.sys s.2.1.dom)))
          (Formula.and (FM gP gsP) envP)) σ := by
    intro l hl hPeq
    subst hPeq
    -- the faModal body, shared by all starts: the right survives the window,
    -- hops (zero-duration) to Safe, holds for 8·dt
    have hbody : ∀ (pres : List (Program (Var 2))),
        (∀ Q ∈ pres, ∀ μ : State (Var 2), Formula.sat domRP μ →
          Program.sem Q μ μ) →
        Formula.sat (faModal (Equiv.refl (Var 2))
          (windowSeg (leftBlock (fLP l)) domLP tgP dt 2)
          (bigSeq (pres ++ [Program.ode (rightBlock (fRP 2) (Term.const 1)) domRP]))
          (Formula.and (FM gP gsP) envP)) σ := by
      intro pres hpres
      rw [faModal_sat]
      intro ν hleft
      have hpx := window_pxL_bound l hl dt hdt 2 hleft
      push_cast at hpx
      have hmaskν := window_maskP l dt 2 hleft
      have hdomLν := windowSeg_end_domL (leftBlock (fLP l)) domLP tgP dt 2
        (by norm_num) hleft
      have hdomRν : Formula.sat domRP ν := by
        rw [sat_domRP]
        rw [hmaskν 0, hmaskν 1]
        exact (sat_domRP σ).mp hdomRσ
      set τ : ℝ := 8 * dt with hτdef
      have hτ : 0 ≤ τ := by positivity
      have hhold := sem_safe_hold τ hτ hdomRν
      set μfin : State (Var 2) :=
        (fun x => if x = Rv 0 then ν (Rv 0) + ν (Rv 1) * τ else ν x) with hμfin
      -- glue: pres are identity runs on ν, then the hold
      have hsemseq : Program.sem
          (bigSeq (pres ++ [Program.ode (rightBlock (fRP 2) (Term.const 1)) domRP]))
          ν μfin := by
        clear hpx
        induction pres with
        | nil =>
            simp only [List.nil_append, bigSeq]
            exact ⟨μfin, hhold, by rw [sem_test]; exact ⟨rfl, trivial⟩⟩
        | cons Q rest ih =>
            simp only [List.cons_append, bigSeq]
            refine ⟨ν, hpres Q List.mem_cons_self ν hdomRν, ?_⟩
            exact ih (fun Q' hQ' => hpres Q' (List.mem_cons_of_mem _ hQ'))
      refine ⟨μfin, by rw [Program.rename_refl]; exact hsemseq, ?_, ?_⟩
      · -- the invariant at the endpoint: catch-up arithmetic
        rw [sat_FM_iff]
        intro g' hg'
        rcases List.mem_cons.mp hg' with rfl | hg'
        · rw [eval_gP]
          have hν0 : μfin (Lv 0) = ν (Lv 0) := by
            simp [hμfin, if_neg (show (Lv 0 : Var 2) ≠ Rv 0 by simp [Lv, Rv, Prod.ext_iff])]
          have hνR : μfin (Rv 0) = ν (Rv 0) + ν (Rv 1) * τ := by simp [hμfin]
          rw [hν0, hνR]
          have hvfloor : (1:ℝ)/4 ≤ ν (Rv 1) := by
            rw [hmaskν 1]; exact hRb.2.1
          have hgain : 2 * dt ≤ ν (Rv 1) * τ := by
            rw [hτdef]
            nlinarith
          have hRν : ν (Rv 0) = σ (Rv 0) := hmaskν 0
          rw [hRν]
          linarith
        · exact absurd hg' (by simp [gsP])
      · -- the environment at the endpoint
        constructor
        · -- domL: μfin agrees with ν on left coords
          have : Formula.sat domLP μfin := by
            rw [sat_domLP]
            have h0 : μfin (Lv 0) = ν (Lv 0) := by
              simp [hμfin, if_neg (show (Lv 0 : Var 2) ≠ Rv 0 by simp [Lv, Rv, Prod.ext_iff])]
            have h1 : μfin (Lv 1) = ν (Lv 1) := by
              simp [hμfin, if_neg (show (Lv 1 : Var 2) ≠ Rv 0 by simp [Lv, Rv, Prod.ext_iff])]
            rw [h0, h1]
            exact (sat_domLP ν).mp hdomLν
          exact this
        · exact sem_ode_ends_in_domain hhold
    -- dispatch on the start mode: zero-hops up the chain, hold in Safe
    interval_cases q
    · refine ⟨[(0, modeP 0, edgeP 0 1), (1, modeP 1, edgeP 1 2), (2, modeP 2, edgeP 2 2)],
        ?_, ?_, ?_, ?_⟩
      · intro s hs
        simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
        rcases hs with rfl | rfl | rfl
        · exact ⟨GrP_modeAt 0 (by norm_num), edgeP_mem 0 1 (by simp [GrP])⟩
        · exact ⟨GrP_modeAt 1 (by norm_num), edgeP_mem 1 2 (by simp [GrP])⟩
        · exact ⟨GrP_modeAt 2 (by norm_num), edgeP_mem 2 2 (by simp [GrP])⟩
      · exact hchain2 _ _ _ rfl rfl
      · intro s hs
        simp only [List.head?_cons, Option.some_inj] at hs
        rw [← hs]
      · have := hbody [Program.ode (rightBlock (fRP 0) (Term.const 1)) domRP,
          Program.ode (rightBlock (fRP 1) (Term.const 1)) domRP]
          (by
            intro Q hQ μ hdom
            simp only [List.mem_cons, List.not_mem_nil, or_false] at hQ
            rcases hQ with rfl | rfl
            · obtain ⟨ρ, hsem, hρ⟩ := static_hop_existsR (fR := fRP 0)
                (lam := Term.const 1) (domR := domRP) hdom
              rwa [hρ] at hsem
            · obtain ⟨ρ, hsem, hρ⟩ := static_hop_existsR (fR := fRP 1)
                (lam := Term.const 1) (domR := domRP) hdom
              rwa [hρ] at hsem)
        simpa [modeP] using this
    · refine ⟨[(1, modeP 1, edgeP 1 2), (2, modeP 2, edgeP 2 2)], ?_, ?_, ?_, ?_⟩
      · intro s hs
        simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
        rcases hs with rfl | rfl
        · exact ⟨GrP_modeAt 1 (by norm_num), edgeP_mem 1 2 (by simp [GrP])⟩
        · exact ⟨GrP_modeAt 2 (by norm_num), edgeP_mem 2 2 (by simp [GrP])⟩
      · refine (List.isChain_cons.mpr ⟨?_, by simp⟩)
        intro y hy
        rw [List.head?_cons, Option.mem_some_iff] at hy
        subst hy; rfl
      · intro s hs
        simp only [List.head?_cons, Option.some_inj] at hs
        rw [← hs]
      · have := hbody [Program.ode (rightBlock (fRP 1) (Term.const 1)) domRP]
          (by
            intro Q hQ μ hdom
            simp only [List.mem_cons, List.not_mem_nil, or_false] at hQ
            subst hQ
            obtain ⟨ρ, hsem, hρ⟩ := static_hop_existsR (fR := fRP 1)
              (lam := Term.const 1) (domR := domRP) hdom
            rwa [hρ] at hsem)
        simpa [modeP] using this
    · refine ⟨[(2, modeP 2, edgeP 2 2)], ?_, ?_, ?_, ?_⟩
      · intro s hs
        simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
        rcases hs with rfl
        exact ⟨GrP_modeAt 2 (by norm_num), edgeP_mem 2 2 (by simp [GrP])⟩
      · simp
      · intro s hs
        simp only [List.head?_cons, Option.some_inj] at hs
        rw [← hs]
      · have := hbody [] (by intro Q hQ; exact absurd hQ (List.not_mem_nil))
        simpa [modeP] using this
  rcases hP with rfl | rfl | rfl
  · exact hbuild 0 (by norm_num) rfl
  · exact hbuild 1 (by norm_num) rfl
  · exact hbuild 2 (by norm_num) rfl

/-- **`rover3_M1`, modal Theorem 3** — the CATCH-UP form: the response ignores
coupling entirely. The right's velocity floor (`v_x ≥ 1/4` in its evolve
domain) means a single Safe hold of duration `8·dt` regains more position
than the left window can gain (`windowSeg_growth` bounds the left by `2·dt`),
so the weakest declared tolerance (`Stop`, offset 2) is re-established by
endpoint arithmetic. Z3-free: NO verdict hypotheses at all. -/
theorem rover3_M1_modal (dt : ℝ) (hdt : 0 ≤ dt) :
    RFormula.rvalid (theorem3Form
      (bigChoice (leftProgsP dt))
      (rightAutomatonBody GrP mvP)
      (RFormula.and (RFormula.and (canonInvM gP gsP) (envLR domLP domRP))
        (mvValidR mvP GrP.modes.length))) := by
  refine theorem3_faithful_multiF_LR GrP mvP (FM gP gsP) domLP domRP
    (leftProgsP dt) (canonInvM gP gsP) (encode_canonInvM gP gsP) ?_ ?_ ?_
  · exact hdis_multi GrP 0 1 dt leftDataP (by decide) httP hRvP hLP
  · exact hstep_assembled_multiF GrP mvP (FM gP gsP) envP (leftProgsP dt)
      hmvFP hmvenvP hfreshP httP hltP (hframesP dt)
      (HmultiP dt hdt)
  · exact hddF_multiE GrP 0 1 dt leftDataP (canonInvM gP gsP) domLP domRP
      (by decide) httP hRvP hLP
      (canonInvM_varsL gP gsP (by
        intro g' hg'
        simp only [gP, gsP, List.mem_cons, List.not_mem_nil, or_false] at hg'
        rcases hg' with rfl <;> exact hgAt _))
      (canonInvM_varsR gP gsP) hdomLP hdomRP

end Rover3M1Modal
end RelCertifier
