/-
Copyright (c) 2026 relCertifier-lean contributors.
Released under Apache 2.0 license.

# T3+ — `refinement_ladder_rover_rung3_6to8`, modal Theorem 3 (multiF, GENERATED)

Generated by `scripts/gen_multif_instance.py` from the coordinate spec: the plain
list-invariant pattern at n = 8 with 4 invariant components in the cover's
stratified-DC order, the one-way terrain chain, and climb dispatch. Existence is
Z3-free (stratified faces).

Residuals: six stratified-DC verdict packs (`VerdR l m`). Axioms: the standard
three + `z3_unsat_sound` at those leaves.
-/
import RelCertifier.Proofs.Encoding.EnvelopeChainM
import RelCertifier.Proofs.Encoding.RepoPrefixR
import RelCertifier.Proofs.Encoding.Reparam
import RelCertifier.Proofs.Encoding.WindowRF
import RelCertifier.Proofs.Encoding.EnvelopeChainR
import RelCertifier.Proofs.Encoding.CanonicalInv
import RelCertifier.Proofs.Encoding.CoverInstance
import RelCertifier.Proofs.Flow.AffineFaces
import RelCertifier.Instances.BenchIR.refinement_ladder_rover_rung3_6to8

namespace RelCertifier
namespace RoverLadderRung3Modal

open DL DLCalTiming DLRel Parse Set

set_option maxHeartbeats 12800000

def vsR : List String := ["v", "s", "psi", "omega_psi", "theta_p", "omega_theta", "z", "phi_r"]
def dummyR : Parse.PMode := ⟨"", [], .tt, .tt, []⟩
def mLR (l : ℕ) : Parse.PMode := refinement_ladder_rover_rung3_6to8_IR.L.modes.getD l dummyR
def mRR (q : ℕ) : Parse.PMode := refinement_ladder_rover_rung3_6to8_IR.R.modes.getD q dummyR

abbrev mvR : Var 8 := (Side.Aux, 0)
abbrev aR : Fin 8 := (1 : Fin 8)
abbrev tgR : Var 8 := (Side.Aux, aR)

noncomputable def fLR (l : ℕ) : Fin 8 → Term (Var 8) := hostDyn vsR 8 Side.L (mLR l)
noncomputable def fRR (q : ℕ) : Fin 8 → Term (Var 8) := hostDyn vsR 8 Side.R (mRR q)
noncomputable def domLR : Formula (Var 8) := hostEvolve vsR 8 Side.L (mLR 0)
noncomputable def domRR : Formula (Var 8) := hostEvolve vsR 8 Side.R (mRR 0)
noncomputable def envR : Formula (Var 8) := Formula.and domLR domRR

def atomsOf : Parse.PForm → List Parse.PForm
  | .and x y => atomsOf x ++ atomsOf y
  | f => [f]

def invRPF : Parse.PForm :=
  (refinement_ladder_rover_rung3_6to8_IR.invariants.getD 0 ("", Parse.PForm.tt)).2

noncomputable def gAt (i : ℕ) : Term (Var 8) :=
  ((Run.invToG vsR 8 ((atomsOf invRPF).getD i .tt)).map ITerm.toHost).getD (Term.const 0)

noncomputable def gR : Term (Var 8) := gAt 0
noncomputable def gsR : List (Term (Var 8)) := [gAt 1, gAt 2, gAt 3]

/-- The cut-ceiling region face of right mode `m`. -/
noncomputable def ceilR (m : ℕ) : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 0))
    (Term.const (if m = 0 then 3/10 else if m = 1 then 1/2 else 13/20))

noncomputable def regionR (m : ℕ) : Formula (Var 8) :=
  Formula.cmp CompOp.le (ceilR m) (Term.const 0)

noncomputable def gs9R (m : ℕ) : List (Term (Var 8)) := gsR ++ [ceilR m]

/-! ## Side-splits -/

theorem fLR_pipe (l : ℕ) (i : Fin 8) : fLR l i =
    (((some (mLR l)).bind (Run.dynOf vsR 8 Side.L)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem fRR_pipe (q : ℕ) (i : Fin 8) : fRR q i =
    (((some (mRR q)).bind (Run.dynOf vsR 8 Side.R)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem domLR_pipe : domLR =
    (((some (mLR 0)).bind (fun m => Run.lowerF vsR 8 Side.L m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl
theorem domRR_pipe : domRR =
    (((some (mRR 0)).bind (fun m => Run.lowerF vsR 8 Side.R m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl

theorem hfLR (l : ℕ) (hl : l < 3) : ∀ i, (fLR l i).fv ⊆ range Lv := fun i x hx =>
  side_eq_L_mem (field_pipeline_side (resolvesTo_L vsR) (some (mLR l))
    (by interval_cases l <;>
      simp [mLR, refinement_ladder_rover_rung3_6to8_IR, Parse.PExpr.namesFree]) i x
    (fLR_pipe l i ▸ hx))

theorem hfRR (q : ℕ) (hq : q < 3) : ∀ i, (fRR q i).fv ⊆ range Rv := fun i x hx =>
  side_eq_R_mem (field_pipeline_side (resolvesTo_R vsR) (some (mRR q))
    (by interval_cases q <;>
      simp [mRR, refinement_ladder_rover_rung3_6to8_IR, Parse.PExpr.namesFree]) i x
    (fRR_pipe q i ▸ hx))

theorem hdomLR : domLR.fv ⊆ range Lv := fun x hx =>
  side_eq_L_mem (form_pipeline_side (resolvesTo_L vsR) (some (mLR 0))
    (by simp [mLR, refinement_ladder_rover_rung3_6to8_IR, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domLR_pipe ▸ hx))

theorem hdomRR : domRR.fv ⊆ range Rv := fun x hx =>
  side_eq_R_mem (form_pipeline_side (resolvesTo_R vsR) (some (mRR 0))
    (by simp [mRR, refinement_ladder_rover_rung3_6to8_IR, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domRR_pipe ▸ hx))

theorem hgAt (i : ℕ) : (gAt i).fv ⊆ range Lv ∪ range Rv := invToG_pipeline_LR _

theorem hmvg : ∀ g' ∈ gR :: gsR, mvR ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [gR, gsR, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with rfl | rfl | rfl | rfl <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem htgg : ∀ g' ∈ gR :: gsR, tgR ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [gR, gsR, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with rfl | rfl | rfl | rfl <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem hmvFR : mvR ∉ (FM gR gsR).fv := notMem_FM_fv hmvg
theorem htgFR : tgR ∉ (FM gR gsR).fv := notMem_FM_fv htgg

theorem hmvenvR : mvR ∉ envR.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomLR h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomRR h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))
theorem htgenvR : tgR ∉ envR.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomLR h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomRR h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))

/-! ## The right graph (one-way chain) -/

noncomputable def modeR (q : ℕ) : RMode (Var 8) :=
  { sys := rightBlock (fRR q) (Term.const 1), dom := domRR, weight := 1 }

def edgeR (st tgt : ℕ) : REdge (Var 8) :=
  { src := st, tgt := tgt, guard := Formula.tt, pruned := false }

noncomputable def GrR : SearchGraph (Var 8) :=
  { modes := [modeR 0, modeR 1, modeR 2],
    edges := [edgeR 0 1, edgeR 0 0, edgeR 1 2, edgeR 1 1, edgeR 2 2] }

theorem GrR_modeAt (q : ℕ) (hq : q < 3) : GrR.modeAt q = some (modeR q) := by
  interval_cases q <;> rfl

theorem httR : ∀ q, ∀ e ∈ GrR.edgesFrom q, e.guard = Formula.tt := by
  intro q e he
  have hmem : e ∈ GrR.edges := List.mem_of_mem_filter he
  simp only [GrR, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> rfl

theorem hltR : ∀ q, ∀ e ∈ GrR.edgesFrom q, e.tgt < GrR.modes.length := by
  intro q e he
  have hmem : e ∈ GrR.edges := List.mem_of_mem_filter he
  simp only [GrR, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> norm_num [GrR, edgeR]

theorem hRvR : ∀ q m, GrR.modeAt q = some m →
    m.sys.boundSet ∪ m.sys.readVars ∪ m.dom.fv ⊆ range Rv := by
  intro q m hm
  have hqm : q < 3 ∧ m = modeR q := by
    match q with
    | 0 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrR] using hm.symm⟩
    | 1 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrR] using hm.symm⟩
    | 2 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrR] using hm.symm⟩
    | q + 3 => exact absurd hm (by simp [SearchGraph.modeAt, GrR])
  obtain ⟨hq3, rfl⟩ := hqm
  intro y hy
  rcases hy with (hy | hy) | hy
  · exact rightBlock_boundSet_sub (fRR q) (Term.const 1) hy
  · exact rightBlock_readVars_sub (fRR q) (Term.const 1) (hfRR q hq3)
      (by simp [Term.fv]) hy
  · exact hdomRR hy

theorem edgeR_mem : ∀ st tgt, edgeR st tgt ∈ GrR.edges →
    edgeR st tgt ∈ GrR.edgesFrom st :=
  fun st tgt he => List.mem_filter.mpr ⟨he, by simp [edgeR]⟩

theorem hfreshR : ∀ q m, GrR.modeAt q = some m →
    mvR ∉ (Program.ode m.sys m.dom).fv := by
  intro q m hm hmv
  exact aux_notin_range_Rv 0 (hRvR q m hm (vars_ode_sub _ _ (Or.inl hmv)))

/-! ## The left window family -/

noncomputable def leftDataR : List (Formula (Var 8) × (Fin 8 → Term (Var 8))
    × Formula (Var 8) × ℕ) :=
  [(Formula.tt, fLR 0, domLR, 3), (Formula.tt, fLR 1, domLR, 3),
   (Formula.tt, fLR 2, domLR, 3)]

noncomputable def leftProgsR (dt : ℝ) : List (Program (Var 8)) :=
  leftDataR.map (fun d => gwindowSeg d.1 (leftBlock d.2.1) d.2.2.1 tgR dt d.2.2.2)

theorem hLR : ∀ d ∈ leftDataR, d.1.fv ⊆ range Lv ∧
    (∀ i, (d.2.1 i).fv ⊆ range Lv) ∧ d.2.2.1.fv ⊆ range Lv := by
  intro d hd
  simp only [leftDataR, List.mem_cons, List.not_mem_nil, or_false] at hd
  rcases hd with rfl | rfl | rfl
  · exact ⟨by simp [Formula.fv], hfLR 0 (by norm_num), hdomLR⟩
  · exact ⟨by simp [Formula.fv], hfLR 1 (by norm_num), hdomLR⟩
  · exact ⟨by simp [Formula.fv], hfLR 2 (by norm_num), hdomLR⟩

theorem hframesR (dt : ℝ) : ∀ P ∈ leftProgsR dt, FramesMv P mvR := by
  intro P hP
  simp only [leftProgsR, List.mem_map] at hP
  obtain ⟨d, hd, rfl⟩ := hP
  refine framesMv_gwindow d.1 d.2.1 d.2.2.1 tgR dt d.2.2.2 mvR (by decide) ?_
  intro h
  obtain ⟨i, hi⟩ := leftBlock_bound_sub d.2.1 _ h
  exact aux_ne_Lv 0 i hi

/-! ## Parse pins -/

theorem hr030 : Run.parseRat "0.30" = some ((3:ℚ)/10) := by
  have h : parseQ "0.30" = some (⟨30, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hr050 : Run.parseRat "0.50" = some ((1:ℚ)/2) := by
  have h : parseQ "0.50" = some (⟨50, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hr065 : Run.parseRat "0.65" = some ((13:ℚ)/20) := by
  have h : parseQ "0.65" = some (⟨65, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hr3 : Run.parseRat "3" = some (3) := by
  have h : parseQ "3" = some (⟨3, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hrm1 : Run.parseRat "-1" = some (-1) := by
  have h : parseQ "-1" = some (⟨-1, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hr0 : Run.parseRat "0" = some (0) := by
  have h : parseQ "0" = some (⟨0, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hr1 : Run.parseRat "1" = some (1) := by
  have h : parseQ "1" = some (⟨1, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hr05 : Run.parseRat "0.5" = some ((1:ℚ)/2) := by
  have h : parseQ "0.5" = some (⟨5, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hr03 : Run.parseRat "0.3" = some ((3:ℚ)/10) := by
  have h : parseQ "0.3" = some (⟨3, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hrm05 : Run.parseRat "-0.5" = some (-(1:ℚ)/2) := by
  have h : parseQ "-0.5" = some (⟨-5, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hr06 : Run.parseRat "0.6" = some ((3:ℚ)/5) := by
  have h : parseQ "0.6" = some (⟨6, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hr015 : Run.parseRat "0.15" = some ((3:ℚ)/20) := by
  have h : parseQ "0.15" = some (⟨15, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hr00 : Run.parseRat "0.0" = some (0) := by
  have h : parseQ "0.0" = some (⟨0, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hr08 : Run.parseRat "0.8" = some ((4:ℚ)/5) := by
  have h : parseQ "0.8" = some (⟨8, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hrm10 : Run.parseRat "-1.0" = some (-1) := by
  have h : parseQ "-1.0" = some (⟨-10, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]

/-! ## Field and shape pins -/

noncomputable def cstR (q : ℕ) : ℝ := if q = 0 then 3/10 else if q = 1 then 1/2 else 13/20

theorem fRR0_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRR q 0) x = 3 * (cstR q - x (Rv 0)) := by
  interval_cases q <;>
    simp [fRR, hostDyn, mRR, refinement_ladder_rover_rung3_6to8_IR, vsR, Run.dynOf,
      Run.lowerE, hr030, hr050, hr065, hr3, hrm1, hr0, hr1, hr05, hr03, hrm05, hr06, hr015, hr00, hr08, hrm10, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv, cstR]
theorem fRR1_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRR q 1) x = x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))) := by
  interval_cases q <;>
    simp [fRR, hostDyn, mRR, refinement_ladder_rover_rung3_6to8_IR, vsR, Run.dynOf,
      Run.lowerE, hr030, hr050, hr065, hr3, hrm1, hr0, hr1, hr05, hr03, hrm05, hr06, hr015, hr00, hr08, hrm10, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRR2_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRR q 2) x = -1 * x (Rv 2) := by
  interval_cases q <;>
    simp [fRR, hostDyn, mRR, refinement_ladder_rover_rung3_6to8_IR, vsR, Run.dynOf,
      Run.lowerE, hr030, hr050, hr065, hr3, hrm1, hr0, hr1, hr05, hr03, hrm05, hr06, hr015, hr00, hr08, hrm10, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRR3_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRR q 3) x = 0 := by
  interval_cases q <;>
    simp [fRR, hostDyn, mRR, refinement_ladder_rover_rung3_6to8_IR, vsR, Run.dynOf,
      Run.lowerE, hr030, hr050, hr065, hr3, hrm1, hr0, hr1, hr05, hr03, hrm05, hr06, hr015, hr00, hr08, hrm10, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRR4_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRR q 4) x = -1 * x (Rv 4) := by
  interval_cases q <;>
    simp [fRR, hostDyn, mRR, refinement_ladder_rover_rung3_6to8_IR, vsR, Run.dynOf,
      Run.lowerE, hr030, hr050, hr065, hr3, hrm1, hr0, hr1, hr05, hr03, hrm05, hr06, hr015, hr00, hr08, hrm10, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRR5_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRR q 5) x = 0 := by
  interval_cases q <;>
    simp [fRR, hostDyn, mRR, refinement_ladder_rover_rung3_6to8_IR, vsR, Run.dynOf,
      Run.lowerE, hr030, hr050, hr065, hr3, hrm1, hr0, hr1, hr05, hr03, hrm05, hr06, hr015, hr00, hr08, hrm10, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRR6_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRR q 6) x = -1 * x (Rv 6) := by
  interval_cases q <;>
    simp [fRR, hostDyn, mRR, refinement_ladder_rover_rung3_6to8_IR, vsR, Run.dynOf,
      Run.lowerE, hr030, hr050, hr065, hr3, hrm1, hr0, hr1, hr05, hr03, hrm05, hr06, hr015, hr00, hr08, hrm10, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRR7_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRR q 7) x = -1 * x (Rv 7) := by
  interval_cases q <;>
    simp [fRR, hostDyn, mRR, refinement_ladder_rover_rung3_6to8_IR, vsR, Run.dynOf,
      Run.lowerE, hr030, hr050, hr065, hr3, hrm1, hr0, hr1, hr05, hr03, hrm05, hr06, hr015, hr00, hr08, hrm10, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]

theorem sat_domRR (x : State (Var 8)) : Formula.sat domRR x ↔
    (-(1:ℝ)/2 ≤ x (Rv 3) ∧ x (Rv 3) ≤ (3:ℝ)/5 ∧ -(1:ℝ)/2 ≤ x (Rv 5) ∧ x (Rv 5) ≤ (3:ℝ)/5 ∧ -(1:ℝ)/2 ≤ x (Rv 7) ∧ x (Rv 7) ≤ (3:ℝ)/20 ∧ -(1:ℝ)/2 ≤ x (Rv 2) ∧ x (Rv 2) ≤ (3:ℝ)/20 ∧ 0 ≤ x (Rv 1) ∧ -(1:ℝ)/2 ≤ x (Rv 4) ∧ x (Rv 4) ≤ (3:ℝ)/20 ∧ 0 ≤ x (Rv 0) ∧ x (Rv 0) ≤ (4:ℝ)/5 ∧ -(1:ℝ) ≤ x (Rv 6) ∧ x (Rv 6) ≤ (3:ℝ)/20) := by
  simp only [domRR, hostEvolve, mRR, refinement_ladder_rover_rung3_6to8_IR, vsR]
  simp [Run.lowerF, Run.lowerE, hrm05, hr06, hr015, hr00, hr08, hrm10,
    Run.resolveVar, List.findIdx?_cons, IForm.toHost, ITerm.toHost, Formula.sat,
    CompOp.interp, Term.eval, Rv]
  tauto

/-! ## Faces -/

noncomputable def faceVLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const (0)) (Term.var (Rv 0))
noncomputable def faceVHi : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 0)) (Term.const ((4:ℝ)/5))
noncomputable def facePsiLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 2))
noncomputable def facePsiHi : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 2)) (Term.const ((3:ℝ)/20))
noncomputable def faceThLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 4))
noncomputable def faceThHi : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 4)) (Term.const ((3:ℝ)/20))
noncomputable def faceZLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ))) (Term.var (Rv 6))
noncomputable def faceZHi : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 6)) (Term.const ((3:ℝ)/20))
noncomputable def facePhLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 7))
noncomputable def facePhHi : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 7)) (Term.const ((3:ℝ)/20))
noncomputable def faceSLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const 0) (Term.var (Rv 1))
noncomputable def faceOPsLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 3))
noncomputable def faceOPsHi : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 3)) (Term.const ((3:ℝ)/5))
noncomputable def faceOThLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 5))
noncomputable def faceOThHi : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 5)) (Term.const ((3:ℝ)/5))

noncomputable def gsSR : List (Term (Var 8)) :=
  [faceVLo, faceVHi, facePsiLo, facePsiHi, faceThLo, faceThHi, faceZLo, faceZHi, facePhLo, facePhHi]
noncomputable def gsNR : List (Term (Var 8)) :=
  [faceSLo, faceOPsLo, faceOPsHi, faceOThLo, faceOThHi]

theorem faces_fv_RR : ∀ gT' ∈ gsSR ++ gsNR, ∀ x ∈ gT'.fv, x ∈ range Rv := by
  intro gT' hgT x hx
  simp only [gsSR, gsNR, List.cons_append, List.nil_append, List.mem_cons,
    List.not_mem_nil, or_false] at hgT
  rcases hgT with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
    · simp only [faceVLo, faceVHi, facePsiLo, facePsiHi, faceThLo, faceThHi, faceZLo, faceZHi, facePhLo, facePhHi, faceSLo, faceOPsLo, faceOPsHi, faceOThLo, faceOThHi, Term.fv,
        Set.mem_union, Set.mem_empty_iff_false, false_or, or_false,
        Set.mem_singleton_iff] at hx
      exact ⟨_, hx.symm⟩

/-! ## The frozen-left joint field -/

theorem odeField_RR (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    odeField (jointSys (fun _ => Term.const 0) (fRR q) (Term.const ((9:ℝ)/4))) x
      = fun c =>
        if c = Rv 0 then ((9:ℝ)/4) * (3 * (cstR q - x (Rv 0)))
        else if c = Rv 1 then ((9:ℝ)/4) * (x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))))
        else if c = Rv 2 then ((9:ℝ)/4) * (-1 * x (Rv 2))
        else if c = Rv 4 then ((9:ℝ)/4) * (-1 * x (Rv 4))
        else if c = Rv 6 then ((9:ℝ)/4) * (-1 * x (Rv 6))
        else if c = Rv 7 then ((9:ℝ)/4) * (-1 * x (Rv 7))
        else 0 := by
  funext c
  by_cases hc : c ∈ (jointSys (fun _ => Term.const 0) (fRR q) (Term.const ((9:ℝ)/4))).bound
  · rw [show odeField (jointSys (fun _ => Term.const 0) (fRR q) (Term.const ((9:ℝ)/4))) x c
        = ((jointSys (fun _ => Term.const 0) (fRR q) (Term.const ((9:ℝ)/4))).rhs c).eval x from by
      simp only [odeField, if_pos hc]]
    obtain ⟨p, hp, hfst⟩ : ∃ p ∈ jointSys (fun _ => Term.const 0) (fRR q) (Term.const ((9:ℝ)/4)),
        p.1 = c := by simpa [ODESystem.bound, List.mem_map] using hc
    rw [← hfst, ODESystem.rhs_eq_of_mem (jointSys_wellFormed _ _ _) hp]
    rw [jointSys_split] at hp
    have hne : ∀ (a b : Fin 8), a ≠ b → (Rv a : Var 8) ≠ Rv b := by
      intro a b hab
      simp [Rv, Prod.ext_iff]
      exact fun h => hab (by exact_mod_cast h)
    rcases List.mem_append.mp hp with hp | hp
    · obtain ⟨j, -, rfl⟩ := List.mem_map.mp hp
      have hLR : ∀ k : Fin 8, (Lv j : Var 8) ≠ Rv k := by
        intro k
        simp [Lv, Rv, Prod.ext_iff]
      simp [Term.eval, hLR 0, hLR 1, hLR 2, hLR 4, hLR 6, hLR 7]
    · obtain ⟨j, -, rfl⟩ := List.mem_map.mp hp
      fin_cases j
      · simp [Term.eval, AOp.interp, fRR0_eval q hq]
      · simp [Term.eval, AOp.interp, fRR1_eval q hq,
          hne 1 0 (by decide)]
      · simp [Term.eval, AOp.interp, fRR2_eval q hq,
          hne 2 0 (by decide),
          hne 2 1 (by decide)]
      · simp [Term.eval, AOp.interp, fRR3_eval q hq,
          hne 3 0 (by decide),
          hne 3 1 (by decide),
          hne 3 2 (by decide),
          hne 3 4 (by decide),
          hne 3 6 (by decide),
          hne 3 7 (by decide)]
      · simp [Term.eval, AOp.interp, fRR4_eval q hq,
          hne 4 0 (by decide),
          hne 4 1 (by decide),
          hne 4 2 (by decide)]
      · simp [Term.eval, AOp.interp, fRR5_eval q hq,
          hne 5 0 (by decide),
          hne 5 1 (by decide),
          hne 5 2 (by decide),
          hne 5 4 (by decide),
          hne 5 6 (by decide),
          hne 5 7 (by decide)]
      · simp [Term.eval, AOp.interp, fRR6_eval q hq,
          hne 6 0 (by decide),
          hne 6 1 (by decide),
          hne 6 2 (by decide),
          hne 6 4 (by decide)]
      · simp [Term.eval, AOp.interp, fRR7_eval q hq,
          hne 7 0 (by decide),
          hne 7 1 (by decide),
          hne 7 2 (by decide),
          hne 7 4 (by decide),
          hne 7 6 (by decide)]
  · have hnotR : ∀ j : Fin 8, c ≠ Rv j := by
      intro j hceq
      refine hc ?_
      rw [hceq, jointSys_split]
      simp only [ODESystem.bound, List.map_append, List.mem_append]
      exact Or.inr (by
        simp only [rightBlock, List.map_map, List.mem_map]
        exact ⟨j, List.mem_finRange j, rfl⟩)
    simp only [odeField, if_neg hc, if_neg (hnotR 0), if_neg (hnotR 1), if_neg (hnotR 2), if_neg (hnotR 4), if_neg (hnotR 6), if_neg (hnotR 7)]

/-! ## Strict inflow -/

theorem hbndS_R (q : ℕ) (hq : q < 3) : ∀ gT' ∈ gsSR, ∀ x : State (Var 8),
    Term.eval gT' x = 0 →
    Lie (jointSys (fun _ => Term.const 0) (fRR q) (Term.const ((9:ℝ)/4)))
      (fun ω => Term.eval gT' ω) x < 0 := by
  have hne : ∀ (a b : Fin 8), a ≠ b → (Rv a : Var 8) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro gT' hgT x hface
  simp only [gsSR, List.mem_cons, List.not_mem_nil, or_false] at hgT
  rcases hgT with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · have hx : x (Rv 0) = 0 := by
      simp only [faceVLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval faceVLo ω)
        = fun y => (-1 : ℝ) * y (Rv 0) + (0) := by
      funext y; simp [faceVLo, Term.eval, AOp.interp]
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 0) (-1) (0) x,
      odeField_RR q hq]
    simp only [eq_self_iff_true, if_true, if_pos rfl, hx]
    interval_cases q <;> norm_num [cstR]
  · have hx : x (Rv 0) = (4:ℝ)/5 := by
      simp only [faceVHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval faceVHi ω)
        = fun y => (1 : ℝ) * y (Rv 0) + (-((4:ℝ)/5)) := by
      funext y; simp [faceVHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 0) 1 (-((4:ℝ)/5)) x,
      odeField_RR q hq]
    simp only [eq_self_iff_true, if_true, if_pos rfl, hx]
    interval_cases q <;> norm_num [cstR]
  · have hx : x (Rv 2) = -(1:ℝ)/2 := by
      simp only [facePsiLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval facePsiLo ω)
        = fun y => (-1 : ℝ) * y (Rv 2) + (-(1:ℝ)/2) := by
      funext y; simp [facePsiLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 2) (-1) (-(1:ℝ)/2) x,
      odeField_RR q hq]
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 2) = (3:ℝ)/20 := by
      simp only [facePsiHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval facePsiHi ω)
        = fun y => (1 : ℝ) * y (Rv 2) + (-((3:ℝ)/20)) := by
      funext y; simp [facePsiHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 2) 1 (-((3:ℝ)/20)) x,
      odeField_RR q hq]
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 4) = -(1:ℝ)/2 := by
      simp only [faceThLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval faceThLo ω)
        = fun y => (-1 : ℝ) * y (Rv 4) + (-(1:ℝ)/2) := by
      funext y; simp [faceThLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 4) (-1) (-(1:ℝ)/2) x,
      odeField_RR q hq]
    simp only [if_neg (hne 4 0 (by decide)), if_neg (hne 4 1 (by decide)), if_neg (hne 4 2 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 4) = (3:ℝ)/20 := by
      simp only [faceThHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval faceThHi ω)
        = fun y => (1 : ℝ) * y (Rv 4) + (-((3:ℝ)/20)) := by
      funext y; simp [faceThHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 4) 1 (-((3:ℝ)/20)) x,
      odeField_RR q hq]
    simp only [if_neg (hne 4 0 (by decide)), if_neg (hne 4 1 (by decide)), if_neg (hne 4 2 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 6) = -(1:ℝ) := by
      simp only [faceZLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval faceZLo ω)
        = fun y => (-1 : ℝ) * y (Rv 6) + (-(1:ℝ)) := by
      funext y; simp [faceZLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 6) (-1) (-(1:ℝ)) x,
      odeField_RR q hq]
    simp only [if_neg (hne 6 0 (by decide)), if_neg (hne 6 1 (by decide)), if_neg (hne 6 2 (by decide)), if_neg (hne 6 4 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 6) = (3:ℝ)/20 := by
      simp only [faceZHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval faceZHi ω)
        = fun y => (1 : ℝ) * y (Rv 6) + (-((3:ℝ)/20)) := by
      funext y; simp [faceZHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 6) 1 (-((3:ℝ)/20)) x,
      odeField_RR q hq]
    simp only [if_neg (hne 6 0 (by decide)), if_neg (hne 6 1 (by decide)), if_neg (hne 6 2 (by decide)), if_neg (hne 6 4 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 7) = -(1:ℝ)/2 := by
      simp only [facePhLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval facePhLo ω)
        = fun y => (-1 : ℝ) * y (Rv 7) + (-(1:ℝ)/2) := by
      funext y; simp [facePhLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 7) (-1) (-(1:ℝ)/2) x,
      odeField_RR q hq]
    simp only [if_neg (hne 7 0 (by decide)), if_neg (hne 7 1 (by decide)), if_neg (hne 7 2 (by decide)), if_neg (hne 7 4 (by decide)), if_neg (hne 7 6 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 7) = (3:ℝ)/20 := by
      simp only [facePhHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval facePhHi ω)
        = fun y => (1 : ℝ) * y (Rv 7) + (-((3:ℝ)/20)) := by
      funext y; simp [facePhHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 7) 1 (-((3:ℝ)/20)) x,
      odeField_RR q hq]
    simp only [if_neg (hne 7 0 (by decide)), if_neg (hne 7 1 (by decide)), if_neg (hne 7 2 (by decide)), if_neg (hne 7 4 (by decide)), if_neg (hne 7 6 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num

/-! ## Non-strict faces -/

theorem hbndN_R (q : ℕ) (hq : q < 3) : ∀ i (hi : i < gsNR.length),
    ∀ x : State (Var 8),
    (∀ gT' ∈ gsSR ++ ([] : List (Term (Var 8))), Term.eval gT' x ≤ 0) →
    Lie (jointSys (fun _ => Term.const 0) (fRR q) (Term.const ((9:ℝ)/4)))
      (fun ω => Term.eval gsNR[i] ω) x ≤ 0 := by
  have hne : ∀ (a b : Fin 8), a ≠ b → (Rv a : Var 8) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro i hi x hx
  have hib : i < 5 := by simpa [gsNR] using hi
  interval_cases i
  · show Lie _ (fun ω => Term.eval faceSLo ω) x ≤ 0
    have hv0 : 0 ≤ x (Rv 0) := by
      have := hx faceVLo (List.mem_append_left _ (by simp [gsSR]))
      simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval faceSLo ω)
        = fun y => (-1 : ℝ) * y (Rv 1) + 0 := by
      funext y; simp [faceSLo, Term.eval, AOp.interp]
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 1) (-1) 0 x,
      odeField_RR q hq]
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    have hbp1 : -(1:ℝ)/2 ≤ x (Rv 2) := by
      have := hx facePsiLo (List.mem_append_left _ (by simp [gsSR]))
      simp only [facePsiLo, Term.eval, AOp.interp] at this; linarith
    have hbp2 : x (Rv 2) ≤ (3:ℝ)/20 := by
      have := hx facePsiHi (List.mem_append_left _ (by simp [gsSR]))
      simp only [facePsiHi, Term.eval, AOp.interp] at this; linarith
    have hbt1 : -(1:ℝ)/2 ≤ x (Rv 4) := by
      have := hx faceThLo (List.mem_append_left _ (by simp [gsSR]))
      simp only [faceThLo, Term.eval, AOp.interp] at this; linarith
    have hbt2 : x (Rv 4) ≤ (3:ℝ)/20 := by
      have := hx faceThHi (List.mem_append_left _ (by simp [gsSR]))
      simp only [faceThHi, Term.eval, AOp.interp] at this; linarith
    have hB : (0:ℝ) ≤ (1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)) := by
      nlinarith [hbp1, hbp2, hbt1, hbt2]
    have hmn := mul_nonneg hv0 hB
    linarith
  · show Lie _ (fun ω => Term.eval faceOPsLo ω) x ≤ 0
    have hfun : (fun ω : State (Var 8) => Term.eval faceOPsLo ω)
        = fun y => (-1 : ℝ) * y (Rv 3) + (-(1:ℝ)/2) := by
      funext y; simp [faceOPsLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 3) (-1) (-(1:ℝ)/2) x,
      odeField_RR q hq]
    simp only [if_neg (hne 3 0 (by decide)), if_neg (hne 3 1 (by decide)), if_neg (hne 3 2 (by decide)), if_neg (hne 3 4 (by decide)), if_neg (hne 3 6 (by decide)), if_neg (hne 3 7 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceOPsHi ω) x ≤ 0
    have hfun : (fun ω : State (Var 8) => Term.eval faceOPsHi ω)
        = fun y => (1 : ℝ) * y (Rv 3) + (-((3:ℝ)/5)) := by
      funext y; simp [faceOPsHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 3) 1 (-((3:ℝ)/5)) x,
      odeField_RR q hq]
    simp only [if_neg (hne 3 0 (by decide)), if_neg (hne 3 1 (by decide)), if_neg (hne 3 2 (by decide)), if_neg (hne 3 4 (by decide)), if_neg (hne 3 6 (by decide)), if_neg (hne 3 7 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceOThLo ω) x ≤ 0
    have hfun : (fun ω : State (Var 8) => Term.eval faceOThLo ω)
        = fun y => (-1 : ℝ) * y (Rv 5) + (-(1:ℝ)/2) := by
      funext y; simp [faceOThLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 5) (-1) (-(1:ℝ)/2) x,
      odeField_RR q hq]
    simp only [if_neg (hne 5 0 (by decide)), if_neg (hne 5 1 (by decide)), if_neg (hne 5 2 (by decide)), if_neg (hne 5 4 (by decide)), if_neg (hne 5 6 (by decide)), if_neg (hne 5 7 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceOThHi ω) x ≤ 0
    have hfun : (fun ω : State (Var 8) => Term.eval faceOThHi ω)
        = fun y => (1 : ℝ) * y (Rv 5) + (-((3:ℝ)/5)) := by
      funext y; simp [faceOThHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 5) 1 (-((3:ℝ)/5)) x,
      odeField_RR q hq]
    simp only [if_neg (hne 5 0 (by decide)), if_neg (hne 5 1 (by decide)), if_neg (hne 5 2 (by decide)), if_neg (hne 5 4 (by decide)), if_neg (hne 5 6 (by decide)), if_neg (hne 5 7 (by decide))]
    norm_num

/-! ## Lipschitz and field bound -/

theorem hLip_R (q : ℕ) (hq : q < 3) (ν : State (Var 8))
    (hν : ∀ gT' ∈ gsSR, Term.eval gT' ν ≤ 0) :
    LipschitzOnWith 80 (odeField (jointSys (fun _ => Term.const 0) (fRR q) (Term.const ((9:ℝ)/4))))
      (Metric.closedBall ν 1) := by
  have hne : ∀ (a b : Fin 8), a ≠ b → (Rv a : Var 8) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  rw [lipschitzOnWith_iff_dist_le_mul]
  intro x hx y hy
  rw [Metric.mem_closedBall] at hx hy
  rw [odeField_RR q hq, odeField_RR q hq]
  have hdc : ∀ j : Fin 8, |x (Rv j) - y (Rv j)| ≤ dist x y := by
    intro j
    have h := dist_le_pi_dist x y (Rv j)
    rwa [Real.dist_eq] at h
  have hd : (0:ℝ) ≤ dist x y := dist_nonneg
  have hcoe : ((80 : NNReal) : ℝ) = 80 := rfl
  rw [hcoe]
  have hband : ∀ (w : State (Var 8)), dist w ν ≤ 1 → ∀ (j : Fin 8) (lo hi : ℝ),
      lo ≤ ν (Rv j) → ν (Rv j) ≤ hi → -2 ≤ lo → hi ≤ 2 → |w (Rv j)| ≤ 3 := by
    intro w hw j lo hi hl hh hlo1 hhi1
    have h := dist_le_pi_dist w ν (Rv j)
    rw [Real.dist_eq] at h
    have hνb : |ν (Rv j)| ≤ 2 := abs_le.mpr ⟨by linarith, by linarith⟩
    have h2 := abs_sub_abs_le_abs_sub (w (Rv j)) (ν (Rv j))
    linarith [abs_le.mp hνb, hw]
  have hνv1 : 0 ≤ ν (Rv 0) := by
    have := hν faceVLo (by simp [gsSR])
    simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
  have hνv2 : ν (Rv 0) ≤ (4:ℝ)/5 := by
    have := hν faceVHi (by simp [gsSR])
    simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
  have hνp1 : -(1:ℝ)/2 ≤ ν (Rv 2) := by
    have := hν facePsiLo (by simp [gsSR])
    simp only [facePsiLo, Term.eval, AOp.interp] at this; linarith
  have hνp2 : ν (Rv 2) ≤ (3:ℝ)/20 := by
    have := hν facePsiHi (by simp [gsSR])
    simp only [facePsiHi, Term.eval, AOp.interp] at this; linarith
  have hνt1 : -(1:ℝ)/2 ≤ ν (Rv 4) := by
    have := hν faceThLo (by simp [gsSR])
    simp only [faceThLo, Term.eval, AOp.interp] at this; linarith
  have hνt2 : ν (Rv 4) ≤ (3:ℝ)/20 := by
    have := hν faceThHi (by simp [gsSR])
    simp only [faceThHi, Term.eval, AOp.interp] at this; linarith
  have hyb0 : |y (Rv 0)| ≤ 3 := hband y hy 0 (0) ((4:ℝ)/5) hνv1 hνv2 (by norm_num) (by norm_num)
  have hxb2 : |x (Rv 2)| ≤ 3 := hband x hx 2 (-(1:ℝ)/2) ((3:ℝ)/20) hνp1 hνp2 (by norm_num) (by norm_num)
  have hyb2 : |y (Rv 2)| ≤ 3 := hband y hy 2 (-(1:ℝ)/2) ((3:ℝ)/20) hνp1 hνp2 (by norm_num) (by norm_num)
  have hxb4 : |x (Rv 4)| ≤ 3 := hband x hx 4 (-(1:ℝ)/2) ((3:ℝ)/20) hνt1 hνt2 (by norm_num) (by norm_num)
  have hyb4 : |y (Rv 4)| ≤ 3 := hband y hy 4 (-(1:ℝ)/2) ((3:ℝ)/20) hνt1 hνt2 (by norm_num) (by norm_num)
  refine dist_pi_le_iff (by positivity) |>.mpr ?_
  intro c
  by_cases hc0 : c = Rv 0
  · subst hc0
    simp only [eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |3 * (cstR q - x (Rv 0)) - 3 * (cstR q - y (Rv 0))| ≤ 3 * dist x y := by
      have hdiff : 3 * (cstR q - x (Rv 0)) - 3 * (cstR q - y (Rv 0)) = -(3 : ℝ) * (x (Rv 0) - y (Rv 0)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(3 : ℝ)| = 3 := by norm_num
      rw [habs]
      nlinarith [hdc 0]
    have hfac : ∀ A B : ℝ, ((9:ℝ)/4) * A - ((9:ℝ)/4) * B = ((9:ℝ)/4) * (A - B) := by
      intro A B; ring
    rw [hfac, abs_mul, abs_of_pos (show (0:ℝ) < ((9:ℝ)/4) by norm_num)]
    nlinarith [hcore, hd]
  by_cases hc1 : c = Rv 1
  · subst hc1
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
        - y (Rv 0) * ((1 - 1/2 * (y (Rv 2) * y (Rv 2))) - 3/10 * (y (Rv 4) * y (Rv 4)))|
        ≤ 27 * dist x y := by
      have hdiff : x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
          - y (Rv 0) * ((1 - 1/2 * (y (Rv 2) * y (Rv 2))) - 3/10 * (y (Rv 4) * y (Rv 4)))
          = ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
              * (x (Rv 0) - y (Rv 0))
            + y (Rv 0) * (-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
                - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4)))) := by
        ring
      rw [hdiff]
      have hBx : |(1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))| ≤ 9 := by
        have h2 : x (Rv 2) * x (Rv 2) ≤ 9 := by nlinarith [abs_le.mp hxb2]
        have h3 : x (Rv 4) * x (Rv 4) ≤ 9 := by nlinarith [abs_le.mp hxb4]
        have h2n : 0 ≤ x (Rv 2) * x (Rv 2) := mul_self_nonneg _
        have h3n : 0 ≤ x (Rv 4) * x (Rv 4) := mul_self_nonneg _
        rw [abs_le]
        constructor <;> nlinarith
      have htri : |(-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
            - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))| ≤ 6 * dist x y := by
        have hA : |(x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2))| ≤ 6 * dist x y := by
          rw [abs_mul]
          have hs : |x (Rv 2) + y (Rv 2)| ≤ 6 := by
            calc |x (Rv 2) + y (Rv 2)| ≤ |x (Rv 2)| + |y (Rv 2)| := abs_add_le _ _
              _ ≤ 6 := by linarith [abs_le.mp hxb2, abs_le.mp hyb2]
          nlinarith [hdc 2, abs_nonneg (x (Rv 2) + y (Rv 2)), abs_nonneg (x (Rv 2) - y (Rv 2))]
        have hB2 : |(x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))| ≤ 6 * dist x y := by
          rw [abs_mul]
          have hs : |x (Rv 4) + y (Rv 4)| ≤ 6 := by
            calc |x (Rv 4) + y (Rv 4)| ≤ |x (Rv 4)| + |y (Rv 4)| := abs_add_le _ _
              _ ≤ 6 := by linarith [abs_le.mp hxb4, abs_le.mp hyb4]
          nlinarith [hdc 4, abs_nonneg (x (Rv 4) + y (Rv 4)), abs_nonneg (x (Rv 4) - y (Rv 4))]
        have e1 : |(-(1/2) : ℝ) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))|
            ≤ 1/2 * (6 * dist x y) := by
          rw [abs_mul]
          have h : |(-(1/2) : ℝ)| = 1/2 := by norm_num
          rw [h]
          nlinarith [abs_nonneg ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))]
        have e2 : |((3:ℝ)/10) * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4)))|
            ≤ 3/10 * (6 * dist x y) := by
          rw [abs_mul]
          have h : |((3:ℝ)/10)| = 3/10 := by norm_num
          rw [h]
          nlinarith [abs_nonneg ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4)))]
        have hsub : |(-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
              - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))|
            ≤ |(-(1/2) : ℝ) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))|
              + |((3:ℝ)/10) * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4)))| := by
          rw [sub_eq_add_neg]
          refine (abs_add_le _ _).trans ?_
          rw [abs_neg]
        linarith
      have hfin1 : |(1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))|
          * |x (Rv 0) - y (Rv 0)| ≤ 9 * dist x y :=
        mul_le_mul hBx (hdc 0) (abs_nonneg _) (by norm_num)
      have hfin2 : |y (Rv 0)| * |(-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
            - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))|
          ≤ 3 * (6 * dist x y) :=
        mul_le_mul hyb0 htri (abs_nonneg _) (by norm_num)
      have hsplit : |((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
              * (x (Rv 0) - y (Rv 0))
            + y (Rv 0) * (-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
                - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))|
          ≤ |((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
              * (x (Rv 0) - y (Rv 0))|
            + |y (Rv 0) * (-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
                - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))| := abs_add_le _ _
      rw [abs_mul, abs_mul] at hsplit
      linarith
    have hfac : ∀ A B : ℝ, ((9:ℝ)/4) * A - ((9:ℝ)/4) * B = ((9:ℝ)/4) * (A - B) := by
      intro A B; ring
    rw [hfac, abs_mul, abs_of_pos (show (0:ℝ) < ((9:ℝ)/4) by norm_num)]
    nlinarith [hcore, hd]
  by_cases hc2 : c = Rv 2
  · subst hc2
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |-1 * x (Rv 2) - -1 * y (Rv 2)| ≤ 1 * dist x y := by
      have hdiff : -1 * x (Rv 2) - -1 * y (Rv 2) = -(1 : ℝ) * (x (Rv 2) - y (Rv 2)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(1 : ℝ)| = 1 := by norm_num
      rw [habs]
      nlinarith [hdc 2]
    have hfac : ∀ A B : ℝ, ((9:ℝ)/4) * A - ((9:ℝ)/4) * B = ((9:ℝ)/4) * (A - B) := by
      intro A B; ring
    rw [hfac, abs_mul, abs_of_pos (show (0:ℝ) < ((9:ℝ)/4) by norm_num)]
    nlinarith [hcore, hd]
  by_cases hc4 : c = Rv 4
  · subst hc4
    simp only [if_neg (hne 4 0 (by decide)), if_neg (hne 4 1 (by decide)), if_neg (hne 4 2 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |-1 * x (Rv 4) - -1 * y (Rv 4)| ≤ 1 * dist x y := by
      have hdiff : -1 * x (Rv 4) - -1 * y (Rv 4) = -(1 : ℝ) * (x (Rv 4) - y (Rv 4)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(1 : ℝ)| = 1 := by norm_num
      rw [habs]
      nlinarith [hdc 4]
    have hfac : ∀ A B : ℝ, ((9:ℝ)/4) * A - ((9:ℝ)/4) * B = ((9:ℝ)/4) * (A - B) := by
      intro A B; ring
    rw [hfac, abs_mul, abs_of_pos (show (0:ℝ) < ((9:ℝ)/4) by norm_num)]
    nlinarith [hcore, hd]
  by_cases hc6 : c = Rv 6
  · subst hc6
    simp only [if_neg (hne 6 0 (by decide)), if_neg (hne 6 1 (by decide)), if_neg (hne 6 2 (by decide)), if_neg (hne 6 4 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |-1 * x (Rv 6) - -1 * y (Rv 6)| ≤ 1 * dist x y := by
      have hdiff : -1 * x (Rv 6) - -1 * y (Rv 6) = -(1 : ℝ) * (x (Rv 6) - y (Rv 6)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(1 : ℝ)| = 1 := by norm_num
      rw [habs]
      nlinarith [hdc 6]
    have hfac : ∀ A B : ℝ, ((9:ℝ)/4) * A - ((9:ℝ)/4) * B = ((9:ℝ)/4) * (A - B) := by
      intro A B; ring
    rw [hfac, abs_mul, abs_of_pos (show (0:ℝ) < ((9:ℝ)/4) by norm_num)]
    nlinarith [hcore, hd]
  by_cases hc7 : c = Rv 7
  · subst hc7
    simp only [if_neg (hne 7 0 (by decide)), if_neg (hne 7 1 (by decide)), if_neg (hne 7 2 (by decide)), if_neg (hne 7 4 (by decide)), if_neg (hne 7 6 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |-1 * x (Rv 7) - -1 * y (Rv 7)| ≤ 1 * dist x y := by
      have hdiff : -1 * x (Rv 7) - -1 * y (Rv 7) = -(1 : ℝ) * (x (Rv 7) - y (Rv 7)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(1 : ℝ)| = 1 := by norm_num
      rw [habs]
      nlinarith [hdc 7]
    have hfac : ∀ A B : ℝ, ((9:ℝ)/4) * A - ((9:ℝ)/4) * B = ((9:ℝ)/4) * (A - B) := by
      intro A B; ring
    rw [hfac, abs_mul, abs_of_pos (show (0:ℝ) < ((9:ℝ)/4) by norm_num)]
    nlinarith [hcore, hd]
  · simp only [if_neg hc0, if_neg hc1, if_neg hc2, if_neg hc4, if_neg hc6, if_neg hc7]
    simp [dist_nonneg]

theorem hfbnd_R (q : ℕ) (hq : q < 3) (ν : State (Var 8))
    (hν : ∀ gT' ∈ gsSR, Term.eval gT' ν ≤ 0) :
    ∀ x ∈ Metric.closedBall ν 1,
      ‖odeField (jointSys (fun _ => Term.const 0) (fRR q) (Term.const ((9:ℝ)/4))) x‖
        ≤ ((80:NNReal) : ℝ) := by
  have hne : ∀ (a b : Fin 8), a ≠ b → (Rv a : Var 8) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro x hx
  rw [Metric.mem_closedBall] at hx
  have hbandf : ∀ (j : Fin 8) (lo hi : ℝ),
      lo ≤ ν (Rv j) → ν (Rv j) ≤ hi → -2 ≤ lo → hi ≤ 2 → |x (Rv j)| ≤ 3 := by
    intro j lo hi hl hh hlo1 hhi1
    have h := dist_le_pi_dist x ν (Rv j)
    rw [Real.dist_eq] at h
    have hνb : |ν (Rv j)| ≤ 2 := abs_le.mpr ⟨by linarith, by linarith⟩
    have h2 := abs_sub_abs_le_abs_sub (x (Rv j)) (ν (Rv j))
    linarith [abs_le.mp hνb, hx]
  have hxb0 : |x (Rv 0)| ≤ 3 := by
    refine hbandf 0 (0) ((4:ℝ)/5) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν faceVLo (by simp [gsSR])
      simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
    · have := hν faceVHi (by simp [gsSR])
      simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
  have hxb2 : |x (Rv 2)| ≤ 3 := by
    refine hbandf 2 (-(1:ℝ)/2) ((3:ℝ)/20) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν facePsiLo (by simp [gsSR])
      simp only [facePsiLo, Term.eval, AOp.interp] at this; linarith
    · have := hν facePsiHi (by simp [gsSR])
      simp only [facePsiHi, Term.eval, AOp.interp] at this; linarith
  have hxb4 : |x (Rv 4)| ≤ 3 := by
    refine hbandf 4 (-(1:ℝ)/2) ((3:ℝ)/20) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν faceThLo (by simp [gsSR])
      simp only [faceThLo, Term.eval, AOp.interp] at this; linarith
    · have := hν faceThHi (by simp [gsSR])
      simp only [faceThHi, Term.eval, AOp.interp] at this; linarith
  have hxb6 : |x (Rv 6)| ≤ 3 := by
    refine hbandf 6 (-(1:ℝ)) ((3:ℝ)/20) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν faceZLo (by simp [gsSR])
      simp only [faceZLo, Term.eval, AOp.interp] at this; linarith
    · have := hν faceZHi (by simp [gsSR])
      simp only [faceZHi, Term.eval, AOp.interp] at this; linarith
  have hxb7 : |x (Rv 7)| ≤ 3 := by
    refine hbandf 7 (-(1:ℝ)/2) ((3:ℝ)/20) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν facePhLo (by simp [gsSR])
      simp only [facePhLo, Term.eval, AOp.interp] at this; linarith
    · have := hν facePhHi (by simp [gsSR])
      simp only [facePhHi, Term.eval, AOp.interp] at this; linarith
  rw [odeField_RR q hq]
  refine pi_norm_le_iff_of_nonneg (by norm_num) |>.mpr ?_
  intro c
  have hLcoe : ((80:NNReal) : ℝ) = 80 := rfl
  rw [hLcoe]
  by_cases hc0 : c = Rv 0
  · subst hc0
    simp only [eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcst : 0 ≤ cstR q ∧ cstR q ≤ 1 := by
      interval_cases q <;> norm_num [cstR]
    have hcore : |3 * (cstR q - x (Rv 0))| ≤ 12 := by
      obtain ⟨hcl, hch⟩ := hcst
      rw [abs_le]
      constructor <;> nlinarith [abs_le.mp hxb0]
    rw [show ((9:ℝ)/4) * (3 * (cstR q - x (Rv 0))) = ((9:ℝ)/4) * (3 * (cstR q - x (Rv 0))) from by ring, abs_mul,
      abs_of_pos (show (0:ℝ) < ((9:ℝ)/4) by norm_num)]
    nlinarith [hcore, abs_nonneg (3 * (cstR q - x (Rv 0)))]
  by_cases hc1 : c = Rv 1
  · subst hc1
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hBx : |(1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))| ≤ 9 := by
      have h2 : x (Rv 2) * x (Rv 2) ≤ 9 := by nlinarith [abs_le.mp hxb2]
      have h3 : x (Rv 4) * x (Rv 4) ≤ 9 := by nlinarith [abs_le.mp hxb4]
      have h2n : 0 ≤ x (Rv 2) * x (Rv 2) := mul_self_nonneg _
      have h3n : 0 ≤ x (Rv 4) * x (Rv 4) := mul_self_nonneg _
      rw [abs_le]
      constructor <;> nlinarith
    have hcore : |x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))| ≤ 27 := by
      rw [abs_mul]
      nlinarith [abs_nonneg (x (Rv 0)), abs_le.mp hxb0, abs_nonneg ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))]
    rw [show ((9:ℝ)/4) * (x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))) = ((9:ℝ)/4) * (x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))) from by ring, abs_mul,
      abs_of_pos (show (0:ℝ) < ((9:ℝ)/4) by norm_num)]
    nlinarith [hcore, abs_nonneg (x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))))]
  by_cases hc2 : c = Rv 2
  · subst hc2
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcore : |-1 * x (Rv 2)| ≤ 3 := by
      rw [abs_mul]
      have habs : |(-1 : ℝ)| = 1 := by norm_num
      rw [habs]
      linarith [abs_le.mp hxb2, abs_nonneg (x (Rv 2))]
    rw [show ((9:ℝ)/4) * (-1 * x (Rv 2)) = ((9:ℝ)/4) * (-1 * x (Rv 2)) from by ring, abs_mul,
      abs_of_pos (show (0:ℝ) < ((9:ℝ)/4) by norm_num)]
    nlinarith [hcore, abs_nonneg (-1 * x (Rv 2))]
  by_cases hc4 : c = Rv 4
  · subst hc4
    simp only [if_neg (hne 4 0 (by decide)), if_neg (hne 4 1 (by decide)), if_neg (hne 4 2 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcore : |-1 * x (Rv 4)| ≤ 3 := by
      rw [abs_mul]
      have habs : |(-1 : ℝ)| = 1 := by norm_num
      rw [habs]
      linarith [abs_le.mp hxb4, abs_nonneg (x (Rv 4))]
    rw [show ((9:ℝ)/4) * (-1 * x (Rv 4)) = ((9:ℝ)/4) * (-1 * x (Rv 4)) from by ring, abs_mul,
      abs_of_pos (show (0:ℝ) < ((9:ℝ)/4) by norm_num)]
    nlinarith [hcore, abs_nonneg (-1 * x (Rv 4))]
  by_cases hc6 : c = Rv 6
  · subst hc6
    simp only [if_neg (hne 6 0 (by decide)), if_neg (hne 6 1 (by decide)), if_neg (hne 6 2 (by decide)), if_neg (hne 6 4 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcore : |-1 * x (Rv 6)| ≤ 3 := by
      rw [abs_mul]
      have habs : |(-1 : ℝ)| = 1 := by norm_num
      rw [habs]
      linarith [abs_le.mp hxb6, abs_nonneg (x (Rv 6))]
    rw [show ((9:ℝ)/4) * (-1 * x (Rv 6)) = ((9:ℝ)/4) * (-1 * x (Rv 6)) from by ring, abs_mul,
      abs_of_pos (show (0:ℝ) < ((9:ℝ)/4) by norm_num)]
    nlinarith [hcore, abs_nonneg (-1 * x (Rv 6))]
  by_cases hc7 : c = Rv 7
  · subst hc7
    simp only [if_neg (hne 7 0 (by decide)), if_neg (hne 7 1 (by decide)), if_neg (hne 7 2 (by decide)), if_neg (hne 7 4 (by decide)), if_neg (hne 7 6 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcore : |-1 * x (Rv 7)| ≤ 3 := by
      rw [abs_mul]
      have habs : |(-1 : ℝ)| = 1 := by norm_num
      rw [habs]
      linarith [abs_le.mp hxb7, abs_nonneg (x (Rv 7))]
    rw [show ((9:ℝ)/4) * (-1 * x (Rv 7)) = ((9:ℝ)/4) * (-1 * x (Rv 7)) from by ring, abs_mul,
      abs_of_pos (show (0:ℝ) < ((9:ℝ)/4) by norm_num)]
    nlinarith [hcore, abs_nonneg (-1 * x (Rv 7))]
  · simp only [if_neg hc0, if_neg hc1, if_neg hc2, if_neg hc4, if_neg hc6, if_neg hc7]
    norm_num

/-! ## Existence -/

theorem esR (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt) :
    ∀ σ, Formula.sat (Formula.and (FM gR (gs9R m)) envR) σ →
      HExistSegB (fLR l) (fRR m) (Term.const ((9:ℝ)/4)) domLR domRR dt
        (Function.update σ tgR 0) := by
  intro σ hσ
  have hceil : σ (Rv 0) ≤ (if m = 0 then 3/10 else if m = 1 then 1/2 else 13/20) := by
    have := (sat_FM_iff gR (gs9R m) σ).mp hσ.1 (ceilR m)
      (List.mem_cons_of_mem _ (List.mem_append_right _ (List.mem_singleton.mpr rfl)))
    simp only [ceilR, Term.eval, AOp.interp] at this
    linarith
  have hR : Formula.sat domRR σ := hσ.2.2
  rw [sat_domRR] at hR
  obtain ⟨hd3l, hd3h, hd5l, hd5h, hd7l, hd7h, hd2l, hd2h, hd1l, hd4l, hd4h, hd0l, hd0h, hd6l, hd6h⟩ := hR
  have hupd : ∀ j : Fin 8, σ (Side.R, j) = Function.update σ tgR 0 (Side.R, j) := by
    intro j
    rw [Function.update_of_ne (by simp [tgR, Prod.ext_iff])]
  have hfS : ∀ gT' ∈ gsSR, Term.eval gT' (Function.update σ tgR 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsSR, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
      · first
          | (simp only [faceVLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceVHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [facePsiLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [facePsiHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceThLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceThHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceZLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceZHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [facePhLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [facePhHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
  have hfN : ∀ gT' ∈ gsNR, Term.eval gT' (Function.update σ tgR 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsNR, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with rfl | rfl | rfl | rfl | rfl <;>
      · first
          | (simp only [faceSLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceOPsLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceOPsHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceOThLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceOThHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
  refine HExistSegB_of_viability_stratA (fLR l) (fRR m) (Term.const ((9:ℝ)/4))
    domLR domRR gsSR [] gsNR 0 le_rfl
    [((Rv 0 : Var 8), (27:ℝ)/4,
      (27/4) * (if m = 0 then 3/10 else if m = 1 then 1/2 else 13/20),
      (if m = 0 then (3:ℝ)/10 else if m = 1 then 1/2 else 13/20))]
    ([] : List (Var 8 × ℝ × ℝ × ℝ))
    (jointSys_wellFormed _ _ _)
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLR l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_RR gT' (by
        rcases List.mem_append.mp hgT with h | h
        · exact List.mem_append_left _ h
        · exact absurd h (List.not_mem_nil)) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLR l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_RR gT' (List.mem_append_right _ hgT) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro p hp hb
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLR l) _ hb
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by
      intro p hp
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      norm_num)
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by
      intro p hp
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      show (27:ℝ)/4 * (if m = 0 then 3/10 else if m = 1 then 1/2 else 13/20)
        ≤ (27:ℝ)/4 * (if m = 0 then (3:ℝ)/10 else if m = 1 then 1/2 else 13/20)
      split_ifs <;> norm_num)
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by
      intro gT' hgT x _ hface
      exact hbndS_R m hm gT' hgT x hface)
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))
    (by
      intro i hi x hxs _
      exact hbndN_R m hm i hi x hxs)
    (by
      intro p hp x _ _
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      have hne : ∀ (a b : Fin 8), a ≠ b → (Rv a : Var 8) ≠ Rv b := by
        intro a b hab
        simp [Rv, Prod.ext_iff]
        exact fun h => hab (by exact_mod_cast h)
      rw [odeField_RR m hm]
      simp only [eq_self_iff_true, if_true, if_pos rfl]
      show (9:ℝ)/4 * (3 * (cstR m - x (Rv 0)))
        ≤ (27:ℝ)/4 * (if m = 0 then 3/10 else if m = 1 then 1/2 else 13/20)
          - (27:ℝ)/4 * x (Rv 0)
      simp only [cstR]
      split_ifs <;> ring_nf <;> norm_num
    )
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by
      intro x hS hN hAU hAL
      have hS' : ∀ gT' ∈ gsSR, Term.eval gT' x ≤ 0 :=
        fun gT' hgT => hS gT' (List.mem_append_left _ hgT)
      have hb0l : 0 ≤ x (Rv 0) := by
        have := hS' faceVLo (by simp [gsSR])
        simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
      have hb0h : x (Rv 0) ≤ (4:ℝ)/5 := by
        have := hS' faceVHi (by simp [gsSR])
        simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
      have hb2l : -(1:ℝ)/2 ≤ x (Rv 2) := by
        have := hS' facePsiLo (by simp [gsSR])
        simp only [facePsiLo, Term.eval, AOp.interp] at this; linarith
      have hb2h : x (Rv 2) ≤ (3:ℝ)/20 := by
        have := hS' facePsiHi (by simp [gsSR])
        simp only [facePsiHi, Term.eval, AOp.interp] at this; linarith
      have hb4l : -(1:ℝ)/2 ≤ x (Rv 4) := by
        have := hS' faceThLo (by simp [gsSR])
        simp only [faceThLo, Term.eval, AOp.interp] at this; linarith
      have hb4h : x (Rv 4) ≤ (3:ℝ)/20 := by
        have := hS' faceThHi (by simp [gsSR])
        simp only [faceThHi, Term.eval, AOp.interp] at this; linarith
      have hb6l : -(1:ℝ) ≤ x (Rv 6) := by
        have := hS' faceZLo (by simp [gsSR])
        simp only [faceZLo, Term.eval, AOp.interp] at this; linarith
      have hb6h : x (Rv 6) ≤ (3:ℝ)/20 := by
        have := hS' faceZHi (by simp [gsSR])
        simp only [faceZHi, Term.eval, AOp.interp] at this; linarith
      have hb7l : -(1:ℝ)/2 ≤ x (Rv 7) := by
        have := hS' facePhLo (by simp [gsSR])
        simp only [facePhLo, Term.eval, AOp.interp] at this; linarith
      have hb7h : x (Rv 7) ≤ (3:ℝ)/20 := by
        have := hS' facePhHi (by simp [gsSR])
        simp only [facePhHi, Term.eval, AOp.interp] at this; linarith
      have hb1l : 0 ≤ x (Rv 1) := by
        have := hN faceSLo (by simp [gsNR])
        simp only [faceSLo, Term.eval, AOp.interp] at this; linarith
      have hb3l : -(1:ℝ)/2 ≤ x (Rv 3) := by
        have := hN faceOPsLo (by simp [gsNR])
        simp only [faceOPsLo, Term.eval, AOp.interp] at this; linarith
      have hb3h : x (Rv 3) ≤ (3:ℝ)/5 := by
        have := hN faceOPsHi (by simp [gsNR])
        simp only [faceOPsHi, Term.eval, AOp.interp] at this; linarith
      have hb5l : -(1:ℝ)/2 ≤ x (Rv 5) := by
        have := hN faceOThLo (by simp [gsNR])
        simp only [faceOThLo, Term.eval, AOp.interp] at this; linarith
      have hb5h : x (Rv 5) ≤ (3:ℝ)/5 := by
        have := hN faceOThHi (by simp [gsNR])
        simp only [faceOThHi, Term.eval, AOp.interp] at this; linarith
      exact (sat_domRR x).mpr ⟨hb3l, hb3h, hb5l, hb5h, hb7l, hb7h, hb2l, hb2h, hb1l, hb4l, hb4h, hb0l, hb0h, hb6l, hb6h⟩)
    80 80 1 one_pos
    (fun ν0 h0 => hLip_R m hm ν0 (fun gT hgT => h0 gT (List.mem_append_left _ hgT)))
    (fun ν0 h0 => hfbnd_R m hm ν0 (fun gT hgT => h0 gT (List.mem_append_left _ hgT)))
    dt hdt
    (Function.update σ tgR 0)
    hfS
    hfN
    (by
      intro p hp
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      show Function.update σ tgR 0 (Rv 0)
        ≤ (if m = 0 then (3:ℝ)/10 else if m = 1 then 1/2 else 13/20)
      rw [← hupd 0]
      exact hceil)
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))
/-! ## Region plumbing -/

theorem ceilR_fv (m : ℕ) : (ceilR m).fv ⊆ range Rv := by
  intro x hx
  simp only [ceilR, Term.fv, Set.union_empty, Set.mem_singleton_iff] at hx
  exact ⟨0, hx.symm⟩

theorem regionR_fv (m : ℕ) : (regionR m).fv ⊆ range Rv := by
  intro x hx
  simp only [regionR, Formula.fv, Term.fv, Set.union_empty] at hx
  exact ceilR_fv m hx

theorem hmvregR : ∀ q, mvR ∉ (regionR q).fv := fun q h =>
  absurd (regionR_fv q h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))

theorem sat_regionR_iff (m : ℕ) (ν : State (Var 8)) :
    Formula.sat (regionR m) ν ↔
      ν (Rv 0) ≤ (if m = 0 then 3/10 else if m = 1 then 1/2 else 13/20) := by
  simp only [regionR, ceilR, Formula.sat, CompOp.interp, Term.eval, AOp.interp]
  constructor <;> intro h <;> linarith

theorem cstR_mono {a b : ℕ} (ha : a < 3) (hb : b < 3) (hab : a ≤ b) :
    (if a = 0 then (3:ℝ)/10 else if a = 1 then 1/2 else 13/20)
      ≤ (if b = 0 then (3:ℝ)/10 else if b = 1 then 1/2 else 13/20) := by
  interval_cases a <;> interval_cases b <;> norm_num <;> omega

theorem htggs9R (m : ℕ) : ∀ g' ∈ gR :: gs9R m, tgR ∉ g'.fv := by
  intro g' hg' h
  rcases List.mem_cons.mp hg' with rfl | hg'
  · exact htgg gR List.mem_cons_self h
  · rcases List.mem_append.mp hg' with hg' | hg'
    · exact htgg g' (List.mem_cons_of_mem _ hg') h
    · rw [List.mem_singleton] at hg'
      subst hg'
      exact absurd (ceilR_fv m h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, tgR, Prod.ext_iff]))

theorem htgF9R (m : ℕ) : tgR ∉ (FM gR (gs9R m)).fv :=
  notMem_FM_fv (htggs9R m)

theorem hmvgs9R (m : ℕ) : ∀ g' ∈ gR :: gs9R m, mvR ∉ g'.fv := by
  intro g' hg' h
  rcases List.mem_cons.mp hg' with rfl | hg'
  · exact hmvg gR List.mem_cons_self h
  · rcases List.mem_append.mp hg' with hg' | hg'
    · exact hmvg g' (List.mem_cons_of_mem _ hg') h
    · rw [List.mem_singleton] at hg'
      subst hg'
      exact absurd (ceilR_fv m h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, mvR, Prod.ext_iff]))

theorem FM_drop9R (m : ℕ) {ν : State (Var 8)}
    (h : Formula.sat (FM gR (gs9R m)) ν) : Formula.sat (FM gR gsR) ν := by
  rw [sat_FM_iff] at h ⊢
  intro g' hg'
  refine h g' ?_
  rcases List.mem_cons.mp hg' with rfl | hg'
  · exact List.mem_cons_self
  · exact List.mem_cons_of_mem _ (List.mem_append_left _ hg')

theorem FM_add9R (m : ℕ) {ν : State (Var 8)}
    (h : Formula.sat (FM gR gsR) ν)
    (hb : ν (Rv 0) ≤ (if m = 0 then 3/10 else if m = 1 then 1/2 else 13/20)) :
    Formula.sat (FM gR (gs9R m)) ν := by
  rw [sat_FM_iff] at h ⊢
  intro g' hg'
  rcases List.mem_cons.mp hg' with rfl | hg'
  · exact h _ List.mem_cons_self
  · rcases List.mem_append.mp hg' with hg' | hg'
    · exact h g' (List.mem_cons_of_mem _ hg')
    · rw [List.mem_singleton] at hg'
      subst hg'
      simp only [ceilR, Term.eval, AOp.interp]
      linarith

/-! ## The route verdicts — region face FIRST in the strata order, so every later
component's query carries the cut ceiling in its domain -/

noncomputable def gsVR (m : ℕ) : List (Term (Var 8)) := gR :: gsR

def VerdR (l m : ℕ) : Prop :=
  ∀ i (hi : i < (ceilR m :: gsVR m).length),
    z3solve (flowQuery ⟨(ceilR m :: gsVR m)[i], fLR l, fRR m, Term.const ((9:ℝ)/4),
      strataDomHost (Formula.and domLR domRR) ((ceilR m :: gsVR m).take i)⟩) = Verdict.unsat
    ∨ z3solve (flowQueryStrict ⟨(ceilR m :: gsVR m)[i], fLR l, fRR m, Term.const ((9:ℝ)/4),
      strataDomHost (Formula.and domLR domRR) ((ceilR m :: gsVR m).take i)⟩) = Verdict.unsat
    ∨ z3solve (flowQuerySuperlevel ⟨(ceilR m :: gsVR m)[i], fLR l, fRR m, Term.const ((9:ℝ)/4),
      strataDomHost (Formula.and domLR domRR) ((ceilR m :: gsVR m).take i)⟩) = Verdict.unsat

/-! ## The coupling at λ = 17/10 over the enriched invariant, and its transport -/

theorem coupleR (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdR l m) :
    ∀ σ', Formula.sat (Formula.and (FM gR (gs9R m)) envR) σ' → σ' tgR = 0 →
      faModalB (Equiv.refl (Var 8))
        (Program.ode (DLCalTiming.clk tgR (leftBlock (fLR l))) domLR)
        (Program.ode (rightBlock (fRR m) (Term.const ((9:ℝ)/4))) domRR)
        (Formula.and (FM gR (gs9R m)) envR) tgR dt σ' := by
  intro σ' hσ' htg0
  have hupd : Function.update σ' tgR (0 : ℝ) = σ' := by
    funext x
    by_cases hx : x = tgR
    · subst hx; rw [Function.update_self]; exact htg0.symm
    · rw [Function.update_of_ne hx]
  have hAll := segPresAll_from_strata_verdicts' (fLR l) (fRR m) (Term.const ((9:ℝ)/4))
    (Formula.and domLR domRR) (ceilR m :: gsVR m) hv
  have hmemV : ∀ g' ∈ gR :: gs9R m, g' ∈ ceilR m :: gsVR m := by
    intro g' hg'
    rcases List.mem_cons.mp hg' with rfl | hg'
    · exact List.mem_cons_of_mem _ List.mem_cons_self
    · rcases List.mem_append.mp hg' with hg' | hg'
      · exact List.mem_cons_of_mem _ (List.mem_cons_of_mem _ hg')
      · rw [List.mem_singleton] at hg'
        subst hg'
        exact List.mem_cons_self
  have hboxes : ∀ g' ∈ gR :: gs9R m, Formula.sat (Formula.box (Program.ode
      (leftBlock (fLR l) ++ rightBlock (fRR m) (Term.const ((9:ℝ)/4)))
      (Formula.and domLR domRR)) (invLe g')) σ' := by
    intro g' hg'
    rw [sat_box]
    intro ω hω
    rw [sat_invLe]
    refine hAll σ' ?_ ω (by rw [← jointSys_split] at hω; exact hω) g' (hmemV g' hg')
    intro g hg
    have hgmem : g ∈ gR :: gs9R m := by
      rcases List.mem_cons.mp hg with rfl | hg
      · exact List.mem_cons_of_mem _ (List.mem_append_right _ (List.mem_singleton.mpr rfl))
      · rcases List.mem_cons.mp hg with rfl | hg
        · exact List.mem_cons_self
        · exact List.mem_cons_of_mem _ (List.mem_append_left _ hg)
    exact (sat_FM_iff gR (gs9R m) σ').mp hσ'.1 g hgmem
  have hbase := segment_faModalB_from_certB_list gR (gs9R m) (fLR l) (fRR m)
    (Term.const ((9:ℝ)/4)) domLR domRR tgR dt
    (LR_blocks_disjoint _ _ _ (hfLR l hl) (hfRR m hm) (by simp [Term.fv]))
    (fun v hv' => Or.inl (by
      obtain ⟨i, rfl⟩ := hdomLR hv'
      exact Lv_mem_leftBlock_boundSet _ i))
    (fun v hv' => Or.inl (by
      obtain ⟨i, rfl⟩ := hdomRR hv'
      exact Rv_mem_rightBlock_boundSet _ _ i))
    (fun h => by
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLR l) _ h
      exact aux_ne_Lv aR i hi)
    (fun h => aux_notin_range_Lv aR (leftBlock_readVars_sub (fLR l) (hfLR l hl) h))
    (fun h => by
      obtain ⟨i, hi⟩ := rightBlock_bound_sub (fRR m) (Term.const ((9:ℝ)/4)) _ h
      exact aux_ne_Rv aR i hi)
    (fun h => aux_notin_range_Rv aR (rightBlock_readVars_sub (fRR m)
      (Term.const ((9:ℝ)/4)) (hfRR m hm) (by simp [Term.fv]) h))
    (fun h => aux_notin_range_Rv aR (rightBlock_boundSet_sub (fRR m)
      (Term.const ((9:ℝ)/4)) h))
    (fun h => aux_notin_range_Lv aR (hdomLR h))
    (fun h => aux_notin_range_Rv aR (hdomRR h))
    (htggs9R m) hboxes
    (esR l m hl hm dt hdt σ' hσ')
  rw [hupd] at hbase
  refine faModalB_strengthen_plant ?_ hbase
  intro ν μ hplant hsem
  have hdomLν : Formula.sat domLR ν := sem_ode_ends_in_domain hplant.1
  have hdomRμ : Formula.sat domRR μ := sem_ode_ends_in_domain hsem
  have hdomLμ : Formula.sat domLR μ := by
    rwa [(Formula.coincidence domLR (fun v hv' => sem_ode_mask hsem (by
      obtain ⟨i, rfl⟩ := hdomLR hv'
      intro hb
      obtain ⟨j, hj⟩ := rightBlock_bound_sub (fRR m) (Term.const ((9:ℝ)/4)) _ hb
      exact absurd hj (by simp [Lv, Rv, Prod.ext_iff]))) :
        Formula.sat domLR μ ↔ Formula.sat domLR ν)]
  exact ⟨hdomLμ, hdomRμ⟩

theorem couple1R (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdR l m) :
    ∀ σ, Formula.sat (Formula.and (FM gR (gs9R m)) envR) σ →
      faModalB (Equiv.refl (Var 8))
        (Program.ode (DLCalTiming.clk tgR (leftBlock (fLR l))) domLR)
        (Program.ode (rightBlock (fRR m) (Term.const 1)) domRR)
        (Formula.and (FM gR (gs9R m)) envR) tgR dt
        (Function.update σ tgR 0) := by
  intro σ hσ
  have htgφ : tgR ∉ (Formula.and (FM gR (gs9R m)) envR).fv := by
    intro h
    rcases h with h | h
    · exact htgF9R m h
    · exact htgenvR h
  have hupdφ : Formula.sat (Formula.and (FM gR (gs9R m)) envR)
      (Function.update σ tgR 0) := by
    rwa [(Formula.coincidence (Formula.and (FM gR (gs9R m)) envR) (fun v hv' =>
      Function.update_of_ne (fun hc => htgφ (by rw [← hc]; exact hv')) _ _) :
        Formula.sat (Formula.and (FM gR (gs9R m)) envR) _ ↔ _)]
  refine faModalB_monoQ ?_ (coupleR l m hl hm dt hdt hv
    (Function.update σ tgR 0) hupdφ (Function.update_self _ _ _))
  intro ν μ hsem
  exact sem_rightBlock_reparam ((9:ℝ)/4) 1 (by norm_num) one_pos hsem


theorem sat_faModal_monoPost {P Q : Program (Var 8)} {A B : Formula (Var 8)}
    (hAB : ∀ ν, Formula.sat A ν → Formula.sat B ν) {σ : State (Var 8)}
    (h : Formula.sat (faModal (Equiv.refl (Var 8)) P Q A) σ) :
    Formula.sat (faModal (Equiv.refl (Var 8)) P Q B) σ := by
  rw [faModal_sat] at h ⊢
  intro ν hν
  obtain ⟨μ, hμ, hA⟩ := h ν hν
  exact ⟨μ, hμ, hAB μ hA⟩

/-! ## The window response — hop prefix, two coupled pieces, region owed -/

theorem respondR (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdR l m) (path : List ℕ) (hpath : ∀ p ∈ path, p < 3)
    {σ : State (Var 8)}
    (hσE : Formula.sat (Formula.and (FM gR (gs9R m)) envR) σ) :
    Formula.sat (faModal (Equiv.refl (Var 8))
      (windowSeg (leftBlock (fLR l)) domLR tgR dt 3)
      (bigSeq ((path.map (fun p => Program.ode (rightBlock (fRR p) (Term.const 1)) domRR))
        ++ [Program.ode (rightBlock (fRR m) (Term.const 1)) domRR,
            Program.ode (rightBlock (fRR m) (Term.const 1)) domRR,
            Program.ode (rightBlock (fRR m) (Term.const 1)) domRR]))
      (Formula.and (Formula.and (FM gR gsR) envR) (regionR m))) σ := by
  have hfa := Hmulti_windowRF_prefixed (fLR l) domLR (FM gR (gs9R m)) envR
    aR dt 3 (htgF9R m) htgenvR
    (path.map (fun p => (⟨fRR p, Term.const 1, domRR⟩ : RepoHop 8)))
    (by
      intro h hh
      obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hh
      exact ⟨hfRR p (hpath p hp), by simp [Term.fv], hdomRR⟩)
    (fun σ' hσ' => hσ'.2.1)
    (by
      intro h hh σ' hσ' htg'
      obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hh
      obtain ⟨ρ, hsem, hρσ⟩ := static_hop_existsR (fR := fRR p)
        (lam := Term.const 1) (domR := domRR) hσ'.2.2
      exact ⟨ρ, hsem, hρσ ▸ hσ'⟩)
    (hfLR l hl) hdomLR
    (List.replicate 3 (Program.ode (rightBlock (fRR m) (Term.const 1)) domRR))
    (by simp) (by norm_num)
    (by
      intro Q hQ
      rw [List.eq_of_mem_replicate hQ, Program.rename_refl]
      exact hdisH_progR (⟨fRR m, Term.const 1, domRR⟩ : RepoHop 8)
        (hfRR m hm) (by simp [Term.fv]) hdomRR (hfLR l hl) hdomLR)
    (by
      intro Q hQ σ' hσ'
      rw [List.eq_of_mem_replicate hQ]
      exact couple1R l m hl hm dt hdt hv σ' hσ')
    hσE
  rw [show (path.map (fun p => (⟨fRR p, Term.const 1, domRR⟩ : RepoHop 8))).map
      (fun h => h.progR)
      = path.map (fun p => Program.ode (rightBlock (fRR p) (Term.const 1)) domRR)
    from by rw [List.map_map]; rfl] at hfa
  have hfa2 : Formula.sat (faModal (Equiv.refl (Var 8))
      (windowSeg (leftBlock (fLR l)) domLR tgR dt 3)
      (bigSeq ((path.map (fun p => Program.ode (rightBlock (fRR p) (Term.const 1)) domRR))
        ++ [Program.ode (rightBlock (fRR m) (Term.const 1)) domRR,
            Program.ode (rightBlock (fRR m) (Term.const 1)) domRR,
            Program.ode (rightBlock (fRR m) (Term.const 1)) domRR]))
      (Formula.and (FM gR (gs9R m)) envR)) σ := by
    simpa [List.replicate] using hfa
  refine sat_faModal_monoPost ?_ hfa2
  intro ν hν
  refine ⟨⟨FM_drop9R m hν.1, hν.2⟩, ?_⟩
  rw [sat_regionR_iff]
  have hface := (sat_FM_iff gR (gs9R m) ν).mp hν.1 (ceilR m)
    (List.mem_cons_of_mem _ (List.mem_append_right _ (List.mem_singleton.mpr rfl)))
  simp only [ceilR, Term.eval, AOp.interp] at hface
  linarith

/-! ## The step provider — climb to `max(l, q)`, region received and owed -/

theorem HmultiR (dt : ℝ) (hdt : 0 ≤ dt)
    (hv00 : VerdR 0 0) (hv01 : VerdR 0 1) (hv02 : VerdR 0 2)
    (hv11 : VerdR 1 1) (hv12 : VerdR 1 2) (hv22 : VerdR 2 2) :
    ∀ P ∈ leftProgsR dt, ∀ (q : ℕ), q < GrR.modes.length → ∀ σ, σ mvR = (q : ℝ) →
      Formula.sat (Formula.and (FM gR gsR) envR) σ → Formula.sat (regionR q) σ →
      ∃ segs : List (ℕ × RMode (Var 8) × REdge (Var 8)),
        (∀ s ∈ segs, GrR.modeAt s.1 = some s.2.1 ∧ s.2.2 ∈ GrR.edgesFrom s.1) ∧
        List.IsChain (fun a b => a.2.2.tgt = b.1) segs ∧
        (∀ s, segs.head? = some s → s.1 = q) ∧
        Formula.sat (faModal (Equiv.refl (Var 8)) P
          (bigSeq (segs.map (fun s => Program.ode s.2.1.sys s.2.1.dom)))
          (Formula.and (Formula.and (FM gR gsR) envR)
            (regionR (qfOf segs q)))) σ := by
  intro P hP q hq σ hmv hσ hreg
  have hq3 : q < 3 := by simpa [GrR] using hq
  have hstep : ∀ (a b : ℕ × RMode (Var 8) × REdge (Var 8)) rest,
      a.2.2.tgt = b.1 → List.IsChain (fun x y => x.2.2.tgt = y.1) (b :: rest) →
      List.IsChain (fun x y => x.2.2.tgt = y.1) (a :: b :: rest) := by
    intro a b rest hab hrest
    refine hrest.cons ?_
    intro y hy
    rw [List.head?_cons, Option.mem_some_iff] at hy
    subst hy
    exact hab
  have hhead1 : ∀ (a : ℕ × RMode (Var 8) × REdge (Var 8)) rest s,
      (a :: rest : List _).head? = some s → s = a := by
    intro a rest s hs
    simpa [List.head?_cons] using hs.symm
  have halign : ∀ st tgt : ℕ, st < 3 → tgt < 3 → edgeR st tgt ∈ GrR.edges →
      GrR.modeAt st = some (modeR st) ∧ edgeR st tgt ∈ GrR.edgesFrom st :=
    fun st tgt hs ht he => ⟨GrR_modeAt st hs, edgeR_mem st tgt he⟩
  have hregv : σ (Rv 0) ≤ (if q = 0 then 3/10 else if q = 1 then 1/2 else 13/20) :=
    (sat_regionR_iff q σ).mp hreg
  have henr : ∀ m : ℕ, m < 3 → q ≤ m →
      Formula.sat (Formula.and (FM gR (gs9R m)) envR) σ :=
    fun m hm3 hqm => ⟨FM_add9R m hσ.1 (le_trans hregv (cstR_mono hq3 hm3 hqm)), hσ.2⟩
  simp only [leftProgsR, leftDataR, List.map_cons, List.map_nil, List.mem_cons,
    List.not_mem_nil, or_false] at hP
  have hgate : ∀ (l : ℕ) (R : Program (Var 8)) (ψ : Formula (Var 8)),
      Formula.sat (faModal (Equiv.refl (Var 8))
        (windowSeg (leftBlock (fLR l)) domLR tgR dt 3) R ψ) σ →
      Formula.sat (faModal (Equiv.refl (Var 8))
        (gwindowSeg Formula.tt (leftBlock (fLR l)) domLR tgR dt 3) R ψ) σ := by
    intro l R ψ hbody
    refine faModal_seqL _ _ _ _ _ _ ?_
    rw [sat_box]
    intro ν hν
    rw [sem_test] at hν
    obtain ⟨rfl, -⟩ := hν
    exact hbody
  rcases hP with rfl | rfl | rfl
  all_goals interval_cases q
  · refine ⟨[(0, modeR 0, edgeR 0 0), (0, modeR 0, edgeR 0 0), (0, modeR 0, edgeR 0 0)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl
      · exact halign 0 0 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 0 0 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 0 0 (by norm_num) (by norm_num) (by simp [GrR])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondR 0 0 (by norm_num) (by norm_num) dt hdt hv00 [] (by simp)
        (henr 0 (by norm_num) (by norm_num))
      have hq : qfOf [(0, modeR 0, edgeR 0 0), (0, modeR 0, edgeR 0 0), (0, modeR 0, edgeR 0 0)] 0 = 0 := rfl
      rw [hq]
      exact hgate 0 _ _ (by simpa [modeR, List.replicate] using this)
  · refine ⟨[(1, modeR 1, edgeR 1 1), (1, modeR 1, edgeR 1 1), (1, modeR 1, edgeR 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrR])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondR 0 1 (by norm_num) (by norm_num) dt hdt hv01 [] (by simp)
        (henr 1 (by norm_num) (by norm_num))
      have hq : qfOf [(1, modeR 1, edgeR 1 1), (1, modeR 1, edgeR 1 1), (1, modeR 1, edgeR 1 1)] 1 = 1 := rfl
      rw [hq]
      exact hgate 0 _ _ (by simpa [modeR, List.replicate] using this)
  · refine ⟨[(2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondR 0 2 (by norm_num) (by norm_num) dt hdt hv02 [] (by simp)
        (henr 2 (by norm_num) (by norm_num))
      have hq : qfOf [(2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2)] 2 = 2 := rfl
      rw [hq]
      exact hgate 0 _ _ (by simpa [modeR, List.replicate] using this)
  · refine ⟨[(0, modeR 0, edgeR 0 1), (1, modeR 1, edgeR 1 1), (1, modeR 1, edgeR 1 1), (1, modeR 1, edgeR 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl
      · exact halign 0 1 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrR])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondR 1 1 (by norm_num) (by norm_num) dt hdt hv11 [0] (by intro p hp; simp only [List.mem_cons, List.not_mem_nil, or_false] at hp; rcases hp with rfl <;> norm_num)
        (henr 1 (by norm_num) (by norm_num))
      have hq : qfOf [(0, modeR 0, edgeR 0 1), (1, modeR 1, edgeR 1 1), (1, modeR 1, edgeR 1 1), (1, modeR 1, edgeR 1 1)] 0 = 1 := rfl
      rw [hq]
      exact hgate 1 _ _ (by simpa [modeR, List.replicate] using this)
  · refine ⟨[(1, modeR 1, edgeR 1 1), (1, modeR 1, edgeR 1 1), (1, modeR 1, edgeR 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrR])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondR 1 1 (by norm_num) (by norm_num) dt hdt hv11 [] (by simp)
        (henr 1 (by norm_num) (by norm_num))
      have hq : qfOf [(1, modeR 1, edgeR 1 1), (1, modeR 1, edgeR 1 1), (1, modeR 1, edgeR 1 1)] 1 = 1 := rfl
      rw [hq]
      exact hgate 1 _ _ (by simpa [modeR, List.replicate] using this)
  · refine ⟨[(2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondR 1 2 (by norm_num) (by norm_num) dt hdt hv12 [] (by simp)
        (henr 2 (by norm_num) (by norm_num))
      have hq : qfOf [(2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2)] 2 = 2 := rfl
      rw [hq]
      exact hgate 1 _ _ (by simpa [modeR, List.replicate] using this)
  · refine ⟨[(0, modeR 0, edgeR 0 1), (1, modeR 1, edgeR 1 2), (2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl | rfl
      · exact halign 0 1 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 1 2 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondR 2 2 (by norm_num) (by norm_num) dt hdt hv22 [0, 1] (by intro p hp; simp only [List.mem_cons, List.not_mem_nil, or_false] at hp; rcases hp with rfl | rfl <;> norm_num)
        (henr 2 (by norm_num) (by norm_num))
      have hq : qfOf [(0, modeR 0, edgeR 0 1), (1, modeR 1, edgeR 1 2), (2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2)] 0 = 2 := rfl
      rw [hq]
      exact hgate 2 _ _ (by simpa [modeR, List.replicate] using this)
  · refine ⟨[(1, modeR 1, edgeR 1 2), (2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl | rfl
      · exact halign 1 2 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp))))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondR 2 2 (by norm_num) (by norm_num) dt hdt hv22 [1] (by intro p hp; simp only [List.mem_cons, List.not_mem_nil, or_false] at hp; rcases hp with rfl <;> norm_num)
        (henr 2 (by norm_num) (by norm_num))
      have hq : qfOf [(1, modeR 1, edgeR 1 2), (2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2)] 1 = 2 := rfl
      rw [hq]
      exact hgate 2 _ _ (by simpa [modeR, List.replicate] using this)
  · refine ⟨[(2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl | rfl | rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrR])
    · exact (hstep _ _ _ rfl (hstep _ _ _ rfl (by simp)))
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondR 2 2 (by norm_num) (by norm_num) dt hdt hv22 [] (by simp)
        (henr 2 (by norm_num) (by norm_num))
      have hq : qfOf [(2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2), (2, modeR 2, edgeR 2 2)] 2 = 2 := rfl
      rw [hq]
      exact hgate 2 _ _ (by simpa [modeR, List.replicate] using this)

/-- **`refinement_ladder_rover_rung3_6to8`, modal Theorem 3** — the region-carrying chain at
the tool's λ = 17/10: each right mode's checked-cut ceiling `v_R ≤ c_m` rides the
loop invariant as its region (`mvRegionR`), the six climb verdict packs carry the
face first so every later component sees the ceiling, and the response climbs to
`max(window, start)` before running two coupled pieces. Residuals: six 5-query
stratified packs. -/
theorem rover_ladder_rung3_6to8_modal (dt : ℝ) (hdt : 0 ≤ dt)
    (hv00 : VerdR 0 0) (hv01 : VerdR 0 1) (hv02 : VerdR 0 2)
    (hv11 : VerdR 1 1) (hv12 : VerdR 1 2) (hv22 : VerdR 2 2) :
    RFormula.rvalid (theorem3Form
      (bigChoice (leftProgsR dt))
      (rightAutomatonBody GrR mvR)
      (RFormula.and (RFormula.and (canonInvM gR gsR) (envLR domLR domRR))
        (mvRegionR mvR regionR GrR.modes.length))) := by
  refine theorem3_faithful_multiR_LR GrR mvR (FM gR gsR) domLR domRR regionR
    (leftProgsR dt) (canonInvM gR gsR) (encode_canonInvM gR gsR) ?_ ?_ ?_
  · refine sides_disjoint 0 1 0 (by decide) (by decide) ?_ ?_
    · refine vars_bigChoice_sub _ _ ?_
      intro p hp
      simp only [leftProgsR, List.mem_map] at hp
      obtain ⟨d, hd, rfl⟩ := hp
      exact vars_gwindowSegL_sub d.1 d.2.1 d.2.2.1 1 dt d.2.2.2 (hLR d hd).1
        (hLR d hd).2.1 (hLR d hd).2.2
    · intro x hx
      rw [Program.rename_refl] at hx
      rcases vars_bodyU_sub GrR _ httR hRvR hx with hx | hx
      · exact Or.inl (Set.mem_insert_iff.mpr (Or.inl (Set.mem_singleton_iff.mp hx)))
      · exact Or.inr hx
  · exact hstep_assembled_multiR GrR mvR (FM gR gsR) envR regionR
      (leftProgsR dt) hmvFR hmvenvR hmvregR hfreshR httR hltR (hframesR dt)
      (HmultiR dt hdt hv00 hv01 hv02 hv11 hv12 hv22)
  · exact hddF_multiR GrR 0 1 dt leftDataR regionR (canonInvM gR gsR) domLR domRR
      (by decide) httR hRvR hLR (fun q _ => regionR_fv q)
      (canonInvM_varsL gR gsR (by
        intro g' hg'
        simp only [gR, gsR, List.mem_cons, List.not_mem_nil, or_false] at hg'
        rcases hg' with rfl | rfl | rfl | rfl <;> exact hgAt _))
      (canonInvM_varsR gR gsR) hdomLR hdomRR

end RoverLadderRung3Modal
end RelCertifier
