/-
Copyright (c) 2026 relCertifier-lean contributors.
Released under Apache 2.0 license.

# T3+ — `story3_rollover_ladder_rung_b`, modal Theorem 3 (multiF, GENERATED)

Generated by `scripts/gen_multif_instance.py` from the coordinate spec: the plain
list-invariant pattern at n = 12 with 2 invariant components in the cover's
stratified-DC order, the one-way terrain chain, and climb dispatch. Existence is
Z3-free (stratified faces).

Residuals: six stratified-DC verdict packs (`VerdV l m`). Axioms: the standard
three + `z3_unsat_sound` at those leaves.
-/
import RelCertifier.Proofs.Encoding.EnvelopeChainM
import RelCertifier.Proofs.Encoding.RepoPrefixR
import RelCertifier.Proofs.Encoding.Reparam
import RelCertifier.Proofs.Encoding.WindowRF
import RelCertifier.Proofs.Encoding.CanonicalInv
import RelCertifier.Proofs.Encoding.CoverInstance
import RelCertifier.Proofs.Flow.AffineFaces
import RelCertifier.Instances.BenchIR.story3_rollover_ladder_rung_b

namespace RelCertifier
namespace Story3RolloverRungBModal

open DL DLCalTiming DLRel Parse Set

set_option maxHeartbeats 12800000

def vsV : List String := ["v", "s", "psi", "omega_psi", "theta_p", "omega_theta", "e", "r", "phi_r", "omega_phi", "z", "y"]
def dummyV : Parse.PMode := ⟨"", [], .tt, .tt, []⟩
def mLV (l : ℕ) : Parse.PMode := story3_rollover_ladder_rung_b_IR.L.modes.getD l dummyV
def mRV (q : ℕ) : Parse.PMode := story3_rollover_ladder_rung_b_IR.R.modes.getD q dummyV

abbrev mvV : Var 12 := (Side.Aux, 0)
abbrev aV : Fin 12 := (1 : Fin 12)
abbrev tgV : Var 12 := (Side.Aux, aV)

noncomputable def fLV (l : ℕ) : Fin 12 → Term (Var 12) := hostDyn vsV 12 Side.L (mLV l)
noncomputable def fRV (q : ℕ) : Fin 12 → Term (Var 12) := hostDyn vsV 12 Side.R (mRV q)
noncomputable def domLV : Formula (Var 12) := hostEvolve vsV 12 Side.L (mLV 0)
noncomputable def domRV : Formula (Var 12) := hostEvolve vsV 12 Side.R (mRV 0)
noncomputable def envV : Formula (Var 12) := Formula.and domLV domRV

def atomsOf : Parse.PForm → List Parse.PForm
  | .and x y => atomsOf x ++ atomsOf y
  | f => [f]

def invVPF : Parse.PForm :=
  (story3_rollover_ladder_rung_b_IR.invariants.getD 1 ("", Parse.PForm.tt)).2

noncomputable def gAt (i : ℕ) : Term (Var 12) :=
  ((Run.invToG vsV 12 ((atomsOf invVPF).getD i .tt)).map ITerm.toHost).getD (Term.const 0)

noncomputable def gV : Term (Var 12) := gAt 0
noncomputable def gsV : List (Term (Var 12)) := [gAt 1]

/-! ## Side-splits -/

theorem fLV_pipe (l : ℕ) (i : Fin 12) : fLV l i =
    (((some (mLV l)).bind (Run.dynOf vsV 12 Side.L)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem fRV_pipe (q : ℕ) (i : Fin 12) : fRV q i =
    (((some (mRV q)).bind (Run.dynOf vsV 12 Side.R)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem domLV_pipe : domLV =
    (((some (mLV 0)).bind (fun m => Run.lowerF vsV 12 Side.L m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl
theorem domRV_pipe : domRV =
    (((some (mRV 0)).bind (fun m => Run.lowerF vsV 12 Side.R m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl

theorem hfLV (l : ℕ) (hl : l < 3) : ∀ i, (fLV l i).fv ⊆ range Lv := fun i x hx =>
  side_eq_L_mem (field_pipeline_side (resolvesTo_L vsV) (some (mLV l))
    (by interval_cases l <;>
      simp [mLV, story3_rollover_ladder_rung_b_IR, Parse.PExpr.namesFree]) i x
    (fLV_pipe l i ▸ hx))

theorem hfRV (q : ℕ) (hq : q < 3) : ∀ i, (fRV q i).fv ⊆ range Rv := fun i x hx =>
  side_eq_R_mem (field_pipeline_side (resolvesTo_R vsV) (some (mRV q))
    (by interval_cases q <;>
      simp [mRV, story3_rollover_ladder_rung_b_IR, Parse.PExpr.namesFree]) i x
    (fRV_pipe q i ▸ hx))

theorem hdomLV : domLV.fv ⊆ range Lv := fun x hx =>
  side_eq_L_mem (form_pipeline_side (resolvesTo_L vsV) (some (mLV 0))
    (by simp [mLV, story3_rollover_ladder_rung_b_IR, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domLV_pipe ▸ hx))

theorem hdomRV : domRV.fv ⊆ range Rv := fun x hx =>
  side_eq_R_mem (form_pipeline_side (resolvesTo_R vsV) (some (mRV 0))
    (by simp [mRV, story3_rollover_ladder_rung_b_IR, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domRV_pipe ▸ hx))

theorem hgAt (i : ℕ) : (gAt i).fv ⊆ range Lv ∪ range Rv := invToG_pipeline_LR _

theorem hmvg : ∀ g' ∈ gV :: gsV, mvV ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [gV, gsV, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with rfl | rfl <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem htgg : ∀ g' ∈ gV :: gsV, tgV ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [gV, gsV, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with rfl | rfl <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem hmvFV : mvV ∉ (FM gV gsV).fv := notMem_FM_fv hmvg
theorem htgFV : tgV ∉ (FM gV gsV).fv := notMem_FM_fv htgg

theorem hmvenvV : mvV ∉ envV.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomLV h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomRV h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))
theorem htgenvV : tgV ∉ envV.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomLV h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomRV h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))

/-! ## The right graph (one-way chain) -/

noncomputable def modeV (q : ℕ) : RMode (Var 12) :=
  { sys := rightBlock (fRV q) (Term.const 1), dom := domRV, weight := 1 }

def edgeV (st tgt : ℕ) : REdge (Var 12) :=
  { src := st, tgt := tgt, guard := Formula.tt, pruned := false }

noncomputable def GrV : SearchGraph (Var 12) :=
  { modes := [modeV 0, modeV 1, modeV 2],
    edges := [edgeV 0 1, edgeV 0 0, edgeV 1 2, edgeV 1 1, edgeV 2 2] }

theorem GrV_modeAt (q : ℕ) (hq : q < 3) : GrV.modeAt q = some (modeV q) := by
  interval_cases q <;> rfl

theorem httV : ∀ q, ∀ e ∈ GrV.edgesFrom q, e.guard = Formula.tt := by
  intro q e he
  have hmem : e ∈ GrV.edges := List.mem_of_mem_filter he
  simp only [GrV, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> rfl

theorem hltV : ∀ q, ∀ e ∈ GrV.edgesFrom q, e.tgt < GrV.modes.length := by
  intro q e he
  have hmem : e ∈ GrV.edges := List.mem_of_mem_filter he
  simp only [GrV, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> norm_num [GrV, edgeV]

theorem hRvV : ∀ q m, GrV.modeAt q = some m →
    m.sys.boundSet ∪ m.sys.readVars ∪ m.dom.fv ⊆ range Rv := by
  intro q m hm
  have hqm : q < 3 ∧ m = modeV q := by
    match q with
    | 0 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrV] using hm.symm⟩
    | 1 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrV] using hm.symm⟩
    | 2 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrV] using hm.symm⟩
    | q + 3 => exact absurd hm (by simp [SearchGraph.modeAt, GrV])
  obtain ⟨hq3, rfl⟩ := hqm
  intro y hy
  rcases hy with (hy | hy) | hy
  · exact rightBlock_boundSet_sub (fRV q) (Term.const 1) hy
  · exact rightBlock_readVars_sub (fRV q) (Term.const 1) (hfRV q hq3)
      (by simp [Term.fv]) hy
  · exact hdomRV hy

theorem edgeV_mem : ∀ st tgt, edgeV st tgt ∈ GrV.edges →
    edgeV st tgt ∈ GrV.edgesFrom st :=
  fun st tgt he => List.mem_filter.mpr ⟨he, by simp [edgeV]⟩

theorem hfreshV : ∀ q m, GrV.modeAt q = some m →
    mvV ∉ (Program.ode m.sys m.dom).fv := by
  intro q m hm hmv
  exact aux_notin_range_Rv 0 (hRvV q m hm (vars_ode_sub _ _ (Or.inl hmv)))

/-! ## The left window family -/

noncomputable def leftDataV : List ((Fin 12 → Term (Var 12)) × Formula (Var 12) × ℕ) :=
  [(fLV 0, domLV, 1), (fLV 1, domLV, 1), (fLV 2, domLV, 1)]

noncomputable def leftProgsV (dt : ℝ) : List (Program (Var 12)) :=
  leftDataV.map (fun d => windowSeg (leftBlock d.1) d.2.1 tgV dt d.2.2)

theorem hLV : ∀ d ∈ leftDataV, (∀ i, (d.1 i).fv ⊆ range Lv) ∧ d.2.1.fv ⊆ range Lv := by
  intro d hd
  simp only [leftDataV, List.mem_cons, List.not_mem_nil, or_false] at hd
  rcases hd with rfl | rfl | rfl
  · exact ⟨hfLV 0 (by norm_num), hdomLV⟩
  · exact ⟨hfLV 1 (by norm_num), hdomLV⟩
  · exact ⟨hfLV 2 (by norm_num), hdomLV⟩

theorem hframesV (dt : ℝ) : ∀ P ∈ leftProgsV dt, FramesMv P mvV := by
  intro P hP
  simp only [leftProgsV, List.mem_map] at hP
  obtain ⟨d, hd, rfl⟩ := hP
  refine framesMv_window (leftBlock d.1) d.2.1 tgV dt d.2.2 mvV (by decide) ?_
  intro h
  obtain ⟨i, hi⟩ := leftBlock_bound_sub d.1 _ h
  exact aux_ne_Lv 0 i hi

/-! ## Parse pins -/

theorem hv030 : Run.parseRat "0.30" = some ((3:ℚ)/10) := by
  have h : parseQ "0.30" = some (⟨30, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hv050 : Run.parseRat "0.50" = some ((1:ℚ)/2) := by
  have h : parseQ "0.50" = some (⟨50, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hv065 : Run.parseRat "0.65" = some ((13:ℚ)/20) := by
  have h : parseQ "0.65" = some (⟨65, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hv3 : Run.parseRat "3" = some (3) := by
  have h : parseQ "3" = some (⟨3, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hvm1 : Run.parseRat "-1" = some (-1) := by
  have h : parseQ "-1" = some (⟨-1, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hv0 : Run.parseRat "0" = some (0) := by
  have h : parseQ "0" = some (⟨0, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hv1 : Run.parseRat "1" = some (1) := by
  have h : parseQ "1" = some (⟨1, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hv05 : Run.parseRat "0.5" = some ((1:ℚ)/2) := by
  have h : parseQ "0.5" = some (⟨5, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hv03 : Run.parseRat "0.3" = some ((3:ℚ)/10) := by
  have h : parseQ "0.3" = some (⟨3, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hvm05 : Run.parseRat "-0.5" = some (-(1:ℚ)/2) := by
  have h : parseQ "-0.5" = some (⟨-5, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hv06 : Run.parseRat "0.6" = some ((3:ℚ)/5) := by
  have h : parseQ "0.6" = some (⟨6, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hv015 : Run.parseRat "0.15" = some ((3:ℚ)/20) := by
  have h : parseQ "0.15" = some (⟨15, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hv00 : Run.parseRat "0.0" = some (0) := by
  have h : parseQ "0.0" = some (⟨0, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hv08 : Run.parseRat "0.8" = some ((4:ℚ)/5) := by
  have h : parseQ "0.8" = some (⟨8, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hvm10 : Run.parseRat "-1.0" = some (-1) := by
  have h : parseQ "-1.0" = some (⟨-10, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hvm152 : Run.parseRat "-1.52" = some (-(38:ℚ)/25) := by
  have h : parseQ "-1.52" = some (⟨-152, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hv152 : Run.parseRat "1.52" = some ((38:ℚ)/25) := by
  have h : parseQ "1.52" = some (⟨152, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hvm304 : Run.parseRat "-3.04" = some (-(76:ℚ)/25) := by
  have h : parseQ "-3.04" = some (⟨-304, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hv304 : Run.parseRat "3.04" = some ((76:ℚ)/25) := by
  have h : parseQ "3.04" = some (⟨304, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hv11 : Run.parseRat "1.1" = some ((11:ℚ)/10) := by
  have h : parseQ "1.1" = some (⟨11, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hv2 : Run.parseRat "2" = some (2) := by
  have h : parseQ "2" = some (⟨2, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hv025 : Run.parseRat "0.25" = some ((1:ℚ)/4) := by
  have h : parseQ "0.25" = some (⟨25, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num

theorem hvm2 : Run.parseRat "-2" = some (-2) := by
  have h : parseQ "-2" = some (⟨-2, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]

/-! ## Field and shape pins -/

noncomputable def cstV (q : ℕ) : ℝ := if q = 0 then 3/10 else if q = 1 then 1/2 else 13/20

theorem fRV0_eval (q : ℕ) (hq : q < 3) (x : State (Var 12)) :
    Term.eval (fRV q 0) x = 3 * (cstV q - x (Rv 0)) := by
  interval_cases q <;>
    simp [fRV, hostDyn, mRV, story3_rollover_ladder_rung_b_IR, vsV, Run.dynOf,
      Run.lowerE, hv030, hv050, hv065, hv3, hvm1, hv0, hv1, hv05, hv03, hvm05, hv06, hv015, hv00, hv08, hvm10, hvm152, hv152, hvm304, hv304, hv11, hv2, hv025, hvm2, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv, cstV]
theorem fRV1_eval (q : ℕ) (hq : q < 3) (x : State (Var 12)) :
    Term.eval (fRV q 1) x = x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))) := by
  interval_cases q <;>
    simp [fRV, hostDyn, mRV, story3_rollover_ladder_rung_b_IR, vsV, Run.dynOf,
      Run.lowerE, hv030, hv050, hv065, hv3, hvm1, hv0, hv1, hv05, hv03, hvm05, hv06, hv015, hv00, hv08, hvm10, hvm152, hv152, hvm304, hv304, hv11, hv2, hv025, hvm2, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRV2_eval (q : ℕ) (hq : q < 3) (x : State (Var 12)) :
    Term.eval (fRV q 2) x = -1 * x (Rv 2) := by
  interval_cases q <;>
    simp [fRV, hostDyn, mRV, story3_rollover_ladder_rung_b_IR, vsV, Run.dynOf,
      Run.lowerE, hv030, hv050, hv065, hv3, hvm1, hv0, hv1, hv05, hv03, hvm05, hv06, hv015, hv00, hv08, hvm10, hvm152, hv152, hvm304, hv304, hv11, hv2, hv025, hvm2, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRV3_eval (q : ℕ) (hq : q < 3) (x : State (Var 12)) :
    Term.eval (fRV q 3) x = 0 := by
  interval_cases q <;>
    simp [fRV, hostDyn, mRV, story3_rollover_ladder_rung_b_IR, vsV, Run.dynOf,
      Run.lowerE, hv030, hv050, hv065, hv3, hvm1, hv0, hv1, hv05, hv03, hvm05, hv06, hv015, hv00, hv08, hvm10, hvm152, hv152, hvm304, hv304, hv11, hv2, hv025, hvm2, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRV4_eval (q : ℕ) (hq : q < 3) (x : State (Var 12)) :
    Term.eval (fRV q 4) x = -1 * x (Rv 4) := by
  interval_cases q <;>
    simp [fRV, hostDyn, mRV, story3_rollover_ladder_rung_b_IR, vsV, Run.dynOf,
      Run.lowerE, hv030, hv050, hv065, hv3, hvm1, hv0, hv1, hv05, hv03, hvm05, hv06, hv015, hv00, hv08, hvm10, hvm152, hv152, hvm304, hv304, hv11, hv2, hv025, hvm2, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRV5_eval (q : ℕ) (hq : q < 3) (x : State (Var 12)) :
    Term.eval (fRV q 5) x = 0 := by
  interval_cases q <;>
    simp [fRV, hostDyn, mRV, story3_rollover_ladder_rung_b_IR, vsV, Run.dynOf,
      Run.lowerE, hv030, hv050, hv065, hv3, hvm1, hv0, hv1, hv05, hv03, hvm05, hv06, hv015, hv00, hv08, hvm10, hvm152, hv152, hvm304, hv304, hv11, hv2, hv025, hvm2, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRV6_eval (q : ℕ) (hq : q < 3) (x : State (Var 12)) :
    Term.eval (fRV q 6) x = x (Rv 7) - 2 * x (Rv 6) := by
  interval_cases q <;>
    simp [fRV, hostDyn, mRV, story3_rollover_ladder_rung_b_IR, vsV, Run.dynOf,
      Run.lowerE, hv030, hv050, hv065, hv3, hvm1, hv0, hv1, hv05, hv03, hvm05, hv06, hv015, hv00, hv08, hvm10, hvm152, hv152, hvm304, hv304, hv11, hv2, hv025, hvm2, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRV7_eval (q : ℕ) (hq : q < 3) (x : State (Var 12)) :
    Term.eval (fRV q 7) x = -2 * x (Rv 7) := by
  interval_cases q <;>
    simp [fRV, hostDyn, mRV, story3_rollover_ladder_rung_b_IR, vsV, Run.dynOf,
      Run.lowerE, hv030, hv050, hv065, hv3, hvm1, hv0, hv1, hv05, hv03, hvm05, hv06, hv015, hv00, hv08, hvm10, hvm152, hv152, hvm304, hv304, hv11, hv2, hv025, hvm2, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRV8_eval (q : ℕ) (hq : q < 3) (x : State (Var 12)) :
    Term.eval (fRV q 8) x = -1 * x (Rv 8) := by
  interval_cases q <;>
    simp [fRV, hostDyn, mRV, story3_rollover_ladder_rung_b_IR, vsV, Run.dynOf,
      Run.lowerE, hv030, hv050, hv065, hv3, hvm1, hv0, hv1, hv05, hv03, hvm05, hv06, hv015, hv00, hv08, hvm10, hvm152, hv152, hvm304, hv304, hv11, hv2, hv025, hvm2, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRV9_eval (q : ℕ) (hq : q < 3) (x : State (Var 12)) :
    Term.eval (fRV q 9) x = 0 := by
  interval_cases q <;>
    simp [fRV, hostDyn, mRV, story3_rollover_ladder_rung_b_IR, vsV, Run.dynOf,
      Run.lowerE, hv030, hv050, hv065, hv3, hvm1, hv0, hv1, hv05, hv03, hvm05, hv06, hv015, hv00, hv08, hvm10, hvm152, hv152, hvm304, hv304, hv11, hv2, hv025, hvm2, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRV10_eval (q : ℕ) (hq : q < 3) (x : State (Var 12)) :
    Term.eval (fRV q 10) x = 0 := by
  interval_cases q <;>
    simp [fRV, hostDyn, mRV, story3_rollover_ladder_rung_b_IR, vsV, Run.dynOf,
      Run.lowerE, hv030, hv050, hv065, hv3, hvm1, hv0, hv1, hv05, hv03, hvm05, hv06, hv015, hv00, hv08, hvm10, hvm152, hv152, hvm304, hv304, hv11, hv2, hv025, hvm2, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRV11_eval (q : ℕ) (hq : q < 3) (x : State (Var 12)) :
    Term.eval (fRV q 11) x = 0 := by
  interval_cases q <;>
    simp [fRV, hostDyn, mRV, story3_rollover_ladder_rung_b_IR, vsV, Run.dynOf,
      Run.lowerE, hv030, hv050, hv065, hv3, hvm1, hv0, hv1, hv05, hv03, hvm05, hv06, hv015, hv00, hv08, hvm10, hvm152, hv152, hvm304, hv304, hv11, hv2, hv025, hvm2, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]

theorem sat_domRV (x : State (Var 12)) : Formula.sat domRV x ↔
    (-(38:ℝ)/25 ≤ x (Rv 6) ∧ x (Rv 6) ≤ (38:ℝ)/25 ∧ -(1:ℝ)/2 ≤ x (Rv 9) ∧ x (Rv 9) ≤ (3:ℝ)/5 ∧ -(1:ℝ)/2 ≤ x (Rv 3) ∧ x (Rv 3) ≤ (3:ℝ)/5 ∧ -(1:ℝ)/2 ≤ x (Rv 5) ∧ x (Rv 5) ≤ (3:ℝ)/5 ∧ -(1:ℝ)/2 ≤ x (Rv 8) ∧ x (Rv 8) ≤ (3:ℝ)/20 ∧ -(1:ℝ)/2 ≤ x (Rv 2) ∧ x (Rv 2) ≤ (3:ℝ)/20 ∧ -(76:ℝ)/25 ≤ x (Rv 7) ∧ x (Rv 7) ≤ (76:ℝ)/25 ∧ 0 ≤ x (Rv 1) ∧ -(1:ℝ)/2 ≤ x (Rv 4) ∧ x (Rv 4) ≤ (3:ℝ)/20 ∧ 0 ≤ x (Rv 0) ∧ x (Rv 0) ≤ (4:ℝ)/5 ∧ -(1:ℝ) ≤ x (Rv 11) ∧ x (Rv 11) ≤ (11:ℝ)/10 ∧ -(1:ℝ) ≤ x (Rv 10) ∧ x (Rv 10) ≤ (11:ℝ)/10) := by
  simp only [domRV, hostEvolve, mRV, story3_rollover_ladder_rung_b_IR, vsV]
  simp [Run.lowerF, Run.lowerE, hvm152, hv152, hvm05, hv06, hv015, hvm304, hv304, hv00, hv08, hvm10, hv11,
    Run.resolveVar, List.findIdx?_cons, IForm.toHost, ITerm.toHost, Formula.sat,
    CompOp.interp, Term.eval, Rv]
  tauto

/-! ## Faces -/

noncomputable def faceVLo : Term (Var 12) :=
  Term.binop AOp.sub (Term.const (0)) (Term.var (Rv 0))
noncomputable def faceVHi : Term (Var 12) :=
  Term.binop AOp.sub (Term.var (Rv 0)) (Term.const ((4:ℝ)/5))
noncomputable def facePsiLo : Term (Var 12) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 2))
noncomputable def facePsiHi : Term (Var 12) :=
  Term.binop AOp.sub (Term.var (Rv 2)) (Term.const ((3:ℝ)/20))
noncomputable def faceThLo : Term (Var 12) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 4))
noncomputable def faceThHi : Term (Var 12) :=
  Term.binop AOp.sub (Term.var (Rv 4)) (Term.const ((3:ℝ)/20))
noncomputable def faceRLo : Term (Var 12) :=
  Term.binop AOp.sub (Term.const (-(76:ℝ)/25)) (Term.var (Rv 7))
noncomputable def faceRHi : Term (Var 12) :=
  Term.binop AOp.sub (Term.var (Rv 7)) (Term.const ((76:ℝ)/25))
noncomputable def facePhLo : Term (Var 12) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 8))
noncomputable def facePhHi : Term (Var 12) :=
  Term.binop AOp.sub (Term.var (Rv 8)) (Term.const ((3:ℝ)/20))
noncomputable def faceSLo : Term (Var 12) :=
  Term.binop AOp.sub (Term.const 0) (Term.var (Rv 1))
noncomputable def faceOPsLo : Term (Var 12) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 3))
noncomputable def faceOPsHi : Term (Var 12) :=
  Term.binop AOp.sub (Term.var (Rv 3)) (Term.const ((3:ℝ)/5))
noncomputable def faceOThLo : Term (Var 12) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 5))
noncomputable def faceOThHi : Term (Var 12) :=
  Term.binop AOp.sub (Term.var (Rv 5)) (Term.const ((3:ℝ)/5))
noncomputable def faceOPhLo : Term (Var 12) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 9))
noncomputable def faceOPhHi : Term (Var 12) :=
  Term.binop AOp.sub (Term.var (Rv 9)) (Term.const ((3:ℝ)/5))
noncomputable def faceZLo : Term (Var 12) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ))) (Term.var (Rv 10))
noncomputable def faceZHi : Term (Var 12) :=
  Term.binop AOp.sub (Term.var (Rv 10)) (Term.const ((11:ℝ)/10))
noncomputable def faceYLo : Term (Var 12) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ))) (Term.var (Rv 11))
noncomputable def faceYHi : Term (Var 12) :=
  Term.binop AOp.sub (Term.var (Rv 11)) (Term.const ((11:ℝ)/10))
noncomputable def faceELo : Term (Var 12) :=
  Term.binop AOp.sub (Term.const (-(38:ℝ)/25)) (Term.var (Rv 6))
noncomputable def faceEHi : Term (Var 12) :=
  Term.binop AOp.sub (Term.var (Rv 6)) (Term.const ((38:ℝ)/25))

noncomputable def faceEAuxLo : Term (Var 12) :=
  Term.binop AOp.sub (Term.const (-(4:ℝ))) (Term.var (Rv 6))
noncomputable def faceEAuxHi : Term (Var 12) :=
  Term.binop AOp.sub (Term.var (Rv 6)) (Term.const ((4:ℝ)))

noncomputable def gsSV : List (Term (Var 12)) :=
  [faceVLo, faceVHi, facePsiLo, facePsiHi, faceThLo, faceThHi, faceRLo, faceRHi,
   facePhLo, facePhHi, faceEAuxLo, faceEAuxHi]
noncomputable def gsNV : List (Term (Var 12)) :=
  [faceSLo, faceOPsLo, faceOPsHi, faceOThLo, faceOThHi, faceOPhLo, faceOPhHi, faceZLo, faceZHi, faceYLo, faceYHi]

theorem faces_fv_RV : ∀ gT' ∈ gsSV ++ gsNV, ∀ x ∈ gT'.fv, x ∈ range Rv := by
  intro gT' hgT x hx
  simp only [gsSV, gsNV, List.cons_append, List.nil_append, List.mem_cons,
    List.not_mem_nil, or_false] at hgT
  rcases hgT with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
    · simp only [faceVLo, faceVHi, facePsiLo, facePsiHi, faceThLo, faceThHi, faceRLo, faceRHi, facePhLo, facePhHi, faceEAuxLo, faceEAuxHi, faceSLo, faceOPsLo, faceOPsHi, faceOThLo, faceOThHi, faceOPhLo, faceOPhHi, faceZLo, faceZHi, faceYLo, faceYHi, faceELo, faceEHi, Term.fv,
        Set.mem_union, Set.mem_empty_iff_false, false_or, or_false,
        Set.mem_singleton_iff] at hx
      exact ⟨_, hx.symm⟩

/-! ## The frozen-left joint field -/

theorem odeField_RV (q : ℕ) (hq : q < 3) (x : State (Var 12)) :
    odeField (jointSys (fun _ => Term.const 0) (fRV q) (Term.const (1))) x
      = fun c =>
        if c = Rv 0 then 3 * (cstV q - x (Rv 0))
        else if c = Rv 1 then x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
        else if c = Rv 2 then -1 * x (Rv 2)
        else if c = Rv 4 then -1 * x (Rv 4)
        else if c = Rv 6 then x (Rv 7) - 2 * x (Rv 6)
        else if c = Rv 7 then -2 * x (Rv 7)
        else if c = Rv 8 then -1 * x (Rv 8)
        else 0 := by
  funext c
  by_cases hc : c ∈ (jointSys (fun _ => Term.const 0) (fRV q) (Term.const (1))).bound
  · rw [show odeField (jointSys (fun _ => Term.const 0) (fRV q) (Term.const (1))) x c
        = ((jointSys (fun _ => Term.const 0) (fRV q) (Term.const (1))).rhs c).eval x from by
      simp only [odeField, if_pos hc]]
    obtain ⟨p, hp, hfst⟩ : ∃ p ∈ jointSys (fun _ => Term.const 0) (fRV q) (Term.const (1)),
        p.1 = c := by simpa [ODESystem.bound, List.mem_map] using hc
    rw [← hfst, ODESystem.rhs_eq_of_mem (jointSys_wellFormed _ _ _) hp]
    rw [jointSys_split] at hp
    have hne : ∀ (a b : Fin 12), a ≠ b → (Rv a : Var 12) ≠ Rv b := by
      intro a b hab
      simp [Rv, Prod.ext_iff]
      exact fun h => hab (by exact_mod_cast h)
    rcases List.mem_append.mp hp with hp | hp
    · obtain ⟨j, -, rfl⟩ := List.mem_map.mp hp
      have hLR : ∀ k : Fin 12, (Lv j : Var 12) ≠ Rv k := by
        intro k
        simp [Lv, Rv, Prod.ext_iff]
      simp [Term.eval, hLR 0, hLR 1, hLR 2, hLR 4, hLR 6, hLR 7, hLR 8]
    · obtain ⟨j, -, rfl⟩ := List.mem_map.mp hp
      fin_cases j
      · simp [Term.eval, AOp.interp, fRV0_eval q hq]
      · simp [Term.eval, AOp.interp, fRV1_eval q hq,
          hne 1 0 (by decide)]
      · simp [Term.eval, AOp.interp, fRV2_eval q hq,
          hne 2 0 (by decide),
          hne 2 1 (by decide)]
      · simp [Term.eval, AOp.interp, fRV3_eval q hq,
          hne 3 0 (by decide),
          hne 3 1 (by decide),
          hne 3 2 (by decide),
          hne 3 4 (by decide),
          hne 3 6 (by decide),
          hne 3 7 (by decide),
          hne 3 8 (by decide)]
      · simp [Term.eval, AOp.interp, fRV4_eval q hq,
          hne 4 0 (by decide),
          hne 4 1 (by decide),
          hne 4 2 (by decide)]
      · simp [Term.eval, AOp.interp, fRV5_eval q hq,
          hne 5 0 (by decide),
          hne 5 1 (by decide),
          hne 5 2 (by decide),
          hne 5 4 (by decide),
          hne 5 6 (by decide),
          hne 5 7 (by decide),
          hne 5 8 (by decide)]
      · simp [Term.eval, AOp.interp, fRV6_eval q hq,
          hne 6 0 (by decide),
          hne 6 1 (by decide),
          hne 6 2 (by decide),
          hne 6 4 (by decide)]
      · simp [Term.eval, AOp.interp, fRV7_eval q hq,
          hne 7 0 (by decide),
          hne 7 1 (by decide),
          hne 7 2 (by decide),
          hne 7 4 (by decide),
          hne 7 6 (by decide)]
      · simp [Term.eval, AOp.interp, fRV8_eval q hq,
          hne 8 0 (by decide),
          hne 8 1 (by decide),
          hne 8 2 (by decide),
          hne 8 4 (by decide),
          hne 8 6 (by decide),
          hne 8 7 (by decide)]
      · simp [Term.eval, AOp.interp, fRV9_eval q hq,
          hne 9 0 (by decide),
          hne 9 1 (by decide),
          hne 9 2 (by decide),
          hne 9 4 (by decide),
          hne 9 6 (by decide),
          hne 9 7 (by decide),
          hne 9 8 (by decide)]
      · simp [Term.eval, AOp.interp, fRV10_eval q hq,
          hne 10 0 (by decide),
          hne 10 1 (by decide),
          hne 10 2 (by decide),
          hne 10 4 (by decide),
          hne 10 6 (by decide),
          hne 10 7 (by decide),
          hne 10 8 (by decide)]
      · simp [Term.eval, AOp.interp, fRV11_eval q hq,
          hne 11 0 (by decide),
          hne 11 1 (by decide),
          hne 11 2 (by decide),
          hne 11 4 (by decide),
          hne 11 6 (by decide),
          hne 11 7 (by decide),
          hne 11 8 (by decide)]
  · have hnotR : ∀ j : Fin 12, c ≠ Rv j := by
      intro j hceq
      refine hc ?_
      rw [hceq, jointSys_split]
      simp only [ODESystem.bound, List.map_append, List.mem_append]
      exact Or.inr (by
        simp only [rightBlock, List.map_map, List.mem_map]
        exact ⟨j, List.mem_finRange j, rfl⟩)
    simp only [odeField, if_neg hc, if_neg (hnotR 0), if_neg (hnotR 1), if_neg (hnotR 2), if_neg (hnotR 4), if_neg (hnotR 6), if_neg (hnotR 7), if_neg (hnotR 8)]

/-! ## Strict inflow -/

theorem hbndS_V (q : ℕ) (hq : q < 3) : ∀ gT' ∈ gsSV, ∀ x : State (Var 12),
    (∀ gT'' ∈ gsSV, Term.eval gT'' x ≤ 0) →
    Term.eval gT' x = 0 →
    Lie (jointSys (fun _ => Term.const 0) (fRV q) (Term.const (1)))
      (fun ω => Term.eval gT' ω) x < 0 := by
  have hne : ∀ (a b : Fin 12), a ≠ b → (Rv a : Var 12) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro gT' hgT x hsub hface
  have hr1 : -(76:ℝ)/25 ≤ x (Rv 7) := by
    have := hsub faceRLo (by simp [gsSV])
    simp only [faceRLo, Term.eval, AOp.interp] at this; linarith
  have hr2 : x (Rv 7) ≤ (76:ℝ)/25 := by
    have := hsub faceRHi (by simp [gsSV])
    simp only [faceRHi, Term.eval, AOp.interp] at this; linarith
  simp only [gsSV, List.mem_cons, List.not_mem_nil, or_false] at hgT
  rcases hgT with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · have hx : x (Rv 0) = 0 := by
      simp only [faceVLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 12) => Term.eval faceVLo ω)
        = fun y => (-1 : ℝ) * y (Rv 0) + (0) := by
      funext y; simp [faceVLo, Term.eval, AOp.interp]
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 0) (-1) (0) x,
      odeField_RV q hq]
    simp only [eq_self_iff_true, if_true, if_pos rfl, hx]
    interval_cases q <;> norm_num [cstV]
  · have hx : x (Rv 0) = (4:ℝ)/5 := by
      simp only [faceVHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 12) => Term.eval faceVHi ω)
        = fun y => (1 : ℝ) * y (Rv 0) + (-((4:ℝ)/5)) := by
      funext y; simp [faceVHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 0) 1 (-((4:ℝ)/5)) x,
      odeField_RV q hq]
    simp only [eq_self_iff_true, if_true, if_pos rfl, hx]
    interval_cases q <;> norm_num [cstV]
  · have hx : x (Rv 2) = -(1:ℝ)/2 := by
      simp only [facePsiLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 12) => Term.eval facePsiLo ω)
        = fun y => (-1 : ℝ) * y (Rv 2) + (-(1:ℝ)/2) := by
      funext y; simp [facePsiLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 2) (-1) (-(1:ℝ)/2) x,
      odeField_RV q hq]
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 2) = (3:ℝ)/20 := by
      simp only [facePsiHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 12) => Term.eval facePsiHi ω)
        = fun y => (1 : ℝ) * y (Rv 2) + (-((3:ℝ)/20)) := by
      funext y; simp [facePsiHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 2) 1 (-((3:ℝ)/20)) x,
      odeField_RV q hq]
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 4) = -(1:ℝ)/2 := by
      simp only [faceThLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 12) => Term.eval faceThLo ω)
        = fun y => (-1 : ℝ) * y (Rv 4) + (-(1:ℝ)/2) := by
      funext y; simp [faceThLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 4) (-1) (-(1:ℝ)/2) x,
      odeField_RV q hq]
    simp only [if_neg (hne 4 0 (by decide)), if_neg (hne 4 1 (by decide)), if_neg (hne 4 2 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 4) = (3:ℝ)/20 := by
      simp only [faceThHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 12) => Term.eval faceThHi ω)
        = fun y => (1 : ℝ) * y (Rv 4) + (-((3:ℝ)/20)) := by
      funext y; simp [faceThHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 4) 1 (-((3:ℝ)/20)) x,
      odeField_RV q hq]
    simp only [if_neg (hne 4 0 (by decide)), if_neg (hne 4 1 (by decide)), if_neg (hne 4 2 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 7) = -(76:ℝ)/25 := by
      simp only [faceRLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 12) => Term.eval faceRLo ω)
        = fun y => (-1 : ℝ) * y (Rv 7) + (-(76:ℝ)/25) := by
      funext y; simp [faceRLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 7) (-1) (-(76:ℝ)/25) x,
      odeField_RV q hq]
    simp only [if_neg (hne 7 0 (by decide)), if_neg (hne 7 1 (by decide)), if_neg (hne 7 2 (by decide)), if_neg (hne 7 4 (by decide)), if_neg (hne 7 6 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 7) = (76:ℝ)/25 := by
      simp only [faceRHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 12) => Term.eval faceRHi ω)
        = fun y => (1 : ℝ) * y (Rv 7) + (-((76:ℝ)/25)) := by
      funext y; simp [faceRHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 7) 1 (-((76:ℝ)/25)) x,
      odeField_RV q hq]
    simp only [if_neg (hne 7 0 (by decide)), if_neg (hne 7 1 (by decide)), if_neg (hne 7 2 (by decide)), if_neg (hne 7 4 (by decide)), if_neg (hne 7 6 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 8) = -(1:ℝ)/2 := by
      simp only [facePhLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 12) => Term.eval facePhLo ω)
        = fun y => (-1 : ℝ) * y (Rv 8) + (-(1:ℝ)/2) := by
      funext y; simp [facePhLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 8) (-1) (-(1:ℝ)/2) x,
      odeField_RV q hq]
    simp only [if_neg (hne 8 0 (by decide)), if_neg (hne 8 1 (by decide)), if_neg (hne 8 2 (by decide)), if_neg (hne 8 4 (by decide)), if_neg (hne 8 6 (by decide)), if_neg (hne 8 7 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 8) = (3:ℝ)/20 := by
      simp only [facePhHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 12) => Term.eval facePhHi ω)
        = fun y => (1 : ℝ) * y (Rv 8) + (-((3:ℝ)/20)) := by
      funext y; simp [facePhHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 8) 1 (-((3:ℝ)/20)) x,
      odeField_RV q hq]
    simp only [if_neg (hne 8 0 (by decide)), if_neg (hne 8 1 (by decide)), if_neg (hne 8 2 (by decide)), if_neg (hne 8 4 (by decide)), if_neg (hne 8 6 (by decide)), if_neg (hne 8 7 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 6) = -(4:ℝ) := by
      simp only [faceEAuxLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 12) => Term.eval faceEAuxLo ω)
        = fun y => (-1 : ℝ) * y (Rv 6) + (-(4:ℝ)) := by
      funext y; simp [faceEAuxLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 6) (-1) (-(4:ℝ)) x,
      odeField_RV q hq]
    simp only [if_neg (hne 6 0 (by decide)), if_neg (hne 6 1 (by decide)),
      if_neg (hne 6 2 (by decide)), if_neg (hne 6 4 (by decide)),
      eq_self_iff_true, if_true, if_pos rfl]
    nlinarith [hr2, hx]
  · have hx : x (Rv 6) = (4:ℝ) := by
      simp only [faceEAuxHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 12) => Term.eval faceEAuxHi ω)
        = fun y => (1 : ℝ) * y (Rv 6) + (-((4:ℝ))) := by
      funext y; simp [faceEAuxHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 6) 1 (-((4:ℝ))) x,
      odeField_RV q hq]
    simp only [if_neg (hne 6 0 (by decide)), if_neg (hne 6 1 (by decide)),
      if_neg (hne 6 2 (by decide)), if_neg (hne 6 4 (by decide)),
      eq_self_iff_true, if_true, if_pos rfl]
    nlinarith [hr1, hx]

/-! ## Non-strict faces -/

theorem hbndN_V (q : ℕ) (hq : q < 3) : ∀ i (hi : i < gsNV.length),
    ∀ x : State (Var 12),
    (∀ gT' ∈ gsSV ++ ([] : List (Term (Var 12))), Term.eval gT' x ≤ 0) →
    Lie (jointSys (fun _ => Term.const 0) (fRV q) (Term.const (1)))
      (fun ω => Term.eval gsNV[i] ω) x ≤ 0 := by
  have hne : ∀ (a b : Fin 12), a ≠ b → (Rv a : Var 12) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro i hi x hx
  have hib : i < 11 := by simpa [gsNV] using hi
  interval_cases i
  · show Lie _ (fun ω => Term.eval faceSLo ω) x ≤ 0
    have hv0 : 0 ≤ x (Rv 0) := by
      have := hx faceVLo (List.mem_append_left _ (by simp [gsSV]))
      simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
    have hfun : (fun ω : State (Var 12) => Term.eval faceSLo ω)
        = fun y => (-1 : ℝ) * y (Rv 1) + 0 := by
      funext y; simp [faceSLo, Term.eval, AOp.interp]
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 1) (-1) 0 x,
      odeField_RV q hq]
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    have hbp1 : -(1:ℝ)/2 ≤ x (Rv 2) := by
      have := hx facePsiLo (List.mem_append_left _ (by simp [gsSV]))
      simp only [facePsiLo, Term.eval, AOp.interp] at this; linarith
    have hbp2 : x (Rv 2) ≤ (3:ℝ)/20 := by
      have := hx facePsiHi (List.mem_append_left _ (by simp [gsSV]))
      simp only [facePsiHi, Term.eval, AOp.interp] at this; linarith
    have hbt1 : -(1:ℝ)/2 ≤ x (Rv 4) := by
      have := hx faceThLo (List.mem_append_left _ (by simp [gsSV]))
      simp only [faceThLo, Term.eval, AOp.interp] at this; linarith
    have hbt2 : x (Rv 4) ≤ (3:ℝ)/20 := by
      have := hx faceThHi (List.mem_append_left _ (by simp [gsSV]))
      simp only [faceThHi, Term.eval, AOp.interp] at this; linarith
    have hB : (0:ℝ) ≤ (1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)) := by
      nlinarith [hbp1, hbp2, hbt1, hbt2]
    have hmn := mul_nonneg hv0 hB
    linarith
  · show Lie _ (fun ω => Term.eval faceOPsLo ω) x ≤ 0
    have hfun : (fun ω : State (Var 12) => Term.eval faceOPsLo ω)
        = fun y => (-1 : ℝ) * y (Rv 3) + (-(1:ℝ)/2) := by
      funext y; simp [faceOPsLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 3) (-1) (-(1:ℝ)/2) x,
      odeField_RV q hq]
    simp only [if_neg (hne 3 0 (by decide)), if_neg (hne 3 1 (by decide)), if_neg (hne 3 2 (by decide)), if_neg (hne 3 4 (by decide)), if_neg (hne 3 6 (by decide)), if_neg (hne 3 7 (by decide)), if_neg (hne 3 8 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceOPsHi ω) x ≤ 0
    have hfun : (fun ω : State (Var 12) => Term.eval faceOPsHi ω)
        = fun y => (1 : ℝ) * y (Rv 3) + (-((3:ℝ)/5)) := by
      funext y; simp [faceOPsHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 3) 1 (-((3:ℝ)/5)) x,
      odeField_RV q hq]
    simp only [if_neg (hne 3 0 (by decide)), if_neg (hne 3 1 (by decide)), if_neg (hne 3 2 (by decide)), if_neg (hne 3 4 (by decide)), if_neg (hne 3 6 (by decide)), if_neg (hne 3 7 (by decide)), if_neg (hne 3 8 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceOThLo ω) x ≤ 0
    have hfun : (fun ω : State (Var 12) => Term.eval faceOThLo ω)
        = fun y => (-1 : ℝ) * y (Rv 5) + (-(1:ℝ)/2) := by
      funext y; simp [faceOThLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 5) (-1) (-(1:ℝ)/2) x,
      odeField_RV q hq]
    simp only [if_neg (hne 5 0 (by decide)), if_neg (hne 5 1 (by decide)), if_neg (hne 5 2 (by decide)), if_neg (hne 5 4 (by decide)), if_neg (hne 5 6 (by decide)), if_neg (hne 5 7 (by decide)), if_neg (hne 5 8 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceOThHi ω) x ≤ 0
    have hfun : (fun ω : State (Var 12) => Term.eval faceOThHi ω)
        = fun y => (1 : ℝ) * y (Rv 5) + (-((3:ℝ)/5)) := by
      funext y; simp [faceOThHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 5) 1 (-((3:ℝ)/5)) x,
      odeField_RV q hq]
    simp only [if_neg (hne 5 0 (by decide)), if_neg (hne 5 1 (by decide)), if_neg (hne 5 2 (by decide)), if_neg (hne 5 4 (by decide)), if_neg (hne 5 6 (by decide)), if_neg (hne 5 7 (by decide)), if_neg (hne 5 8 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceOPhLo ω) x ≤ 0
    have hfun : (fun ω : State (Var 12) => Term.eval faceOPhLo ω)
        = fun y => (-1 : ℝ) * y (Rv 9) + (-(1:ℝ)/2) := by
      funext y; simp [faceOPhLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 9) (-1) (-(1:ℝ)/2) x,
      odeField_RV q hq]
    simp only [if_neg (hne 9 0 (by decide)), if_neg (hne 9 1 (by decide)), if_neg (hne 9 2 (by decide)), if_neg (hne 9 4 (by decide)), if_neg (hne 9 6 (by decide)), if_neg (hne 9 7 (by decide)), if_neg (hne 9 8 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceOPhHi ω) x ≤ 0
    have hfun : (fun ω : State (Var 12) => Term.eval faceOPhHi ω)
        = fun y => (1 : ℝ) * y (Rv 9) + (-((3:ℝ)/5)) := by
      funext y; simp [faceOPhHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 9) 1 (-((3:ℝ)/5)) x,
      odeField_RV q hq]
    simp only [if_neg (hne 9 0 (by decide)), if_neg (hne 9 1 (by decide)), if_neg (hne 9 2 (by decide)), if_neg (hne 9 4 (by decide)), if_neg (hne 9 6 (by decide)), if_neg (hne 9 7 (by decide)), if_neg (hne 9 8 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceZLo ω) x ≤ 0
    have hfun : (fun ω : State (Var 12) => Term.eval faceZLo ω)
        = fun y => (-1 : ℝ) * y (Rv 10) + (-(1:ℝ)) := by
      funext y; simp [faceZLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 10) (-1) (-(1:ℝ)) x,
      odeField_RV q hq]
    simp only [if_neg (hne 10 0 (by decide)), if_neg (hne 10 1 (by decide)), if_neg (hne 10 2 (by decide)), if_neg (hne 10 4 (by decide)), if_neg (hne 10 6 (by decide)), if_neg (hne 10 7 (by decide)), if_neg (hne 10 8 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceZHi ω) x ≤ 0
    have hfun : (fun ω : State (Var 12) => Term.eval faceZHi ω)
        = fun y => (1 : ℝ) * y (Rv 10) + (-((11:ℝ)/10)) := by
      funext y; simp [faceZHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 10) 1 (-((11:ℝ)/10)) x,
      odeField_RV q hq]
    simp only [if_neg (hne 10 0 (by decide)), if_neg (hne 10 1 (by decide)), if_neg (hne 10 2 (by decide)), if_neg (hne 10 4 (by decide)), if_neg (hne 10 6 (by decide)), if_neg (hne 10 7 (by decide)), if_neg (hne 10 8 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceYLo ω) x ≤ 0
    have hfun : (fun ω : State (Var 12) => Term.eval faceYLo ω)
        = fun y => (-1 : ℝ) * y (Rv 11) + (-(1:ℝ)) := by
      funext y; simp [faceYLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 11) (-1) (-(1:ℝ)) x,
      odeField_RV q hq]
    simp only [if_neg (hne 11 0 (by decide)), if_neg (hne 11 1 (by decide)), if_neg (hne 11 2 (by decide)), if_neg (hne 11 4 (by decide)), if_neg (hne 11 6 (by decide)), if_neg (hne 11 7 (by decide)), if_neg (hne 11 8 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceYHi ω) x ≤ 0
    have hfun : (fun ω : State (Var 12) => Term.eval faceYHi ω)
        = fun y => (1 : ℝ) * y (Rv 11) + (-((11:ℝ)/10)) := by
      funext y; simp [faceYHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 11) 1 (-((11:ℝ)/10)) x,
      odeField_RV q hq]
    simp only [if_neg (hne 11 0 (by decide)), if_neg (hne 11 1 (by decide)), if_neg (hne 11 2 (by decide)), if_neg (hne 11 4 (by decide)), if_neg (hne 11 6 (by decide)), if_neg (hne 11 7 (by decide)), if_neg (hne 11 8 (by decide))]
    norm_num

/-! ## Lipschitz and field bound -/

theorem hLip_V (q : ℕ) (hq : q < 3) (ν : State (Var 12))
    (hν : ∀ gT' ∈ gsSV, Term.eval gT' ν ≤ 0) :
    LipschitzOnWith 60 (odeField (jointSys (fun _ => Term.const 0) (fRV q) (Term.const (1))))
      (Metric.closedBall ν 1) := by
  have hne : ∀ (a b : Fin 12), a ≠ b → (Rv a : Var 12) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  rw [lipschitzOnWith_iff_dist_le_mul]
  intro x hx y hy
  rw [Metric.mem_closedBall] at hx hy
  rw [odeField_RV q hq, odeField_RV q hq]
  have hdc : ∀ j : Fin 12, |x (Rv j) - y (Rv j)| ≤ dist x y := by
    intro j
    have h := dist_le_pi_dist x y (Rv j)
    rwa [Real.dist_eq] at h
  have hd : (0:ℝ) ≤ dist x y := dist_nonneg
  have hcoe : ((60 : NNReal) : ℝ) = 60 := rfl
  rw [hcoe]
  have hband : ∀ (w : State (Var 12)), dist w ν ≤ 1 → ∀ (j : Fin 12) (lo hi : ℝ),
      lo ≤ ν (Rv j) → ν (Rv j) ≤ hi → -2 ≤ lo → hi ≤ 2 → |w (Rv j)| ≤ 3 := by
    intro w hw j lo hi hl hh hlo1 hhi1
    have h := dist_le_pi_dist w ν (Rv j)
    rw [Real.dist_eq] at h
    have hνb : |ν (Rv j)| ≤ 2 := abs_le.mpr ⟨by linarith, by linarith⟩
    have h2 := abs_sub_abs_le_abs_sub (w (Rv j)) (ν (Rv j))
    linarith [abs_le.mp hνb, hw]
  have hνv1 : 0 ≤ ν (Rv 0) := by
    have := hν faceVLo (by simp [gsSV])
    simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
  have hνv2 : ν (Rv 0) ≤ (4:ℝ)/5 := by
    have := hν faceVHi (by simp [gsSV])
    simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
  have hνp1 : -(1:ℝ)/2 ≤ ν (Rv 2) := by
    have := hν facePsiLo (by simp [gsSV])
    simp only [facePsiLo, Term.eval, AOp.interp] at this; linarith
  have hνp2 : ν (Rv 2) ≤ (3:ℝ)/20 := by
    have := hν facePsiHi (by simp [gsSV])
    simp only [facePsiHi, Term.eval, AOp.interp] at this; linarith
  have hνt1 : -(1:ℝ)/2 ≤ ν (Rv 4) := by
    have := hν faceThLo (by simp [gsSV])
    simp only [faceThLo, Term.eval, AOp.interp] at this; linarith
  have hνt2 : ν (Rv 4) ≤ (3:ℝ)/20 := by
    have := hν faceThHi (by simp [gsSV])
    simp only [faceThHi, Term.eval, AOp.interp] at this; linarith
  have hyb0 : |y (Rv 0)| ≤ 3 := hband y hy 0 (0) ((4:ℝ)/5) hνv1 hνv2 (by norm_num) (by norm_num)
  have hxb2 : |x (Rv 2)| ≤ 3 := hband x hx 2 (-(1:ℝ)/2) ((3:ℝ)/20) hνp1 hνp2 (by norm_num) (by norm_num)
  have hyb2 : |y (Rv 2)| ≤ 3 := hband y hy 2 (-(1:ℝ)/2) ((3:ℝ)/20) hνp1 hνp2 (by norm_num) (by norm_num)
  have hxb4 : |x (Rv 4)| ≤ 3 := hband x hx 4 (-(1:ℝ)/2) ((3:ℝ)/20) hνt1 hνt2 (by norm_num) (by norm_num)
  have hyb4 : |y (Rv 4)| ≤ 3 := hband y hy 4 (-(1:ℝ)/2) ((3:ℝ)/20) hνt1 hνt2 (by norm_num) (by norm_num)
  refine dist_pi_le_iff (by positivity) |>.mpr ?_
  intro c
  by_cases hc0 : c = Rv 0
  · subst hc0
    simp only [eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |3 * (cstV q - x (Rv 0)) - 3 * (cstV q - y (Rv 0))| ≤ 3 * dist x y := by
      have hdiff : 3 * (cstV q - x (Rv 0)) - 3 * (cstV q - y (Rv 0)) = -(3 : ℝ) * (x (Rv 0) - y (Rv 0)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(3 : ℝ)| = 3 := by norm_num
      rw [habs]
      nlinarith [hdc 0]
    skip
    nlinarith [hcore, hd]
  by_cases hc1 : c = Rv 1
  · subst hc1
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
        - y (Rv 0) * ((1 - 1/2 * (y (Rv 2) * y (Rv 2))) - 3/10 * (y (Rv 4) * y (Rv 4)))|
        ≤ 27 * dist x y := by
      have hdiff : x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
          - y (Rv 0) * ((1 - 1/2 * (y (Rv 2) * y (Rv 2))) - 3/10 * (y (Rv 4) * y (Rv 4)))
          = ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
              * (x (Rv 0) - y (Rv 0))
            + y (Rv 0) * (-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
                - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4)))) := by
        ring
      rw [hdiff]
      have hBx : |(1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))| ≤ 9 := by
        have h2 : x (Rv 2) * x (Rv 2) ≤ 9 := by nlinarith [abs_le.mp hxb2]
        have h3 : x (Rv 4) * x (Rv 4) ≤ 9 := by nlinarith [abs_le.mp hxb4]
        have h2n : 0 ≤ x (Rv 2) * x (Rv 2) := mul_self_nonneg _
        have h3n : 0 ≤ x (Rv 4) * x (Rv 4) := mul_self_nonneg _
        rw [abs_le]
        constructor <;> nlinarith
      have htri : |(-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
            - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))| ≤ 6 * dist x y := by
        have hA : |(x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2))| ≤ 6 * dist x y := by
          rw [abs_mul]
          have hs : |x (Rv 2) + y (Rv 2)| ≤ 6 := by
            calc |x (Rv 2) + y (Rv 2)| ≤ |x (Rv 2)| + |y (Rv 2)| := abs_add_le _ _
              _ ≤ 6 := by linarith [abs_le.mp hxb2, abs_le.mp hyb2]
          nlinarith [hdc 2, abs_nonneg (x (Rv 2) + y (Rv 2)), abs_nonneg (x (Rv 2) - y (Rv 2))]
        have hB2 : |(x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))| ≤ 6 * dist x y := by
          rw [abs_mul]
          have hs : |x (Rv 4) + y (Rv 4)| ≤ 6 := by
            calc |x (Rv 4) + y (Rv 4)| ≤ |x (Rv 4)| + |y (Rv 4)| := abs_add_le _ _
              _ ≤ 6 := by linarith [abs_le.mp hxb4, abs_le.mp hyb4]
          nlinarith [hdc 4, abs_nonneg (x (Rv 4) + y (Rv 4)), abs_nonneg (x (Rv 4) - y (Rv 4))]
        have e1 : |(-(1/2) : ℝ) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))|
            ≤ 1/2 * (6 * dist x y) := by
          rw [abs_mul]
          have h : |(-(1/2) : ℝ)| = 1/2 := by norm_num
          rw [h]
          nlinarith [abs_nonneg ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))]
        have e2 : |((3:ℝ)/10) * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4)))|
            ≤ 3/10 * (6 * dist x y) := by
          rw [abs_mul]
          have h : |((3:ℝ)/10)| = 3/10 := by norm_num
          rw [h]
          nlinarith [abs_nonneg ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4)))]
        have hsub : |(-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
              - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))|
            ≤ |(-(1/2) : ℝ) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))|
              + |((3:ℝ)/10) * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4)))| := by
          rw [sub_eq_add_neg]
          refine (abs_add_le _ _).trans ?_
          rw [abs_neg]
        linarith
      have hfin1 : |(1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))|
          * |x (Rv 0) - y (Rv 0)| ≤ 9 * dist x y :=
        mul_le_mul hBx (hdc 0) (abs_nonneg _) (by norm_num)
      have hfin2 : |y (Rv 0)| * |(-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
            - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))|
          ≤ 3 * (6 * dist x y) :=
        mul_le_mul hyb0 htri (abs_nonneg _) (by norm_num)
      have hsplit : |((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
              * (x (Rv 0) - y (Rv 0))
            + y (Rv 0) * (-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
                - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))|
          ≤ |((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
              * (x (Rv 0) - y (Rv 0))|
            + |y (Rv 0) * (-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
                - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))| := abs_add_le _ _
      rw [abs_mul, abs_mul] at hsplit
      linarith
    skip
    nlinarith [hcore, hd]
  by_cases hc2 : c = Rv 2
  · subst hc2
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |-1 * x (Rv 2) - -1 * y (Rv 2)| ≤ 1 * dist x y := by
      have hdiff : -1 * x (Rv 2) - -1 * y (Rv 2) = -(1 : ℝ) * (x (Rv 2) - y (Rv 2)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(1 : ℝ)| = 1 := by norm_num
      rw [habs]
      nlinarith [hdc 2]
    skip
    nlinarith [hcore, hd]
  by_cases hc4 : c = Rv 4
  · subst hc4
    simp only [if_neg (hne 4 0 (by decide)), if_neg (hne 4 1 (by decide)), if_neg (hne 4 2 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |-1 * x (Rv 4) - -1 * y (Rv 4)| ≤ 1 * dist x y := by
      have hdiff : -1 * x (Rv 4) - -1 * y (Rv 4) = -(1 : ℝ) * (x (Rv 4) - y (Rv 4)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(1 : ℝ)| = 1 := by norm_num
      rw [habs]
      nlinarith [hdc 4]
    skip
    nlinarith [hcore, hd]
  by_cases hc6 : c = Rv 6
  · subst hc6
    simp only [if_neg (hne 6 0 (by decide)), if_neg (hne 6 1 (by decide)),
      if_neg (hne 6 2 (by decide)), if_neg (hne 6 4 (by decide)),
      eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |x (Rv 7) - 2 * x (Rv 6) - (y (Rv 7) - 2 * y (Rv 6))|
        ≤ 3 * dist x y := by
      have hdiff : x (Rv 7) - 2 * x (Rv 6) - (y (Rv 7) - 2 * y (Rv 6))
          = (x (Rv 7) - y (Rv 7)) - 2 * (x (Rv 6) - y (Rv 6)) := by ring
      rw [hdiff]
      have h1 := hdc 7
      have h2 := hdc 6
      have h3 : |2 * (x (Rv 6) - y (Rv 6))| ≤ 2 * dist x y := by
        rw [abs_mul]
        have : |(2:ℝ)| = 2 := by norm_num
        rw [this]
        nlinarith
      calc |(x (Rv 7) - y (Rv 7)) - 2 * (x (Rv 6) - y (Rv 6))|
          ≤ |x (Rv 7) - y (Rv 7)| + |2 * (x (Rv 6) - y (Rv 6))| := by
            rw [sub_eq_add_neg]
            refine (abs_add_le _ _).trans ?_
            rw [abs_neg]
        _ ≤ 3 * dist x y := by linarith
    nlinarith [hcore, hd]
  by_cases hc7 : c = Rv 7
  · subst hc7
    simp only [if_neg (hne 7 0 (by decide)), if_neg (hne 7 1 (by decide)),
      if_neg (hne 7 2 (by decide)), if_neg (hne 7 4 (by decide)),
      if_neg (hne 7 6 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |-2 * x (Rv 7) - -2 * y (Rv 7)| ≤ 2 * dist x y := by
      have hdiff : -2 * x (Rv 7) - -2 * y (Rv 7) = -(2 : ℝ) * (x (Rv 7) - y (Rv 7)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(2 : ℝ)| = 2 := by norm_num
      rw [habs]
      nlinarith [hdc 7]
    nlinarith [hcore, hd]
  by_cases hc8 : c = Rv 8
  · subst hc8
    simp only [if_neg (hne 8 0 (by decide)), if_neg (hne 8 1 (by decide)), if_neg (hne 8 2 (by decide)), if_neg (hne 8 4 (by decide)), if_neg (hne 8 6 (by decide)), if_neg (hne 8 7 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |-1 * x (Rv 8) - -1 * y (Rv 8)| ≤ 1 * dist x y := by
      have hdiff : -1 * x (Rv 8) - -1 * y (Rv 8) = -(1 : ℝ) * (x (Rv 8) - y (Rv 8)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(1 : ℝ)| = 1 := by norm_num
      rw [habs]
      nlinarith [hdc 8]
    skip
    nlinarith [hcore, hd]
  · simp only [if_neg hc0, if_neg hc1, if_neg hc2, if_neg hc4, if_neg hc6, if_neg hc7, if_neg hc8]
    simp [dist_nonneg]

theorem hfbnd_V (q : ℕ) (hq : q < 3) (ν : State (Var 12))
    (hν : ∀ gT' ∈ gsSV, Term.eval gT' ν ≤ 0) :
    ∀ x ∈ Metric.closedBall ν 1,
      ‖odeField (jointSys (fun _ => Term.const 0) (fRV q) (Term.const (1))) x‖
        ≤ ((60:NNReal) : ℝ) := by
  have hne : ∀ (a b : Fin 12), a ≠ b → (Rv a : Var 12) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro x hx
  rw [Metric.mem_closedBall] at hx
  have hbandf : ∀ (j : Fin 12) (lo hi : ℝ),
      lo ≤ ν (Rv j) → ν (Rv j) ≤ hi → -2 ≤ lo → hi ≤ 2 → |x (Rv j)| ≤ 3 := by
    intro j lo hi hl hh hlo1 hhi1
    have h := dist_le_pi_dist x ν (Rv j)
    rw [Real.dist_eq] at h
    have hνb : |ν (Rv j)| ≤ 2 := abs_le.mpr ⟨by linarith, by linarith⟩
    have h2 := abs_sub_abs_le_abs_sub (x (Rv j)) (ν (Rv j))
    linarith [abs_le.mp hνb, hx]
  have hxb0 : |x (Rv 0)| ≤ 3 := by
    refine hbandf 0 (0) ((4:ℝ)/5) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν faceVLo (by simp [gsSV])
      simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
    · have := hν faceVHi (by simp [gsSV])
      simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
  have hxb2 : |x (Rv 2)| ≤ 3 := by
    refine hbandf 2 (-(1:ℝ)/2) ((3:ℝ)/20) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν facePsiLo (by simp [gsSV])
      simp only [facePsiLo, Term.eval, AOp.interp] at this; linarith
    · have := hν facePsiHi (by simp [gsSV])
      simp only [facePsiHi, Term.eval, AOp.interp] at this; linarith
  have hxb4 : |x (Rv 4)| ≤ 3 := by
    refine hbandf 4 (-(1:ℝ)/2) ((3:ℝ)/20) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν faceThLo (by simp [gsSV])
      simp only [faceThLo, Term.eval, AOp.interp] at this; linarith
    · have := hν faceThHi (by simp [gsSV])
      simp only [faceThHi, Term.eval, AOp.interp] at this; linarith
  have hxb7 : |x (Rv 7)| ≤ 5 := by
    have h := dist_le_pi_dist x ν (Rv 7)
    rw [Real.dist_eq] at h
    have hl : -(76:ℝ)/25 ≤ ν (Rv 7) := by
      have := hν faceRLo (by simp [gsSV])
      simp only [faceRLo, Term.eval, AOp.interp] at this; linarith
    have hh : ν (Rv 7) ≤ (76:ℝ)/25 := by
      have := hν faceRHi (by simp [gsSV])
      simp only [faceRHi, Term.eval, AOp.interp] at this; linarith
    have hνb : |ν (Rv 7)| ≤ 4 := abs_le.mpr ⟨by linarith, by linarith⟩
    have h2 := abs_sub_abs_le_abs_sub (x (Rv 7)) (ν (Rv 7))
    linarith [abs_le.mp hνb, hx]
  have hxb6 : |x (Rv 6)| ≤ 5 := by
    have h := dist_le_pi_dist x ν (Rv 6)
    rw [Real.dist_eq] at h
    have hl : -(4:ℝ) ≤ ν (Rv 6) := by
      have := hν faceEAuxLo (by simp [gsSV])
      simp only [faceEAuxLo, Term.eval, AOp.interp] at this; linarith
    have hh : ν (Rv 6) ≤ (4:ℝ) := by
      have := hν faceEAuxHi (by simp [gsSV])
      simp only [faceEAuxHi, Term.eval, AOp.interp] at this; linarith
    have hνb : |ν (Rv 6)| ≤ 4 := abs_le.mpr ⟨by linarith, by linarith⟩
    have h2 := abs_sub_abs_le_abs_sub (x (Rv 6)) (ν (Rv 6))
    linarith [abs_le.mp hνb, hx]
  have hxb8 : |x (Rv 8)| ≤ 3 := by
    refine hbandf 8 (-(1:ℝ)/2) ((3:ℝ)/20) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν facePhLo (by simp [gsSV])
      simp only [facePhLo, Term.eval, AOp.interp] at this; linarith
    · have := hν facePhHi (by simp [gsSV])
      simp only [facePhHi, Term.eval, AOp.interp] at this; linarith
  rw [odeField_RV q hq]
  refine pi_norm_le_iff_of_nonneg (by norm_num) |>.mpr ?_
  intro c
  have hLcoe : ((60:NNReal) : ℝ) = 60 := rfl
  rw [hLcoe]
  by_cases hc0 : c = Rv 0
  · subst hc0
    simp only [eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcst : 0 ≤ cstV q ∧ cstV q ≤ 1 := by
      interval_cases q <;> norm_num [cstV]
    have hcore : |3 * (cstV q - x (Rv 0))| ≤ 12 := by
      obtain ⟨hcl, hch⟩ := hcst
      rw [abs_le]
      constructor <;> nlinarith [abs_le.mp hxb0]

    nlinarith [hcore, abs_nonneg (3 * (cstV q - x (Rv 0)))]
  by_cases hc1 : c = Rv 1
  · subst hc1
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hBx : |(1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))| ≤ 9 := by
      have h2 : x (Rv 2) * x (Rv 2) ≤ 9 := by nlinarith [abs_le.mp hxb2]
      have h3 : x (Rv 4) * x (Rv 4) ≤ 9 := by nlinarith [abs_le.mp hxb4]
      have h2n : 0 ≤ x (Rv 2) * x (Rv 2) := mul_self_nonneg _
      have h3n : 0 ≤ x (Rv 4) * x (Rv 4) := mul_self_nonneg _
      rw [abs_le]
      constructor <;> nlinarith
    have hcore : |x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))| ≤ 27 := by
      rw [abs_mul]
      nlinarith [abs_nonneg (x (Rv 0)), abs_le.mp hxb0, abs_nonneg ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))]

    nlinarith [hcore, abs_nonneg (x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))))]
  by_cases hc2 : c = Rv 2
  · subst hc2
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcore : |-1 * x (Rv 2)| ≤ 3 := by
      rw [abs_mul]
      have habs : |(-1 : ℝ)| = 1 := by norm_num
      rw [habs]
      linarith [abs_le.mp hxb2, abs_nonneg (x (Rv 2))]

    nlinarith [hcore, abs_nonneg (-1 * x (Rv 2))]
  by_cases hc4 : c = Rv 4
  · subst hc4
    simp only [if_neg (hne 4 0 (by decide)), if_neg (hne 4 1 (by decide)), if_neg (hne 4 2 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcore : |-1 * x (Rv 4)| ≤ 3 := by
      rw [abs_mul]
      have habs : |(-1 : ℝ)| = 1 := by norm_num
      rw [habs]
      linarith [abs_le.mp hxb4, abs_nonneg (x (Rv 4))]

    nlinarith [hcore, abs_nonneg (-1 * x (Rv 4))]
  by_cases hc6 : c = Rv 6
  · subst hc6
    simp only [if_neg (hne 6 0 (by decide)), if_neg (hne 6 1 (by decide)),
      if_neg (hne 6 2 (by decide)), if_neg (hne 6 4 (by decide)),
      eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcore : |x (Rv 7) - 2 * x (Rv 6)| ≤ 15 := by
      have h1 := abs_le.mp hxb7
      have h2 := abs_le.mp hxb6
      rw [abs_le]
      constructor <;> linarith
    linarith [hcore]
  by_cases hc7 : c = Rv 7
  · subst hc7
    simp only [if_neg (hne 7 0 (by decide)), if_neg (hne 7 1 (by decide)),
      if_neg (hne 7 2 (by decide)), if_neg (hne 7 4 (by decide)),
      if_neg (hne 7 6 (by decide)), eq_self_iff_true, if_true, if_pos rfl,
      Real.norm_eq_abs]
    have hcore : |(-2 : ℝ) * x (Rv 7)| ≤ 10 := by
      rw [abs_mul]
      have habs : |(-2 : ℝ)| = 2 := by norm_num
      rw [habs]
      nlinarith [abs_le.mp hxb7, abs_nonneg (x (Rv 7))]
    linarith [hcore]
  by_cases hc8 : c = Rv 8
  · subst hc8
    simp only [if_neg (hne 8 0 (by decide)), if_neg (hne 8 1 (by decide)), if_neg (hne 8 2 (by decide)), if_neg (hne 8 4 (by decide)), if_neg (hne 8 6 (by decide)), if_neg (hne 8 7 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcore : |-1 * x (Rv 8)| ≤ 3 := by
      rw [abs_mul]
      have habs : |(-1 : ℝ)| = 1 := by norm_num
      rw [habs]
      linarith [abs_le.mp hxb8, abs_nonneg (x (Rv 8))]

    nlinarith [hcore, abs_nonneg (-1 * x (Rv 8))]
  · simp only [if_neg hc0, if_neg hc1, if_neg hc2, if_neg hc4, if_neg hc6, if_neg hc7, if_neg hc8]
    norm_num

/-! ## Existence -/

theorem esV (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt) :
    ∀ σ, Formula.sat (Formula.and (FM gV gsV) envV) σ →
      HExistSegB (fLV l) (fRV m) (Term.const (1)) domLV domRV dt
        (Function.update σ tgV 0) := by
  intro σ hσ
  have hR : Formula.sat domRV σ := hσ.2.2
  rw [sat_domRV] at hR
  obtain ⟨hd6l, hd6h, hd9l, hd9h, hd3l, hd3h, hd5l, hd5h, hd8l, hd8h, hd2l, hd2h, hd7l, hd7h, hd1l, hd4l, hd4h, hd0l, hd0h, hd11l, hd11h, hd10l, hd10h⟩ := hR
  have hupd : ∀ j : Fin 12, σ (Side.R, j) = Function.update σ tgV 0 (Side.R, j) := by
    intro j
    rw [Function.update_of_ne (by simp [tgV, Prod.ext_iff])]
  have hfS : ∀ gT' ∈ gsSV, Term.eval gT' (Function.update σ tgV 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsSV, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
      · first
          | (simp only [faceVLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceVHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [facePsiLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [facePsiHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceThLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceThHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceRLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceRHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [facePhLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [facePhHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceEAuxLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceEAuxHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
  have hfN : ∀ gT' ∈ gsNV, Term.eval gT' (Function.update σ tgV 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsNV, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
      · first
          | (simp only [faceSLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceOPsLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceOPsHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceOThLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceOThHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceOPhLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceOPhHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceZLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceZHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceYLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceYHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
  refine HExistSegB_of_viability_stratA (fLV l) (fRV m) (Term.const (1))
    domLV domRV gsSV [] gsNV 0 le_rfl
    [((Rv 6 : Var 12), 2, (76:ℝ)/25, (38:ℝ)/25)]
    [((Rv 6 : Var 12), 2, -(76:ℝ)/25, -(38:ℝ)/25)]
    (jointSys_wellFormed _ _ _)
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLV l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_RV gT' (by
        rcases List.mem_append.mp hgT with h | h
        · exact List.mem_append_left _ h
        · exact absurd h (List.not_mem_nil)) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLV l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_RV gT' (List.mem_append_right _ hgT) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro p hp hb
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLV l) _ hb
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro p hp hb
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLV l) _ hb
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro p hp
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      norm_num)
    (by
      intro p hp
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      norm_num)
    (by
      intro p hp
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      norm_num)
    (by
      intro p hp
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      norm_num)
    (by
      intro gT' hgT x hsub hface
      exact hbndS_V m hm gT' hgT x
        (fun g hg => hsub g (List.mem_append_left _ hg)) hface)
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))
    (by
      intro i hi x hxs _
      exact hbndN_V m hm i hi x hxs)
    (by
      intro p hp x hxs _
      have hne : ∀ (a b : Fin 12), a ≠ b → (Rv a : Var 12) ≠ Rv b := by
        intro a b hab
        simp [Rv, Prod.ext_iff]
        exact fun h => hab (by exact_mod_cast h)
      have hr2 : x (Rv 7) ≤ (76:ℝ)/25 := by
        have := hxs faceRHi (List.mem_append_left _ (by simp [gsSV]))
        simp only [faceRHi, Term.eval, AOp.interp] at this; linarith
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      rw [odeField_RV m hm]
      simp only [if_neg (hne 6 0 (by decide)), if_neg (hne 6 1 (by decide)),
        if_neg (hne 6 2 (by decide)), if_neg (hne 6 4 (by decide)),
        eq_self_iff_true, if_true, if_pos rfl]
      show x (Rv 7) - 2 * x (Rv 6) ≤ (76:ℝ)/25 - 2 * x (Rv 6)
      linarith)
    (by
      intro p hp x hxs _
      have hne : ∀ (a b : Fin 12), a ≠ b → (Rv a : Var 12) ≠ Rv b := by
        intro a b hab
        simp [Rv, Prod.ext_iff]
        exact fun h => hab (by exact_mod_cast h)
      have hr1 : -(76:ℝ)/25 ≤ x (Rv 7) := by
        have := hxs faceRLo (List.mem_append_left _ (by simp [gsSV]))
        simp only [faceRLo, Term.eval, AOp.interp] at this; linarith
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      rw [odeField_RV m hm]
      simp only [if_neg (hne 6 0 (by decide)), if_neg (hne 6 1 (by decide)),
        if_neg (hne 6 2 (by decide)), if_neg (hne 6 4 (by decide)),
        eq_self_iff_true, if_true, if_pos rfl]
      show -(76:ℝ)/25 - 2 * x (Rv 6) ≤ x (Rv 7) - 2 * x (Rv 6)
      linarith)
    (by
      intro x hS hN hAU hAL
      have hS' : ∀ gT' ∈ gsSV, Term.eval gT' x ≤ 0 :=
        fun gT' hgT => hS gT' (List.mem_append_left _ hgT)
      have hb0l : 0 ≤ x (Rv 0) := by
        have := hS' faceVLo (by simp [gsSV])
        simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
      have hb0h : x (Rv 0) ≤ (4:ℝ)/5 := by
        have := hS' faceVHi (by simp [gsSV])
        simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
      have hb2l : -(1:ℝ)/2 ≤ x (Rv 2) := by
        have := hS' facePsiLo (by simp [gsSV])
        simp only [facePsiLo, Term.eval, AOp.interp] at this; linarith
      have hb2h : x (Rv 2) ≤ (3:ℝ)/20 := by
        have := hS' facePsiHi (by simp [gsSV])
        simp only [facePsiHi, Term.eval, AOp.interp] at this; linarith
      have hb4l : -(1:ℝ)/2 ≤ x (Rv 4) := by
        have := hS' faceThLo (by simp [gsSV])
        simp only [faceThLo, Term.eval, AOp.interp] at this; linarith
      have hb4h : x (Rv 4) ≤ (3:ℝ)/20 := by
        have := hS' faceThHi (by simp [gsSV])
        simp only [faceThHi, Term.eval, AOp.interp] at this; linarith
      have hb7l : -(76:ℝ)/25 ≤ x (Rv 7) := by
        have := hS' faceRLo (by simp [gsSV])
        simp only [faceRLo, Term.eval, AOp.interp] at this; linarith
      have hb7h : x (Rv 7) ≤ (76:ℝ)/25 := by
        have := hS' faceRHi (by simp [gsSV])
        simp only [faceRHi, Term.eval, AOp.interp] at this; linarith
      have hb8l : -(1:ℝ)/2 ≤ x (Rv 8) := by
        have := hS' facePhLo (by simp [gsSV])
        simp only [facePhLo, Term.eval, AOp.interp] at this; linarith
      have hb8h : x (Rv 8) ≤ (3:ℝ)/20 := by
        have := hS' facePhHi (by simp [gsSV])
        simp only [facePhHi, Term.eval, AOp.interp] at this; linarith
      have hb1l : 0 ≤ x (Rv 1) := by
        have := hN faceSLo (by simp [gsNV])
        simp only [faceSLo, Term.eval, AOp.interp] at this; linarith
      have hb3l : -(1:ℝ)/2 ≤ x (Rv 3) := by
        have := hN faceOPsLo (by simp [gsNV])
        simp only [faceOPsLo, Term.eval, AOp.interp] at this; linarith
      have hb3h : x (Rv 3) ≤ (3:ℝ)/5 := by
        have := hN faceOPsHi (by simp [gsNV])
        simp only [faceOPsHi, Term.eval, AOp.interp] at this; linarith
      have hb5l : -(1:ℝ)/2 ≤ x (Rv 5) := by
        have := hN faceOThLo (by simp [gsNV])
        simp only [faceOThLo, Term.eval, AOp.interp] at this; linarith
      have hb5h : x (Rv 5) ≤ (3:ℝ)/5 := by
        have := hN faceOThHi (by simp [gsNV])
        simp only [faceOThHi, Term.eval, AOp.interp] at this; linarith
      have hb9l : -(1:ℝ)/2 ≤ x (Rv 9) := by
        have := hN faceOPhLo (by simp [gsNV])
        simp only [faceOPhLo, Term.eval, AOp.interp] at this; linarith
      have hb9h : x (Rv 9) ≤ (3:ℝ)/5 := by
        have := hN faceOPhHi (by simp [gsNV])
        simp only [faceOPhHi, Term.eval, AOp.interp] at this; linarith
      have hb10l : -(1:ℝ) ≤ x (Rv 10) := by
        have := hN faceZLo (by simp [gsNV])
        simp only [faceZLo, Term.eval, AOp.interp] at this; linarith
      have hb10h : x (Rv 10) ≤ (11:ℝ)/10 := by
        have := hN faceZHi (by simp [gsNV])
        simp only [faceZHi, Term.eval, AOp.interp] at this; linarith
      have hb11l : -(1:ℝ) ≤ x (Rv 11) := by
        have := hN faceYLo (by simp [gsNV])
        simp only [faceYLo, Term.eval, AOp.interp] at this; linarith
      have hb11h : x (Rv 11) ≤ (11:ℝ)/10 := by
        have := hN faceYHi (by simp [gsNV])
        simp only [faceYHi, Term.eval, AOp.interp] at this; linarith
      have hb6h : x (Rv 6) ≤ (38:ℝ)/25 := by
        have := hAU ((Rv 6 : Var 12), 2, (76:ℝ)/25, (38:ℝ)/25) (by simp)
        simpa using this
      have hb6l : -(38:ℝ)/25 ≤ x (Rv 6) := by
        have := hAL ((Rv 6 : Var 12), 2, -(76:ℝ)/25, -(38:ℝ)/25) (by simp)
        simpa using this
      exact (sat_domRV x).mpr ⟨hb6l, hb6h, hb9l, hb9h, hb3l, hb3h, hb5l, hb5h, hb8l, hb8h, hb2l, hb2h, hb7l, hb7h, hb1l, hb4l, hb4h, hb0l, hb0h, hb11l, hb11h, hb10l, hb10h⟩)
    60 60 1 one_pos
    (fun ν0 h0 => hLip_V m hm ν0 (fun gT hgT => h0 gT (List.mem_append_left _ hgT)))
    (fun ν0 h0 => hfbnd_V m hm ν0 (fun gT hgT => h0 gT (List.mem_append_left _ hgT)))
    dt hdt
    (Function.update σ tgV 0)
    hfS
    hfN
    (by
      intro p hp
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      show Function.update σ tgV 0 (Rv 6) ≤ (38:ℝ)/25
      rw [← hupd 6]
      linarith)
    (by
      intro p hp
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hp
      subst hp
      show -(38:ℝ)/25 ≤ Function.update σ tgV 0 (Rv 6)
      rw [← hupd 6]
      linarith)
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))

/-! ## The route verdicts (stratified-DC at the cover's λ) -/

def VerdV (l m : ℕ) : Prop :=
  ∀ i (hi : i < (gV :: gsV).length),
    z3solve (flowQuery ⟨(gV :: gsV)[i], fLV l, fRV m, Term.const (1),
      strataDomHost (Formula.and domLV domRV) ((gV :: gsV).take i)⟩) = Verdict.unsat
    ∨ z3solve (flowQueryStrict ⟨(gV :: gsV)[i], fLV l, fRV m, Term.const (1),
      strataDomHost (Formula.and domLV domRV) ((gV :: gsV).take i)⟩) = Verdict.unsat
    ∨ z3solve (flowQuerySuperlevel ⟨(gV :: gsV)[i], fLV l, fRV m, Term.const (1),
      strataDomHost (Formula.and domLV domRV) ((gV :: gsV).take i)⟩) = Verdict.unsat

/-! ## The coupling at λ, and its λ = 1 transport (L7) -/

theorem coupleV (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdV l m) :
    ∀ σ', Formula.sat (Formula.and (FM gV gsV) envV) σ' → σ' tgV = 0 →
      faModalB (Equiv.refl (Var 12))
        (Program.ode (DLCalTiming.clk tgV (leftBlock (fLV l))) domLV)
        (Program.ode (rightBlock (fRV m) (Term.const (1))) domRV)
        (Formula.and (FM gV gsV) envV) tgV dt σ' := by
  intro σ' hσ' htg0
  have hupd : Function.update σ' tgV (0 : ℝ) = σ' := by
    funext x
    by_cases hx : x = tgV
    · subst hx; rw [Function.update_self]; exact htg0.symm
    · rw [Function.update_of_ne hx]
  have hAll := segPresAll_from_strata_verdicts' (fLV l) (fRV m) (Term.const (1))
    (Formula.and domLV domRV) (gV :: gsV) hv
  have hboxes : ∀ g' ∈ gV :: gsV, Formula.sat (Formula.box (Program.ode
      (leftBlock (fLV l) ++ rightBlock (fRV m) (Term.const (1)))
      (Formula.and domLV domRV)) (invLe g')) σ' := by
    intro g' hg'
    rw [sat_box]
    intro ω hω
    rw [sat_invLe]
    refine hAll σ' ?_ ω (by rw [← jointSys_split] at hω; exact hω) g' hg'
    intro g hg
    exact (sat_FM_iff gV gsV σ').mp hσ'.1 g hg
  have hbase := segment_faModalB_from_certB_list gV gsV (fLV l) (fRV m)
    (Term.const (1)) domLV domRV tgV dt
    (LR_blocks_disjoint _ _ _ (hfLV l hl) (hfRV m hm) (by simp [Term.fv]))
    (fun v hv' => Or.inl (by
      obtain ⟨i, rfl⟩ := hdomLV hv'
      exact Lv_mem_leftBlock_boundSet _ i))
    (fun v hv' => Or.inl (by
      obtain ⟨i, rfl⟩ := hdomRV hv'
      exact Rv_mem_rightBlock_boundSet _ _ i))
    (fun h => by
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLV l) _ h
      exact aux_ne_Lv aV i hi)
    (fun h => aux_notin_range_Lv aV (leftBlock_readVars_sub (fLV l) (hfLV l hl) h))
    (fun h => by
      obtain ⟨i, hi⟩ := rightBlock_bound_sub (fRV m) (Term.const (1)) _ h
      exact aux_ne_Rv aV i hi)
    (fun h => aux_notin_range_Rv aV (rightBlock_readVars_sub (fRV m)
      (Term.const (1)) (hfRV m hm) (by simp [Term.fv]) h))
    (fun h => aux_notin_range_Rv aV (rightBlock_boundSet_sub (fRV m)
      (Term.const (1)) h))
    (fun h => aux_notin_range_Lv aV (hdomLV h))
    (fun h => aux_notin_range_Rv aV (hdomRV h))
    htgg hboxes
    (esV l m hl hm dt hdt σ' hσ')
  rw [hupd] at hbase
  refine faModalB_strengthen_plant ?_ hbase
  intro ν μ hplant hsem
  have hdomLν : Formula.sat domLV ν := sem_ode_ends_in_domain hplant.1
  have hdomRμ : Formula.sat domRV μ := sem_ode_ends_in_domain hsem
  have hdomLμ : Formula.sat domLV μ := by
    rwa [(Formula.coincidence domLV (fun v hv' => sem_ode_mask hsem (by
      obtain ⟨i, rfl⟩ := hdomLV hv'
      intro hb
      obtain ⟨j, hj⟩ := rightBlock_bound_sub (fRV m) (Term.const (1)) _ hb
      exact absurd hj (by simp [Lv, Rv, Prod.ext_iff]))) :
        Formula.sat domLV μ ↔ Formula.sat domLV ν)]
  exact ⟨hdomLμ, hdomRμ⟩

theorem couple1V (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdV l m) :
    ∀ σ, Formula.sat (Formula.and (FM gV gsV) envV) σ →
      faModalB (Equiv.refl (Var 12))
        (Program.ode (DLCalTiming.clk tgV (leftBlock (fLV l))) domLV)
        (Program.ode (rightBlock (fRV m) (Term.const 1)) domRV) (Formula.and (FM gV gsV) envV) tgV dt
        (Function.update σ tgV 0) := by
  intro σ hσ
  have htgφ : tgV ∉ (Formula.and (FM gV gsV) envV).fv := by
    intro h
    rcases h with h | h
    · exact htgFV h
    · exact htgenvV h
  have hupdφ : Formula.sat (Formula.and (FM gV gsV) envV)
      (Function.update σ tgV 0) := by
    rwa [(Formula.coincidence (Formula.and (FM gV gsV) envV) (fun v hv' =>
      Function.update_of_ne (fun hc => htgφ (by rw [← hc]; exact hv')) _ _) :
        Formula.sat (Formula.and (FM gV gsV) envV) _ ↔ _)]
  refine faModalB_monoQ ?_ (coupleV l m hl hm dt hdt hv
    (Function.update σ tgV 0) hupdφ (Function.update_self _ _ _))
  intro ν μ hsem
  exact sem_rightBlock_reparam (1) 1 (by norm_num) one_pos hsem

/-! ## The window response (1 pieces at the in-place mode) -/

theorem respondV (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdV l m) (path : List ℕ) (hpath : ∀ p ∈ path, p < 3)
    {σ : State (Var 12)}
    (hσ : Formula.sat (Formula.and (FM gV gsV) envV) σ) :
    Formula.sat (faModal (Equiv.refl (Var 12))
      (windowSeg (leftBlock (fLV l)) domLV tgV dt 1)
      (bigSeq ((path.map (fun p => Program.ode (rightBlock (fRV p) (Term.const 1)) domRV))
        ++ [Program.ode (rightBlock (fRV m) (Term.const 1)) domRV]))
      (Formula.and (FM gV gsV) envV)) σ := by
  have hfa := Hmulti_windowRF_prefixed (fLV l) domLV (FM gV gsV) envV
    aV dt 1 htgFV htgenvV
    (path.map (fun p => (⟨fRV p, Term.const 1, domRV⟩ : RepoHop 12)))
    (by
      intro h hh
      obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hh
      exact ⟨hfRV p (hpath p hp), by simp [Term.fv], hdomRV⟩)
    (fun σ' hσ' => hσ'.2.1)
    (by
      intro h hh σ' hσ' htg'
      obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hh
      obtain ⟨ρ, hsem, hρσ⟩ := static_hop_existsR (fR := fRV p)
        (lam := Term.const 1) (domR := domRV) hσ'.2.2
      exact ⟨ρ, hsem, hρσ ▸ hσ'⟩)
    (hfLV l hl) hdomLV
    (List.replicate 1 (Program.ode (rightBlock (fRV m) (Term.const 1)) domRV)) (by simp) (by norm_num)
    (by
      intro Q hQ
      rw [List.eq_of_mem_replicate hQ, Program.rename_refl]
      exact hdisH_progR (⟨fRV m, Term.const 1, domRV⟩ : RepoHop 12)
        (hfRV m hm) (by simp [Term.fv]) hdomRV (hfLV l hl) hdomLV)
    (by
      intro Q hQ σ' hσ'
      rw [List.eq_of_mem_replicate hQ]
      exact couple1V l m hl hm dt hdt hv σ' hσ')
    hσ
  rw [show (path.map (fun p => (⟨fRV p, Term.const 1, domRV⟩ : RepoHop 12))).map
      (fun h => h.progR)
      = path.map (fun p => Program.ode (rightBlock (fRV p) (Term.const 1)) domRV)
    from by rw [List.map_map]; rfl] at hfa
  simpa [List.replicate] using hfa

/-! ## The step provider — every window certifies every mode, so the response
stays in place -/

theorem HmultiV (dt : ℝ) (hdt : 0 ≤ dt) (hv00 : VerdV 0 0) (hv01 : VerdV 0 1) (hv02 : VerdV 0 2) (hv10 : VerdV 1 0) (hv11 : VerdV 1 1) (hv12 : VerdV 1 2) (hv20 : VerdV 2 0) (hv21 : VerdV 2 1) (hv22 : VerdV 2 2) :
    ∀ P ∈ leftProgsV dt, ∀ (q : ℕ), q < GrV.modes.length → ∀ σ, σ mvV = (q : ℝ) →
      Formula.sat (Formula.and (FM gV gsV) envV) σ →
      ∃ segs : List (ℕ × RMode (Var 12) × REdge (Var 12)),
        (∀ s ∈ segs, GrV.modeAt s.1 = some s.2.1 ∧ s.2.2 ∈ GrV.edgesFrom s.1) ∧
        List.IsChain (fun a b => a.2.2.tgt = b.1) segs ∧
        (∀ s, segs.head? = some s → s.1 = q) ∧
        Formula.sat (faModal (Equiv.refl (Var 12)) P
          (bigSeq (segs.map (fun s => Program.ode s.2.1.sys s.2.1.dom)))
          (Formula.and (FM gV gsV) envV)) σ := by
  intro P hP q hq σ hmv hσ
  have hq3 : q < 3 := by simpa [GrV] using hq
  have hself : GrV.modeAt q = some (modeV q) ∧ edgeV q q ∈ GrV.edgesFrom q := by
    refine ⟨GrV_modeAt q hq3, edgeV_mem q q ?_⟩
    interval_cases q <;> simp [GrV]
  have hstep : ∀ (a b : ℕ × RMode (Var 12) × REdge (Var 12)) rest,
      a.2.2.tgt = b.1 → List.IsChain (fun x y => x.2.2.tgt = y.1) (b :: rest) →
      List.IsChain (fun x y => x.2.2.tgt = y.1) (a :: b :: rest) := by
    intro a b rest hab hrest
    refine hrest.cons ?_
    intro y hy
    rw [List.head?_cons, Option.mem_some_iff] at hy
    subst hy
    exact hab
  have hhead1 : ∀ (a : ℕ × RMode (Var 12) × REdge (Var 12)) rest s,
      (a :: rest : List _).head? = some s → s = a := by
    intro a rest s hs
    simpa [List.head?_cons] using hs.symm
  simp only [leftProgsV, leftDataV, List.map_cons, List.map_nil, List.mem_cons,
    List.not_mem_nil, or_false] at hP
  have halign : ∀ st tgt : ℕ, st < 3 → tgt < 3 → edgeV st tgt ∈ GrV.edges →
      GrV.modeAt st = some (modeV st) ∧ edgeV st tgt ∈ GrV.edgesFrom st :=
    fun st tgt hs ht he => ⟨GrV_modeAt st hs, edgeV_mem st tgt he⟩
  rcases hP with rfl | rfl | rfl
  all_goals interval_cases q
  · refine ⟨[(0, modeV 0, edgeV 0 0)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 0 0 (by norm_num) (by norm_num) (by simp [GrV])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondV 0 0 (by norm_num) (by norm_num) dt hdt hv00 [] (by simp) hσ
      simpa [modeV, List.replicate] using this
  · refine ⟨[(1, modeV 1, edgeV 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrV])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondV 0 1 (by norm_num) (by norm_num) dt hdt hv01 [] (by simp) hσ
      simpa [modeV, List.replicate] using this
  · refine ⟨[(2, modeV 2, edgeV 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrV])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondV 0 2 (by norm_num) (by norm_num) dt hdt hv02 [] (by simp) hσ
      simpa [modeV, List.replicate] using this
  · refine ⟨[(0, modeV 0, edgeV 0 0)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 0 0 (by norm_num) (by norm_num) (by simp [GrV])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondV 1 0 (by norm_num) (by norm_num) dt hdt hv10 [] (by simp) hσ
      simpa [modeV, List.replicate] using this
  · refine ⟨[(1, modeV 1, edgeV 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrV])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondV 1 1 (by norm_num) (by norm_num) dt hdt hv11 [] (by simp) hσ
      simpa [modeV, List.replicate] using this
  · refine ⟨[(2, modeV 2, edgeV 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrV])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondV 1 2 (by norm_num) (by norm_num) dt hdt hv12 [] (by simp) hσ
      simpa [modeV, List.replicate] using this
  · refine ⟨[(0, modeV 0, edgeV 0 0)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 0 0 (by norm_num) (by norm_num) (by simp [GrV])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondV 2 0 (by norm_num) (by norm_num) dt hdt hv20 [] (by simp) hσ
      simpa [modeV, List.replicate] using this
  · refine ⟨[(1, modeV 1, edgeV 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrV])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondV 2 1 (by norm_num) (by norm_num) dt hdt hv21 [] (by simp) hσ
      simpa [modeV, List.replicate] using this
  · refine ⟨[(2, modeV 2, edgeV 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrV])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondV 2 2 (by norm_num) (by norm_num) dt hdt hv22 [] (by simp) hσ
      simpa [modeV, List.replicate] using this

/-- **`story3_rollover_ladder_rung_b`, modal Theorem 3** (λ = 1, k = 1). -/
theorem story3_rollover_rung_b_modal (dt : ℝ) (hdt : 0 ≤ dt) (hv00 : VerdV 0 0) (hv01 : VerdV 0 1) (hv02 : VerdV 0 2) (hv10 : VerdV 1 0) (hv11 : VerdV 1 1) (hv12 : VerdV 1 2) (hv20 : VerdV 2 0) (hv21 : VerdV 2 1) (hv22 : VerdV 2 2) :
    RFormula.rvalid (theorem3Form
      (bigChoice (leftProgsV dt))
      (rightAutomatonBody GrV mvV)
      (RFormula.and (RFormula.and (canonInvM gV gsV) (envLR domLV domRV))
        (mvValidR mvV GrV.modes.length))) := by
  refine theorem3_faithful_multiF_LR GrV mvV (FM gV gsV) domLV domRV
    (leftProgsV dt) (canonInvM gV gsV) (encode_canonInvM gV gsV) ?_ ?_ ?_
  · exact hdis_multi GrV 0 1 dt leftDataV (by decide) httV hRvV hLV
  · exact hstep_assembled_multiF GrV mvV (FM gV gsV) envV (leftProgsV dt)
      hmvFV hmvenvV hfreshV httV hltV (hframesV dt)
      (HmultiV dt hdt hv00 hv01 hv02 hv10 hv11 hv12 hv20 hv21 hv22)
  · exact hddF_multiE GrV 0 1 dt leftDataV (canonInvM gV gsV) domLV domRV
      (by decide) httV hRvV hLV
      (canonInvM_varsL gV gsV (by
        intro g' hg'
        simp only [gV, gsV, List.mem_cons, List.not_mem_nil, or_false] at hg'
        rcases hg' with rfl | rfl <;> exact hgAt _))
      (canonInvM_varsR gV gsV) hdomLV hdomRV

end Story3RolloverRungBModal
end RelCertifier
