/-
Copyright (c) 2026 relCertifier-lean contributors.
Released under Apache 2.0 license.

# T3+ — `story1_attdist_rung_a_6to8`, modal Theorem 3 (multiF, GENERATED)

Generated by `scripts/gen_multif_instance.py` from the coordinate spec: the plain
list-invariant pattern at n = 8 with 2 invariant components in the cover's
stratified-DC order, the one-way terrain chain, and climb dispatch. Existence is
Z3-free (stratified faces).

Residuals: six stratified-DC verdict packs (`VerdD l m`). Axioms: the standard
three + `z3_unsat_sound` at those leaves.
-/
import RelCertifier.Proofs.Encoding.EnvelopeChainM
import RelCertifier.Proofs.Encoding.RepoPrefixR
import RelCertifier.Proofs.Encoding.Reparam
import RelCertifier.Proofs.Encoding.WindowRF
import RelCertifier.Proofs.Encoding.CanonicalInv
import RelCertifier.Proofs.Encoding.CoverInstance
import RelCertifier.Proofs.Flow.StratifiedFaces
import RelCertifier.Instances.BenchIR.story1_attdist_rung_a_6to8

namespace RelCertifier
namespace Story1AttdistRungAModal

open DL DLCalTiming DLRel Parse Set

set_option maxHeartbeats 12800000

def vsD : List String := ["v", "s", "psi", "omega_psi", "theta_p", "omega_theta", "z", "phi_r"]
def dummyD : Parse.PMode := ⟨"", [], .tt, .tt, []⟩
def mLD (l : ℕ) : Parse.PMode := story1_attdist_rung_a_6to8_IR.L.modes.getD l dummyD
def mRD (q : ℕ) : Parse.PMode := story1_attdist_rung_a_6to8_IR.R.modes.getD q dummyD

abbrev mvD : Var 8 := (Side.Aux, 0)
abbrev aD : Fin 8 := (1 : Fin 8)
abbrev tgD : Var 8 := (Side.Aux, aD)

noncomputable def fLD (l : ℕ) : Fin 8 → Term (Var 8) := hostDyn vsD 8 Side.L (mLD l)
noncomputable def fRD (q : ℕ) : Fin 8 → Term (Var 8) := hostDyn vsD 8 Side.R (mRD q)
noncomputable def domLD : Formula (Var 8) := hostEvolve vsD 8 Side.L (mLD 0)
noncomputable def domRD : Formula (Var 8) := hostEvolve vsD 8 Side.R (mRD 0)
noncomputable def envD : Formula (Var 8) := Formula.and domLD domRD

def atomsOf : Parse.PForm → List Parse.PForm
  | .and x y => atomsOf x ++ atomsOf y
  | f => [f]

def invDPF : Parse.PForm :=
  (story1_attdist_rung_a_6to8_IR.invariants.getD 1 ("", Parse.PForm.tt)).2

noncomputable def gAt (i : ℕ) : Term (Var 8) :=
  ((Run.invToG vsD 8 ((atomsOf invDPF).getD i .tt)).map ITerm.toHost).getD (Term.const 0)

noncomputable def gD : Term (Var 8) := gAt 0
noncomputable def gsD : List (Term (Var 8)) := [gAt 1]

/-! ## Side-splits -/

theorem fLD_pipe (l : ℕ) (i : Fin 8) : fLD l i =
    (((some (mLD l)).bind (Run.dynOf vsD 8 Side.L)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem fRD_pipe (q : ℕ) (i : Fin 8) : fRD q i =
    (((some (mRD q)).bind (Run.dynOf vsD 8 Side.R)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem domLD_pipe : domLD =
    (((some (mLD 0)).bind (fun m => Run.lowerF vsD 8 Side.L m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl
theorem domRD_pipe : domRD =
    (((some (mRD 0)).bind (fun m => Run.lowerF vsD 8 Side.R m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl

theorem hfLD (l : ℕ) (hl : l < 3) : ∀ i, (fLD l i).fv ⊆ range Lv := fun i x hx =>
  side_eq_L_mem (field_pipeline_side (resolvesTo_L vsD) (some (mLD l))
    (by interval_cases l <;>
      simp [mLD, story1_attdist_rung_a_6to8_IR, Parse.PExpr.namesFree]) i x
    (fLD_pipe l i ▸ hx))

theorem hfRD (q : ℕ) (hq : q < 3) : ∀ i, (fRD q i).fv ⊆ range Rv := fun i x hx =>
  side_eq_R_mem (field_pipeline_side (resolvesTo_R vsD) (some (mRD q))
    (by interval_cases q <;>
      simp [mRD, story1_attdist_rung_a_6to8_IR, Parse.PExpr.namesFree]) i x
    (fRD_pipe q i ▸ hx))

theorem hdomLD : domLD.fv ⊆ range Lv := fun x hx =>
  side_eq_L_mem (form_pipeline_side (resolvesTo_L vsD) (some (mLD 0))
    (by simp [mLD, story1_attdist_rung_a_6to8_IR, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domLD_pipe ▸ hx))

theorem hdomRD : domRD.fv ⊆ range Rv := fun x hx =>
  side_eq_R_mem (form_pipeline_side (resolvesTo_R vsD) (some (mRD 0))
    (by simp [mRD, story1_attdist_rung_a_6to8_IR, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domRD_pipe ▸ hx))

theorem hgAt (i : ℕ) : (gAt i).fv ⊆ range Lv ∪ range Rv := invToG_pipeline_LR _

theorem hmvg : ∀ g' ∈ gD :: gsD, mvD ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [gD, gsD, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with rfl | rfl <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem htgg : ∀ g' ∈ gD :: gsD, tgD ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [gD, gsD, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with rfl | rfl <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem hmvFD : mvD ∉ (FM gD gsD).fv := notMem_FM_fv hmvg
theorem htgFD : tgD ∉ (FM gD gsD).fv := notMem_FM_fv htgg

theorem hmvenvD : mvD ∉ envD.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomLD h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomRD h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))
theorem htgenvD : tgD ∉ envD.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomLD h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomRD h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))

/-! ## The right graph (one-way chain) -/

noncomputable def modeD (q : ℕ) : RMode (Var 8) :=
  { sys := rightBlock (fRD q) (Term.const 1), dom := domRD, weight := 1 }

def edgeD (st tgt : ℕ) : REdge (Var 8) :=
  { src := st, tgt := tgt, guard := Formula.tt, pruned := false }

noncomputable def GrD : SearchGraph (Var 8) :=
  { modes := [modeD 0, modeD 1, modeD 2],
    edges := [edgeD 0 1, edgeD 0 0, edgeD 1 2, edgeD 1 1, edgeD 2 2] }

theorem GrD_modeAt (q : ℕ) (hq : q < 3) : GrD.modeAt q = some (modeD q) := by
  interval_cases q <;> rfl

theorem httD : ∀ q, ∀ e ∈ GrD.edgesFrom q, e.guard = Formula.tt := by
  intro q e he
  have hmem : e ∈ GrD.edges := List.mem_of_mem_filter he
  simp only [GrD, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> rfl

theorem hltD : ∀ q, ∀ e ∈ GrD.edgesFrom q, e.tgt < GrD.modes.length := by
  intro q e he
  have hmem : e ∈ GrD.edges := List.mem_of_mem_filter he
  simp only [GrD, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> norm_num [GrD, edgeD]

theorem hRvD : ∀ q m, GrD.modeAt q = some m →
    m.sys.boundSet ∪ m.sys.readVars ∪ m.dom.fv ⊆ range Rv := by
  intro q m hm
  have hqm : q < 3 ∧ m = modeD q := by
    match q with
    | 0 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrD] using hm.symm⟩
    | 1 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrD] using hm.symm⟩
    | 2 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, GrD] using hm.symm⟩
    | q + 3 => exact absurd hm (by simp [SearchGraph.modeAt, GrD])
  obtain ⟨hq3, rfl⟩ := hqm
  intro y hy
  rcases hy with (hy | hy) | hy
  · exact rightBlock_boundSet_sub (fRD q) (Term.const 1) hy
  · exact rightBlock_readVars_sub (fRD q) (Term.const 1) (hfRD q hq3)
      (by simp [Term.fv]) hy
  · exact hdomRD hy

theorem edgeD_mem : ∀ st tgt, edgeD st tgt ∈ GrD.edges →
    edgeD st tgt ∈ GrD.edgesFrom st :=
  fun st tgt he => List.mem_filter.mpr ⟨he, by simp [edgeD]⟩

theorem hfreshD : ∀ q m, GrD.modeAt q = some m →
    mvD ∉ (Program.ode m.sys m.dom).fv := by
  intro q m hm hmv
  exact aux_notin_range_Rv 0 (hRvD q m hm (vars_ode_sub _ _ (Or.inl hmv)))

/-! ## The left window family -/

noncomputable def leftDataD : List ((Fin 8 → Term (Var 8)) × Formula (Var 8) × ℕ) :=
  [(fLD 0, domLD, 1), (fLD 1, domLD, 1), (fLD 2, domLD, 1)]

noncomputable def leftProgsD (dt : ℝ) : List (Program (Var 8)) :=
  leftDataD.map (fun d => windowSeg (leftBlock d.1) d.2.1 tgD dt d.2.2)

theorem hLD : ∀ d ∈ leftDataD, (∀ i, (d.1 i).fv ⊆ range Lv) ∧ d.2.1.fv ⊆ range Lv := by
  intro d hd
  simp only [leftDataD, List.mem_cons, List.not_mem_nil, or_false] at hd
  rcases hd with rfl | rfl | rfl
  · exact ⟨hfLD 0 (by norm_num), hdomLD⟩
  · exact ⟨hfLD 1 (by norm_num), hdomLD⟩
  · exact ⟨hfLD 2 (by norm_num), hdomLD⟩

theorem hframesD (dt : ℝ) : ∀ P ∈ leftProgsD dt, FramesMv P mvD := by
  intro P hP
  simp only [leftProgsD, List.mem_map] at hP
  obtain ⟨d, hd, rfl⟩ := hP
  refine framesMv_window (leftBlock d.1) d.2.1 tgD dt d.2.2 mvD (by decide) ?_
  intro h
  obtain ⟨i, hi⟩ := leftBlock_bound_sub d.1 _ h
  exact aux_ne_Lv 0 i hi

/-! ## Parse pins -/

theorem hd030 : Run.parseRat "0.30" = some ((3:ℚ)/10) := by
  have h : parseQ "0.30" = some (⟨30, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hd050 : Run.parseRat "0.50" = some ((1:ℚ)/2) := by
  have h : parseQ "0.50" = some (⟨50, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hd065 : Run.parseRat "0.65" = some ((13:ℚ)/20) := by
  have h : parseQ "0.65" = some (⟨65, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hd3 : Run.parseRat "3" = some (3) := by
  have h : parseQ "3" = some (⟨3, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hdm1 : Run.parseRat "-1" = some (-1) := by
  have h : parseQ "-1" = some (⟨-1, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hd0 : Run.parseRat "0" = some (0) := by
  have h : parseQ "0" = some (⟨0, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hd1 : Run.parseRat "1" = some (1) := by
  have h : parseQ "1" = some (⟨1, 1⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hd05 : Run.parseRat "0.5" = some ((1:ℚ)/2) := by
  have h : parseQ "0.5" = some (⟨5, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hd03 : Run.parseRat "0.3" = some ((3:ℚ)/10) := by
  have h : parseQ "0.3" = some (⟨3, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hdm05 : Run.parseRat "-0.5" = some (-(1:ℚ)/2) := by
  have h : parseQ "-0.5" = some (⟨-5, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hd06 : Run.parseRat "0.6" = some ((3:ℚ)/5) := by
  have h : parseQ "0.6" = some (⟨6, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hd015 : Run.parseRat "0.15" = some ((3:ℚ)/20) := by
  have h : parseQ "0.15" = some (⟨15, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hd00 : Run.parseRat "0.0" = some (0) := by
  have h : parseQ "0.0" = some (⟨0, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hd08 : Run.parseRat "0.8" = some ((4:ℚ)/5) := by
  have h : parseQ "0.8" = some (⟨8, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num
theorem hdm10 : Run.parseRat "-1.0" = some (-1) := by
  have h : parseQ "-1.0" = some (⟨-10, 10⟩ : QF) := by decide
  simp [Run.parseRat, h]
theorem hd025 : Run.parseRat "0.25" = some ((1:ℚ)/4) := by
  have h : parseQ "0.25" = some (⟨25, 100⟩ : QF) := by decide
  simp [Run.parseRat, h]; norm_num

/-! ## Field and shape pins -/

noncomputable def cstD (q : ℕ) : ℝ := if q = 0 then 3/10 else if q = 1 then 1/2 else 13/20

theorem fRD0_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRD q 0) x = 3 * (cstD q - x (Rv 0)) := by
  interval_cases q <;>
    simp [fRD, hostDyn, mRD, story1_attdist_rung_a_6to8_IR, vsD, Run.dynOf,
      Run.lowerE, hd030, hd050, hd065, hd3, hdm1, hd0, hd1, hd05, hd03, hdm05, hd06, hd015, hd00, hd08, hdm10, hd025, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv, cstD]
theorem fRD1_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRD q 1) x = x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))) := by
  interval_cases q <;>
    simp [fRD, hostDyn, mRD, story1_attdist_rung_a_6to8_IR, vsD, Run.dynOf,
      Run.lowerE, hd030, hd050, hd065, hd3, hdm1, hd0, hd1, hd05, hd03, hdm05, hd06, hd015, hd00, hd08, hdm10, hd025, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRD2_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRD q 2) x = -1 * x (Rv 2) := by
  interval_cases q <;>
    simp [fRD, hostDyn, mRD, story1_attdist_rung_a_6to8_IR, vsD, Run.dynOf,
      Run.lowerE, hd030, hd050, hd065, hd3, hdm1, hd0, hd1, hd05, hd03, hdm05, hd06, hd015, hd00, hd08, hdm10, hd025, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRD3_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRD q 3) x = 0 := by
  interval_cases q <;>
    simp [fRD, hostDyn, mRD, story1_attdist_rung_a_6to8_IR, vsD, Run.dynOf,
      Run.lowerE, hd030, hd050, hd065, hd3, hdm1, hd0, hd1, hd05, hd03, hdm05, hd06, hd015, hd00, hd08, hdm10, hd025, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRD4_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRD q 4) x = -1 * x (Rv 4) := by
  interval_cases q <;>
    simp [fRD, hostDyn, mRD, story1_attdist_rung_a_6to8_IR, vsD, Run.dynOf,
      Run.lowerE, hd030, hd050, hd065, hd3, hdm1, hd0, hd1, hd05, hd03, hdm05, hd06, hd015, hd00, hd08, hdm10, hd025, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRD5_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRD q 5) x = 0 := by
  interval_cases q <;>
    simp [fRD, hostDyn, mRD, story1_attdist_rung_a_6to8_IR, vsD, Run.dynOf,
      Run.lowerE, hd030, hd050, hd065, hd3, hdm1, hd0, hd1, hd05, hd03, hdm05, hd06, hd015, hd00, hd08, hdm10, hd025, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRD6_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRD q 6) x = -1 * x (Rv 6) := by
  interval_cases q <;>
    simp [fRD, hostDyn, mRD, story1_attdist_rung_a_6to8_IR, vsD, Run.dynOf,
      Run.lowerE, hd030, hd050, hd065, hd3, hdm1, hd0, hd1, hd05, hd03, hdm05, hd06, hd015, hd00, hd08, hdm10, hd025, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]
theorem fRD7_eval (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    Term.eval (fRD q 7) x = -1 * x (Rv 7) := by
  interval_cases q <;>
    simp [fRD, hostDyn, mRD, story1_attdist_rung_a_6to8_IR, vsD, Run.dynOf,
      Run.lowerE, hd030, hd050, hd065, hd3, hdm1, hd0, hd1, hd05, hd03, hdm05, hd06, hd015, hd00, hd08, hdm10, hd025, Run.resolveVar,
      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp, Rv]

theorem sat_domRD (x : State (Var 8)) : Formula.sat domRD x ↔
    (-(1:ℝ)/2 ≤ x (Rv 3) ∧ x (Rv 3) ≤ (3:ℝ)/5 ∧ -(1:ℝ)/2 ≤ x (Rv 5) ∧ x (Rv 5) ≤ (3:ℝ)/5 ∧ -(1:ℝ)/2 ≤ x (Rv 7) ∧ x (Rv 7) ≤ (3:ℝ)/20 ∧ -(1:ℝ)/2 ≤ x (Rv 2) ∧ x (Rv 2) ≤ (3:ℝ)/20 ∧ 0 ≤ x (Rv 1) ∧ -(1:ℝ)/2 ≤ x (Rv 4) ∧ x (Rv 4) ≤ (3:ℝ)/20 ∧ 0 ≤ x (Rv 0) ∧ x (Rv 0) ≤ (4:ℝ)/5 ∧ -(1:ℝ) ≤ x (Rv 6) ∧ x (Rv 6) ≤ (3:ℝ)/20) := by
  simp only [domRD, hostEvolve, mRD, story1_attdist_rung_a_6to8_IR, vsD]
  simp [Run.lowerF, Run.lowerE, hdm05, hd06, hd015, hd00, hd08, hdm10,
    Run.resolveVar, List.findIdx?_cons, IForm.toHost, ITerm.toHost, Formula.sat,
    CompOp.interp, Term.eval, Rv]
  tauto

/-! ## Faces -/

noncomputable def faceVLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const (0)) (Term.var (Rv 0))
noncomputable def faceVHi : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 0)) (Term.const ((4:ℝ)/5))
noncomputable def facePsiLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 2))
noncomputable def facePsiHi : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 2)) (Term.const ((3:ℝ)/20))
noncomputable def faceThLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 4))
noncomputable def faceThHi : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 4)) (Term.const ((3:ℝ)/20))
noncomputable def faceZLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ))) (Term.var (Rv 6))
noncomputable def faceZHi : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 6)) (Term.const ((3:ℝ)/20))
noncomputable def facePhLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 7))
noncomputable def facePhHi : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 7)) (Term.const ((3:ℝ)/20))
noncomputable def faceSLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const 0) (Term.var (Rv 1))
noncomputable def faceOPsLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 3))
noncomputable def faceOPsHi : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 3)) (Term.const ((3:ℝ)/5))
noncomputable def faceOThLo : Term (Var 8) :=
  Term.binop AOp.sub (Term.const (-(1:ℝ)/2)) (Term.var (Rv 5))
noncomputable def faceOThHi : Term (Var 8) :=
  Term.binop AOp.sub (Term.var (Rv 5)) (Term.const ((3:ℝ)/5))

noncomputable def gsSD : List (Term (Var 8)) :=
  [faceVLo, faceVHi, facePsiLo, facePsiHi, faceThLo, faceThHi, faceZLo, faceZHi, facePhLo, facePhHi]
noncomputable def gsND : List (Term (Var 8)) :=
  [faceSLo, faceOPsLo, faceOPsHi, faceOThLo, faceOThHi]

theorem faces_fv_RD : ∀ gT' ∈ gsSD ++ gsND, ∀ x ∈ gT'.fv, x ∈ range Rv := by
  intro gT' hgT x hx
  simp only [gsSD, gsND, List.cons_append, List.nil_append, List.mem_cons,
    List.not_mem_nil, or_false] at hgT
  rcases hgT with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
    · simp only [faceVLo, faceVHi, facePsiLo, facePsiHi, faceThLo, faceThHi, faceZLo, faceZHi, facePhLo, facePhHi, faceSLo, faceOPsLo, faceOPsHi, faceOThLo, faceOThHi, Term.fv,
        Set.mem_union, Set.mem_empty_iff_false, false_or, or_false,
        Set.mem_singleton_iff] at hx
      exact ⟨_, hx.symm⟩

/-! ## The frozen-left joint field -/

theorem odeField_RD (q : ℕ) (hq : q < 3) (x : State (Var 8)) :
    odeField (jointSys (fun _ => Term.const 0) (fRD q) (Term.const (1))) x
      = fun c =>
        if c = Rv 0 then 3 * (cstD q - x (Rv 0))
        else if c = Rv 1 then x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
        else if c = Rv 2 then -1 * x (Rv 2)
        else if c = Rv 4 then -1 * x (Rv 4)
        else if c = Rv 6 then -1 * x (Rv 6)
        else if c = Rv 7 then -1 * x (Rv 7)
        else 0 := by
  funext c
  by_cases hc : c ∈ (jointSys (fun _ => Term.const 0) (fRD q) (Term.const (1))).bound
  · rw [show odeField (jointSys (fun _ => Term.const 0) (fRD q) (Term.const (1))) x c
        = ((jointSys (fun _ => Term.const 0) (fRD q) (Term.const (1))).rhs c).eval x from by
      simp only [odeField, if_pos hc]]
    obtain ⟨p, hp, hfst⟩ : ∃ p ∈ jointSys (fun _ => Term.const 0) (fRD q) (Term.const (1)),
        p.1 = c := by simpa [ODESystem.bound, List.mem_map] using hc
    rw [← hfst, ODESystem.rhs_eq_of_mem (jointSys_wellFormed _ _ _) hp]
    rw [jointSys_split] at hp
    have hne : ∀ (a b : Fin 8), a ≠ b → (Rv a : Var 8) ≠ Rv b := by
      intro a b hab
      simp [Rv, Prod.ext_iff]
      exact fun h => hab (by exact_mod_cast h)
    rcases List.mem_append.mp hp with hp | hp
    · obtain ⟨j, -, rfl⟩ := List.mem_map.mp hp
      have hLR : ∀ k : Fin 8, (Lv j : Var 8) ≠ Rv k := by
        intro k
        simp [Lv, Rv, Prod.ext_iff]
      simp [Term.eval, hLR 0, hLR 1, hLR 2, hLR 4, hLR 6, hLR 7]
    · obtain ⟨j, -, rfl⟩ := List.mem_map.mp hp
      fin_cases j
      · simp [Term.eval, AOp.interp, fRD0_eval q hq]
      · simp [Term.eval, AOp.interp, fRD1_eval q hq,
          hne 1 0 (by decide)]
      · simp [Term.eval, AOp.interp, fRD2_eval q hq,
          hne 2 0 (by decide),
          hne 2 1 (by decide)]
      · simp [Term.eval, AOp.interp, fRD3_eval q hq,
          hne 3 0 (by decide),
          hne 3 1 (by decide),
          hne 3 2 (by decide),
          hne 3 4 (by decide),
          hne 3 6 (by decide),
          hne 3 7 (by decide)]
      · simp [Term.eval, AOp.interp, fRD4_eval q hq,
          hne 4 0 (by decide),
          hne 4 1 (by decide),
          hne 4 2 (by decide)]
      · simp [Term.eval, AOp.interp, fRD5_eval q hq,
          hne 5 0 (by decide),
          hne 5 1 (by decide),
          hne 5 2 (by decide),
          hne 5 4 (by decide),
          hne 5 6 (by decide),
          hne 5 7 (by decide)]
      · simp [Term.eval, AOp.interp, fRD6_eval q hq,
          hne 6 0 (by decide),
          hne 6 1 (by decide),
          hne 6 2 (by decide),
          hne 6 4 (by decide)]
      · simp [Term.eval, AOp.interp, fRD7_eval q hq,
          hne 7 0 (by decide),
          hne 7 1 (by decide),
          hne 7 2 (by decide),
          hne 7 4 (by decide),
          hne 7 6 (by decide)]
  · have hnotR : ∀ j : Fin 8, c ≠ Rv j := by
      intro j hceq
      refine hc ?_
      rw [hceq, jointSys_split]
      simp only [ODESystem.bound, List.map_append, List.mem_append]
      exact Or.inr (by
        simp only [rightBlock, List.map_map, List.mem_map]
        exact ⟨j, List.mem_finRange j, rfl⟩)
    simp only [odeField, if_neg hc, if_neg (hnotR 0), if_neg (hnotR 1), if_neg (hnotR 2), if_neg (hnotR 4), if_neg (hnotR 6), if_neg (hnotR 7)]

/-! ## Strict inflow -/

theorem hbndS_D (q : ℕ) (hq : q < 3) : ∀ gT' ∈ gsSD, ∀ x : State (Var 8),
    Term.eval gT' x = 0 →
    Lie (jointSys (fun _ => Term.const 0) (fRD q) (Term.const (1)))
      (fun ω => Term.eval gT' ω) x < 0 := by
  have hne : ∀ (a b : Fin 8), a ≠ b → (Rv a : Var 8) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro gT' hgT x hface
  simp only [gsSD, List.mem_cons, List.not_mem_nil, or_false] at hgT
  rcases hgT with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · have hx : x (Rv 0) = 0 := by
      simp only [faceVLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval faceVLo ω)
        = fun y => (-1 : ℝ) * y (Rv 0) + (0) := by
      funext y; simp [faceVLo, Term.eval, AOp.interp]
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 0) (-1) (0) x,
      odeField_RD q hq]
    simp only [eq_self_iff_true, if_true, if_pos rfl, hx]
    interval_cases q <;> norm_num [cstD]
  · have hx : x (Rv 0) = (4:ℝ)/5 := by
      simp only [faceVHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval faceVHi ω)
        = fun y => (1 : ℝ) * y (Rv 0) + (-((4:ℝ)/5)) := by
      funext y; simp [faceVHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 0) 1 (-((4:ℝ)/5)) x,
      odeField_RD q hq]
    simp only [eq_self_iff_true, if_true, if_pos rfl, hx]
    interval_cases q <;> norm_num [cstD]
  · have hx : x (Rv 2) = -(1:ℝ)/2 := by
      simp only [facePsiLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval facePsiLo ω)
        = fun y => (-1 : ℝ) * y (Rv 2) + (-(1:ℝ)/2) := by
      funext y; simp [facePsiLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 2) (-1) (-(1:ℝ)/2) x,
      odeField_RD q hq]
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 2) = (3:ℝ)/20 := by
      simp only [facePsiHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval facePsiHi ω)
        = fun y => (1 : ℝ) * y (Rv 2) + (-((3:ℝ)/20)) := by
      funext y; simp [facePsiHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 2) 1 (-((3:ℝ)/20)) x,
      odeField_RD q hq]
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 4) = -(1:ℝ)/2 := by
      simp only [faceThLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval faceThLo ω)
        = fun y => (-1 : ℝ) * y (Rv 4) + (-(1:ℝ)/2) := by
      funext y; simp [faceThLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 4) (-1) (-(1:ℝ)/2) x,
      odeField_RD q hq]
    simp only [if_neg (hne 4 0 (by decide)), if_neg (hne 4 1 (by decide)), if_neg (hne 4 2 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 4) = (3:ℝ)/20 := by
      simp only [faceThHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval faceThHi ω)
        = fun y => (1 : ℝ) * y (Rv 4) + (-((3:ℝ)/20)) := by
      funext y; simp [faceThHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 4) 1 (-((3:ℝ)/20)) x,
      odeField_RD q hq]
    simp only [if_neg (hne 4 0 (by decide)), if_neg (hne 4 1 (by decide)), if_neg (hne 4 2 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 6) = -(1:ℝ) := by
      simp only [faceZLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval faceZLo ω)
        = fun y => (-1 : ℝ) * y (Rv 6) + (-(1:ℝ)) := by
      funext y; simp [faceZLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 6) (-1) (-(1:ℝ)) x,
      odeField_RD q hq]
    simp only [if_neg (hne 6 0 (by decide)), if_neg (hne 6 1 (by decide)), if_neg (hne 6 2 (by decide)), if_neg (hne 6 4 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 6) = (3:ℝ)/20 := by
      simp only [faceZHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval faceZHi ω)
        = fun y => (1 : ℝ) * y (Rv 6) + (-((3:ℝ)/20)) := by
      funext y; simp [faceZHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 6) 1 (-((3:ℝ)/20)) x,
      odeField_RD q hq]
    simp only [if_neg (hne 6 0 (by decide)), if_neg (hne 6 1 (by decide)), if_neg (hne 6 2 (by decide)), if_neg (hne 6 4 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 7) = -(1:ℝ)/2 := by
      simp only [facePhLo, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval facePhLo ω)
        = fun y => (-1 : ℝ) * y (Rv 7) + (-(1:ℝ)/2) := by
      funext y; simp [facePhLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 7) (-1) (-(1:ℝ)/2) x,
      odeField_RD q hq]
    simp only [if_neg (hne 7 0 (by decide)), if_neg (hne 7 1 (by decide)), if_neg (hne 7 2 (by decide)), if_neg (hne 7 4 (by decide)), if_neg (hne 7 6 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num
  · have hx : x (Rv 7) = (3:ℝ)/20 := by
      simp only [facePhHi, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval facePhHi ω)
        = fun y => (1 : ℝ) * y (Rv 7) + (-((3:ℝ)/20)) := by
      funext y; simp [facePhHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 7) 1 (-((3:ℝ)/20)) x,
      odeField_RD q hq]
    simp only [if_neg (hne 7 0 (by decide)), if_neg (hne 7 1 (by decide)), if_neg (hne 7 2 (by decide)), if_neg (hne 7 4 (by decide)), if_neg (hne 7 6 (by decide)), eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num

/-! ## Non-strict faces -/

theorem hbndN_D (q : ℕ) (hq : q < 3) : ∀ i (hi : i < gsND.length),
    ∀ x : State (Var 8),
    (∀ gT' ∈ gsSD ++ ([] : List (Term (Var 8))), Term.eval gT' x ≤ 0) →
    Lie (jointSys (fun _ => Term.const 0) (fRD q) (Term.const (1)))
      (fun ω => Term.eval gsND[i] ω) x ≤ 0 := by
  have hne : ∀ (a b : Fin 8), a ≠ b → (Rv a : Var 8) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro i hi x hx
  have hib : i < 5 := by simpa [gsND] using hi
  interval_cases i
  · show Lie _ (fun ω => Term.eval faceSLo ω) x ≤ 0
    have hv0 : 0 ≤ x (Rv 0) := by
      have := hx faceVLo (List.mem_append_left _ (by simp [gsSD]))
      simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
    have hfun : (fun ω : State (Var 8) => Term.eval faceSLo ω)
        = fun y => (-1 : ℝ) * y (Rv 1) + 0 := by
      funext y; simp [faceSLo, Term.eval, AOp.interp]
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 1) (-1) 0 x,
      odeField_RD q hq]
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    have hbp1 : -(1:ℝ)/2 ≤ x (Rv 2) := by
      have := hx facePsiLo (List.mem_append_left _ (by simp [gsSD]))
      simp only [facePsiLo, Term.eval, AOp.interp] at this; linarith
    have hbp2 : x (Rv 2) ≤ (3:ℝ)/20 := by
      have := hx facePsiHi (List.mem_append_left _ (by simp [gsSD]))
      simp only [facePsiHi, Term.eval, AOp.interp] at this; linarith
    have hbt1 : -(1:ℝ)/2 ≤ x (Rv 4) := by
      have := hx faceThLo (List.mem_append_left _ (by simp [gsSD]))
      simp only [faceThLo, Term.eval, AOp.interp] at this; linarith
    have hbt2 : x (Rv 4) ≤ (3:ℝ)/20 := by
      have := hx faceThHi (List.mem_append_left _ (by simp [gsSD]))
      simp only [faceThHi, Term.eval, AOp.interp] at this; linarith
    have hB : (0:ℝ) ≤ (1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)) := by
      nlinarith [hbp1, hbp2, hbt1, hbt2]
    have hmn := mul_nonneg hv0 hB
    linarith
  · show Lie _ (fun ω => Term.eval faceOPsLo ω) x ≤ 0
    have hfun : (fun ω : State (Var 8) => Term.eval faceOPsLo ω)
        = fun y => (-1 : ℝ) * y (Rv 3) + (-(1:ℝ)/2) := by
      funext y; simp [faceOPsLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 3) (-1) (-(1:ℝ)/2) x,
      odeField_RD q hq]
    simp only [if_neg (hne 3 0 (by decide)), if_neg (hne 3 1 (by decide)), if_neg (hne 3 2 (by decide)), if_neg (hne 3 4 (by decide)), if_neg (hne 3 6 (by decide)), if_neg (hne 3 7 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceOPsHi ω) x ≤ 0
    have hfun : (fun ω : State (Var 8) => Term.eval faceOPsHi ω)
        = fun y => (1 : ℝ) * y (Rv 3) + (-((3:ℝ)/5)) := by
      funext y; simp [faceOPsHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 3) 1 (-((3:ℝ)/5)) x,
      odeField_RD q hq]
    simp only [if_neg (hne 3 0 (by decide)), if_neg (hne 3 1 (by decide)), if_neg (hne 3 2 (by decide)), if_neg (hne 3 4 (by decide)), if_neg (hne 3 6 (by decide)), if_neg (hne 3 7 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceOThLo ω) x ≤ 0
    have hfun : (fun ω : State (Var 8) => Term.eval faceOThLo ω)
        = fun y => (-1 : ℝ) * y (Rv 5) + (-(1:ℝ)/2) := by
      funext y; simp [faceOThLo, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 5) (-1) (-(1:ℝ)/2) x,
      odeField_RD q hq]
    simp only [if_neg (hne 5 0 (by decide)), if_neg (hne 5 1 (by decide)), if_neg (hne 5 2 (by decide)), if_neg (hne 5 4 (by decide)), if_neg (hne 5 6 (by decide)), if_neg (hne 5 7 (by decide))]
    norm_num
  · show Lie _ (fun ω => Term.eval faceOThHi ω) x ≤ 0
    have hfun : (fun ω : State (Var 8) => Term.eval faceOThHi ω)
        = fun y => (1 : ℝ) * y (Rv 5) + (-((3:ℝ)/5)) := by
      funext y; simp [faceOThHi, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv 5) 1 (-((3:ℝ)/5)) x,
      odeField_RD q hq]
    simp only [if_neg (hne 5 0 (by decide)), if_neg (hne 5 1 (by decide)), if_neg (hne 5 2 (by decide)), if_neg (hne 5 4 (by decide)), if_neg (hne 5 6 (by decide)), if_neg (hne 5 7 (by decide))]
    norm_num

/-! ## Lipschitz and field bound -/

theorem hLip_D (q : ℕ) (hq : q < 3) (ν : State (Var 8))
    (hν : ∀ gT' ∈ gsSD, Term.eval gT' ν ≤ 0) :
    LipschitzOnWith 60 (odeField (jointSys (fun _ => Term.const 0) (fRD q) (Term.const (1))))
      (Metric.closedBall ν 1) := by
  have hne : ∀ (a b : Fin 8), a ≠ b → (Rv a : Var 8) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  rw [lipschitzOnWith_iff_dist_le_mul]
  intro x hx y hy
  rw [Metric.mem_closedBall] at hx hy
  rw [odeField_RD q hq, odeField_RD q hq]
  have hdc : ∀ j : Fin 8, |x (Rv j) - y (Rv j)| ≤ dist x y := by
    intro j
    have h := dist_le_pi_dist x y (Rv j)
    rwa [Real.dist_eq] at h
  have hd : (0:ℝ) ≤ dist x y := dist_nonneg
  have hcoe : ((60 : NNReal) : ℝ) = 60 := rfl
  rw [hcoe]
  have hband : ∀ (w : State (Var 8)), dist w ν ≤ 1 → ∀ (j : Fin 8) (lo hi : ℝ),
      lo ≤ ν (Rv j) → ν (Rv j) ≤ hi → -2 ≤ lo → hi ≤ 2 → |w (Rv j)| ≤ 3 := by
    intro w hw j lo hi hl hh hlo1 hhi1
    have h := dist_le_pi_dist w ν (Rv j)
    rw [Real.dist_eq] at h
    have hνb : |ν (Rv j)| ≤ 2 := abs_le.mpr ⟨by linarith, by linarith⟩
    have h2 := abs_sub_abs_le_abs_sub (w (Rv j)) (ν (Rv j))
    linarith [abs_le.mp hνb, hw]
  have hνv1 : 0 ≤ ν (Rv 0) := by
    have := hν faceVLo (by simp [gsSD])
    simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
  have hνv2 : ν (Rv 0) ≤ (4:ℝ)/5 := by
    have := hν faceVHi (by simp [gsSD])
    simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
  have hνp1 : -(1:ℝ)/2 ≤ ν (Rv 2) := by
    have := hν facePsiLo (by simp [gsSD])
    simp only [facePsiLo, Term.eval, AOp.interp] at this; linarith
  have hνp2 : ν (Rv 2) ≤ (3:ℝ)/20 := by
    have := hν facePsiHi (by simp [gsSD])
    simp only [facePsiHi, Term.eval, AOp.interp] at this; linarith
  have hνt1 : -(1:ℝ)/2 ≤ ν (Rv 4) := by
    have := hν faceThLo (by simp [gsSD])
    simp only [faceThLo, Term.eval, AOp.interp] at this; linarith
  have hνt2 : ν (Rv 4) ≤ (3:ℝ)/20 := by
    have := hν faceThHi (by simp [gsSD])
    simp only [faceThHi, Term.eval, AOp.interp] at this; linarith
  have hyb0 : |y (Rv 0)| ≤ 3 := hband y hy 0 (0) ((4:ℝ)/5) hνv1 hνv2 (by norm_num) (by norm_num)
  have hxb2 : |x (Rv 2)| ≤ 3 := hband x hx 2 (-(1:ℝ)/2) ((3:ℝ)/20) hνp1 hνp2 (by norm_num) (by norm_num)
  have hyb2 : |y (Rv 2)| ≤ 3 := hband y hy 2 (-(1:ℝ)/2) ((3:ℝ)/20) hνp1 hνp2 (by norm_num) (by norm_num)
  have hxb4 : |x (Rv 4)| ≤ 3 := hband x hx 4 (-(1:ℝ)/2) ((3:ℝ)/20) hνt1 hνt2 (by norm_num) (by norm_num)
  have hyb4 : |y (Rv 4)| ≤ 3 := hband y hy 4 (-(1:ℝ)/2) ((3:ℝ)/20) hνt1 hνt2 (by norm_num) (by norm_num)
  refine dist_pi_le_iff (by positivity) |>.mpr ?_
  intro c
  by_cases hc0 : c = Rv 0
  · subst hc0
    simp only [eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |3 * (cstD q - x (Rv 0)) - 3 * (cstD q - y (Rv 0))| ≤ 3 * dist x y := by
      have hdiff : 3 * (cstD q - x (Rv 0)) - 3 * (cstD q - y (Rv 0)) = -(3 : ℝ) * (x (Rv 0) - y (Rv 0)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(3 : ℝ)| = 3 := by norm_num
      rw [habs]
      nlinarith [hdc 0]
    skip
    nlinarith [hcore, hd]
  by_cases hc1 : c = Rv 1
  · subst hc1
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
        - y (Rv 0) * ((1 - 1/2 * (y (Rv 2) * y (Rv 2))) - 3/10 * (y (Rv 4) * y (Rv 4)))|
        ≤ 27 * dist x y := by
      have hdiff : x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
          - y (Rv 0) * ((1 - 1/2 * (y (Rv 2) * y (Rv 2))) - 3/10 * (y (Rv 4) * y (Rv 4)))
          = ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
              * (x (Rv 0) - y (Rv 0))
            + y (Rv 0) * (-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
                - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4)))) := by
        ring
      rw [hdiff]
      have hBx : |(1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))| ≤ 9 := by
        have h2 : x (Rv 2) * x (Rv 2) ≤ 9 := by nlinarith [abs_le.mp hxb2]
        have h3 : x (Rv 4) * x (Rv 4) ≤ 9 := by nlinarith [abs_le.mp hxb4]
        have h2n : 0 ≤ x (Rv 2) * x (Rv 2) := mul_self_nonneg _
        have h3n : 0 ≤ x (Rv 4) * x (Rv 4) := mul_self_nonneg _
        rw [abs_le]
        constructor <;> nlinarith
      have htri : |(-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
            - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))| ≤ 6 * dist x y := by
        have hA : |(x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2))| ≤ 6 * dist x y := by
          rw [abs_mul]
          have hs : |x (Rv 2) + y (Rv 2)| ≤ 6 := by
            calc |x (Rv 2) + y (Rv 2)| ≤ |x (Rv 2)| + |y (Rv 2)| := abs_add_le _ _
              _ ≤ 6 := by linarith [abs_le.mp hxb2, abs_le.mp hyb2]
          nlinarith [hdc 2, abs_nonneg (x (Rv 2) + y (Rv 2)), abs_nonneg (x (Rv 2) - y (Rv 2))]
        have hB2 : |(x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))| ≤ 6 * dist x y := by
          rw [abs_mul]
          have hs : |x (Rv 4) + y (Rv 4)| ≤ 6 := by
            calc |x (Rv 4) + y (Rv 4)| ≤ |x (Rv 4)| + |y (Rv 4)| := abs_add_le _ _
              _ ≤ 6 := by linarith [abs_le.mp hxb4, abs_le.mp hyb4]
          nlinarith [hdc 4, abs_nonneg (x (Rv 4) + y (Rv 4)), abs_nonneg (x (Rv 4) - y (Rv 4))]
        have e1 : |(-(1/2) : ℝ) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))|
            ≤ 1/2 * (6 * dist x y) := by
          rw [abs_mul]
          have h : |(-(1/2) : ℝ)| = 1/2 := by norm_num
          rw [h]
          nlinarith [abs_nonneg ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))]
        have e2 : |((3:ℝ)/10) * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4)))|
            ≤ 3/10 * (6 * dist x y) := by
          rw [abs_mul]
          have h : |((3:ℝ)/10)| = 3/10 := by norm_num
          rw [h]
          nlinarith [abs_nonneg ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4)))]
        have hsub : |(-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
              - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))|
            ≤ |(-(1/2) : ℝ) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))|
              + |((3:ℝ)/10) * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4)))| := by
          rw [sub_eq_add_neg]
          refine (abs_add_le _ _).trans ?_
          rw [abs_neg]
        linarith
      have hfin1 : |(1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))|
          * |x (Rv 0) - y (Rv 0)| ≤ 9 * dist x y :=
        mul_le_mul hBx (hdc 0) (abs_nonneg _) (by norm_num)
      have hfin2 : |y (Rv 0)| * |(-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
            - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))|
          ≤ 3 * (6 * dist x y) :=
        mul_le_mul hyb0 htri (abs_nonneg _) (by norm_num)
      have hsplit : |((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
              * (x (Rv 0) - y (Rv 0))
            + y (Rv 0) * (-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
                - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))|
          ≤ |((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))
              * (x (Rv 0) - y (Rv 0))|
            + |y (Rv 0) * (-(1/2) * ((x (Rv 2) + y (Rv 2)) * (x (Rv 2) - y (Rv 2)))
                - 3/10 * ((x (Rv 4) + y (Rv 4)) * (x (Rv 4) - y (Rv 4))))| := abs_add_le _ _
      rw [abs_mul, abs_mul] at hsplit
      linarith
    skip
    nlinarith [hcore, hd]
  by_cases hc2 : c = Rv 2
  · subst hc2
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |-1 * x (Rv 2) - -1 * y (Rv 2)| ≤ 1 * dist x y := by
      have hdiff : -1 * x (Rv 2) - -1 * y (Rv 2) = -(1 : ℝ) * (x (Rv 2) - y (Rv 2)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(1 : ℝ)| = 1 := by norm_num
      rw [habs]
      nlinarith [hdc 2]
    skip
    nlinarith [hcore, hd]
  by_cases hc4 : c = Rv 4
  · subst hc4
    simp only [if_neg (hne 4 0 (by decide)), if_neg (hne 4 1 (by decide)), if_neg (hne 4 2 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |-1 * x (Rv 4) - -1 * y (Rv 4)| ≤ 1 * dist x y := by
      have hdiff : -1 * x (Rv 4) - -1 * y (Rv 4) = -(1 : ℝ) * (x (Rv 4) - y (Rv 4)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(1 : ℝ)| = 1 := by norm_num
      rw [habs]
      nlinarith [hdc 4]
    skip
    nlinarith [hcore, hd]
  by_cases hc6 : c = Rv 6
  · subst hc6
    simp only [if_neg (hne 6 0 (by decide)), if_neg (hne 6 1 (by decide)), if_neg (hne 6 2 (by decide)), if_neg (hne 6 4 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |-1 * x (Rv 6) - -1 * y (Rv 6)| ≤ 1 * dist x y := by
      have hdiff : -1 * x (Rv 6) - -1 * y (Rv 6) = -(1 : ℝ) * (x (Rv 6) - y (Rv 6)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(1 : ℝ)| = 1 := by norm_num
      rw [habs]
      nlinarith [hdc 6]
    skip
    nlinarith [hcore, hd]
  by_cases hc7 : c = Rv 7
  · subst hc7
    simp only [if_neg (hne 7 0 (by decide)), if_neg (hne 7 1 (by decide)), if_neg (hne 7 2 (by decide)), if_neg (hne 7 4 (by decide)), if_neg (hne 7 6 (by decide)), eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |-1 * x (Rv 7) - -1 * y (Rv 7)| ≤ 1 * dist x y := by
      have hdiff : -1 * x (Rv 7) - -1 * y (Rv 7) = -(1 : ℝ) * (x (Rv 7) - y (Rv 7)) := by ring
      rw [hdiff, abs_mul]
      have habs : |-(1 : ℝ)| = 1 := by norm_num
      rw [habs]
      nlinarith [hdc 7]
    skip
    nlinarith [hcore, hd]
  · simp only [if_neg hc0, if_neg hc1, if_neg hc2, if_neg hc4, if_neg hc6, if_neg hc7]
    simp [dist_nonneg]

theorem hfbnd_D (q : ℕ) (hq : q < 3) (ν : State (Var 8))
    (hν : ∀ gT' ∈ gsSD, Term.eval gT' ν ≤ 0) :
    ∀ x ∈ Metric.closedBall ν 1,
      ‖odeField (jointSys (fun _ => Term.const 0) (fRD q) (Term.const (1))) x‖
        ≤ ((60:NNReal) : ℝ) := by
  have hne : ∀ (a b : Fin 8), a ≠ b → (Rv a : Var 8) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro x hx
  rw [Metric.mem_closedBall] at hx
  have hbandf : ∀ (j : Fin 8) (lo hi : ℝ),
      lo ≤ ν (Rv j) → ν (Rv j) ≤ hi → -2 ≤ lo → hi ≤ 2 → |x (Rv j)| ≤ 3 := by
    intro j lo hi hl hh hlo1 hhi1
    have h := dist_le_pi_dist x ν (Rv j)
    rw [Real.dist_eq] at h
    have hνb : |ν (Rv j)| ≤ 2 := abs_le.mpr ⟨by linarith, by linarith⟩
    have h2 := abs_sub_abs_le_abs_sub (x (Rv j)) (ν (Rv j))
    linarith [abs_le.mp hνb, hx]
  have hxb0 : |x (Rv 0)| ≤ 3 := by
    refine hbandf 0 (0) ((4:ℝ)/5) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν faceVLo (by simp [gsSD])
      simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
    · have := hν faceVHi (by simp [gsSD])
      simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
  have hxb2 : |x (Rv 2)| ≤ 3 := by
    refine hbandf 2 (-(1:ℝ)/2) ((3:ℝ)/20) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν facePsiLo (by simp [gsSD])
      simp only [facePsiLo, Term.eval, AOp.interp] at this; linarith
    · have := hν facePsiHi (by simp [gsSD])
      simp only [facePsiHi, Term.eval, AOp.interp] at this; linarith
  have hxb4 : |x (Rv 4)| ≤ 3 := by
    refine hbandf 4 (-(1:ℝ)/2) ((3:ℝ)/20) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν faceThLo (by simp [gsSD])
      simp only [faceThLo, Term.eval, AOp.interp] at this; linarith
    · have := hν faceThHi (by simp [gsSD])
      simp only [faceThHi, Term.eval, AOp.interp] at this; linarith
  have hxb6 : |x (Rv 6)| ≤ 3 := by
    refine hbandf 6 (-(1:ℝ)) ((3:ℝ)/20) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν faceZLo (by simp [gsSD])
      simp only [faceZLo, Term.eval, AOp.interp] at this; linarith
    · have := hν faceZHi (by simp [gsSD])
      simp only [faceZHi, Term.eval, AOp.interp] at this; linarith
  have hxb7 : |x (Rv 7)| ≤ 3 := by
    refine hbandf 7 (-(1:ℝ)/2) ((3:ℝ)/20) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν facePhLo (by simp [gsSD])
      simp only [facePhLo, Term.eval, AOp.interp] at this; linarith
    · have := hν facePhHi (by simp [gsSD])
      simp only [facePhHi, Term.eval, AOp.interp] at this; linarith
  rw [odeField_RD q hq]
  refine pi_norm_le_iff_of_nonneg (by norm_num) |>.mpr ?_
  intro c
  have hLcoe : ((60:NNReal) : ℝ) = 60 := rfl
  rw [hLcoe]
  by_cases hc0 : c = Rv 0
  · subst hc0
    simp only [eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcst : 0 ≤ cstD q ∧ cstD q ≤ 1 := by
      interval_cases q <;> norm_num [cstD]
    have hcore : |3 * (cstD q - x (Rv 0))| ≤ 12 := by
      obtain ⟨hcl, hch⟩ := hcst
      rw [abs_le]
      constructor <;> nlinarith [abs_le.mp hxb0]

    nlinarith [hcore, abs_nonneg (3 * (cstD q - x (Rv 0)))]
  by_cases hc1 : c = Rv 1
  · subst hc1
    simp only [if_neg (hne 1 0 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hBx : |(1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))| ≤ 9 := by
      have h2 : x (Rv 2) * x (Rv 2) ≤ 9 := by nlinarith [abs_le.mp hxb2]
      have h3 : x (Rv 4) * x (Rv 4) ≤ 9 := by nlinarith [abs_le.mp hxb4]
      have h2n : 0 ≤ x (Rv 2) * x (Rv 2) := mul_self_nonneg _
      have h3n : 0 ≤ x (Rv 4) * x (Rv 4) := mul_self_nonneg _
      rw [abs_le]
      constructor <;> nlinarith
    have hcore : |x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))| ≤ 27 := by
      rw [abs_mul]
      nlinarith [abs_nonneg (x (Rv 0)), abs_le.mp hxb0, abs_nonneg ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4)))]

    nlinarith [hcore, abs_nonneg (x (Rv 0) * ((1 - 1/2 * (x (Rv 2) * x (Rv 2))) - 3/10 * (x (Rv 4) * x (Rv 4))))]
  by_cases hc2 : c = Rv 2
  · subst hc2
    simp only [if_neg (hne 2 0 (by decide)), if_neg (hne 2 1 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcore : |-1 * x (Rv 2)| ≤ 3 := by
      rw [abs_mul]
      have habs : |(-1 : ℝ)| = 1 := by norm_num
      rw [habs]
      linarith [abs_le.mp hxb2, abs_nonneg (x (Rv 2))]

    nlinarith [hcore, abs_nonneg (-1 * x (Rv 2))]
  by_cases hc4 : c = Rv 4
  · subst hc4
    simp only [if_neg (hne 4 0 (by decide)), if_neg (hne 4 1 (by decide)), if_neg (hne 4 2 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcore : |-1 * x (Rv 4)| ≤ 3 := by
      rw [abs_mul]
      have habs : |(-1 : ℝ)| = 1 := by norm_num
      rw [habs]
      linarith [abs_le.mp hxb4, abs_nonneg (x (Rv 4))]

    nlinarith [hcore, abs_nonneg (-1 * x (Rv 4))]
  by_cases hc6 : c = Rv 6
  · subst hc6
    simp only [if_neg (hne 6 0 (by decide)), if_neg (hne 6 1 (by decide)), if_neg (hne 6 2 (by decide)), if_neg (hne 6 4 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcore : |-1 * x (Rv 6)| ≤ 3 := by
      rw [abs_mul]
      have habs : |(-1 : ℝ)| = 1 := by norm_num
      rw [habs]
      linarith [abs_le.mp hxb6, abs_nonneg (x (Rv 6))]

    nlinarith [hcore, abs_nonneg (-1 * x (Rv 6))]
  by_cases hc7 : c = Rv 7
  · subst hc7
    simp only [if_neg (hne 7 0 (by decide)), if_neg (hne 7 1 (by decide)), if_neg (hne 7 2 (by decide)), if_neg (hne 7 4 (by decide)), if_neg (hne 7 6 (by decide)), eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
    have hcore : |-1 * x (Rv 7)| ≤ 3 := by
      rw [abs_mul]
      have habs : |(-1 : ℝ)| = 1 := by norm_num
      rw [habs]
      linarith [abs_le.mp hxb7, abs_nonneg (x (Rv 7))]

    nlinarith [hcore, abs_nonneg (-1 * x (Rv 7))]
  · simp only [if_neg hc0, if_neg hc1, if_neg hc2, if_neg hc4, if_neg hc6, if_neg hc7]
    norm_num

/-! ## Existence -/

theorem esD (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt) :
    ∀ σ, Formula.sat (Formula.and (FM gD gsD) envD) σ →
      HExistSegB (fLD l) (fRD m) (Term.const (1)) domLD domRD dt
        (Function.update σ tgD 0) := by
  intro σ hσ
  have hR : Formula.sat domRD σ := hσ.2.2
  rw [sat_domRD] at hR
  obtain ⟨hd3l, hd3h, hd5l, hd5h, hd7l, hd7h, hd2l, hd2h, hd1l, hd4l, hd4h, hd0l, hd0h, hd6l, hd6h⟩ := hR
  have hupd : ∀ j : Fin 8, σ (Side.R, j) = Function.update σ tgD 0 (Side.R, j) := by
    intro j
    rw [Function.update_of_ne (by simp [tgD, Prod.ext_iff])]
  have hfS : ∀ gT' ∈ gsSD, Term.eval gT' (Function.update σ tgD 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsSD, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
      · first
          | (simp only [faceVLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceVHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [facePsiLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [facePsiHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceThLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceThHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceZLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceZHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [facePhLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [facePhHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
  have hfN : ∀ gT' ∈ gsND, Term.eval gT' (Function.update σ tgD 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsND, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with rfl | rfl | rfl | rfl | rfl <;>
      · first
          | (simp only [faceSLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceOPsLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceOPsHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceOThLo, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
          | (simp only [faceOThHi, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)
  refine HExistSegB_of_viability_stratified (fLD l) (fRD m) (Term.const (1))
    domLD domRD gsSD [] gsND 0 le_rfl
    (jointSys_wellFormed _ _ _)
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLD l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_RD gT' (by
        rcases List.mem_append.mp hgT with h | h
        · exact List.mem_append_left _ h
        · exact absurd h (List.not_mem_nil)) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLD l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_RD gT' (List.mem_append_right _ hgT) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro gT' hgT x _ hface
      exact hbndS_D m hm gT' hgT x hface)
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))
    (by
      intro i hi x hxs _
      exact hbndN_D m hm i hi x hxs)
    (by
      intro x hS hN
      have hS' : ∀ gT' ∈ gsSD, Term.eval gT' x ≤ 0 :=
        fun gT' hgT => hS gT' (List.mem_append_left _ hgT)
      have hb0l : 0 ≤ x (Rv 0) := by
        have := hS' faceVLo (by simp [gsSD])
        simp only [faceVLo, Term.eval, AOp.interp] at this; linarith
      have hb0h : x (Rv 0) ≤ (4:ℝ)/5 := by
        have := hS' faceVHi (by simp [gsSD])
        simp only [faceVHi, Term.eval, AOp.interp] at this; linarith
      have hb2l : -(1:ℝ)/2 ≤ x (Rv 2) := by
        have := hS' facePsiLo (by simp [gsSD])
        simp only [facePsiLo, Term.eval, AOp.interp] at this; linarith
      have hb2h : x (Rv 2) ≤ (3:ℝ)/20 := by
        have := hS' facePsiHi (by simp [gsSD])
        simp only [facePsiHi, Term.eval, AOp.interp] at this; linarith
      have hb4l : -(1:ℝ)/2 ≤ x (Rv 4) := by
        have := hS' faceThLo (by simp [gsSD])
        simp only [faceThLo, Term.eval, AOp.interp] at this; linarith
      have hb4h : x (Rv 4) ≤ (3:ℝ)/20 := by
        have := hS' faceThHi (by simp [gsSD])
        simp only [faceThHi, Term.eval, AOp.interp] at this; linarith
      have hb6l : -(1:ℝ) ≤ x (Rv 6) := by
        have := hS' faceZLo (by simp [gsSD])
        simp only [faceZLo, Term.eval, AOp.interp] at this; linarith
      have hb6h : x (Rv 6) ≤ (3:ℝ)/20 := by
        have := hS' faceZHi (by simp [gsSD])
        simp only [faceZHi, Term.eval, AOp.interp] at this; linarith
      have hb7l : -(1:ℝ)/2 ≤ x (Rv 7) := by
        have := hS' facePhLo (by simp [gsSD])
        simp only [facePhLo, Term.eval, AOp.interp] at this; linarith
      have hb7h : x (Rv 7) ≤ (3:ℝ)/20 := by
        have := hS' facePhHi (by simp [gsSD])
        simp only [facePhHi, Term.eval, AOp.interp] at this; linarith
      have hb1l : 0 ≤ x (Rv 1) := by
        have := hN faceSLo (by simp [gsND])
        simp only [faceSLo, Term.eval, AOp.interp] at this; linarith
      have hb3l : -(1:ℝ)/2 ≤ x (Rv 3) := by
        have := hN faceOPsLo (by simp [gsND])
        simp only [faceOPsLo, Term.eval, AOp.interp] at this; linarith
      have hb3h : x (Rv 3) ≤ (3:ℝ)/5 := by
        have := hN faceOPsHi (by simp [gsND])
        simp only [faceOPsHi, Term.eval, AOp.interp] at this; linarith
      have hb5l : -(1:ℝ)/2 ≤ x (Rv 5) := by
        have := hN faceOThLo (by simp [gsND])
        simp only [faceOThLo, Term.eval, AOp.interp] at this; linarith
      have hb5h : x (Rv 5) ≤ (3:ℝ)/5 := by
        have := hN faceOThHi (by simp [gsND])
        simp only [faceOThHi, Term.eval, AOp.interp] at this; linarith
      exact (sat_domRD x).mpr ⟨hb3l, hb3h, hb5l, hb5h, hb7l, hb7h, hb2l, hb2h, hb1l, hb4l, hb4h, hb0l, hb0h, hb6l, hb6h⟩)
    60 60 1 one_pos
    (fun ν0 h0 => hLip_D m hm ν0 (fun gT hgT => h0 gT (List.mem_append_left _ hgT)))
    (fun ν0 h0 => hfbnd_D m hm ν0 (fun gT hgT => h0 gT (List.mem_append_left _ hgT)))
    dt hdt
    (Function.update σ tgD 0)
    hfS
    hfN
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))

/-! ## The route verdicts (stratified-DC at the cover's λ) -/

def VerdD (l m : ℕ) : Prop :=
  ∀ i (hi : i < (gD :: gsD).length),
    z3solve (flowQuery ⟨(gD :: gsD)[i], fLD l, fRD m, Term.const (1),
      strataDomHost (Formula.and domLD domRD) ((gD :: gsD).take i)⟩) = Verdict.unsat
    ∨ z3solve (flowQueryStrict ⟨(gD :: gsD)[i], fLD l, fRD m, Term.const (1),
      strataDomHost (Formula.and domLD domRD) ((gD :: gsD).take i)⟩) = Verdict.unsat
    ∨ z3solve (flowQuerySuperlevel ⟨(gD :: gsD)[i], fLD l, fRD m, Term.const (1),
      strataDomHost (Formula.and domLD domRD) ((gD :: gsD).take i)⟩) = Verdict.unsat

/-! ## The coupling at λ, and its λ = 1 transport (L7) -/

theorem coupleD (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdD l m) :
    ∀ σ', Formula.sat (Formula.and (FM gD gsD) envD) σ' → σ' tgD = 0 →
      faModalB (Equiv.refl (Var 8))
        (Program.ode (DLCalTiming.clk tgD (leftBlock (fLD l))) domLD)
        (Program.ode (rightBlock (fRD m) (Term.const (1))) domRD)
        (Formula.and (FM gD gsD) envD) tgD dt σ' := by
  intro σ' hσ' htg0
  have hupd : Function.update σ' tgD (0 : ℝ) = σ' := by
    funext x
    by_cases hx : x = tgD
    · subst hx; rw [Function.update_self]; exact htg0.symm
    · rw [Function.update_of_ne hx]
  have hAll := segPresAll_from_strata_verdicts' (fLD l) (fRD m) (Term.const (1))
    (Formula.and domLD domRD) (gD :: gsD) hv
  have hboxes : ∀ g' ∈ gD :: gsD, Formula.sat (Formula.box (Program.ode
      (leftBlock (fLD l) ++ rightBlock (fRD m) (Term.const (1)))
      (Formula.and domLD domRD)) (invLe g')) σ' := by
    intro g' hg'
    rw [sat_box]
    intro ω hω
    rw [sat_invLe]
    refine hAll σ' ?_ ω (by rw [← jointSys_split] at hω; exact hω) g' hg'
    intro g hg
    exact (sat_FM_iff gD gsD σ').mp hσ'.1 g hg
  have hbase := segment_faModalB_from_certB_list gD gsD (fLD l) (fRD m)
    (Term.const (1)) domLD domRD tgD dt
    (LR_blocks_disjoint _ _ _ (hfLD l hl) (hfRD m hm) (by simp [Term.fv]))
    (fun v hv' => Or.inl (by
      obtain ⟨i, rfl⟩ := hdomLD hv'
      exact Lv_mem_leftBlock_boundSet _ i))
    (fun v hv' => Or.inl (by
      obtain ⟨i, rfl⟩ := hdomRD hv'
      exact Rv_mem_rightBlock_boundSet _ _ i))
    (fun h => by
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fLD l) _ h
      exact aux_ne_Lv aD i hi)
    (fun h => aux_notin_range_Lv aD (leftBlock_readVars_sub (fLD l) (hfLD l hl) h))
    (fun h => by
      obtain ⟨i, hi⟩ := rightBlock_bound_sub (fRD m) (Term.const (1)) _ h
      exact aux_ne_Rv aD i hi)
    (fun h => aux_notin_range_Rv aD (rightBlock_readVars_sub (fRD m)
      (Term.const (1)) (hfRD m hm) (by simp [Term.fv]) h))
    (fun h => aux_notin_range_Rv aD (rightBlock_boundSet_sub (fRD m)
      (Term.const (1)) h))
    (fun h => aux_notin_range_Lv aD (hdomLD h))
    (fun h => aux_notin_range_Rv aD (hdomRD h))
    htgg hboxes
    (esD l m hl hm dt hdt σ' hσ')
  rw [hupd] at hbase
  refine faModalB_strengthen_plant ?_ hbase
  intro ν μ hplant hsem
  have hdomLν : Formula.sat domLD ν := sem_ode_ends_in_domain hplant.1
  have hdomRμ : Formula.sat domRD μ := sem_ode_ends_in_domain hsem
  have hdomLμ : Formula.sat domLD μ := by
    rwa [(Formula.coincidence domLD (fun v hv' => sem_ode_mask hsem (by
      obtain ⟨i, rfl⟩ := hdomLD hv'
      intro hb
      obtain ⟨j, hj⟩ := rightBlock_bound_sub (fRD m) (Term.const (1)) _ hb
      exact absurd hj (by simp [Lv, Rv, Prod.ext_iff]))) :
        Formula.sat domLD μ ↔ Formula.sat domLD ν)]
  exact ⟨hdomLμ, hdomRμ⟩

theorem couple1D (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdD l m) :
    ∀ σ, Formula.sat (Formula.and (FM gD gsD) envD) σ →
      faModalB (Equiv.refl (Var 8))
        (Program.ode (DLCalTiming.clk tgD (leftBlock (fLD l))) domLD)
        (Program.ode (rightBlock (fRD m) (Term.const 1)) domRD) (Formula.and (FM gD gsD) envD) tgD dt
        (Function.update σ tgD 0) := by
  intro σ hσ
  have htgφ : tgD ∉ (Formula.and (FM gD gsD) envD).fv := by
    intro h
    rcases h with h | h
    · exact htgFD h
    · exact htgenvD h
  have hupdφ : Formula.sat (Formula.and (FM gD gsD) envD)
      (Function.update σ tgD 0) := by
    rwa [(Formula.coincidence (Formula.and (FM gD gsD) envD) (fun v hv' =>
      Function.update_of_ne (fun hc => htgφ (by rw [← hc]; exact hv')) _ _) :
        Formula.sat (Formula.and (FM gD gsD) envD) _ ↔ _)]
  refine faModalB_monoQ ?_ (coupleD l m hl hm dt hdt hv
    (Function.update σ tgD 0) hupdφ (Function.update_self _ _ _))
  intro ν μ hsem
  exact sem_rightBlock_reparam (1) 1 (by norm_num) one_pos hsem

/-! ## The window response (1 pieces at the in-place mode) -/

theorem respondD (l m : ℕ) (hl : l < 3) (hm : m < 3) (dt : ℝ) (hdt : 0 ≤ dt)
    (hv : VerdD l m) (path : List ℕ) (hpath : ∀ p ∈ path, p < 3)
    {σ : State (Var 8)}
    (hσ : Formula.sat (Formula.and (FM gD gsD) envD) σ) :
    Formula.sat (faModal (Equiv.refl (Var 8))
      (windowSeg (leftBlock (fLD l)) domLD tgD dt 1)
      (bigSeq ((path.map (fun p => Program.ode (rightBlock (fRD p) (Term.const 1)) domRD))
        ++ [Program.ode (rightBlock (fRD m) (Term.const 1)) domRD]))
      (Formula.and (FM gD gsD) envD)) σ := by
  have hfa := Hmulti_windowRF_prefixed (fLD l) domLD (FM gD gsD) envD
    aD dt 1 htgFD htgenvD
    (path.map (fun p => (⟨fRD p, Term.const 1, domRD⟩ : RepoHop 8)))
    (by
      intro h hh
      obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hh
      exact ⟨hfRD p (hpath p hp), by simp [Term.fv], hdomRD⟩)
    (fun σ' hσ' => hσ'.2.1)
    (by
      intro h hh σ' hσ' htg'
      obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hh
      obtain ⟨ρ, hsem, hρσ⟩ := static_hop_existsR (fR := fRD p)
        (lam := Term.const 1) (domR := domRD) hσ'.2.2
      exact ⟨ρ, hsem, hρσ ▸ hσ'⟩)
    (hfLD l hl) hdomLD
    (List.replicate 1 (Program.ode (rightBlock (fRD m) (Term.const 1)) domRD)) (by simp) (by norm_num)
    (by
      intro Q hQ
      rw [List.eq_of_mem_replicate hQ, Program.rename_refl]
      exact hdisH_progR (⟨fRD m, Term.const 1, domRD⟩ : RepoHop 8)
        (hfRD m hm) (by simp [Term.fv]) hdomRD (hfLD l hl) hdomLD)
    (by
      intro Q hQ σ' hσ'
      rw [List.eq_of_mem_replicate hQ]
      exact couple1D l m hl hm dt hdt hv σ' hσ')
    hσ
  rw [show (path.map (fun p => (⟨fRD p, Term.const 1, domRD⟩ : RepoHop 8))).map
      (fun h => h.progR)
      = path.map (fun p => Program.ode (rightBlock (fRD p) (Term.const 1)) domRD)
    from by rw [List.map_map]; rfl] at hfa
  simpa [List.replicate] using hfa

/-! ## The step provider — every window certifies every mode, so the response
stays in place -/

theorem HmultiD (dt : ℝ) (hdt : 0 ≤ dt) (hv00 : VerdD 0 0) (hv01 : VerdD 0 1) (hv02 : VerdD 0 2) (hv10 : VerdD 1 0) (hv11 : VerdD 1 1) (hv12 : VerdD 1 2) (hv20 : VerdD 2 0) (hv21 : VerdD 2 1) (hv22 : VerdD 2 2) :
    ∀ P ∈ leftProgsD dt, ∀ (q : ℕ), q < GrD.modes.length → ∀ σ, σ mvD = (q : ℝ) →
      Formula.sat (Formula.and (FM gD gsD) envD) σ →
      ∃ segs : List (ℕ × RMode (Var 8) × REdge (Var 8)),
        (∀ s ∈ segs, GrD.modeAt s.1 = some s.2.1 ∧ s.2.2 ∈ GrD.edgesFrom s.1) ∧
        List.IsChain (fun a b => a.2.2.tgt = b.1) segs ∧
        (∀ s, segs.head? = some s → s.1 = q) ∧
        Formula.sat (faModal (Equiv.refl (Var 8)) P
          (bigSeq (segs.map (fun s => Program.ode s.2.1.sys s.2.1.dom)))
          (Formula.and (FM gD gsD) envD)) σ := by
  intro P hP q hq σ hmv hσ
  have hq3 : q < 3 := by simpa [GrD] using hq
  have hself : GrD.modeAt q = some (modeD q) ∧ edgeD q q ∈ GrD.edgesFrom q := by
    refine ⟨GrD_modeAt q hq3, edgeD_mem q q ?_⟩
    interval_cases q <;> simp [GrD]
  have hstep : ∀ (a b : ℕ × RMode (Var 8) × REdge (Var 8)) rest,
      a.2.2.tgt = b.1 → List.IsChain (fun x y => x.2.2.tgt = y.1) (b :: rest) →
      List.IsChain (fun x y => x.2.2.tgt = y.1) (a :: b :: rest) := by
    intro a b rest hab hrest
    refine hrest.cons ?_
    intro y hy
    rw [List.head?_cons, Option.mem_some_iff] at hy
    subst hy
    exact hab
  have hhead1 : ∀ (a : ℕ × RMode (Var 8) × REdge (Var 8)) rest s,
      (a :: rest : List _).head? = some s → s = a := by
    intro a rest s hs
    simpa [List.head?_cons] using hs.symm
  simp only [leftProgsD, leftDataD, List.map_cons, List.map_nil, List.mem_cons,
    List.not_mem_nil, or_false] at hP
  have halign : ∀ st tgt : ℕ, st < 3 → tgt < 3 → edgeD st tgt ∈ GrD.edges →
      GrD.modeAt st = some (modeD st) ∧ edgeD st tgt ∈ GrD.edgesFrom st :=
    fun st tgt hs ht he => ⟨GrD_modeAt st hs, edgeD_mem st tgt he⟩
  rcases hP with rfl | rfl | rfl
  all_goals interval_cases q
  · refine ⟨[(0, modeD 0, edgeD 0 0)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 0 0 (by norm_num) (by norm_num) (by simp [GrD])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondD 0 0 (by norm_num) (by norm_num) dt hdt hv00 [] (by simp) hσ
      simpa [modeD, List.replicate] using this
  · refine ⟨[(1, modeD 1, edgeD 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrD])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondD 0 1 (by norm_num) (by norm_num) dt hdt hv01 [] (by simp) hσ
      simpa [modeD, List.replicate] using this
  · refine ⟨[(2, modeD 2, edgeD 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrD])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondD 0 2 (by norm_num) (by norm_num) dt hdt hv02 [] (by simp) hσ
      simpa [modeD, List.replicate] using this
  · refine ⟨[(0, modeD 0, edgeD 0 0)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 0 0 (by norm_num) (by norm_num) (by simp [GrD])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondD 1 0 (by norm_num) (by norm_num) dt hdt hv10 [] (by simp) hσ
      simpa [modeD, List.replicate] using this
  · refine ⟨[(1, modeD 1, edgeD 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrD])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondD 1 1 (by norm_num) (by norm_num) dt hdt hv11 [] (by simp) hσ
      simpa [modeD, List.replicate] using this
  · refine ⟨[(2, modeD 2, edgeD 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrD])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondD 1 2 (by norm_num) (by norm_num) dt hdt hv12 [] (by simp) hσ
      simpa [modeD, List.replicate] using this
  · refine ⟨[(0, modeD 0, edgeD 0 0)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 0 0 (by norm_num) (by norm_num) (by simp [GrD])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondD 2 0 (by norm_num) (by norm_num) dt hdt hv20 [] (by simp) hσ
      simpa [modeD, List.replicate] using this
  · refine ⟨[(1, modeD 1, edgeD 1 1)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 1 1 (by norm_num) (by norm_num) (by simp [GrD])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondD 2 1 (by norm_num) (by norm_num) dt hdt hv21 [] (by simp) hσ
      simpa [modeD, List.replicate] using this
  · refine ⟨[(2, modeD 2, edgeD 2 2)], ?_, ?_, ?_, ?_⟩
    · intro s hs
      simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
      rcases hs with rfl
      · exact halign 2 2 (by norm_num) (by norm_num) (by simp [GrD])
    · simp
    · exact fun s hs => by rw [hhead1 _ _ _ hs]
    · have := respondD 2 2 (by norm_num) (by norm_num) dt hdt hv22 [] (by simp) hσ
      simpa [modeD, List.replicate] using this

/-- **`story1_attdist_rung_a_6to8`, modal Theorem 3** (λ = 1, k = 1). -/
theorem story1_attdist_rung_a_modal (dt : ℝ) (hdt : 0 ≤ dt) (hv00 : VerdD 0 0) (hv01 : VerdD 0 1) (hv02 : VerdD 0 2) (hv10 : VerdD 1 0) (hv11 : VerdD 1 1) (hv12 : VerdD 1 2) (hv20 : VerdD 2 0) (hv21 : VerdD 2 1) (hv22 : VerdD 2 2) :
    RFormula.rvalid (theorem3Form
      (bigChoice (leftProgsD dt))
      (rightAutomatonBody GrD mvD)
      (RFormula.and (RFormula.and (canonInvM gD gsD) (envLR domLD domRD))
        (mvValidR mvD GrD.modes.length))) := by
  refine theorem3_faithful_multiF_LR GrD mvD (FM gD gsD) domLD domRD
    (leftProgsD dt) (canonInvM gD gsD) (encode_canonInvM gD gsD) ?_ ?_ ?_
  · exact hdis_multi GrD 0 1 dt leftDataD (by decide) httD hRvD hLD
  · exact hstep_assembled_multiF GrD mvD (FM gD gsD) envD (leftProgsD dt)
      hmvFD hmvenvD hfreshD httD hltD (hframesD dt)
      (HmultiD dt hdt hv00 hv01 hv02 hv10 hv11 hv12 hv20 hv21 hv22)
  · exact hddF_multiE GrD 0 1 dt leftDataD (canonInvM gD gsD) domLD domRD
      (by decide) httD hRvD hLD
      (canonInvM_varsL gD gsD (by
        intro g' hg'
        simp only [gD, gsD, List.mem_cons, List.not_mem_nil, or_false] at hg'
        rcases hg' with rfl | rfl <;> exact hgAt _))
      (canonInvM_varsR gD gsD) hdomLD hdomRD

end Story1AttdistRungAModal
end RelCertifier
