"""Generator for plain multiF instances (λ = 1, k = 1, uniform invariant).

Emits a complete Lean instance file from a coordinate spec: defs, side-splits,
graph, windows, pins, field/dom pins, faces, odeField, Lie blocks, Lipschitz,
field bound, existence (stratified or stratA), and the climb-dispatch assembly.
"""

def gen(spec):
    N = spec['n']; SUF = spec['suf']; IR = spec['ir']; NS = spec['ns']
    BENCH = spec['bench']; THM = spec['thm']
    vars_lean = '[' + ', '.join(f'"{v}"' for v in spec['vars']) + ']'
    rows = spec['rows']            # i -> ('affine',) | ('bracket', p, t) | ('vel',) | ('decay',) | ('zero',)
    strict = spec['strict']        # [(coord, lo, hi, nameLo, nameHi)]
    aux = spec.get('aux', [])      # [(coord, lo, name)]  auxiliary strict lower face
    nonstrict = spec['nonstrict']  # [(coord, lo, hi, nameLo, nameHi)] zero-field bands
    s_face = spec.get('s_face')    # (coord, name) conditioned face, or None
    affineL = spec.get('affineL', [])   # [(coord,)] equilibrium lower faces
    dom = spec['dom']              # [(coord, lo, hi|None)]
    gs_idx = spec['gs']            # invariant atom indices, DC order (first is head)
    cst = spec['cst']              # per-mode drive constants as lean reals
    K = spec['K']; L = spec['L']
    nmodes = spec.get('nmodes', 3)
    pins = spec['pins']            # [(name, literal, lean_value, needs_norm)]
    hasBracket = any(r[0] == 'bracket' for r in rows.values())

    # coordinates with a non-zero row, in field-if order
    nz = [i for i in sorted(rows) if rows[i][0] != 'zero']

    def negs(j):
        return [k for k in nz if nz.index(k) < nz.index(j)] if j in nz else nz

    def ifnegs(j):
        return "".join(f"if_neg (hne {j} {k} (by decide)), " for k in negs(j))

    LAM = spec.get('lam', '1')
    DR = spec.get('drive', 3)
    KWv = spec.get('kw', 1)
    def rowval(i, xs='x', scaled=False):
        kind = rows[i]
        LM = ("" if LAM == '1' or not scaled else "(" + LAM + ") * ")
        if kind[0] == 'affine':
            return (LM + f'({DR} * (cst{SUF} q - {xs} (Rv {i})))') if LM else f'{DR} * (cst{SUF} q - {xs} (Rv {i}))'
        if kind[0] == 'vel':
            return LM + f'{xs} (Rv 0)'
        if kind[0] == 'bracket':
            _, p, t = kind
            core = (f'{xs} (Rv 0) * ((1 - 1/2 * ({xs} (Rv {p}) * {xs} (Rv {p})))'
                    f' - 3/10 * ({xs} (Rv {t}) * {xs} (Rv {t})))')
            return (LM + '(' + core + ')') if LM else core
        if kind[0] == 'decay':
            return (LM + f'(-1 * {xs} (Rv {i}))') if LM else f'-1 * {xs} (Rv {i})'
        return '0'

    O = []
    A = O.append
    A(f'''/-
Copyright (c) 2026 relCertifier-lean contributors.
Released under Apache 2.0 license.

# T3+ — `{BENCH}`, modal Theorem 3 (multiF, GENERATED)

Generated by `scripts/gen_multif_instance.py` from the coordinate spec: the plain
list-invariant pattern at n = {N} with {len(gs_idx)} invariant components in the cover's
stratified-DC order, the one-way terrain chain, and climb dispatch. Existence is
Z3-free ({'stratA — the equilibrium faces ride affine lower bounds' if affineL else 'stratified faces'}).

Residuals: six stratified-DC verdict packs (`Verd{SUF} l m`). Axioms: the standard
three + `z3_unsat_sound` at those leaves.
-/
import RelCertifier.Proofs.Encoding.EnvelopeChainM
import RelCertifier.Proofs.Encoding.RepoPrefixR
import RelCertifier.Proofs.Encoding.CanonicalInv
import RelCertifier.Proofs.Encoding.CoverInstance
import RelCertifier.Proofs.Flow.{'AffineFaces' if affineL else 'StratifiedFaces'}
import RelCertifier.Instances.BenchIR.{BENCH}

namespace RelCertifier
namespace {NS}

open DL DLCalTiming DLRel Parse Set

set_option maxHeartbeats 12800000

def vs{SUF} : List String := {vars_lean}
def dummy{SUF} : Parse.PMode := ⟨"", [], .tt, .tt, []⟩
def mL{SUF} (l : ℕ) : Parse.PMode := {IR}.L.modes.getD l dummy{SUF}
def mR{SUF} (q : ℕ) : Parse.PMode := {IR}.R.modes.getD q dummy{SUF}

abbrev mv{SUF} : Var {N} := (Side.Aux, 0)
abbrev a{SUF} : Fin {N} := (1 : Fin {N})
abbrev tg{SUF} : Var {N} := (Side.Aux, a{SUF})

noncomputable def fL{SUF} (l : ℕ) : Fin {N} → Term (Var {N}) := hostDyn vs{SUF} {N} Side.L (mL{SUF} l)
noncomputable def fR{SUF} (q : ℕ) : Fin {N} → Term (Var {N}) := hostDyn vs{SUF} {N} Side.R (mR{SUF} q)
noncomputable def domL{SUF} : Formula (Var {N}) := hostEvolve vs{SUF} {N} Side.L (mL{SUF} 0)
noncomputable def domR{SUF} : Formula (Var {N}) := hostEvolve vs{SUF} {N} Side.R (mR{SUF} 0)
noncomputable def env{SUF} : Formula (Var {N}) := Formula.and domL{SUF} domR{SUF}

def atomsOf : Parse.PForm → List Parse.PForm
  | .and x y => atomsOf x ++ atomsOf y
  | f => [f]

def inv{SUF}PF : Parse.PForm :=
  ({IR}.invariants.getD 0 ("", Parse.PForm.tt)).2

noncomputable def gAt (i : ℕ) : Term (Var {N}) :=
  ((Run.invToG vs{SUF} {N} ((atomsOf inv{SUF}PF).getD i .tt)).map ITerm.toHost).getD (Term.const 0)

noncomputable def g{SUF} : Term (Var {N}) := gAt {gs_idx[0]}
noncomputable def gs{SUF} : List (Term (Var {N})) := [{", ".join(f"gAt {i}" for i in gs_idx[1:])}]

/-! ## Side-splits -/

theorem fL{SUF}_pipe (l : ℕ) (i : Fin {N}) : fL{SUF} l i =
    (((some (mL{SUF} l)).bind (Run.dynOf vs{SUF} {N} Side.L)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem fR{SUF}_pipe (q : ℕ) (i : Fin {N}) : fR{SUF} q i =
    (((some (mR{SUF} q)).bind (Run.dynOf vs{SUF} {N} Side.R)).map
      (fun f => ITerm.toHost (f i))).getD (Term.const 0) := rfl
theorem domL{SUF}_pipe : domL{SUF} =
    (((some (mL{SUF} 0)).bind (fun m => Run.lowerF vs{SUF} {N} Side.L m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl
theorem domR{SUF}_pipe : domR{SUF} =
    (((some (mR{SUF} 0)).bind (fun m => Run.lowerF vs{SUF} {N} Side.R m.evolve)).map
      IForm.toHost).getD Formula.tt := rfl

theorem hfL{SUF} (l : ℕ) (hl : l < {nmodes}) : ∀ i, (fL{SUF} l i).fv ⊆ range Lv := fun i x hx =>
  side_eq_L_mem (field_pipeline_side (resolvesTo_L vs{SUF}) (some (mL{SUF} l))
    (by interval_cases l <;>
      simp [mL{SUF}, {IR}, Parse.PExpr.namesFree]) i x
    (fL{SUF}_pipe l i ▸ hx))

theorem hfR{SUF} (q : ℕ) (hq : q < {nmodes}) : ∀ i, (fR{SUF} q i).fv ⊆ range Rv := fun i x hx =>
  side_eq_R_mem (field_pipeline_side (resolvesTo_R vs{SUF}) (some (mR{SUF} q))
    (by interval_cases q <;>
      simp [mR{SUF}, {IR}, Parse.PExpr.namesFree]) i x
    (fR{SUF}_pipe q i ▸ hx))

theorem hdomL{SUF} : domL{SUF}.fv ⊆ range Lv := fun x hx =>
  side_eq_L_mem (form_pipeline_side (resolvesTo_L vs{SUF}) (some (mL{SUF} 0))
    (by simp [mL{SUF}, {IR}, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domL{SUF}_pipe ▸ hx))

theorem hdomR{SUF} : domR{SUF}.fv ⊆ range Rv := fun x hx =>
  side_eq_R_mem (form_pipeline_side (resolvesTo_R vs{SUF}) (some (mR{SUF} 0))
    (by simp [mR{SUF}, {IR}, Parse.PForm.namesFree,
      Parse.PExpr.namesFree]) x (domR{SUF}_pipe ▸ hx))

theorem hgAt (i : ℕ) : (gAt i).fv ⊆ range Lv ∪ range Rv := invToG_pipeline_LR _

theorem hmvg : ∀ g' ∈ g{SUF} :: gs{SUF}, mv{SUF} ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [g{SUF}, gs{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with {" | ".join(["rfl"]*len(gs_idx))} <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem htgg : ∀ g' ∈ g{SUF} :: gs{SUF}, tg{SUF} ∉ g'.fv := by
  intro g' hg' h
  have hLR : g'.fv ⊆ range Lv ∪ range Rv := by
    simp only [g{SUF}, gs{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hg'
    rcases hg' with {" | ".join(["rfl"]*len(gs_idx))} <;> exact hgAt _
  rcases hLR h with ⟨i, hi⟩ | ⟨i, hi⟩ <;> exact absurd hi (by simp [Lv, Rv, Prod.ext_iff])

theorem hmvF{SUF} : mv{SUF} ∉ (FM g{SUF} gs{SUF}).fv := notMem_FM_fv hmvg
theorem htgF{SUF} : tg{SUF} ∉ (FM g{SUF} gs{SUF}).fv := notMem_FM_fv htgg

theorem hmvenv{SUF} : mv{SUF} ∉ env{SUF}.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomL{SUF} h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomR{SUF} h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))
theorem htgenv{SUF} : tg{SUF} ∉ env{SUF}.fv := fun h => by
  rcases h with h | h
  · exact absurd (hdomL{SUF} h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Lv, Prod.ext_iff]))
  · exact absurd (hdomR{SUF} h) (by rintro ⟨i, hi⟩; exact absurd hi (by simp [Rv, Prod.ext_iff]))

/-! ## The right graph (one-way chain) -/

noncomputable def mode{SUF} (q : ℕ) : RMode (Var {N}) :=
  {{ sys := rightBlock (fR{SUF} q) (Term.const 1), dom := domR{SUF}, weight := 1 }}

def edge{SUF} (st tgt : ℕ) : REdge (Var {N}) :=
  {{ src := st, tgt := tgt, guard := Formula.tt, pruned := false }}

noncomputable def Gr{SUF} : SearchGraph (Var {N}) :=
  {{ modes := [mode{SUF} 0, mode{SUF} 1, mode{SUF} 2],
    edges := [edge{SUF} 0 1, edge{SUF} 0 0, edge{SUF} 1 2, edge{SUF} 1 1, edge{SUF} 2 2] }}

theorem Gr{SUF}_modeAt (q : ℕ) (hq : q < 3) : Gr{SUF}.modeAt q = some (mode{SUF} q) := by
  interval_cases q <;> rfl

theorem htt{SUF} : ∀ q, ∀ e ∈ Gr{SUF}.edgesFrom q, e.guard = Formula.tt := by
  intro q e he
  have hmem : e ∈ Gr{SUF}.edges := List.mem_of_mem_filter he
  simp only [Gr{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> rfl

theorem hlt{SUF} : ∀ q, ∀ e ∈ Gr{SUF}.edgesFrom q, e.tgt < Gr{SUF}.modes.length := by
  intro q e he
  have hmem : e ∈ Gr{SUF}.edges := List.mem_of_mem_filter he
  simp only [Gr{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hmem
  rcases hmem with rfl | rfl | rfl | rfl | rfl <;> norm_num [Gr{SUF}, edge{SUF}]

theorem hRv{SUF} : ∀ q m, Gr{SUF}.modeAt q = some m →
    m.sys.boundSet ∪ m.sys.readVars ∪ m.dom.fv ⊆ range Rv := by
  intro q m hm
  have hqm : q < 3 ∧ m = mode{SUF} q := by
    match q with
    | 0 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, Gr{SUF}] using hm.symm⟩
    | 1 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, Gr{SUF}] using hm.symm⟩
    | 2 => exact ⟨by norm_num, by simpa [SearchGraph.modeAt, Gr{SUF}] using hm.symm⟩
    | q + 3 => exact absurd hm (by simp [SearchGraph.modeAt, Gr{SUF}])
  obtain ⟨hq3, rfl⟩ := hqm
  intro y hy
  rcases hy with (hy | hy) | hy
  · exact rightBlock_boundSet_sub (fR{SUF} q) (Term.const 1) hy
  · exact rightBlock_readVars_sub (fR{SUF} q) (Term.const 1) (hfR{SUF} q hq3)
      (by simp [Term.fv]) hy
  · exact hdomR{SUF} hy

theorem edge{SUF}_mem : ∀ st tgt, edge{SUF} st tgt ∈ Gr{SUF}.edges →
    edge{SUF} st tgt ∈ Gr{SUF}.edgesFrom st :=
  fun st tgt he => List.mem_filter.mpr ⟨he, by simp [edge{SUF}]⟩

theorem hfresh{SUF} : ∀ q m, Gr{SUF}.modeAt q = some m →
    mv{SUF} ∉ (Program.ode m.sys m.dom).fv := by
  intro q m hm hmv
  exact aux_notin_range_Rv 0 (hRv{SUF} q m hm (vars_ode_sub _ _ (Or.inl hmv)))

/-! ## The left window family -/

noncomputable def leftData{SUF} : List ((Fin {N} → Term (Var {N})) × Formula (Var {N}) × ℕ) :=
  [(fL{SUF} 0, domL{SUF}, {KWv}), (fL{SUF} 1, domL{SUF}, {KWv}), (fL{SUF} 2, domL{SUF}, {KWv})]

noncomputable def leftProgs{SUF} (dt : ℝ) : List (Program (Var {N})) :=
  leftData{SUF}.map (fun d => windowSeg (leftBlock d.1) d.2.1 tg{SUF} dt d.2.2)

theorem hL{SUF} : ∀ d ∈ leftData{SUF}, (∀ i, (d.1 i).fv ⊆ range Lv) ∧ d.2.1.fv ⊆ range Lv := by
  intro d hd
  simp only [leftData{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hd
  rcases hd with rfl | rfl | rfl
  · exact ⟨hfL{SUF} 0 (by norm_num), hdomL{SUF}⟩
  · exact ⟨hfL{SUF} 1 (by norm_num), hdomL{SUF}⟩
  · exact ⟨hfL{SUF} 2 (by norm_num), hdomL{SUF}⟩

theorem hframes{SUF} (dt : ℝ) : ∀ P ∈ leftProgs{SUF} dt, FramesMv P mv{SUF} := by
  intro P hP
  simp only [leftProgs{SUF}, List.mem_map] at hP
  obtain ⟨d, hd, rfl⟩ := hP
  refine framesMv_window (leftBlock d.1) d.2.1 tg{SUF} dt d.2.2 mv{SUF} (by decide) ?_
  intro h
  obtain ⟨i, hi⟩ := leftBlock_bound_sub d.1 _ h
  exact aux_ne_Lv 0 i hi

/-! ## Parse pins -/
''')
    for nm, lit, val, nn in pins:
        A(f'''
theorem {nm} : Run.parseRat "{lit}" = some ({val}) := by
  have h : parseQ "{lit}" = some (⟨{spec['pinq'][lit][0]}, {spec['pinq'][lit][1]}⟩ : QF) := by decide
  simp [Run.parseRat, h]{"; norm_num" if nn else ""}''')

    pinnames = ", ".join(p[0] for p in pins)
    A(f'''

/-! ## Field and shape pins -/

noncomputable def cst{SUF} (q : ℕ) : ℝ := if q = 0 then {cst[0]} else if q = 1 then {cst[1]} else {cst[2]}
''')
    SB = (f"fR{SUF}, hostDyn, mR{SUF}, {IR}, vs{SUF}, Run.dynOf,\n"
          f"      Run.lowerE, {pinnames}, Run.resolveVar,\n"
          f"      List.findIdx?_cons, List.finRange, ITerm.toHost, Term.eval, AOp.interp")
    for i in sorted(rows):
        extra = f", Rv, cst{SUF}" if rows[i][0] == 'affine' else ", Rv"
        A(f'''
theorem fR{SUF}{i}_eval (q : ℕ) (hq : q < {nmodes}) (x : State (Var {N})) :
    Term.eval (fR{SUF} q {i}) x = {rowval(i)} := by
  interval_cases q <;>
    simp [{SB}{extra}]''')

    conj = " ∧ ".join(
        (f"{lo} ≤ x (Rv {c})" if hi is None else f"{lo} ≤ x (Rv {c}) ∧ x (Rv {c}) ≤ {hi}")
        for c, lo, hi in dom)
    dompins = ", ".join(spec['dompins'])
    A(f'''

theorem sat_domR{SUF} (x : State (Var {N})) : Formula.sat domR{SUF} x ↔
    ({conj}) := by
  simp only [domR{SUF}, hostEvolve, mR{SUF}, {IR}, vs{SUF}]
  simp [Run.lowerF, Run.lowerE, {dompins},
    Run.resolveVar, List.findIdx?_cons, IForm.toHost, ITerm.toHost, Formula.sat,
    CompOp.interp, Term.eval, Rv]
  tauto

/-! ## Faces -/
''')
    for c, lo, hi, nlo, nhi in strict:
        A(f'''
noncomputable def {nlo} : Term (Var {N}) :=
  Term.binop AOp.sub (Term.const ({lo})) (Term.var (Rv {c}))
noncomputable def {nhi} : Term (Var {N}) :=
  Term.binop AOp.sub (Term.var (Rv {c})) (Term.const ({hi}))''')
    for c, lo, nm in aux:
        A(f'''
noncomputable def {nm} : Term (Var {N}) :=
  Term.binop AOp.sub (Term.const ({lo})) (Term.var (Rv {c}))''')
    if s_face:
        A(f'''
noncomputable def {s_face[1]} : Term (Var {N}) :=
  Term.binop AOp.sub (Term.const 0) (Term.var (Rv {s_face[0]}))''')
    for c, lo, hi, nlo, nhi in nonstrict:
        A(f'''
noncomputable def {nlo} : Term (Var {N}) :=
  Term.binop AOp.sub (Term.const ({lo})) (Term.var (Rv {c}))
noncomputable def {nhi} : Term (Var {N}) :=
  Term.binop AOp.sub (Term.var (Rv {c})) (Term.const ({hi}))''')

    sfaces = [x for t in strict for x in (t[3], t[4])] + [t[2] for t in aux]
    nfaces = ([s_face[1]] if s_face else []) + [x for t in nonstrict for x in (t[3], t[4])]
    allf = sfaces + nfaces
    A(f'''

noncomputable def gsS{SUF} : List (Term (Var {N})) :=
  [{", ".join(sfaces)}]
noncomputable def gsN{SUF} : List (Term (Var {N})) :=
  [{", ".join(nfaces)}]''')
    if affineL:
        A(f'''
noncomputable def gsAL{SUF} : List (Var {N} × ℝ × ℝ × ℝ) :=
  [{", ".join(f"((Rv {c} : Var {N}), 1, 0, 0)" for (c,) in affineL)}]''')
    A(f'''

theorem faces_fv_R{SUF} : ∀ gT' ∈ gsS{SUF} ++ gsN{SUF}, ∀ x ∈ gT'.fv, x ∈ range Rv := by
  intro gT' hgT x hx
  simp only [gsS{SUF}, gsN{SUF}, List.cons_append, List.nil_append, List.mem_cons,
    List.not_mem_nil, or_false] at hgT
  rcases hgT with {" | ".join(["rfl"]*len(allf))} <;>
    · simp only [{", ".join(allf)}, Term.fv,
        Set.mem_union, Set.mem_empty_iff_false, false_or, or_false,
        Set.mem_singleton_iff] at hx
      exact ⟨_, hx.symm⟩

/-! ## The frozen-left joint field -/
''')
    ifs = "\n".join(f"        else if c = Rv {j} then {rowval(j, scaled=True)}" for j in nz[1:])
    branches = []
    for j in sorted(rows):
        hyps = "".join(f",\n          hne {j} {k} (by decide)" for k in negs(j))
        branches.append(f"      · simp [Term.eval, AOp.interp, fR{SUF}{j}_eval q hq{hyps}]")
    hLRs = ", ".join(f"hLR {k}" for k in nz)
    A(f'''
theorem odeField_R{SUF} (q : ℕ) (hq : q < {nmodes}) (x : State (Var {N})) :
    odeField (jointSys (fun _ => Term.const 0) (fR{SUF} q) (Term.const ({LAM}))) x
      = fun c =>
        if c = Rv {nz[0]} then {rowval(nz[0], scaled=True)}
{ifs}
        else 0 := by
  funext c
  by_cases hc : c ∈ (jointSys (fun _ => Term.const 0) (fR{SUF} q) (Term.const ({LAM}))).bound
  · rw [show odeField (jointSys (fun _ => Term.const 0) (fR{SUF} q) (Term.const ({LAM}))) x c
        = ((jointSys (fun _ => Term.const 0) (fR{SUF} q) (Term.const ({LAM}))).rhs c).eval x from by
      simp only [odeField, if_pos hc]]
    obtain ⟨p, hp, hfst⟩ : ∃ p ∈ jointSys (fun _ => Term.const 0) (fR{SUF} q) (Term.const ({LAM})),
        p.1 = c := by simpa [ODESystem.bound, List.mem_map] using hc
    rw [← hfst, ODESystem.rhs_eq_of_mem (jointSys_wellFormed _ _ _) hp]
    rw [jointSys_split] at hp
    have hne : ∀ (a b : Fin {N}), a ≠ b → (Rv a : Var {N}) ≠ Rv b := by
      intro a b hab
      simp [Rv, Prod.ext_iff]
      exact fun h => hab (by exact_mod_cast h)
    rcases List.mem_append.mp hp with hp | hp
    · obtain ⟨j, -, rfl⟩ := List.mem_map.mp hp
      have hLR : ∀ k : Fin {N}, (Lv j : Var {N}) ≠ Rv k := by
        intro k
        simp [Lv, Rv, Prod.ext_iff]
      simp [Term.eval, {hLRs}]
    · obtain ⟨j, -, rfl⟩ := List.mem_map.mp hp
      fin_cases j
{chr(10).join(branches)}
  · have hnotR : ∀ j : Fin {N}, c ≠ Rv j := by
      intro j hceq
      refine hc ?_
      rw [hceq, jointSys_split]
      simp only [ODESystem.bound, List.map_append, List.mem_append]
      exact Or.inr (by
        simp only [rightBlock, List.map_map, List.mem_map]
        exact ⟨j, List.mem_finRange j, rfl⟩)
    simp only [odeField, if_neg hc{"".join(f", if_neg (hnotR {j})" for j in nz)}]

/-! ## Strict inflow -/
''')
    # strict branches
    sbr = []
    for c, lo, hi, nlo, nhi in strict:
        tail = "interval_cases q <;> norm_num [cst" + SUF + "]" if rows[c][0] == 'affine' else "norm_num"
        ringlo = "" if lo == "0" else "; ring"
        sbr.append(f'''  · have hx : x (Rv {c}) = {lo} := by
      simp only [{nlo}, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var {N}) => Term.eval {nlo} ω)
        = fun y => (-1 : ℝ) * y (Rv {c}) + ({lo}) := by
      funext y; simp [{nlo}, Term.eval, AOp.interp]{ringlo}
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv {c}) (-1) ({lo}) x,
      odeField_R{SUF} q hq]
    simp only [{ifnegs(c)}eq_self_iff_true, if_true, if_pos rfl, hx]
    {tail}
  · have hx : x (Rv {c}) = {hi} := by
      simp only [{nhi}, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var {N}) => Term.eval {nhi} ω)
        = fun y => (1 : ℝ) * y (Rv {c}) + (-({hi})) := by
      funext y; simp [{nhi}, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv {c}) 1 (-({hi})) x,
      odeField_R{SUF} q hq]
    simp only [{ifnegs(c)}eq_self_iff_true, if_true, if_pos rfl, hx]
    {tail}''')
    for c, lo, nm in aux:
        ringlo = "" if lo == "0" else "; ring"
        sbr.append(f'''  · have hx : x (Rv {c}) = {lo} := by
      simp only [{nm}, Term.eval, AOp.interp] at hface; linarith
    have hfun : (fun ω : State (Var {N}) => Term.eval {nm} ω)
        = fun y => (-1 : ℝ) * y (Rv {c}) + ({lo}) := by
      funext y; simp [{nm}, Term.eval, AOp.interp]{ringlo}
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv {c}) (-1) ({lo}) x,
      odeField_R{SUF} q hq]
    simp only [{ifnegs(c)}eq_self_iff_true, if_true, if_pos rfl, hx]
    norm_num''')
    A(f'''
theorem hbndS_{SUF} (q : ℕ) (hq : q < {nmodes}) : ∀ gT' ∈ gsS{SUF}, ∀ x : State (Var {N}),
    Term.eval gT' x = 0 →
    Lie (jointSys (fun _ => Term.const 0) (fR{SUF} q) (Term.const ({LAM})))
      (fun ω => Term.eval gT' ω) x < 0 := by
  have hne : ∀ (a b : Fin {N}), a ≠ b → (Rv a : Var {N}) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro gT' hgT x hface
  simp only [gsS{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hgT
  rcases hgT with {" | ".join(["rfl"]*len(sfaces))}
{chr(10).join(sbr)}

/-! ## Non-strict faces -/
''')
    # nonstrict: s face (needs core) then zero-field bands
    nbr = []
    if s_face:
        sc = s_face[0]
        bracket_facts = ""
        if hasBracket:
            _, p, t = next(r for r in rows.values() if r[0] == 'bracket')
            pb = next((lo, hi, nlo, nhi) for c, lo, hi, nlo, nhi in strict if c == p)
            tb = next((lo, hi, nlo, nhi) for c, lo, hi, nlo, nhi in strict if c == t)
            bracket_facts = f'''
    have hbp1 : {pb[0]} ≤ x (Rv {p}) := by
      have := hx {pb[2]} (List.mem_append_left _ (by simp [gsS{SUF}]))
      simp only [{pb[2]}, Term.eval, AOp.interp] at this; linarith
    have hbp2 : x (Rv {p}) ≤ {pb[1]} := by
      have := hx {pb[3]} (List.mem_append_left _ (by simp [gsS{SUF}]))
      simp only [{pb[3]}, Term.eval, AOp.interp] at this; linarith
    have hbt1 : {tb[0]} ≤ x (Rv {t}) := by
      have := hx {tb[2]} (List.mem_append_left _ (by simp [gsS{SUF}]))
      simp only [{tb[2]}, Term.eval, AOp.interp] at this; linarith
    have hbt2 : x (Rv {t}) ≤ {tb[1]} := by
      have := hx {tb[3]} (List.mem_append_left _ (by simp [gsS{SUF}]))
      simp only [{tb[3]}, Term.eval, AOp.interp] at this; linarith
    have hB : (0:ℝ) ≤ (1 - 1/2 * (x (Rv {p}) * x (Rv {p}))) - 3/10 * (x (Rv {t}) * x (Rv {t})) := by
      nlinarith [hbp1, hbp2, hbt1, hbt2]
    have hmn := mul_nonneg hv0 hB
    linarith'''
        else:
            bracket_facts = "\n    linarith"
        nbr.append(f'''  · show Lie _ (fun ω => Term.eval {s_face[1]} ω) x ≤ 0
    have hv0 : 0 ≤ x (Rv 0) := by
      have := hx {strict[0][3]} (List.mem_append_left _ (by simp [gsS{SUF}]))
      simp only [{strict[0][3]}, Term.eval, AOp.interp] at this; linarith
    have hfun : (fun ω : State (Var {N}) => Term.eval {s_face[1]} ω)
        = fun y => (-1 : ℝ) * y (Rv {sc}) + 0 := by
      funext y; simp [{s_face[1]}, Term.eval, AOp.interp]
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv {sc}) (-1) 0 x,
      odeField_R{SUF} q hq]
    simp only [{ifnegs(sc)}eq_self_iff_true, if_true, if_pos rfl]{bracket_facts}''')
    for c, lo, hi, nlo, nhi in nonstrict:
        negstr = "".join(f"if_neg (hne {c} {k} (by decide)), " for k in nz)
        ringlo = "" if lo == "0" else "; ring"
        nbr.append(f'''  · show Lie _ (fun ω => Term.eval {nlo} ω) x ≤ 0
    have hfun : (fun ω : State (Var {N}) => Term.eval {nlo} ω)
        = fun y => (-1 : ℝ) * y (Rv {c}) + ({lo}) := by
      funext y; simp [{nlo}, Term.eval, AOp.interp]{ringlo}
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv {c}) (-1) ({lo}) x,
      odeField_R{SUF} q hq]
    simp only [{negstr[:-2]}]
    norm_num
  · show Lie _ (fun ω => Term.eval {nhi} ω) x ≤ 0
    have hfun : (fun ω : State (Var {N}) => Term.eval {nhi} ω)
        = fun y => (1 : ℝ) * y (Rv {c}) + (-({hi})) := by
      funext y; simp [{nhi}, Term.eval, AOp.interp]; ring
    rw [hfun, lie_affine_coord _ (jointSys_wellFormed _ _ _) (Rv {c}) 1 (-({hi})) x,
      odeField_R{SUF} q hq]
    simp only [{negstr[:-2]}]
    norm_num''')
    A(f'''
theorem hbndN_{SUF} (q : ℕ) (hq : q < {nmodes}) : ∀ i (hi : i < gsN{SUF}.length),
    ∀ x : State (Var {N}),
    (∀ gT' ∈ gsS{SUF} ++ ([] : List (Term (Var {N}))), Term.eval gT' x ≤ 0) →
    Lie (jointSys (fun _ => Term.const 0) (fR{SUF} q) (Term.const ({LAM})))
      (fun ω => Term.eval gsN{SUF}[i] ω) x ≤ 0 := by
  have hne : ∀ (a b : Fin {N}), a ≠ b → (Rv a : Var {N}) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro i hi x hx
  have hib : i < {len(nfaces)} := by simpa [gsN{SUF}] using hi
  interval_cases i
{chr(10).join(nbr)}

/-! ## Lipschitz and field bound -/
''')
    # ---- Lipschitz and field bound (lambda-aware: factor lambda out, bound the core) ----
    LMul = "" if LAM == '1' else "(" + LAM + ") * "
    def corediff(j):
        k = rows[j][0]
        if k == 'affine':
            return (f"{DR} * (cst{SUF} q - x (Rv {j})) - {DR} * (cst{SUF} q - y (Rv {j}))",
                    f"-({DR} : ℝ) * (x (Rv {j}) - y (Rv {j}))", f"-({DR} : ℝ)", str(DR), j)
        if k == 'vel':
            return ("x (Rv 0) - y (Rv 0)", "(1 : ℝ) * (x (Rv 0) - y (Rv 0))", "(1 : ℝ)", "1", 0)
        return (f"-1 * x (Rv {j}) - -1 * y (Rv {j})",
                f"-(1 : ℝ) * (x (Rv {j}) - y (Rv {j}))", "-(1 : ℝ)", "1", j)
    lipfac = ("skip" if not LMul else
        "have hfac : ∀ A B : ℝ, " + LMul + "A - " + LMul + "B = (" + LAM + ") * (A - B) := by\n"
        "      intro A B; ring\n"
        "    rw [hfac, abs_mul, abs_of_pos (show (0:ℝ) < (" + LAM + ") by norm_num)]")
    lipbr = []
    for j in nz:
        kk = rows[j][0]
        pre = ifnegs(j) if j != nz[0] else ""
        if kk == 'bracket':
            _, pp, tt = rows[j]
            lipbr.append(f'''  by_cases hc{j} : c = Rv {j}
  · subst hc{j}
    simp only [{pre}eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |x (Rv 0) * ((1 - 1/2 * (x (Rv {pp}) * x (Rv {pp}))) - 3/10 * (x (Rv {tt}) * x (Rv {tt})))
        - y (Rv 0) * ((1 - 1/2 * (y (Rv {pp}) * y (Rv {pp}))) - 3/10 * (y (Rv {tt}) * y (Rv {tt})))|
        ≤ 13 * dist x y := by
      have hdiff : x (Rv 0) * ((1 - 1/2 * (x (Rv {pp}) * x (Rv {pp}))) - 3/10 * (x (Rv {tt}) * x (Rv {tt})))
          - y (Rv 0) * ((1 - 1/2 * (y (Rv {pp}) * y (Rv {pp}))) - 3/10 * (y (Rv {tt}) * y (Rv {tt})))
          = ((1 - 1/2 * (x (Rv {pp}) * x (Rv {pp}))) - 3/10 * (x (Rv {tt}) * x (Rv {tt})))
              * (x (Rv 0) - y (Rv 0))
            + y (Rv 0) * (-(1/2) * ((x (Rv {pp}) + y (Rv {pp})) * (x (Rv {pp}) - y (Rv {pp})))
                - 3/10 * ((x (Rv {tt}) + y (Rv {tt})) * (x (Rv {tt}) - y (Rv {tt})))) := by
        ring
      rw [hdiff]
      have hBx : |(1 - 1/2 * (x (Rv {pp}) * x (Rv {pp}))) - 3/10 * (x (Rv {tt}) * x (Rv {tt}))| ≤ 5 := by
        have h2 : x (Rv {pp}) * x (Rv {pp}) ≤ 4 := by nlinarith [abs_le.mp hxb{pp}]
        have h3 : x (Rv {tt}) * x (Rv {tt}) ≤ 4 := by nlinarith [abs_le.mp hxb{tt}]
        have h2n : 0 ≤ x (Rv {pp}) * x (Rv {pp}) := mul_self_nonneg _
        have h3n : 0 ≤ x (Rv {tt}) * x (Rv {tt}) := mul_self_nonneg _
        rw [abs_le]
        constructor <;> nlinarith
      have htri : |(-(1/2) * ((x (Rv {pp}) + y (Rv {pp})) * (x (Rv {pp}) - y (Rv {pp})))
            - 3/10 * ((x (Rv {tt}) + y (Rv {tt})) * (x (Rv {tt}) - y (Rv {tt}))))| ≤ 4 * dist x y := by
        have hA : |(x (Rv {pp}) + y (Rv {pp})) * (x (Rv {pp}) - y (Rv {pp}))| ≤ 4 * dist x y := by
          rw [abs_mul]
          have hs : |x (Rv {pp}) + y (Rv {pp})| ≤ 4 := by
            calc |x (Rv {pp}) + y (Rv {pp})| ≤ |x (Rv {pp})| + |y (Rv {pp})| := abs_add_le _ _
              _ ≤ 4 := by linarith [abs_le.mp hxb{pp}, abs_le.mp hyb{pp}]
          nlinarith [hdc {pp}, abs_nonneg (x (Rv {pp}) + y (Rv {pp})), abs_nonneg (x (Rv {pp}) - y (Rv {pp}))]
        have hB2 : |(x (Rv {tt}) + y (Rv {tt})) * (x (Rv {tt}) - y (Rv {tt}))| ≤ 4 * dist x y := by
          rw [abs_mul]
          have hs : |x (Rv {tt}) + y (Rv {tt})| ≤ 4 := by
            calc |x (Rv {tt}) + y (Rv {tt})| ≤ |x (Rv {tt})| + |y (Rv {tt})| := abs_add_le _ _
              _ ≤ 4 := by linarith [abs_le.mp hxb{tt}, abs_le.mp hyb{tt}]
          nlinarith [hdc {tt}, abs_nonneg (x (Rv {tt}) + y (Rv {tt})), abs_nonneg (x (Rv {tt}) - y (Rv {tt}))]
        have e1 : |(-(1/2) : ℝ) * ((x (Rv {pp}) + y (Rv {pp})) * (x (Rv {pp}) - y (Rv {pp})))|
            ≤ 1/2 * (4 * dist x y) := by
          rw [abs_mul]
          have h : |(-(1/2) : ℝ)| = 1/2 := by norm_num
          rw [h]
          nlinarith [abs_nonneg ((x (Rv {pp}) + y (Rv {pp})) * (x (Rv {pp}) - y (Rv {pp})))]
        have e2 : |((3:ℝ)/10) * ((x (Rv {tt}) + y (Rv {tt})) * (x (Rv {tt}) - y (Rv {tt})))|
            ≤ 3/10 * (4 * dist x y) := by
          rw [abs_mul]
          have h : |((3:ℝ)/10)| = 3/10 := by norm_num
          rw [h]
          nlinarith [abs_nonneg ((x (Rv {tt}) + y (Rv {tt})) * (x (Rv {tt}) - y (Rv {tt})))]
        have hsub : |(-(1/2) * ((x (Rv {pp}) + y (Rv {pp})) * (x (Rv {pp}) - y (Rv {pp})))
              - 3/10 * ((x (Rv {tt}) + y (Rv {tt})) * (x (Rv {tt}) - y (Rv {tt}))))|
            ≤ |(-(1/2) : ℝ) * ((x (Rv {pp}) + y (Rv {pp})) * (x (Rv {pp}) - y (Rv {pp})))|
              + |((3:ℝ)/10) * ((x (Rv {tt}) + y (Rv {tt})) * (x (Rv {tt}) - y (Rv {tt})))| := by
          rw [sub_eq_add_neg]
          refine (abs_add_le _ _).trans ?_
          rw [abs_neg]
        linarith
      have hfin1 : |(1 - 1/2 * (x (Rv {pp}) * x (Rv {pp}))) - 3/10 * (x (Rv {tt}) * x (Rv {tt}))|
          * |x (Rv 0) - y (Rv 0)| ≤ 5 * dist x y :=
        mul_le_mul hBx (hdc 0) (abs_nonneg _) (by norm_num)
      have hfin2 : |y (Rv 0)| * |(-(1/2) * ((x (Rv {pp}) + y (Rv {pp})) * (x (Rv {pp}) - y (Rv {pp})))
            - 3/10 * ((x (Rv {tt}) + y (Rv {tt})) * (x (Rv {tt}) - y (Rv {tt}))))|
          ≤ 2 * (4 * dist x y) :=
        mul_le_mul hyb0 htri (abs_nonneg _) (by norm_num)
      have hsplit : |((1 - 1/2 * (x (Rv {pp}) * x (Rv {pp}))) - 3/10 * (x (Rv {tt}) * x (Rv {tt})))
              * (x (Rv 0) - y (Rv 0))
            + y (Rv 0) * (-(1/2) * ((x (Rv {pp}) + y (Rv {pp})) * (x (Rv {pp}) - y (Rv {pp})))
                - 3/10 * ((x (Rv {tt}) + y (Rv {tt})) * (x (Rv {tt}) - y (Rv {tt}))))|
          ≤ |((1 - 1/2 * (x (Rv {pp}) * x (Rv {pp}))) - 3/10 * (x (Rv {tt}) * x (Rv {tt})))
              * (x (Rv 0) - y (Rv 0))|
            + |y (Rv 0) * (-(1/2) * ((x (Rv {pp}) + y (Rv {pp})) * (x (Rv {pp}) - y (Rv {pp})))
                - 3/10 * ((x (Rv {tt}) + y (Rv {tt})) * (x (Rv {tt}) - y (Rv {tt}))))| := abs_add_le _ _
      rw [abs_mul, abs_mul] at hsplit
      linarith
    {lipfac}
    nlinarith [hcore, hd]''')
        else:
            raw, fac, coefexpr, coefval, dj = corediff(j)
            lipbr.append(f'''  by_cases hc{j} : c = Rv {j}
  · subst hc{j}
    simp only [{pre}eq_self_iff_true, if_true, if_pos rfl]
    rw [Real.dist_eq]
    have hcore : |{raw}| ≤ {coefval} * dist x y := by
      have hdiff : {raw} = {fac} := by ring
      rw [hdiff, abs_mul]
      have habs : |{coefexpr}| = {coefval} := by norm_num
      rw [habs]
      nlinarith [hdc {dj}]
    {lipfac}
    nlinarith [hcore, hd]''')
    ballfacts = ""
    if hasBracket:
        _, pp, tt = next(r for r in rows.values() if r[0] == 'bracket')
        pb = next((lo, hi, nlo, nhi) for c, lo, hi, nlo, nhi in strict if c == pp)
        tb = next((lo, hi, nlo, nhi) for c, lo, hi, nlo, nhi in strict if c == tt)
        vb = strict[0]
        ballfacts = f'''
  have hband : ∀ (w : State (Var {N})), dist w ν ≤ 1 → ∀ (j : Fin {N}) (lo hi : ℝ),
      lo ≤ ν (Rv j) → ν (Rv j) ≤ hi → -1 ≤ lo → hi ≤ 1 → |w (Rv j)| ≤ 2 := by
    intro w hw j lo hi hl hh hlo1 hhi1
    have h := dist_le_pi_dist w ν (Rv j)
    rw [Real.dist_eq] at h
    have hνb : |ν (Rv j)| ≤ 1 := abs_le.mpr ⟨by linarith, by linarith⟩
    have h2 := abs_sub_abs_le_abs_sub (w (Rv j)) (ν (Rv j))
    linarith [abs_le.mp hνb, hw]
  have hνv1 : {vb[1]} ≤ ν (Rv 0) := by
    have := hν {vb[3]} (by simp [gsS{SUF}])
    simp only [{vb[3]}, Term.eval, AOp.interp] at this; linarith
  have hνv2 : ν (Rv 0) ≤ {vb[2]} := by
    have := hν {vb[4]} (by simp [gsS{SUF}])
    simp only [{vb[4]}, Term.eval, AOp.interp] at this; linarith
  have hνp1 : {pb[0]} ≤ ν (Rv {pp}) := by
    have := hν {pb[2]} (by simp [gsS{SUF}])
    simp only [{pb[2]}, Term.eval, AOp.interp] at this; linarith
  have hνp2 : ν (Rv {pp}) ≤ {pb[1]} := by
    have := hν {pb[3]} (by simp [gsS{SUF}])
    simp only [{pb[3]}, Term.eval, AOp.interp] at this; linarith
  have hνt1 : {tb[0]} ≤ ν (Rv {tt}) := by
    have := hν {tb[2]} (by simp [gsS{SUF}])
    simp only [{tb[2]}, Term.eval, AOp.interp] at this; linarith
  have hνt2 : ν (Rv {tt}) ≤ {tb[1]} := by
    have := hν {tb[3]} (by simp [gsS{SUF}])
    simp only [{tb[3]}, Term.eval, AOp.interp] at this; linarith
  have hyb0 : |y (Rv 0)| ≤ 2 := hband y hy 0 ({vb[1]}) ({vb[2]}) hνv1 hνv2 (by norm_num) (by norm_num)
  have hxb{pp} : |x (Rv {pp})| ≤ 2 := hband x hx {pp} ({pb[0]}) ({pb[1]}) hνp1 hνp2 (by norm_num) (by norm_num)
  have hyb{pp} : |y (Rv {pp})| ≤ 2 := hband y hy {pp} ({pb[0]}) ({pb[1]}) hνp1 hνp2 (by norm_num) (by norm_num)
  have hxb{tt} : |x (Rv {tt})| ≤ 2 := hband x hx {tt} ({tb[0]}) ({tb[1]}) hνt1 hνt2 (by norm_num) (by norm_num)
  have hyb{tt} : |y (Rv {tt})| ≤ 2 := hband y hy {tt} ({tb[0]}) ({tb[1]}) hνt1 hνt2 (by norm_num) (by norm_num)'''
    lipsig = (f"theorem hLip_{SUF} (q : ℕ) (hq : q < {nmodes}) (ν : State (Var {N}))\n"
              f"    (hν : ∀ gT' ∈ gsS{SUF}, Term.eval gT' ν ≤ 0) :" if hasBracket else
              f"theorem hLip_{SUF} (q : ℕ) (hq : q < {nmodes}) (ν : State (Var {N})) :")
    A(f'''
{lipsig}
    LipschitzOnWith {K} (odeField (jointSys (fun _ => Term.const 0) (fR{SUF} q) (Term.const ({LAM}))))
      (Metric.closedBall ν 1) := by
  have hne : ∀ (a b : Fin {N}), a ≠ b → (Rv a : Var {N}) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  rw [lipschitzOnWith_iff_dist_le_mul]
  intro x hx y hy
  rw [Metric.mem_closedBall] at hx hy
  rw [odeField_R{SUF} q hq, odeField_R{SUF} q hq]
  have hdc : ∀ j : Fin {N}, |x (Rv j) - y (Rv j)| ≤ dist x y := by
    intro j
    have h := dist_le_pi_dist x y (Rv j)
    rwa [Real.dist_eq] at h
  have hd : (0:ℝ) ≤ dist x y := dist_nonneg
  have hcoe : (({K} : NNReal) : ℝ) = {K} := rfl
  rw [hcoe]{ballfacts}
  refine dist_pi_le_iff (by positivity) |>.mpr ?_
  intro c
{chr(10).join(lipbr)}
  · simp only [{", ".join(f"if_neg hc{j}" for j in nz)}]
    simp [dist_nonneg]
''')
    fb_facts = [f'''  have hbandf : ∀ (j : Fin {N}) (lo hi : ℝ),
      lo ≤ ν (Rv j) → ν (Rv j) ≤ hi → -1 ≤ lo → hi ≤ 1 → |x (Rv j)| ≤ 2 := by
    intro j lo hi hl hh hlo1 hhi1
    have h := dist_le_pi_dist x ν (Rv j)
    rw [Real.dist_eq] at h
    have hνb : |ν (Rv j)| ≤ 1 := abs_le.mpr ⟨by linarith, by linarith⟩
    have h2 := abs_sub_abs_le_abs_sub (x (Rv j)) (ν (Rv j))
    linarith [abs_le.mp hνb, hx]''']
    for c, lo, hi, nlo, nhi in strict:
        fb_facts.append(f'''  have hxb{c} : |x (Rv {c})| ≤ 2 := by
    refine hbandf {c} ({lo}) ({hi}) ?_ ?_ (by norm_num) (by norm_num)
    · have := hν {nlo} (by simp [gsS{SUF}])
      simp only [{nlo}, Term.eval, AOp.interp] at this; linarith
    · have := hν {nhi} (by simp [gsS{SUF}])
      simp only [{nhi}, Term.eval, AOp.interp] at this; linarith''')
    fbr = []
    for j in nz:
        kk = rows[j][0]
        pre = ifnegs(j) if j != nz[0] else ""
        if kk == 'bracket':
            _, pp, tt = rows[j]
            core = f"x (Rv 0) * ((1 - 1/2 * (x (Rv {pp}) * x (Rv {pp}))) - 3/10 * (x (Rv {tt}) * x (Rv {tt})))"
            extra = f'''    have hBx : |(1 - 1/2 * (x (Rv {pp}) * x (Rv {pp}))) - 3/10 * (x (Rv {tt}) * x (Rv {tt}))| ≤ 5 := by
      have h2 : x (Rv {pp}) * x (Rv {pp}) ≤ 4 := by nlinarith [abs_le.mp hxb{pp}]
      have h3 : x (Rv {tt}) * x (Rv {tt}) ≤ 4 := by nlinarith [abs_le.mp hxb{tt}]
      have h2n : 0 ≤ x (Rv {pp}) * x (Rv {pp}) := mul_self_nonneg _
      have h3n : 0 ≤ x (Rv {tt}) * x (Rv {tt}) := mul_self_nonneg _
      rw [abs_le]
      constructor <;> nlinarith
    have hcore : |{core}| ≤ 10 := by
      rw [abs_mul]
      nlinarith [abs_nonneg (x (Rv 0)), abs_le.mp hxb0, abs_nonneg ((1 - 1/2 * (x (Rv {pp}) * x (Rv {pp}))) - 3/10 * (x (Rv {tt}) * x (Rv {tt})))]'''
        elif kk == 'affine':
            core = f"{DR} * (cst{SUF} q - x (Rv {j}))"
            extra = f'''    have hcst : 0 ≤ cst{SUF} q ∧ cst{SUF} q ≤ 1 := by
      interval_cases q <;> norm_num [cst{SUF}]
    have hcore : |{core}| ≤ {3*DR} := by
      obtain ⟨hcl, hch⟩ := hcst
      rw [abs_le]
      constructor <;> nlinarith [abs_le.mp hxb{j}]'''
        elif kk == 'vel':
            core = "x (Rv 0)"
            extra = "    have hcore : |x (Rv 0)| ≤ 2 := hxb0"
        else:
            core = f"-1 * x (Rv {j})"
            extra = f'''    have hcore : |{core}| ≤ 2 := by
      rw [abs_mul]
      have habs : |(-1 : ℝ)| = 1 := by norm_num
      rw [habs]
      linarith [abs_le.mp hxb{j}, abs_nonneg (x (Rv {j}))]'''
        scal = ("" if not LMul else
                f'''    rw [show {LMul}({core}) = ({LAM}) * ({core}) from by ring, abs_mul,
      abs_of_pos (show (0:ℝ) < ({LAM}) by norm_num)]''')
        fbr.append(f'''  by_cases hc{j} : c = Rv {j}
  · subst hc{j}
    simp only [{pre}eq_self_iff_true, if_true, if_pos rfl, Real.norm_eq_abs]
{extra}
{scal}
    nlinarith [hcore, abs_nonneg ({core})]''')
    A(f'''
theorem hfbnd_{SUF} (q : ℕ) (hq : q < {nmodes}) (ν : State (Var {N}))
    (hν : ∀ gT' ∈ gsS{SUF}, Term.eval gT' ν ≤ 0) :
    ∀ x ∈ Metric.closedBall ν 1,
      ‖odeField (jointSys (fun _ => Term.const 0) (fR{SUF} q) (Term.const ({LAM}))) x‖
        ≤ (({L}:NNReal) : ℝ) := by
  have hne : ∀ (a b : Fin {N}), a ≠ b → (Rv a : Var {N}) ≠ Rv b := by
    intro a b hab
    simp [Rv, Prod.ext_iff]
    exact fun h => hab (by exact_mod_cast h)
  intro x hx
  rw [Metric.mem_closedBall] at hx
{chr(10).join(fb_facts)}
  rw [odeField_R{SUF} q hq]
  refine pi_norm_le_iff_of_nonneg (by norm_num) |>.mpr ?_
  intro c
  have hLcoe : (({L}:NNReal) : ℝ) = {L} := rfl
  rw [hLcoe]
{chr(10).join(fbr)}
  · simp only [{", ".join(f"if_neg hc{j}" for j in nz)}]
    norm_num

/-! ## Existence -/
''')
    # existence
    domnames = []
    for c, lo, hi in dom:
        domnames.append(f"hd{c}l")
        if hi is not None:
            domnames.append(f"hd{c}h")
    sanchor = []
    for c, lo, hi, nlo, nhi in strict:
        sanchor.append(f'          | (simp only [{nlo}, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)')
        sanchor.append(f'          | (simp only [{nhi}, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)')
    for c, lo, nm in aux:
        sanchor.append(f'          | (simp only [{nm}, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)')
    nanchor = []
    if s_face:
        nanchor.append(f'          | (simp only [{s_face[1]}, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)')
    for c, lo, hi, nlo, nhi in nonstrict:
        nanchor.append(f'          | (simp only [{nlo}, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)')
        nanchor.append(f'          | (simp only [{nhi}, Term.eval, AOp.interp, Rv]; rw [← hupd]; linarith)')
    # rebuild dom
    rebuild = []
    have_names = {}
    for c, lo, hi, nlo, nhi in strict:
        rebuild.append(f'''      have hb{c}l : {lo} ≤ x (Rv {c}) := by
        have := hS' {nlo} (by simp [gsS{SUF}])
        simp only [{nlo}, Term.eval, AOp.interp] at this; linarith
      have hb{c}h : x (Rv {c}) ≤ {hi} := by
        have := hS' {nhi} (by simp [gsS{SUF}])
        simp only [{nhi}, Term.eval, AOp.interp] at this; linarith''')
        have_names[(c, 'l')] = f'hb{c}l'; have_names[(c, 'h')] = f'hb{c}h'
    if s_face:
        rebuild.append(f'''      have hb{s_face[0]}l : 0 ≤ x (Rv {s_face[0]}) := by
        have := hN {s_face[1]} (by simp [gsN{SUF}])
        simp only [{s_face[1]}, Term.eval, AOp.interp] at this; linarith''')
        have_names[(s_face[0], 'l')] = f'hb{s_face[0]}l'
    for c, lo, hi, nlo, nhi in nonstrict:
        rebuild.append(f'''      have hb{c}l : {lo} ≤ x (Rv {c}) := by
        have := hN {nlo} (by simp [gsN{SUF}])
        simp only [{nlo}, Term.eval, AOp.interp] at this; linarith
      have hb{c}h : x (Rv {c}) ≤ {hi} := by
        have := hN {nhi} (by simp [gsN{SUF}])
        simp only [{nhi}, Term.eval, AOp.interp] at this; linarith''')
        have_names[(c, 'l')] = f'hb{c}l'; have_names[(c, 'h')] = f'hb{c}h'
    for (c,) in affineL:
        rebuild.append(f'''      have hb{c}l : 0 ≤ x (Rv {c}) := by
        have := hAL ((Rv {c} : Var {N}), 1, 0, 0) (by simp [gsAL{SUF}])
        simpa using this''')
        have_names[(c, 'l')] = f'hb{c}l'
    tup = []
    for c, lo, hi in dom:
        tup.append(have_names[(c, 'l')])
        if hi is not None:
            tup.append(have_names[(c, 'h')])
    liparg = (f"(fun ν0 h0 => hLip_{SUF} m hm ν0 (fun gT hgT => h0 gT (List.mem_append_left _ hgT)))"
              if hasBracket else f"(fun ν0 _ => hLip_{SUF} m hm ν0)")
    if affineL:
        A(f'''
theorem es{SUF} (l m : ℕ) (hl : l < {nmodes}) (hm : m < {nmodes}) (dt : ℝ) (hdt : 0 ≤ dt) :
    ∀ σ, Formula.sat (Formula.and (FM g{SUF} gs{SUF}) env{SUF}) σ →
      HExistSegB (fL{SUF} l) (fR{SUF} m) (Term.const ({LAM})) domL{SUF} domR{SUF} dt
        (Function.update σ tg{SUF} 0) := by
  intro σ hσ
  have hR : Formula.sat domR{SUF} σ := hσ.2.2
  rw [sat_domR{SUF}] at hR
  obtain ⟨{", ".join(domnames)}⟩ := hR
  have hupd : ∀ j : Fin {N}, σ (Side.R, j) = Function.update σ tg{SUF} 0 (Side.R, j) := by
    intro j
    rw [Function.update_of_ne (by simp [tg{SUF}, Prod.ext_iff])]
  have hfS : ∀ gT' ∈ gsS{SUF}, Term.eval gT' (Function.update σ tg{SUF} 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsS{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with {" | ".join(["rfl"]*len(sfaces))} <;>
      · first
{chr(10).join(sanchor)}
  have hfN : ∀ gT' ∈ gsN{SUF}, Term.eval gT' (Function.update σ tg{SUF} 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsN{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with {" | ".join(["rfl"]*len(nfaces))} <;>
      · first
{chr(10).join(nanchor)}
  refine HExistSegB_of_viability_stratA (fL{SUF} l) (fR{SUF} m) (Term.const ({LAM}))
    domL{SUF} domR{SUF} gsS{SUF} [] gsN{SUF} 0 le_rfl
    ([] : List (Var {N} × ℝ × ℝ × ℝ)) gsAL{SUF}
    (jointSys_wellFormed _ _ _)
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fL{SUF} l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_R{SUF} gT' (by
        rcases List.mem_append.mp hgT with h | h
        · exact List.mem_append_left _ h
        · exact absurd h (List.not_mem_nil)) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fL{SUF} l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_R{SUF} gT' (List.mem_append_right _ hgT) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by
      intro p hp hb
      simp only [gsAL{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hp
      rcases hp with {" | ".join(["rfl"]*len(affineL))} <;>
        · obtain ⟨i, hi⟩ := leftBlock_bound_sub (fL{SUF} l) _ hb
          exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by
      intro p hp
      simp only [gsAL{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hp
      rcases hp with {" | ".join(["rfl"]*len(affineL))} <;> norm_num)
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by
      intro p hp
      simp only [gsAL{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hp
      rcases hp with {" | ".join(["rfl"]*len(affineL))} <;> norm_num)
    (by
      intro gT' hgT x _ hface
      exact hbndS_{SUF} m hm gT' hgT x hface)
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))
    (by
      intro i hi x hxs _
      exact hbndN_{SUF} m hm i hi x hxs)
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by
      intro p hp x _ _
      simp only [gsAL{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hp
      have hne : ∀ (a b : Fin {N}), a ≠ b → (Rv a : Var {N}) ≠ Rv b := by
        intro a b hab
        simp [Rv, Prod.ext_iff]
        exact fun h => hab (by exact_mod_cast h)
      rcases hp with {" | ".join(["rfl"]*len(affineL))}
{chr(10).join(f"""      · rw [odeField_R{SUF} m hm]
        simp only [{ifnegs(c)}eq_self_iff_true, if_true, if_pos rfl]
        norm_num""" for (c,) in affineL)})
    (by
      intro x hS hN hAU hAL
      have hS' : ∀ gT' ∈ gsS{SUF}, Term.eval gT' x ≤ 0 :=
        fun gT' hgT => hS gT' (List.mem_append_left _ hgT)
{chr(10).join(rebuild)}
      exact (sat_domR{SUF} x).mpr ⟨{", ".join(tup)}⟩)
    {K} {L} 1 one_pos
    {liparg}
    (fun ν0 h0 => hfbnd_{SUF} m hm ν0 (fun gT hgT => h0 gT (List.mem_append_left _ hgT)))
    dt hdt
    (Function.update σ tg{SUF} 0)
    hfS
    hfN
    (by intro p hp; exact absurd hp (List.not_mem_nil))
    (by
      intro p hp
      simp only [gsAL{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hp
      rcases hp with {" | ".join(["rfl"]*len(affineL))}
{chr(10).join(f"""      · show (0:ℝ) ≤ Function.update σ tg{SUF} 0 (Rv {c})
        rw [← hupd {c}]
        linarith""" for (c,) in affineL)})
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))
''')
    else:
        A(f'''
theorem es{SUF} (l m : ℕ) (hl : l < {nmodes}) (hm : m < {nmodes}) (dt : ℝ) (hdt : 0 ≤ dt) :
    ∀ σ, Formula.sat (Formula.and (FM g{SUF} gs{SUF}) env{SUF}) σ →
      HExistSegB (fL{SUF} l) (fR{SUF} m) (Term.const ({LAM})) domL{SUF} domR{SUF} dt
        (Function.update σ tg{SUF} 0) := by
  intro σ hσ
  have hR : Formula.sat domR{SUF} σ := hσ.2.2
  rw [sat_domR{SUF}] at hR
  obtain ⟨{", ".join(domnames)}⟩ := hR
  have hupd : ∀ j : Fin {N}, σ (Side.R, j) = Function.update σ tg{SUF} 0 (Side.R, j) := by
    intro j
    rw [Function.update_of_ne (by simp [tg{SUF}, Prod.ext_iff])]
  have hfS : ∀ gT' ∈ gsS{SUF}, Term.eval gT' (Function.update σ tg{SUF} 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsS{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with {" | ".join(["rfl"]*len(sfaces))} <;>
      · first
{chr(10).join(sanchor)}
  have hfN : ∀ gT' ∈ gsN{SUF}, Term.eval gT' (Function.update σ tg{SUF} 0) ≤ 0 := by
    intro gT' hgT
    simp only [gsN{SUF}, List.mem_cons, List.not_mem_nil, or_false] at hgT
    rcases hgT with {" | ".join(["rfl"]*len(nfaces))} <;>
      · first
{chr(10).join(nanchor)}
  refine HExistSegB_of_viability_stratified (fL{SUF} l) (fR{SUF} m) (Term.const ({LAM}))
    domL{SUF} domR{SUF} gsS{SUF} [] gsN{SUF} 0 le_rfl
    (jointSys_wellFormed _ _ _)
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fL{SUF} l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_R{SUF} gT' (by
        rcases List.mem_append.mp hgT with h | h
        · exact List.mem_append_left _ h
        · exact absurd h (List.not_mem_nil)) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro gT' hgT x hxf hb
      obtain ⟨i, hi⟩ := leftBlock_bound_sub (fL{SUF} l) _ hb
      obtain ⟨j, hj⟩ := faces_fv_R{SUF} gT' (List.mem_append_right _ hgT) x hxf
      rw [← hj] at hi
      exact absurd hi (by simp [Lv, Rv, Prod.ext_iff]))
    (by
      intro gT' hgT x _ hface
      exact hbndS_{SUF} m hm gT' hgT x hface)
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))
    (by
      intro i hi x hxs _
      exact hbndN_{SUF} m hm i hi x hxs)
    (by
      intro x hS hN
      have hS' : ∀ gT' ∈ gsS{SUF}, Term.eval gT' x ≤ 0 :=
        fun gT' hgT => hS gT' (List.mem_append_left _ hgT)
{chr(10).join(rebuild)}
      exact (sat_domR{SUF} x).mpr ⟨{", ".join(tup)}⟩)
    {K} {L} 1 one_pos
    {liparg}
    (fun ν0 h0 => hfbnd_{SUF} m hm ν0 (fun gT hgT => h0 gT (List.mem_append_left _ hgT)))
    dt hdt
    (Function.update σ tg{SUF} 0)
    hfS
    hfN
    (by intro gT' hgT; exact absurd hgT (List.not_mem_nil))
''')
    if spec.get('no_tail'):
        return "".join(O)
    # assembly: rename the pilot tail
    src = open('RelCertifier/Instances/RoverLadderRung1Modal.lean').read()
    tail = src[src.index('/-! ## The route verdicts'):src.index('end RoverLadderRung1Modal')]
    ren = [('VerdE', f'Verd{SUF}'), ('coupleE', f'couple{SUF}'), ('static_hopE', f'static_hop{SUF}'),
           ('hops_convE', f'hops_conv{SUF}'), ('respondE', f'respond{SUF}'), ('HmultiE', f'Hmulti{SUF}'),
           ('rover_ladder_rung1_modal', THM), ('hframesE', f'hframes{SUF}'),
           ('gsE', f'gs{SUF}'), ('gE', f'g{SUF}'), ('fLE', f'fL{SUF}'), ('fRE', f'fR{SUF}'),
           ('domLE', f'domL{SUF}'), ('domRE', f'domR{SUF}'), ('envE', f'env{SUF}'),
           ('tgE', f'tg{SUF}'), ('mvE', f'mv{SUF}'), ('aE', f'a{SUF}'), ('esE', f'es{SUF}'),
           ('GrE_modeAt', f'Gr{SUF}_modeAt'), ('edgeE_mem', f'edge{SUF}_mem'),
           ('GrE', f'Gr{SUF}'), ('modeE', f'mode{SUF}'), ('edgeE', f'edge{SUF}'),
           ('leftProgsE', f'leftProgs{SUF}'), ('leftDataE', f'leftData{SUF}'),
           ('hfLE', f'hfL{SUF}'), ('hfRE', f'hfR{SUF}'), ('hdomLE', f'hdomL{SUF}'),
           ('hdomRE', f'hdomR{SUF}'), ('htgFE', f'htgF{SUF}'), ('htgenvE', f'htgenv{SUF}'),
           ('hmvFE', f'hmvF{SUF}'), ('hmvenvE', f'hmvenv{SUF}'), ('hfreshE', f'hfresh{SUF}'),
           ('httE', f'htt{SUF}'), ('hltE', f'hlt{SUF}'), ('hLE', f'hL{SUF}'), ('hRvE', f'hRv{SUF}'),
           ('State (Var 3)', f'State (Var {N})'), ('Var 3)', f'Var {N})'),
           ('RepoHop 3', f'RepoHop {N}'), (f'Fin 3 → Term (Var {N})', f'Fin {N} → Term (Var {N})')]
    for a, b in ren:
        tail = tail.replace(a, b)
    tail = tail.replace("rcases hg' with rfl | rfl <;> exact hgAt _",
                        " | ".join(["rcases hg' with rfl"] + ["rfl"]*(len(gs_idx)-1)) + " <;> exact hgAt _")
    A("\n" + tail + f"\nend {NS}\nend RelCertifier\n")
    return "".join(O)
